### ISSUE TITLE
Error after Updating to v2.5.2

### ISSUE THREAD

**Issue by MartinHotmann** [shlinkio/shlink#1011]
#### How Shlink is set-up

* Shlink Version: 2.5.2
* Shlink Client Verion: 3.0.1
* PHP Version: 7.4
* How do you serve Shlink: Self-hosted Apache
* Database engine used: MariaDB

After updating from v2.4.2 to v2.5.2 the Backend is not working anymore. Cant say much as the Log is just showing 500 Errors. But I can append them here aswell.

Here some pictures:

Error at Client side:
![Shlink error](https://user-images.githubusercontent.com/17692860/107366504-844f3700-6ade-11eb-9143-56817dcd47e1.PNG)

Log (v2.4.2):
![v2 4 2](https://user-images.githubusercontent.com/17692860/107366731-c24c5b00-6ade-11eb-823c-09250be36398.PNG)

Log (v2.5.2):
![v2 5 2](https://user-images.githubusercontent.com/17692860/107366743-c4aeb500-6ade-11eb-82d3-f7c043d87fb2.PNG)

Console Migration/Update Output:
![Console Migration Output](https://user-images.githubusercontent.com/17692860/107366563-97620700-6ade-11eb-9b30-be02cf2cb8b7.PNG)

**Comment by acelaya** [comment]
Yes please, add the error traces.

**Comment by MartinHotmann** [comment]
Could you tell me how exactly I should create them. The server itself did not produce any PHP related errors, beside the one I already appended as pictures

**Comment by acelaya** [comment]
Then I would say the request is not reaching Shlink. Can you check apache error logs?

**Comment by MartinHotmann** [comment]
Now thats funny.. I just increased the Memory Limit and now it works without any problems.. So I set it back to what it was before but it still runs. Thats weird as the core problem now is not solved nor analysed.. But I will close this ticket for now and reopen if necessary.

Thanks for your fast response!

**Comment by acelaya** [comment]
Perfect. Let me know if anything comes up.

The errors should still be in apache logs, so we should still be in time to check the root cause of you want.

**Comment by MartinHotmann** [comment]
This actually is the Apache Log:

> ![v2 5 2](https://user-images.githubusercontent.com/17692860/107366743-c4aeb500-6ade-11eb-82d3-f7c043d87fb2.PNG)

**Comment by acelaya** [comment]
But there should be a file with the reason of the errors 😅 

Maybe the instance is not configured to log errors 🤷🏼‍♂️

**Comment by MartinHotmann** [comment]
Yes it was not. Now it is, but the error is gone 😅

**Comment by acelaya** [comment]
Ok, perfect.
