### ISSUE TITLE
cannot disable "Validate URL"

### ISSUE THREAD

**Issue by cirrusflyer** [shlinkio/shlink#1013]
I'm unable to disable "Validate URL" or have it unchecked by default.  It's set to false in the generated_config.php and the app_config.php in the cache has been deleted and allowed to rebuild.

* Shlink Version: 2.5.2
* PHP Version: 7.4
* How do you serve Shlink: Self-hosted LEMP Ubuntu 20.04.2 LTS
* Database engine used: MySQL

#### Summary

cannot disable Validate URL

**Comment by acelaya** [comment]
What are you using as client? Are you using shlink-web-client? If so, notice it always explicitly enables validation on every request. You need to disable this checkbox:

![Screenshot_20210210-072720](https://user-images.githubusercontent.com/2719332/107473787-84e4dd80-6b71-11eb-87a0-13a9bb53ee1f.png)

If you are using any other client, can you share the request you que making when creating the short URL?

**Comment by cirrusflyer** [comment]
Using the shlink-web-client and we can uncheck this, but it's always the default.  We'd like to not have it be the default.

**Comment by acelaya** [comment]
Ok, I see the confusion. Shlink and shlink-web-client work as separated apps, so Shlink's config does not directly affect shlink-web-client's behavior.

I'll open a new feature request in shlink-web-client to allow changing the default behavior for that checkbox.

**Comment by acelaya** [comment]
See https://github.com/shlinkio/shlink-web-client/issues/385

**Comment by cirrusflyer** [comment]
Thanks.  What's the point of having the setting in the config file then?

**Comment by acelaya** [comment]
Shlink is designed to be a web service that can be integrated anywhere. Even though shlink-web-client is the *official* web client, it is not the only one.

The config option is used as a fallback for when the `validateUrl` param is not sent at all to the "create short URL" endpoint. The thing is that shlink-web-client always sends it (as `true` or as `false`), so it never falls back to it.

It's a bit confusing and counterintuitive for this specific config option. I want to give it another thought, but this is how it works at the moment 🙂

**Comment by cirrusflyer** [comment]
But here's the issue - when we try to create short URLs using links like this:

https://pubs.nctm.org/view/journals/mtlt/114/1/article-p47.xml?tab_body=fullHtml

They produce an error.  But when we uncheck the Validate, they work fine.  And the URLs are perfectly working URLs.

**Comment by cirrusflyer** [comment]
Thanks.  Are there other clients you can point me to that don't check the validate by default?

**Comment by acelaya** [comment]
Hey @cirrusflyer, this is what I meant when I said you were confusing Shlink config with shlink-web-client config.

https://youtu.be/E8rDQS0fGjY

I still need to find better wording, but you get the idea. This option will be available when shlink-web-client 3.1.0 gets released.

The option in Shlink itself doesn't make much sense at this point. It's there for historical reasons, because at first, you couldn't change this on a per short URL basis, you just had the "global" option.

That's why I said it's confusing. This global option will be removed from Shlink once v3.0.0 is released.

**Comment by cirrusflyer** [comment]
Thanks.  That new setting would be perfect.
