### ISSUE TITLE
slugs allow forward slashes.

### ISSUE THREAD

**Issue by ksonda** [shlinkio/shlink#1020]
#### Summary

I'm interested in using shlink as a persistent identifier service similar to doi.org . For this to work, I need "custom slugs" to be able to be full paths, and thus allow "/" as a character. Would this be possible?

**Comment by acelaya** [comment]
Hey @ksonda 

I'm afraid this is not possible at the moment.

**Comment by acelaya** [comment]
Duplicates https://github.com/shlinkio/shlink/issues/854
