### ISSUE TITLE
Mercury info Rest URL 501

### ISSUE THREAD

**Issue by benhartwich** [shlinkio/shlink#1028]
#### How Shlink is set-up

* Shlink Version: 2.6.0
* PHP Version: 7.4.15
* How do you serve Shlink: Self-hosted nginx
* Database engine used: MariaDB

#### Summary

At my console log at chrome there is 501 error after upgrading to 2.6.0:

`xhr.js:175 GET https://xy.at/rest/v2/mercure-info 501`

If I open the link directly at my browser I get: ERR_INVALID_RESPONSE

**Comment by acelaya** [comment]
Yes, that's expected.

https://api-spec.shlink.io/#/Integrations/mercureInfo
