### ISSUE TITLE
Errors when shortening Twitter URLs

### ISSUE THREAD

**Issue by stefan-as** [shlinkio/shlink#1031]
This is more a bug on Twitter side and I am not sure if there is something you can do, beside hacky workarounds. So, maybe this is just for documentation.

Shlink fails when validating new short URLs pointing to Twitter. The reason is that Twitter hard blocks all clients that are not listed in their whitelist and drops 400 responses (https://help.twitter.com/en/using-twitter/twitter-supported-browsers). Since Shlink's validation requests are initiated by PHP code, they are answered with a 400 response and are not accepted by Shlink.

Same behavior can by triggered using curl:
```
curl -I https://mobile.twitter.com/vinn_ayy/status/1336178629450018817
HTTP/2 400 
```

As a workaround, one can remove the checkbox "Validate URL" when creating short URLs pointing to twitter.

**Comment by acelaya** [comment]
Wow! Good catch. I have just reproduced it with basically any Twitter URL.

I think there has to be some way to bypass their check. It's probably a bot protection system, but Google indexes them and the URLs are publicly accessible from a browser, so there has to be some combination of headers to make them think it's a user.

I'll give it a thought.

**Comment by acelaya** [comment]
I have found a quite simple fix for this. Sending a real browser's User-Agent when validating the URL, makes twitter trust the request.
