### ISSUE TITLE
Two shortlinks, one goes the other doesn't

### ISSUE THREAD

**Issue by cesare190** [shlinkio/shlink#1048]
Regarding [the ticket I opened today](https://github.com/shlinkio/shlink/issues/1047) (Rome time zone) I have a question for you. I don't understand why of two short links active on the same domain one works and the other doesn't.

The links involved are:
```
https://[REDACTED]/H3d3f -> https://[REDACTED].it (not working)
https://[REDACTED]/eYEFA -> https://[REDACTED].it (works)
https://[REDACTED]/YNITu -> https://[REDACTED].org (not working)
https://[REDACTED]/QO6fI -> https://[REDACTED].org (works)
```

I tried to restart Apache, PHP-FPM and to minimize the configuration of the V-Host also providing the inhibition of the mod_pagespeed. As for the other ticket I am using Apache, MariaDB and PHP 8.0

This is the configuration of the vhost

```
# HTTP SERVER
<VirtualHost *: 80>
    ServerName [REDACTED]
    ServerAdmin HIDE
    DocumentRoot /var/www/shorturl/[REDACTED]/public

    <Directory /var/www/shorturl/[REDACTED]/public>
        Options FollowSymLinks Includes ExecCGI
        AllowOverride all
        Order allow, deny
        Allow from all
    </Directory>
</VirtualHost>

# HTTPS SERVER
<IfModule mod_ssl.c>
<VirtualHost *: 443>
    ServerName [REDACTED]
    ServerAdmin HIDE
    DocumentRoot /var/www/shorturl/[REDACTED]/public


    # enable HTTP / 2, if available
    Protocols h2 http / 1.1

    # HTTP Strict Transport Security (mod_headers is required) (63072000 seconds)
    Header always set Strict-Transport-Security "max-age = 63072000"

    <Directory /var/www/shorturl/[REDACTED]/public>
        Options FollowSymLinks Includes ExecCGI
        AllowOverride all
        Order allow, deny
        Allow from all
    </Directory>

    SSLEngine on
    SSLProtocol all -SSLv3 -TLSv1 -TLSv1.1 -TLSv1
    SSLCipherSuite ECDHE-ECDSA-AES128-GCM-SHA256: ECDHE-RSA-AES128-GCM-SHA256: ECDHE-ECDSA-AES256-GCM-SHA384: ECDHE-RSA-AES256-GCM-SHA384: ECDHE-ECDSA-CHA305 -RSA-CHACHA20-POLY1305: DHE-RSA-AES128-GCM-SHA256: DHE-RSA-AES256-GCM-SHA384
    SSLHonorCipherOrder off
    SSLSessionTickets off

    ModPagespeed off

    SSLCertificateFile [REDACTED]
    SSLCertificateKeyFile [REDACTED]
    Includes [REDACTED]
    </VirtualHost>
</IfModule>
```

Some links have been generated via webapp others via ./bin/cli but it seems that by chance some work and some don't.

When they do not work, the message "An unexpected error occurred" appears but no error message appears in the managed logs.

**Comment by acelaya** [comment]
It's hard to tell, but when using apache, if you see that error, the actual exception is probably in apache error logs, not in shlink ones.

**Comment by cesare190** [comment]
I know, I was aware of it. The problem is that no error is logged in any report. Both the shlink and apache logs are empty.

**Comment by acelaya** [comment]
That's weird. Maybe they error is precisely caused by some missing permission to write in the filesystem, which is throwing the error when trying to write logs.

It could also be done missing extension.

Try double checking all the steps here, and make sure everything is done https://shlink.io/documentation/install-dist-file/

**Comment by cesare190** [comment]
I don't know if this is related. With "./bin/cli short-url parse" on a not working shortlink I get:

`PHP Warning:  require(data/proxies/__CG__ShlinkioShlinkRestEntityApiKey.php): Failed to open stream: No such file or directory in /var/www/shorturl/[REDACTED]/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php on line 185
PHP Fatal error:  Uncaught Error: Failed opening required 'data/proxies/__CG__ShlinkioShlinkRestEntityApiKey.php' (include_path='.:/usr/share/php') in /var/www/shorturl/[REDACTED]/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php:185
Stack trace:
#0 /var/www/shorturl/[REDACTED]/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php(98): Doctrine\Common\Proxy\AbstractProxyFactory->getProxyDefinition()
#1 /var/www/shorturl/[REDACTED]/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(2816): Doctrine\Common\Proxy\AbstractProxyFactory->getProxy()
#2 /var/www/shorturl/[REDACTED]/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php(271): Doctrine\ORM\UnitOfWork->createEntity()
#3 /var/www/shorturl/[REDACTED]/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php(492): Doctrine\ORM\Internal\Hydration\ObjectHydrator->getEntity()
#4 /var/www/shorturl/[REDACTED]/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php(162): Doctrine\ORM\Internal\Hydration\ObjectHydrator->hydrateRowData()
#5 /var/www/shorturl/[REDACTED]/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php(202): Doctrine\ORM\Internal\Hydration\ObjectHydrator->hydrateAllData()
#6 /var/www/shorturl/[REDACTED]/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(1097): Doctrine\ORM\Internal\Hydration\AbstractHydrator->hydrateAll()
#7 /var/www/shorturl/[REDACTED]/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(1042): Doctrine\ORM\AbstractQuery->executeIgnoreQueryCache()
#8 /var/www/shorturl/[REDACTED]/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(850): Doctrine\ORM\AbstractQuery->execute()
#9 /var/www/shorturl/[REDACTED]/module/Core/src/Repository/ShortUrlRepository.php(180): Doctrine\ORM\AbstractQuery->getOneOrNullResult()
#10 /var/www/shorturl/[REDACTED]/module/Core/src/Service/ShortUrl/ShortUrlResolver.php(33): Shlinkio\Shlink\Core\Repository\ShortUrlRepository->findOne()
#11 /var/www/shorturl/[REDACTED]/module/CLI/src/Command/ShortUrl/ResolveUrlCommand.php(60): Shlinkio\Shlink\Core\Service\ShortUrl\ShortUrlResolver->resolveShortUrl()
#12 /var/www/shorturl/[REDACTED]/vendor/symfony/console/Command/Command.php(256): Shlinkio\Shlink\CLI\Command\ShortUrl\ResolveUrlCommand->execute()
#13 /var/www/shorturl/[REDACTED]/vendor/symfony/console/Application.php(971): Symfony\Component\Console\Command\Command->run()
#14 /var/www/shorturl/[REDACTED]/vendor/symfony/console/Application.php(290): Symfony\Component\Console\Application->doRunCommand()
#15 /var/www/shorturl/[REDACTED]/vendor/symfony/console/Application.php(166): Symfony\Component\Console\Application->doRun()
#16 /var/www/shorturl/[REDACTED]/config/run.php(14): Symfony\Component\Console\Application->run()
#17 /var/www/shorturl/[REDACTED]/bin/cli(7): {closure}()
#18 {main}
  thrown in /var/www/shorturl/[REDACTED]/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php on line 185`

**Comment by acelaya** [comment]
Ooohh, so that's the error.

The problem is that, since you got an error on the migrations step during installation, it didn't generate the proxies, which was the next step. Basically you didn't finish the installation process, which can have some side effects.

I released v2.6.2 yesterday, which fixes the migrations issue. Try updating to it.

**Comment by cesare190** [comment]
yes, unfortunately I did not see it because it did not occur to me to make the parse dell'url. I finished updating now and it resolved as you said. Thanks for the help and for your work.

**Comment by acelaya** [comment]
That kind of error should en up in apache logs. You probably don't have error logging enabled, or you have a too high error reporting level in php's config (as you can see, it's a warning).

In any case, I'm glad it's sorted out 🙂
