### ISSUE TITLE
Allow fetching all visits combined, not by short URL or tag

### ISSUE THREAD

**Issue by MartinHotmann** [shlinkio/shlink#1063]
#### Summary

Shlink: v2.6.2 (PHP 8.0)
Shlink Web Client: v3.1.0

I would like to ask if its possible to combine/unify ALL requests in one server and show them in one big map to see where (for this server) most people are coming from. Dont know if its much work but would be interested in how this map would look like :)

**Comment by acelaya** [comment]
This feature is now implemented and will be part of Shlink 3.0.0

Support to take advantage of it will be implemented in shlink-web-client v3.6.0
