### ISSUE TITLE
Dynamic Forwarding

### ISSUE THREAD

**Issue by MartinHotmann** [shlinkio/shlink#1069]
I would like to request a new feature thats called "dynamic forwarding" what it does is: it gives you the change to dynamically without preconfiguration create all kind of Links that then will be tracked.

It should work like this:

`https://app.shlink.io/?[###LINK###]`
`https://app.shlink.io/?https://www.domain.tld/path/to/navigate/to/image.png`

So the Link this will be redirected to is (obviously) `https://www.domain.tld/path/to/navigate/to/image.png`
These Links should be tracked in a "FreeStyle" section.

Why do I request this?
- sometimes you dont want to hide the link
- it makes you more flexible in creating these links
- if links are triggered of "clicked" by JS people dont see the links anyway

So I think that would be a good addition to what Shlink already offers and make you beeing flexible in quickly creating dynamic Links. Yes they are not shortened, but tracked. Thats what this feature is about.

**Comment by acelaya** [comment]
This is a bit of an edge case and I see many problems arising from this, so closing in order to narrow down the amount of features due to limited amount of time.
