### ISSUE TITLE
Add setting `check_visits_threshold` in docker image

### ISSUE THREAD

**Issue by syserr0r** [shlinkio/shlink#1077]
A minor change, however contributing requires an issue be opened before making a pull request.

**Comment by acelaya** [comment]
I probably need to improve the contributing doc, as it's obviously not clear 😅

What it means is that you should create a ticket, and wait for feedback there BEFORE you open the PR.

Doing both at the same time does not really make any difference.

**Comment by syserr0r** [comment]
My bad, anything you'd like me to do/change?
