### ISSUE TITLE
shlink/X/foo/bar expected to resolve to Y/foo/bar

### ISSUE THREAD

**Issue by gww-parity** [shlinkio/shlink#1080]
Somewhere in between bug report and feature request:

#### How Shlink is set-up

* Shlink Version: x.y.z
* PHP Version: x.y.z
* How do you serve Shlink: Self-hosted Apache|Self-hosted nginx|Self-hosted swoole|Docker image
* Database engine used: MySQL|MariaDB|PostgreSQL|SQLite (x.y.z)

#### Summary

* https://ourshlink/XYZ

resolves -> https://abc/XYZ

but 

* https://ourshlink/XYZ/
* https://ourshlink/XYZ/document.md

does not resolve.

#### Current behavior

For:  https://ourshlink/XYZ -> https://abc/XYZ

But

* https://ourshlink/XYZ/
* https://ourshlink/XYZ/document.md

does not resolve.

#### Expected behavior

For:  https://ourshlink/XYZ -> https://abc/XYZ

We get

* https://ourshlink/XYZ/ -> https://abc/XYZ/
* https://ourshlink/XYZ/document.md -> https://abc/XYZ/document.md

**Comment by innocuoussoul** [comment]
+1 for this.

**Comment by acelaya** [comment]
Hey @gww-parity, I need a bit of clarification on this one, as I'm not really getting what you mean.

 Are you saying that short urls should behave like this, or do you mean this should happen when using the BASE_URL redirect?

Also, if you mean the first one, do you expect all the short urls to behave like this, or only those which have been configured to do so?

**Comment by gww-parity** [comment]
> Are you saying that short urls should behave like this, or do you mean this should happen when using the BASE_URL redirect?

Basically for short link "L" configured in a system that redirects person to some destination "D",

if  there is "/" slash after "L", followed by whatever , i.e. : "L/..." it should redirect person to "D/...".

I apologize but I didn't got "using the BASE_URL redirect" part - therefore if my question does not address your concerns could you clarify what you meant by this?

> Also, if you mean the first one, do you expect all the short urls to behave like this, or only those which have been configured to do so?

To me it would make sense if all urls would behave like this (or this be a default), but maybe there is reason behind why it should be configurable.

**Comment by acelaya** [comment]
Thanks @gww-parity. This answers my question 🙂

**Comment by acelaya** [comment]
@gww-parity @innocuoussoul this is now implemented. Coming to Shlink 2.8.0

I'll probably release a v2.8.0-alpha.1 version later this week including this. If you can test it, it would be amazing.

**Comment by acelaya** [comment]
I have just released the alpha version https://github.com/shlinkio/shlink/releases/tag/v2.8.0-alpha.1

If you use the docker image, wait until this workflow finishes succesfully https://github.com/shlinkio/shlink/actions/runs/1036763865

**Comment by chrisp23** [comment]
Testing via the docker image, doesn't seem to be working as intended.

added the following as a link: https://acme.somewebsite.com with shortlink "testtest"

go.somewebsite.com/testtest forwards correctly

go.somewebsite.com/testtest/1234 fails to redirect to https://acme.somewebsite.com/1234

**Comment by acelaya** [comment]
I forgot to mention that the feature is disabled by default, as it would be a breaking change otherwise.

For the docker image, you need to pass the `REDIRECT_APPEND_EXTRA_PATH` env var with value true, as in `REDIRECT_APPEND_EXTRA_PATH=true`.

That will enable it.

**Comment by chrisp23** [comment]
heh. that was it!
