### ISSUE TITLE
Migration issue (500  / AbstractMySQLDriver.php Permission denied)

### ISSUE THREAD

**Issue by tacerus** [shlinkio/shlink#1081]
#### How Shlink is set-up

* Shlink Version: Shlink 2.4.2
* PHP Version: PHP 7.4.6 (FPM)
* How do you serve Shlink: Self-hosted nginx (1.19.10)
* Database engine used: MySQL (Percona XtraDB Cluster Server 8.0.22-13.1)

#### Summary

Hi,

first of all I apologize for opening an issue about such an outdated version of Shlink and the possibly unsupported setup. I run this instance of Shlink since a long time with no issues, it run very reliably and I never had to touch anything - probably part of why I never realized newer versions have been released.
I now wanted to move the instance to a new server, but encounter some issues - since I already copied the data I figured it would be best to get the existing instance running on the new server before I attempt to upgrade to a new version of Shlink.

What I did:
- Copied the shlink/ and shlink-web/ directories to the new webserver's serving location
- Dumped the datbase, and imported it on the new server
- Created nginx vhost configurations for Shlink and the Shlink webclient according to the provided examples
- Re-created the directory and database users and permissions (created the exact same Unix users and groups for Shlink, even with the same UID and GID, and created the new MySQL role with the same name, password and full grants on the Shlink database - the database name, user and password I verified to match the values set in the Shlink configuration)
- Switched all relevant DNS records over to the IP addresses of the new server

What works:
- I can fully operate the Shlink CLI and access my existing Short links through it

What does not work:
- Accessing existing short links through the browser: Visible is a "Oops! We encountered a 500 Internal Server Error error." page, the browser console just logs a GET 500 error, and the Shlink log in shlink/data/log/shlink<latest date>.log print what looks like Permission issues on either the SQL driver's PHP file or the database itself - I was not able to fully understand it and uploaded the output from the point of trying to access a short URL here: https://pasta.lysergic.dev/?95681100bf142272#3f5Hj1vkuYcoEXpVw4zEKw8tqBdrYaC2EkSR7mb7n3HT
- Accessing the Shlink Web Client - it shows a "Oops! Could not connect to this Shlink server.", and the browser console logs a GET 503 error - checking the REST API's health site directly (which is what seemingly is also the cause for the web client not connecting) reveals:
`{"status":"fail","version":"2.4.2","links":{"about":"https://shlink.io","project":"https://github.com/shlinkio/shlink"}}` - Trying to access the API no log output is generated in shlink/data/log/shlink<latest date>.log

What I attempted:

- I verified the database permissions, and seeing the CLI allows me to list domains and all my short URLs with no errors I assume those should be fine (correct me?)
- I attempted executing shlink/bin/update - this ran through with no errors
- I attempted executing db:migrate - this ran through with no errors
- I verified the API key in api-key:list matches the one in the Shlink web configuration
- Checked if nginx, php-fpm or mysqld log anything related to Shlink - this is not the case

I would highly appreciate if someone could have a look at my logfile and possibly share an idea as to what else I could check. I feel like I did everything to properly migrate the instance but missed a small piece. Again, I am aware of my version of Shlink being outdated, and my SQL server possibly being unsupported and understand if this is out of bounds of the regular troubleshooting advice. I am opening this issue since I have a lot of short URLs and wanted to avoid loosing them all. If it is my only option, I will of course go for the fresh install, however if someone has an idea that would allow me to keep my data and get my migrated instance running, that would save a lot of hassle. I basically figured it's at least worth a shot asking here. :-)

Thank you very much for reading (and of course for the great program!).

**Comment by acelaya** [comment]
By googling that MySQL error, it seems as if your credential were wrong.

The first thing that comes to my mind is that you could have brought the cached config file from your old instance, which is likely to have weird side effects.

Check if you have a `data/cache/app_config.php` file, and if so, delete it. Then try again.

**Comment by tacerus** [comment]
Hi, thank you for the input. I assumed if I am able to access the data through the CLI, this meant the database connection was successful. I have this file and removed it, but the behavior unfortunately is still the same.

I now attempted changing the MySQL user password and the parameter in config/params/generated_config.php as well, that unfortunately did not change the behavior either.

**Comment by acelaya** [comment]
It's going to be quite hard to find where is the culprit for this, so I would recommend you did a clean install of the same Shlink version (2.4.2), complete the installation process, check if new links work on a clean database, and then delete that database and replace it with the export containing all your data.

Shlink itself is stateless (or it should be considered stateless), so you shouldn't need to bring the folder itself from your old server, just the data.

**Comment by tacerus** [comment]
Thank you! Apparently some table schemes were wrong not allowing it to write. I dumped the database again with create options and disabled locks and shlink is now living happily on the new system with my existing data.
