### ISSUE TITLE
API use fail, 500 Internal Server Error

### ISSUE THREAD

**Issue by vidalpascual** [shlinkio/shlink#1083]
#### How Shlink is set-up

* Shlink Version: 2.6.2
* PHP Version: 8.0.2
* How do you serve Shlink: Docker image
* Database engine used: MariaDB (10.5.4) in Docker

#### Summary

After upgrade from Shlink 2.3, I can't use the API POST method to create a new short URL. I get a 500 Internal Server Error. If I try to create a new short link using API GET method, all works fine, but with that method I cant use tags.

#### Current behavior

POST request to https://domain.com/rest/v2/short-urls
  with _X-Api-Key=my API Key_ in the headers
  with _longURL=https://www.google.com/_ and _tags=other_ in the body.

I get:
```
{
    "title": "Internal Server Error",
    "type": "INTERNAL_SERVER_ERROR",
    "status": 500,
    "detail": "An unknown error occurred."
}
```

#### Expected behavior

POST request to https://domain.com/rest/v2/short-urls
  with _X-Api-Key=my API Key_ in the headers
  with _longURL=https://www.google.com/_ and _tags=other_ in the body.

I should get:
```
{
  "shortCode": "string",
  "shortUrl": "string",
  "longUrl": "string",
  "dateCreated": "2021-05-04T09:00:34.700Z",
  "visitsCount": 0,
  "tags": [
    "string"
  ],
  "meta": {
    "validSince": "string",
    "validUntil": "string",
    "maxVisits": 0
  },
  "domain": "string",
  "title": "string"
}
```

#### How to reproduce

Trying a new API POST request to my server.

**Comment by bitwon** [comment]
@acelaya Same problem on our side.

**Comment by bitwon** [comment]
@vidalpascual I looked into the container logs and I see that it was a change in the API. You have to use an array to define your tag/s. 

`{
    "longUrl": "https://github.com/shlinkio/shlink/issues/1083",
    "tags": ["Github issue 1083"],
    "findIfExists": true,
    "title": "Hello World!"
}`

**Comment by vidalpascual** [comment]
> @vidalpascual I looked into the container logs and I see that it was a change in the API. You have to use an array to define your tag/s.
> 
> `{ "longUrl": "https://github.com/shlinkio/shlink/issues/1083", "tags": ["Github issue 1083"], "findIfExists": true, "title": "Hello World!" }`

This was the case. Thank you so mucho for the solution!
