### ISSUE TITLE
Custom link alphabet/charset

### ISSUE THREAD

**Issue by pxeger** [shlinkio/shlink#1086]
#### Summary

It would be nice if you could customise the alphabet or set of characters used to generate the random shortlinks, e.g. to make them more friendly to type in manually by making them all uppercase or disambiguating lowercase `L`, uppercase `i`, and `1`. It could also allow users to include extra special characters in the URL to provide higher possible information density.

**Comment by pxeger** [comment]
You can modify the alphabet manually in `module/Core/functions/functions.php`. Maybe it could be part of the installation script to do that too?

**Comment by acelaya** [comment]
This used to be possible and it was a source of a lot of issues and confusion, so I ended up removing it.
