### ISSUE TITLE
`visit:locate` should be periodicaly runned by the docker container

### ISSUE THREAD

**Issue by mikafouenski** [shlinkio/shlink#1089]
Hello,

I think it should be nice if the shlink command `visit:locate` was triggered directly inside the docker container.

For me, running shlink shouldn't be more than spinning up the images.

In the [documentation](https://shlink.io/documentation/long-running-tasks/#long-running-tasks) it's written:
>When serving Shlink with swoole, locating visits is automatically done just after redirecting end users. However, it might be a good idea to have previous scheduling in place, as a backup in case some of those asynchronous processes fail.

I thought the docker image was running swoole. :thinking:

Anyway, I really like your software, this is just an improvement point.
Kind regards,
Mika

---
Using docker image [shlinkio/shlink:2.6.2](https://hub.docker.com/layers/shlinkio/shlink/2.6.2/images/sha256-eaf9ba24ffa5b36b26e1916dabf8a7df060da7bcf7f9ca24b698ef3bd5a4f97f?context=explore)
With env var `ANONYMIZE_REMOTE_ADDR: "false"` and postgres database.

**Comment by acelaya** [comment]
> Anyway, I really like your software, this is just an improvement point.

Thanks for the kind words 🙂 

As per your request, it's a bit tricky.

Usually it's not a good practice to have that kind of side effect on docker images.

The image should just do one thing once started, and scheduling tasks and such is up to you.

That said, I should probably clarify that in the docs, and maybe add some example of how to schedule that on the main container-based infrastructures.
