### ISSUE TITLE
Support trailing slashes

### ISSUE THREAD

**Issue by bahuma20** [shlinkio/shlink#1090]
Currently, when i try to visit an url with a trailing slash after the slug, i get an 404.

Some browsers do that automatically.

Could it be implented that trailing slashes are always removed before finding a slug that matches?

The end result should be a situation, where both of those links work:
- `https://myshort.link/test`
- `https://myshort.link/test/`

**Comment by acelaya** [comment]
I was going to consider this a bug (which probably is the case), but at the same time, it's kind of breaking change if the behavior changes and someone was expecting the trailing slash to throw a 404.

Because of that, I will investigate if I can implemente it as an option you can opt-in to.

**Comment by acelaya** [comment]
Hey!

I'm going to close this, as it's more complex than I anticipated, and it's actually pretty easy to achieve with any web server:

* Nginx: https://ubiq.co/tech-blog/remove-trailing-slash-in-nginx/
* Apache: https://ubiq.co/tech-blog/how-to-remove-trailing-slash-in-apache/
* Caddy: https://caddy.community/t/efficient-remove-trailing-slash-redirect/3289

**Comment by acelaya** [comment]
This will be supported in Shlink 3.3.0, with optional opt-in via env var/config option.
