### ISSUE TITLE
Expose requested path and domain in "not-found" redirects

### ISSUE THREAD

**Issue by matiasgarciaisaia** [shlinkio/shlink#1105]
#### Summary

I'd like a way to include the requested (and missing) short URL info when redirecting with `INVALID_SHORT_URL_REDIRECT_TO`.

I'm imagin using "variables" like [Google Chrome's `%s` in keywords](https://support.google.com/chrome/answer/95426?co=GENIE.Platform%3DDesktop&hl=en#zippy=%2Curl-with-s-in-place-of-query-field).

So if `INVALID_SHORT_URL_REDIRECT_TO` is set to `https://fallback.example.com/%s?domain=%d`, requesting a non-existing `https://shlink.example.com/this-is-not-here` will redirect users to `https://fallback.example.com/this-is-not-here?domain=shlink`.

Variations that I can think of: URL encoding or not (maybe `%s` vs `%S`?), leaving default domain absent (`?domain=`) vs filling it anyway. I may be missing other options.

#### Background

I'm setting a single Shlink instance with private and public links. Private links go through an [OAuth2 Proxy](https://oauth2-proxy.github.io/oauth2-proxy/) that checks visitors are authorized (ie, belong to my company's Google Workspace) and then just forward the requests to the single Shlink instance that defaults to the public domain.

So my Shlink instance's default domain is `example.com`, and then I have `private.example.com` that reverse-proxies (with auth!).

We were previously using Google Short Links (which will die next week), that served both public and private links on the same `example.com` domain. So I need to keep supporting both `example.com/this-is-public` taking you to youtube.com and `example.com/this-is-private` taking you to `private.example.com/this-is-private` (which would eventually take you to `super-secret.example.com/secret.txt` if you're authenticated).

I plan to set the `INVALID_SHORT_URL_REDIRECT_TO` of the Shlink instance to `https://private.example.com/%s` (or whatever), so when `https://example.com/this-is-private` fails, it redirects the user to `https://private.example.com/this-is-private`.

There may be other useful use-cases - I can't come up with them now.

**What do you think about the feature?** Whenever we have designed it, I can try implementing it.

-----

As an aside, I've currently worked around the issue by manually creating redirects from example.com/this-is-private to https://private.example.com/this-is-private, but it isn't nice at all.

**Comment by acelaya** [comment]
I think this shouldn't be super hard to implement, and could be applied to the three "not found" redirects.

However, I would use more descriptive placeholders, as `%s` and `%d` might not be that intuitive, and they conflict with placeholders used in printf functions.

Maybe `%ORIGINAL_PATH%` and `%DOMAIN%` would be better. The latter would be supported in `INVALID_SHORT_URL_REDIRECT_TO`, `REGULAR_404_REDIRECT_TO` and `BASE_URL_REDIRECT_TO`, and the former, in `INVALID_SHORT_URL_REDIRECT_TO` and `REGULAR_404_REDIRECT_TO`.

That would result in URLs like `https://fallback.example.com/%ORIGINAL_PATH%?domain=%DOMAIN%`.

I will also try to check of the placeholders were set as query params, URL-encoding them in that case. That allows for any combination:

* `https://fallback.example.com/foo?domain=%DOMAIN%&original-path=%ORIGINAL_PATH%`
* `https://fallback.example.com/foo/%DOMAIN%/%ORIGINAL_PATH%`
* Etc...
