### ISSUE TITLE
API Role for creating short URLs only

### ISSUE THREAD

**Issue by calvinbui** [shlinkio/shlink#1106]
#### Summary

I'm currently using Shlink with PrivateBin to shorten URLs.

PrivateBin will do an API call through the user's browser to generate a short URL with Shlink. The network call can be viewed by the user which exposes the API key. This can then be used perform other operations against the Shlink API.

I would like there to be an API key role that is 'create only', so that key can't be used to view previously created short URLs.

**Comment by acelaya** [comment]
Duplicates https://github.com/shlinkio/shlink/issues/473
