### ISSUE TITLE
Pagination not working correctly with tags or searchTerm

### ISSUE THREAD

**Issue by toppev** [shlinkio/shlink#1109]
#### How Shlink is set-up

* Shlink Version: 2.7.1
* How do you serve Shlink: Docker image
* Database engine used: MariaDB

#### Summary

When fetching multiple pages from the `/rest/v2/short-urls` endpoint using either the `tags` or `searchTerm` query parameters, the results include some duplicates (about 20 duplicates out of 300 total entries when perPage=100, on different pages, I think).

#### Expected behavior
Return all distinct entries.

#### How to reproduce

1. Create multiple tinyurls
2. Use  `/rest/v2/short-urls?searchTerm=something` (maybe `&perPage` too)
3. If you combine all returned entries, there are missing entries replaced with duplicates
4. If you use perPage greater than total number of entries it does not return any duplicates

**Comment by acelaya** [comment]
I have tried several combinations and haven't been able to reproduce it.

Could you provide some dump of a dataset where this can be reproduced? I guess it requires some combination and I'm just not being able to get there.

It would also be helpful to get some of the requests where you can reproduce it for that dataset (with the tags/searchTerm in the query).
