### ISSUE TITLE
how to add a custom domain?

### ISSUE THREAD

**Issue by saikarthikp9** [shlinkio/shlink#1111]
just exploring options and i was going through the documentation, I don't see any mention of a DNS entry for the custom domains. What is the setup process involved here?

**Comment by acelaya** [comment]
You don't need any special setup on the DNS. Just point all the domains you want Shlink to handle, to your server, as you would usually do with any other application.

**Comment by saikarthikp9** [comment]
thanks, that makes sense! Will try it out
