### ISSUE TITLE
Allow disabling query parameter forwarding

### ISSUE THREAD

**Issue by antwonw** [shlinkio/shlink#1112]
Right now Shlink passes URL parameters, such as UTMs. However, there are instances where the long URL appends UTM URL parameters that one might not want Shlink to pass along. It would be nice if an Extra Check could be added at the creation of the short url to strip the URL parameters before passing the user along.

Example with Remove Parameter checked on Short URL:
Mailchimp campaign is sent with a link to a Shlink URL. Mailchimp appends UTM to the Shlink URL. User clicks Shlink URL in Mailchimp Campaign. Shlink redirects the user to the Long URL with no Mailchimp UTM parameters.

**Comment by acelaya** [comment]
Shlink forwrads the query params by default, but making it optional shouldn't be hard to do.

**Comment by acelaya** [comment]
This is now implemented. To be released in v2.9.0
