### ISSUE TITLE
How to use the REST APIs locally between two containers? 

### ISSUE THREAD

**Issue by saikarthikp9** [shlinkio/shlink#1117]
* Shlink Version: 2.7.1
* How do you serve: Docker image
* Database engine used: PostgreSQL

#### Summary

**Setup**:
I have shlink up and running in an AWS ECS container and exposed publicly behind a load balancer which is accessible and usable. I have a domain name: https://shlink.example.com pointing to the loadbalancer. 
I have another APP container running alongside shlink from where I need to make REST API calls. Currently I am using the https://shlink.example.com to reach the shlink server from the APP container but quite often has a big lag about up to 20 secs per API call. By setting the following env vars: SHORT_DOMAIN_HOST and SHORT_DOMAIN_SCHEMA, it only accepts queries through this URL. 

**Question**: 
How can I reach the shlink server without publicly resolving this domain address (shlink.example.com) Is there a way to reach the domain locally while also having the server exposed publicly?

**Comment by acelaya** [comment]
That has nothing to do with the SHORT_DOMAIN_* env vars. Those are used only for certain internal logics and to allow Shlink to generate proper short urls as part of API responses.

Shlink will accept internal requests if the networking is properly set up.
