### ISSUE TITLE
migrate from dist file version installation to Docker version

### ISSUE THREAD

**Issue by raldridgenctm** [shlinkio/shlink#1126]
Is there any way to migrate existing data from a dist file version installation to the Docker version?

**Comment by acelaya** [comment]
What database are you using?

(BTW, please, next time feel in the template info. I'm planning on setting-up a bot that will reject tickets which do not fulfill the template)

**Comment by raldridgenctm** [comment]
Thanks.  Currently using MySQL.  Version 2.6.2 of Shlink with PHP 7.4.

**Comment by acelaya** [comment]
Then you can just configure the same database and you won't loose any data.

**Comment by acelaya** [comment]
> I'd just migrate the data from the current database to the MySQL Docker database?

You don't need to migrate anything. Just use the same database.

> And can I install the latest Docker version of Shlink with MySQL and not have any issues with database changes due to Shlink version change?

Yes. When the docker container starts-up, it will run the database migrations and get everything up to date.

**Comment by cirrusflyer** [comment]
Can I use this tool instead?  I'm going to migrate from one Shlink instance using MySQL to another using Mariadb.

https://github.com/shlinkio/shlink-importer

**Comment by cirrusflyer** [comment]
Thoughts?
