### ISSUE TITLE
Query parameters are removed from longUrl

### ISSUE THREAD

**Issue by martijnmichel** [shlinkio/shlink#1129]
I am creating a short version of a firebase dynamic link to my app through the api:

URL: https://stroopwafel.page.link/?apn=org.stroopwafel.music.app&ibi=org.stroopwafel.music.app&amv=0&ofl=https://sonid.app&isi=1490221762&ipbi=org.stroopwafel.music.app&link=https://stroopwafel.page.link/--exercise--interval--m2

But what I get back is: (notice the missing query params)
```
crawlable: false
dateCreated: "2021-07-28T14:04:19+00:00"
domain: null
longUrl: "https://stroopwafel.page.link/?apn=org.stroopwafel.music.app"
meta: {validSince: null, validUntil: null, maxVisits: null}
shortCode: "vV6Zq"
shortUrl: "https://link.sonid.app/vV6Zq"
tags: []
title: null
visitsCount: 0
```

**Comment by martijnmichel** [comment]
Seems it works when I use the POST endpoint.

**Comment by acelaya** [comment]
What were you using if not the POST endpoint?

**Comment by martijnmichel** [comment]
The GET endpoint..

**Comment by acelaya** [comment]
In that one you need to make sure the long URL is urlencoded, as it travels as a query param itself.

**Comment by martijnmichel** [comment]
I did find another bug however, when using the shortURL it routes correctly to the app but then in the app only gives me the ?link= query param of the longUrl. When I go to it directly (with a button on my website) the whole url is there.
