### ISSUE TITLE
Add ability to clear short URL visits

### ISSUE THREAD

**Issue by acelaya** [shlinkio/shlink#1148]
#### Summary

Allow to reset the visits for a short URL, via endpoint or CLI command.

- `DELETE /short-urls/{shortCode}/visits{?domain}`
- `short-urls:visits-clear` / `short-urls:visits-purge` (start with the word `visits` so that it is listed next to `short-urls:visits`)

Display confirmation on CLI command, stating once done, it cannot be undone.

When shlink-web-client implements the endpoint, also add confirmation where the user needs to perform an action to proceed.

Take into consideration API key roles. An API key should not be allowed to purge visits on a short URL that it cannot fetch (it should work out of the box, but it's worth double checking).

**Comment by acelaya** [comment]
A bit of an edge case and not really useful.

Can be done at database level if the specific case ever comes to place.

**Comment by UCI-MIND-IT** [comment]
Hi! I was about to create a new feature request issue but managed to find this one. Users in our organization have come across 2 scenarios where this feature would be wonderful:

* It is common for our Shlink users to test shortlink functionality by visiting a new shortlink that was just created. Shlink will track these "dev/debug visits" in the Visit Stats page.
* We have prepared a large batch of shortlinks for a new social campaign, but a handful of links have already received visits according to their Visit Stats page despite us not releasing any of these links to the public (only _some_ are marked as coming from a bot or crawler, so we can't rely on the "Exclude potential bots" filter).

For both of these cases, we would like to wipe the Visit Stats clean for the affected shortlinks so we can be assured that the visit stats page reports as much relevant traffic as possible.

Our current band-aid solution is to delete the affected shortlinks and recreate them, which takes time. I checked the [CLI entry point documentation](https://shlink.io/documentation/command-line-interface/entry-point/) for any advanced/hidden features and it seems like there are only options to _list_ visits, but not delete them or manipulate them in any way.

Sorry to revive this years-old ticket, but would you reconsider implementing this feature? If not, how can I go about doing this at the database level? Thank you for your time!

**Comment by acelaya** [comment]
Re-opening this.
