### ISSUE TITLE
Allow setting default configuration for QR codes

### ISSUE THREAD

**Issue by acelaya** [shlinkio/shlink#1149]
#### Summary

Currently, QR codes have some sensitive hardcoded default options (format, size, etc).

If one wants to overwrite those, the URL needs to receive the new values as query params.

Allow defining custom defaults, via configuration or env vars, that would be used instead of the hardcoded defaults if not provided via query params.

**Comment by MartinHotmann** [comment]
As it also applies to the "QR Code" topic, I would like to ask for a download button which makes it more easy to download the configured QR Code. Sometimes we want to share the actual QR Code and not yet again another Link to it.

**Comment by acelaya** [comment]
That would be more a topic for shlink-web-client than Shlink itself.

Basically the existing url IS effectively the one to download it.

In fact, you can already right-click on the image and save it.

But yeah, adding a button that does it for you, should be easy.

**Comment by acelaya** [comment]
@MartinHotmann I have already implemented a download button for QR codes in shlink-web-client. However, it requires an improvement in Shlink, so the button will be hidden until a Shlink v2.9.0 instance is consumed, which is not yet available.
