### ISSUE TITLE
Typo in api-sec for PATCH /domains/redirects

### ISSUE THREAD

**Issue by codaamok** [shlinkio/shlink#1151]
Currently, the description is:

> Sets the URLs that you want a visitor to get redirected to for ot found" URLs for a specific domain

Perhaps needs to be:

> Sets the URLs that you want a visitor to get redirected to for "not found" URLs for a specific domain

https://api-spec.shlink.io/#/Domains/setDomainRedirects

**Comment by acelaya** [comment]
Thanks!
