### ISSUE TITLE
Missing SSL Support for MySQL connection

### ISSUE THREAD

**Issue by Towl** [shlinkio/shlink#1167]
## Description

It's not currently possible to configure shlink when the DB is a mysql/mariadb with ssl enforced.

Here is the output we if nothing is done on the configuration:
```bash
Creating fresh database if needed...

In AbstractMySQLDriver.php line 128:

  An exception occurred in driver: SQLSTATE[HY000] [3159] Connections using i
  nsecure transport are prohibited while --require_secure_transport=ON.


In Exception.php line 18:

  SQLSTATE[HY000] [3159] Connections using insecure transport are prohibited
  while --require_secure_transport=ON.


In PDOConnection.php line 39:

  SQLSTATE[HY000] [3159] Connections using insecure transport are prohibited
  while --require_secure_transport=ON.


db:create
```

## To reproduce

You can cherry-pick the following commits: 
* docker environment for ssl test : https://github.com/fc-tms/shlink/commit/2909843ef3b3366def150c19686dff1340c27355
* mysql config to enable ssl : https://github.com/fc-tms/shlink/commit/fbdd271ffd1699ce945d54c0dcb112d46b468ed0

generate the self-signed certificates:
```bash
./gen-certs.sh
```

And then run the docker-compose:
```bash
docker-compose -f docker-compose.ssl-test.yml up
```
Maybe, shlink will start before the db and crash due to connection refused. Re-run the up command when the db is ready and you'll see the error mentioned above. You can try configure shlink however you want. I wasn't able to find a way to make it works without changes in the code.

## Investigation

I figured out that the issue is coming from Doctrine support of `pdo_mysql` driver. Doctrine doesn't provide a way to configure the SSL on this driver as describe here: https://www.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/configuration.html#pdo-mysql

## Potential solution

Use `mysqli` instead of `pdo_mysql` for this. I think `pdo_mysql` could simply be replaced by `mysqli`, but maybe both needs to be installed to handle all the cases.

Anyway, in my case, I did the following changes to make it works:
* https://github.com/fc-tms/shlink/commit/ea0edbcab132aaa11cd41c38bb43016b3957023c
* https://github.com/fc-tms/shlink/commit/0ab89fd9d1c4b930232a3c47d64c4a682cff35d0

I didn't run all the tests but it solve my issue so I'm going to use it for now.
I hope this will help you improve your application. Let me know if you want to spend some time on it to integrate it properly.

**Comment by acelaya** [comment]
After some investigation, this is not going to be implemented.

In most of the cases it is not recommended to use SSL for the database connection anyway, as it potentially adds network overhead. Instead, the best approach is too avoid exposing the database outside your private network.

With that in mind, I would still consider implementing it if it was possible with the currently required driver, but having to use a different one adds a lot of extra complexity and possible combinations that will affect maintainability of the project.
