### ISSUE TITLE
Should the API error on a slug of `rest`?

### ISSUE THREAD

**Issue by NReilingh** [shlinkio/shlink#1173]
Just occurred to me that since the API uses `/rest` as its path, there might be unexpected/undefined behavior if you create a shortlink with a slug of `rest`. Not sure if there are other routes that this would also apply to.

The API currently accepts this as a slug, but `https://shlink/rest` will always be processed as an API route, so an unaware user will receive an unexpected response (Chrome errors, Safari downloads an XML file) if they try to access the shortlink. A solution would be to enhance `short-url:generate` and `short-url:list` to error or warn if a reserved slug is requested.

**Comment by acelaya** [comment]
It should probably throw an error, but it has been like this for 5 years and no one has complained.

I think it's an edge case.
