### ISSUE TITLE
PHP Parse Error upon installation

### ISSUE THREAD

**Issue by CStafford-14** [shlinkio/shlink#1176]
#### How Shlink is set-up

* Shlink Version: 2.8.1
* PHP Version: 7.4.3
* How do you serve Shlink: Self-hosted Apache
* Database engine used: MySQL

#### Summary

When trying to run the install script (via command line on Ubuntu 20.04), I get the following error: `PHP Parse error:  syntax error, unexpected '=>' (T_DOUBLE_ARROW) in /home/cesium/shlink2.8.1_php8.0_dist/module/Core/functions/functions.php on line 55`

I noticed on the troubleshooting page that this could be due to the PHP version on the CLI isn't late enough. However, running `php -v` does show my system installation is 7.4.3, which is officially stated to be supported by Shlink.

**Comment by acelaya** [comment]
Shlink 2.8 no longer sports PHP 7.4

Where did you see it is supported?

**Comment by CStafford-14** [comment]
On the website.

![Screenshot from 2021-09-13 12-03-58](https://user-images.githubusercontent.com/35039669/133118246-99b7f7ea-e96f-40b5-8cc4-858a1fdd3e00.png)

**Comment by acelaya** [comment]
I was almost sure I changed that 🤔😅

Ok, sorry about that. I removed support for PHP 7.4 in Shlink 2.8
