### ISSUE TITLE
"No URL found with short code" but included in the DB

### ISSUE THREAD

**Issue by herrseverin** [shlinkio/shlink#1177]
I use an admin API key. I have given a restricted API key to colleagues. When I want to look at the visits for URLs generated with the restricted API key, I always get a red box: No URL found with short code ...

But in the database I see the URL and the visits. What am I doing wrong? Which setting do I have to change? Thank you very much.

Server: v2.8.0 - Client: v3.2.1

**Comment by acelaya** [comment]
What kind of restricted API key is it?

Also, do you mean that you see no URLs when accessing with the restricted API key, or you don't see the URLs created with the restricted API key when accesing with the admin one.

Also, this "red box" you mention doesn't sound good. Can you share a screenshot?

**Comment by herrseverin** [comment]
Sorry for my late reply. Been a bit busy lately. Its both Domain and Author restricted. I see the URL created with the restricted API key when accessing with the admin one, but when I try to visit the stats I get this message. [https://imgur.com/a/HaHsep8](https://imgur.com/a/HaHsep8) 

But I do see the stats in the Database. And the Link is there and working.

**Comment by acelaya** [comment]
Does this URL use the default domain, or a different one?

**Comment by herrseverin** [comment]
Thank you for reopening. Default domain.

**Comment by acelaya** [comment]
Do you get that error when accessing with the non-admin API key?

Also, how is it in the default domain if the API key used to create it is restricted to one non-default domain?

**Comment by acelaya** [comment]
I think I'm missing something in the picture, because I'm being unable to reproduce this.

I have tried manually, by creating short URLs with one API key, and then I can perfectly interact with them through an admin API key.

I have even added more integration tests trying to reproduce it (see #1193). They all passed as expected, and there was already an extensive set of integration and E2E tests covering API key permissions.

The only way I can proceed any forther is if I get a copy of your exact database, but I can understand if you are not willing to do that.

**Comment by herrseverin** [comment]
I think I did something wrong. I can't reproduce the error with other API keys. So its just this single API Key. So the chance is very high that I did something wrong somewhere. I thought maybe there was a quickfix or something. But then I just assign a new API Key to the team. There is no data loss after all. Thank you very much for the effort. If there is anything else I can do, let me know.

**Comment by acelaya** [comment]
Thanks for the confirmation

**Comment by kzshantonu** [comment]
Hi, I seem to be having this issue. domain.name is set at the default domain, aka if I run `shlink domain:list` I do get Is default = yes for domain.name. If I do `shlink short-url:visits -d domain.name shortcode` I get all the visits correctly, but if I don't specify `-d` I don't. What am I doing wrong?
