### ISSUE TITLE
Parse error: syntax error, unexpected '=>' (T_DOUBLE_ARROW) in functions.php

### ISSUE THREAD

**Issue by Linutux** [shlinkio/shlink#1182]
I have installed shlink but can't open it, because I only get the following error message:

> Parse error: syntax error, unexpected '=>' (T_DOUBLE_ARROW) in /var/customers/webs/null/domain.de/module/Core/functions/functions.php on line 55

I use php 8.0.10 with apache2

**Comment by acelaya** [comment]
I think you are actually not using PHP 8.

Sometimes systems have multiple versions and you see the right one from CLI, but the wrong one is used from web requests

**Comment by Linutux** [comment]
You are right. I am sorry!
