### ISSUE TITLE
PgBouncer unexpected response from query on db:create

### ISSUE THREAD

**Issue by Antiarchitect** [shlinkio/shlink#1183]
#### How Shlink is set-up

Official docker image 2.8.1

#### Summary

Connecting via PgBouncer I get:

```
Creating fresh database if needed...                                                           
In AbstractPostgreSQLDriver.php line 88:                                                       
                                                                                               
  An exception occurred in driver: SQLSTATE[08006] [7] ERROR:  unexpected response from login query
                                                                                               
In Exception.php line 18:                                                                      
                                                                                               
  SQLSTATE[08006] [7] ERROR:  unexpected response from login query                             
                                                                                               
In PDOConnection.php line 39:                                                                  
                                                                                               
  SQLSTATE[08006] [7] ERROR:  unexpected response from login query                             
                                                                                               
db:create
```

Connection directly goes absolutely fine.

The database is pre-created in my case so if I comment out https://github.com/shlinkio/shlink/blob/develop/docker/docker-entrypoint.sh#L7 everything after that goes fine (update and migrations) and the app is running perfectly. It seems `db:create` needs some extra permissions even if the database is already created.

#### Current behavior

./docker-entrypoint.sh cannot pass db:create phase even if database already created when connecting via PgBouncer

#### Expected behavior

./docker-enrypoint.sh passes normally

**Comment by acelaya** [comment]
I'm afraid I have never tested Shlink against this PgBouncer service. It works fine when conecting directly to a postgres instance or cluster, so I guess it does not completely fulfill the same interface.

Would be nice to get help from someone with experience with it.

**Comment by Antiarchitect** [comment]
I bet it tries to connect to the default database (which is postgres) when trying to create a new db without having sufficient permissions in my case. A little bit of sed magic did the trick.
