### ISSUE TITLE
URL generation algo ? (and related to security questions)

### ISSUE THREAD

**Issue by semangard** [shlinkio/shlink#1190]
Hello,

I haven't found into your doc the explanation on how the URL is dynamically generated when https://api-spec.shlink.io/#/Short%20URLs/createShortUrl is called for ex

Of course you can define the URL length
but :
- what are the supported characters ? alphanum + upper and lower case : right ?
- how random is the generated URL ?
- can two instances of shlink generate the same short URL at the same time (because based on the same algo and same parameters) ?

Also what are your recommendations regarding security.
Short URL could be sensitive : in that case what is the reasonable length to minimize brute-force ?

What are the embedded features against brute-force ?

Thanks and Regards

**Comment by acelaya** [comment]
> * how random is the generated URL ?

Shlink uses this library to generate the unique short codes https://github.com/PUGX/shortid-php

> * what are the supported characters ? alphanum + upper and lower case : right ?

Alphanum both lower and uppercase. It can be changed if you manually edit the code, but it's not officially supported. It used to be in Shlink v1.x, but it was a constant source of confusion and opened issues just for not understanding how it worked, so it was removed.

This is the logic to generate the short codes https://github.com/shlinkio/shlink/blob/develop/module/Core/functions/functions.php#L34

> * can two instances of shlink generate the same short URL at the same time (because based on the same algo and same parameters) ?

On paper, yes. Not very likely, but could potentially happen.

> Also what are your recommendations regarding security.
> Short URL could be sensitive : in that case what is the reasonable length to minimize brute-force ?
> What are the embedded features against brute-force ?

There's no mechanism against brute force. URLs are public by definition, so it wouldn't make a lot of sense. It's not a password.

The purpose of Shlink is not keeping URLs secret.

**Comment by semangard** [comment]
thanks for yours answers

BTW if shlink is used to deliver an URL in order to get a QRCode... the URL could become more sensitive
