### ISSUE TITLE
I want to dynamically change the domain that a short link points to, without changing the short_link

### ISSUE THREAD

**Issue by sbutler-gh** [shlinkio/shlink#1192]
#### Summary

Say I create the shortlink shlink.io/website-slides, pointed to URL_A.

I post that short-link in some comments and threads, and after some time, I have a new set of slides.  I don't want to go back and add messages everywhere I posted shlink.io/website-slides with some message like ('oh by the way, the updated slides are here at URL_B.')

Instead, I would just like to updated shlink.io/website-slides, so that it points to URL_B.

This is a feature that rebrandly does well, and it's the main reason I use rebrandly.

And in general, thanks for your work on this project!!

**Comment by acelaya** [comment]
This is already possible. You can just change the longUrl of any existing url
