### ISSUE TITLE
Allow long URL to be case sensitive, affecting findIfExists flag

### ISSUE THREAD

**Issue by davidstoker** [shlinkio/shlink#1208]
#### How Shlink is set-up

* Shlink Version: 2.9.1
* PHP Version: 8
* How do you serve Shlink: Docker image
* Database engine used: MySQL 5.7 (AWS Aurora)

#### Summary

Case-sensitive URLs are returning the same short link URL even when `findIfExists` is set to `true`.

#### Current behavior

In my deployed setup I have the `original_url` column with a `utf8_unicode_ci` collation. 

1. If I pass a URL like http://example.com/test with `findIfExists` set to `true`, I get a short link http://foo.com/abc123
2. If a pass a different URL (anything after domain should be case sensitive) like http://example.com/TeSt and `findIfExists` set to `true`, I get the same http://foo.com/abc123 short link back

#### Expected behavior

I expected differing results. It makes sense that an existing short code is already seen as existing since the `utf8_unicode_ci` is case-insensitive. 

I see that the `short_code` column is intentionally set to use a `utf8_bin` collation to ensure the UNIQUE constraint is case sensitive for short codes. Would it make sense to have a similar configuration for `original_url` to ensure that lookup of existing URLs is case-sensitive as well?

#### How to reproduce

0. Check MySQL database configuration and see if a case-insensitive collation is in use
1. Generate short link for a URL like http://example.com/test and note the result
2. Generate short link for URL like http://example.com/TeSt with `findIfExists` set to `true` and note that the same short code from step 1 was returned

**Comment by acelaya** [comment]
This is no longer applicable, now that Shlink supports `strict` and `loose` [modes](https://shlink.io/documentation/some-features/#short-urls-mode).
