### ISSUE TITLE
Errors on install (PHP 7.1)

### ISSUE THREAD

**Issue by rwsss** [shlinkio/shlink#122]
Greetings, I have warnings during installation process, on running a command `php bin/install` and the setup is interrupted by an error:

```
PHP Warning:  Unsupported declare 'strict_types' in /sata2/home/users/xreact/www/test.example.pro/module/Common/functions/functions.php on line 2
PHP Warning:  Unsupported declare 'strict_types' in /sata2/home/users/xreact/www/test.example.pro/module/CLI/src/Factory/InstallApplicationFactory.php on line 2
PHP Warning:  Unsupported declare 'strict_types' in /sata2/home/users/xreact/www/test.example.pro/module/CLI/src/Command/Install/InstallCommand.php on line 2
PHP Parse error:  syntax error, unexpected ':', expecting ';' or '{' in /sata2/home/users/xreact/www/test.example.pro/module/CLI/src/Command/Install/InstallCommand.php on line 172
```

As I said, I have php v7.1. Could you please advise? Thank you!

**Comment by acelaya** [comment]
I'm affraid you are not really using PHP 7.1, otherwise those errors won't ever come up.
You probably have more than one PHP version installed, and the one in your path is not PHP 7.1, but PHP 5.*, I guess.

Try running `php -v` from the terminal in order to see the actual PHP version.

**Comment by rwsss** [comment]
Indeed you are right! The version is 5.6.3. However it should be sufficient, as per installation [instructions](https://shlink.io/installation).

**Comment by acelaya** [comment]
Right, those instructions are outdated.

Shlink requires PHP 7 or greater since version [1.6](https://github.com/shlinkio/shlink/releases/tag/v1.6.0). I'll update the instructions as soon as possible. Thanks :)

**Comment by rwsss** [comment]
Thank you for lightning-fast support!
