### ISSUE TITLE
Add ability to purge Orphan Visits

### ISSUE THREAD

**Issue by adan89lion** [shlinkio/shlink#1222]
#### Summary
Letting user to purge orphan visits, or setup a schedule to purge after x amount of time is essential. My Shlink instance gets hit by Wordpress bots several times a day, so the Orphan Visits is full of ``https://example.com/wp/wp-login.php`` or ``https://example.com/blog/wp-login.php``.

Also, if a user visits or bookmarks a shortened link via Safari, the browser will attempt to access ``apple-touch-icon-precomposed.png`` and ``apple-touch-icon.png`` in the root path.

In a long term view, this chart will be meaningless since it's full of bot requests instead of administrators trying to find which link is obsolete but still being visited.

---

It would be useful if Shlink can:
- allow users to purge the Orphan Visits, and/or
- automatically rotate them after a specific amount of time (via the env variables)
without needing to meddle the database manually.

**Comment by acelaya** [comment]
Duplicates https://github.com/shlinkio/shlink/issues/1110
