### ISSUE TITLE
Tag unique constraint error in postgres

### ISSUE THREAD

**Issue by WanderingBrooks** [shlinkio/shlink#1226]
#### How Shlink is set-up

* Shlink Version: 2.8.1
* How do you serve Shlink: Docker image
* Database engine used: PostgreSQL

#### Summary

We are getting the following error from the API when creating multiple links at the same time

Error

```json
{
 "title": "Internal Server Error",
 "type": "INTERNAL_SERVER_ERROR",
 "status": 500,
 "detail": "An unknown error occurred."
}
```

In the docker container logs we see an error that a tag is being inserted multiple times and a unique constraint error is being thrown.

```
Next Doctrine\\DBAL\\Exception\\UniqueConstraintViolationException: An exception occurred while executing 'INSERT INTO tags (name) VALUES (?)' with params [\"bbq-id:177\"]:\n\n
SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint \"uniq_6fbc94265e237e06\"\n
DETAIL:  Key (name)=(bbq-id:177) already exists. in /etc/shlink/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:70\n
```

In our most recent occurence of the error 2 requests were sent at the same time 1 succeeded and 1 failed. They had 3 tags in common one of them being the 'bbq-id:117' in the error above. Could this be some kind of race condition?

Thanks for maintaining such an amazing tool any help would be greatly appreciated.

**Comment by acelaya** [comment]
Yes, this is a known issue that I haven't been able to fix yet.

It's indeed a race condition when two parallel requests are sending the same tag that is new, and both try to create it.

I tried to solve it via database locks, but it does not work as expected for nob-existing resources.

See https://github.com/shlinkio/shlink/issues/953

**Comment by WanderingBrooks** [comment]
Thanks for the quick response! We'll try to implement a fix on our side for now then :).

**Comment by acelaya** [comment]
If you find a solution, many people will be grateful if you contribute it to the project 🙂
