### ISSUE TITLE
Geolocation not working - IPs are not detected. 

### ISSUE THREAD

**Issue by ingeniousambivert** [shlinkio/shlink#1227]
#### How Shlink is set-up

* Shlink Version:  2.9.2
* PHP Version: 7.4.x
* How do you serve Shlink: Docker image
* Database engine used: PostgreSQL

#### Summary

I was initially using an nginx reverse proxy in front of the shlink instance, but with that the geolocation feature did not work, I would get unknown everytime. So I decided to get rid of the reverse proxy and hit the shlink instance directly, but the geolocation still shows unknown, there is no problem with the geolite configs, the api-key works, the visit commands work. But the geolocation doesn't. I am not sure what I am doing wrong. Can someone point out ?

Just for reference, here is my nginx config -

``` 
server {
    listen 80;
    location / {
        proxy_hide_header 'Access-Control-Allow-Origin';
        add_header 'Access-Control-Allow-Origin' '*' always;
        proxy_set_header Host $host;
        proxy_set_header Referer $http_referer;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Host $remote_addr;
        proxy_set_header X-Forwarded-Referrer $http_referer;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://server:8080;
        proxy_read_timeout 90s;
    }
}
```

And my .env for the docker instance - 

```
# Instance Configs
PORT=8080

# Domain Configs
DEFAULT_DOMAIN=localhost:8080
USE_HTTPS=false

# Postgres Configs
POSTGRES_USER=user
POSTGRES_PASSWORD=pass
POSTGRES_DB=shlink

# Primary Database Configs
DB_DRIVER=postgres
DB_USER=user
DB_PASSWORD=pass
DB_NAME=shlink
# DB_HOST=postgres
DB_HOST=shlink_postgres_1
DB_PORT=5432

# GeoLocation Database Configs
GEOLITE_LICENSE_KEY=123abc

# Docker Specific Configs
ENABLE_PERIODIC_VISIT_LOCATE=true

```

This is the response object for visits -

```
"visitLocation": {
        "countryCode": "",
        "countryName": "",
        "regionName": "",
        "cityName": "",
        "latitude": 0,
        "longitude": 0,
        "timezone": "",
        "isEmpty": true
      },
   ```
   
   I am guessing the `isEmpty` flag being `true` would mean that the IP address could not be captured ?     

PS. This is an amazing project. Huge thanks @acelaya. Great Work!!

**Comment by acelaya** [comment]
Can you check the remote_addr column in the visits table in the database? Does it have any values?

**Comment by ingeniousambivert** [comment]
> Can you check the remote_addr column in the visits table in the database? Does it have any values?

It has this value - `192.168.240.0` for every visit which is the subnet of the docker network I am running the instance on. So I  think I messed up something while setting up the instance with docker. Any clue what might be causing this?

**Comment by acelaya** [comment]
I'll convert this into a discussion, to see if anyone else has more knowledge about docker networking.
