### ISSUE TITLE
Redirect invalid shortcode to search query

### ISSUE THREAD

**Issue by onetreehiller** [shlinkio/shlink#1228]
#### How Shlink is set-up

* Shlink Version: 2.9.2
* PHP Version: 8.0.12
* How do you serve Shlink: Self-hosted nginx
* Database engine used: MariaDB

#### Summary

Not sure if this can be done: If a url with invalid shortcode like `https://mydomain.com/ITEM` is requested (**ITEM** is not a valid shortcode), can it be re-directed to a search query like `https://longurl.com/search/?search=ITEM`

I tried to set `./bin/set-option` [28] to `https://longurl.com/search/?search={ORIGINAL_PATH}`, but it will redirect to `https://longurl.com/search/?search=/ITEM`, which is an invalid search query with the leading slash. Ultimately, I want to redirect the URL to `https://longurl.com/search/?search=ITEM`. Is there a way to remove the leading slash `/`?

**Comment by acelaya** [comment]
No, it's not possible at the moment. You can only do it with the leading slash.
