### ISSUE TITLE
Cycling warnings during installation

### ISSUE THREAD

**Issue by rwsss** [shlinkio/shlink#123]
Greetings,

As I attempt to run `bin/install` with PHP 7.1  im getting warnings that are cycling endlessly unless I stop execution:

```
PHP Warning:  feof() expects parameter 1 to be resource, string given in /vendor/symfony/console/Helper/QuestionHelper.php on line 242
PHP Warning:  fread() expects parameter 1 to be resource, string given in /vendor/symfony/console/Helper/QuestionHelper.php on line 243
```

Strangely enough I tried this on another instance and it worked just fine.

Could you please advise?

**Comment by acelaya** [comment]
Sure. I'll investigate.
Thanks
