### ISSUE TITLE
Add a documented place to do a volume mount when using an internal SQLite database

### ISSUE THREAD

**Issue by hwittenborn** [shlinkio/shlink#1238]
Looking at the [standard installation instructions with the SQLite database](https://shlink.io/documentation/install-docker-image/#usage), I see that there's no volume mount to store the database data across container removals:

![image](https://user-images.githubusercontent.com/74838472/143664839-3d3f6e3e-9ae5-48cb-9760-7f7b41311bb1.png)

I feel like there should be a noted way to do such though, as otherwise any SQLite users are gonna have to redo their setup every time they recreate the containers.

**Comment by acelaya** [comment]
I'm afraid that is not possible. I tried in the past and it doesn't work 

See this https://shlink.io/documentation/troubleshooting/#how-to-keep-data-on-docker-image-between-container-recreations, and the issue it links to.

If you need to persist data, consider migrating to an external database.

**Comment by hwittenborn** [comment]
From the [linked issue](https://github.com/shlinkio/shlink-docker-image/issues/40#issuecomment-491924262):

> If the database file is exposed via a volume, then docker creates a file when the container is run, and then, when the database tool tries to populate the databse, it fails because it is not actually an SQLite-compliant file.

Could you elaborate on why that doesn't work? The following works just fine on my local machine:

```sh
touch db.sqlite
sqlite3 db.sqlite
```

**Comment by acelaya** [comment]
The comment explains everything. I don't know how to elaborate any further. Try the command in there and you'll see what happens.

**Comment by hwittenborn** [comment]
I saw [this issue](https://github.com/shlinkio/shlink/issues/681#issuecomment-600718059) linked - was that the only thing causing issues, or was there something else?
