### ISSUE TITLE
Import via YOURLS API

### ISSUE THREAD

**Issue by enoversum** [shlinkio/shlink#1242]
It's already possible, via a plugin, to export data from YOURLS as CSV and import the data to Shlink accordingly. Given that statistics cannot be transferred through CSV, a native YOURLS import would be helpful to not lose tracking stats. YOURLS themselves have an API to support that: https://yourls.org/#API .

**Comment by acelaya** [comment]
Wow. I have been checking YOURLS API, and it's pretty useless 😅 

You can basically just get the amount of visits on a short URL, without any further information on it, and you need to know the list of URLs beforehand.

I'm exploring the option of providing a simple YOURLS plugin that covers the missing capabilities, as it doesn't seem to be super complex to do.

The idea is that Shlink asks you to install that plugin first, and then it will try to use it to fetch the info.

If the plugin is not installed, the import will fail with a meaningful error including instructions on how to proceed.

**Comment by enoversum** [comment]
@acelaya Haha, I have to admit, I never delved into the API at all, from a first uneducated look it seemed you can get to the data of URLs more easily than you described, but I guess that was just the pretty outlook. Thanks for taking care of it! I'm grateful, because it's open source and you're devoting your time to it, nothing to be taken for granted.

**Comment by acelaya** [comment]
> from a first [...] look it seemed you can get to the data

When I first checked the docs, it definitely seemed like some stuff was possible. It has been when I have started to play with it when I have found out about the limitations.

**Comment by enoversum** [comment]
@acelaya There is at least a WordPress plugin that is able to attach a long URL (of a WP post) to a custom shortlink you can create directly out of a post, and obviously some kind of sync referring the short to the long URL afterwards. That doesn't say much about how or in what way you can get data out of it for an import, just that it seems a bit flexible.

**Comment by acelaya** [comment]
Yep, the API exposes an action to create short URLs, but not much about "listing" short URLs, or getting detailed information about clicks (only the amount can be fetched out of the box, and only if you know the URL beforehand).

**Comment by acelaya** [comment]
This should do the trick https://github.com/acelaya/yourls-shlink-import-plugin

**Comment by enoversum** [comment]
> This should do the trick https://github.com/acelaya/yourls-shlink-import-plugin

Ah, thanks, _that_ was fast! Will try later then, good thing for a lazy Sunday 😁. As for operating the import — is there a way to do it from the backend, or would I need to do it from the command line as described? No biggie in any case, I won’t be importing YOURLS URLs daily. 

Totally out of context, but is my feature request to have [the short URL also on the quick-shortening screen for the web-app](https://github.com/shlinkio/shlink-web-client/issues/531) something rather on the back of your roadmap, and/or a longer and more complex task? I'm not wanting to rush you, really, just interested because that is something that YOURLS really excels at, entering new, customised shortlinks very quickly. Having this in Shlink (as an option for those who love the current solution) would absolutely convince me to finally make the leap.

**Comment by acelaya** [comment]
> Will try later then

No, that does nothing on its own. That plugin just extends YOURLS API so that an import via API is possible, but Shlink does not yet know how to import from YOURLS. I'm working on that at the moment, and it will require using the command line as with any other source.

> Totally out of context...

Let's not mix topics. You can open a conversation on that issue if you want.

**Comment by enoversum** [comment]
> No, that does nothing on its own. That plugin just extends YOURLS API so that an import via API is possible, but Shlink does not yet know how to import from YOURLS. I'm working on that at the moment, and it will require using the command line as with any other source.
Ah, I see, it’s operational at the moment yet? It’s just a starting point, and I can’t import any actual URLs as of yet?

> Let's not mix topics. You can open a conversation on that issue if you want.
Okay, the 'issue' already exists, I just don’t want to stress you out. Understood. I’ll though add the question there for clarity 🤗.

**Comment by acelaya** [comment]
> It’s just a starting point, and I can’t import any actual URLs as of yet?

Exactly. Shlink will "learn" how to import links from YOURLS from v2.10 onwards (see this ticket's milestone).

That plugin is just some extra functionality for YOURLS itself, otherwise the import would not be possible at all, no matter what Shlink does 🙂

**Comment by enoversum** [comment]
@acelaya Ah, now I got it. It’s a YOURLS plugin, hence the installation instructions. So Shlink will be able to get more data and handle it in the future. Alright, thanks, seems _now_ I finally got it. Very much appreciated! I’ll hang tight then 🙂.

**Comment by acelaya** [comment]
This is now implemented and will be part of Shlink 2.10

**Comment by enoversum** [comment]
Very quick how you finished it! Have a good Sunday! ♥

**Comment by enoversum** [comment]
@acelaya I'm not sure if I need to open up another issue for this. I successfully imported YOURLS data into shlink 2.10. With just a tiny downside: All URLs are imported with the default SHLINK shortening URL I provided. 
As an example: 

- my shlink instance sits at **shl.ink**, default shortening domain is **shl.ink**
- my old YOURLS installation (and shortening URL) sits at **your.ls**. 
- All imported links show as **shl.ink/shortlink** instead of **your.ls/shortlink**.

I simply installed the current version of the Shlink import plugin in my YOURLS installation, activated it, imported through CLI successfully, this is what happened 😉.

**Comment by acelaya** [comment]
That's more or less expected.

I'm assuming you have setup Shlink on a different domain just to be able to import the links, but your intention is to point the original domain you were using with YOURLS to the Shlink instance once migrated.

If that's the case, then all is fine. Once you tell Shlink its domain is your.ls via DEFAULT_DOMAIN env var or configuration, it will show the proper domain everywhere.

**Comment by enoversum** [comment]
@acelaya Ah, only I didn't expect it, honestly. In fact, I have two YOURLS installations (multi-domain isn't officially and practically doable with YOURLS) that I wanted to merge to one Shlink installation, and you're right, I've set up a sub-domain just for testing, and importing YOURLS links, and yesterday imported the first of the domains/installations to Shlink. It would be lovely if you could change the import in a way to ask which shortlink domain should be connected to the imported links - this way I could import multiple domains, and keep whatever suits me (e.g. still use the YOURLS installation until I am ready to switch) running. At this point, I'd not be able to import two different installations with two different shortlink domains.

As for changing the default shortlink domain - is it just that one setting in the config file for Shlink to switch, assuming the domain I change it to also points to Shlink? I can see that additional domains are stored in the database and connected to short links if used, but I wasn't sure it's just the one setting from the config folder.

**Comment by acelaya** [comment]
Yep, it definitely makes sense to allow importing the domain of you want.

I will add it to the roadmap.

**Comment by enoversum** [comment]
Thanks, that is lovely. Would help a lot, as described 😉.

> As for changing the default shortlink domain - is it just that one setting in the config file for Shlink to switch, assuming the domain I change it to also points to Shlink? I can see that additional domains are stored in the database and connected to short links if used, but I wasn't sure it's just the one setting from the config folder.

Is it as simple as that?

**Comment by acelaya** [comment]
> Is it as simple as that?

Yes
