### ISSUE TITLE
Links missing after docker update. Is this expected using SQLite?

### ISSUE THREAD

**Issue by binarydad** [shlinkio/shlink#1243]
This is a dumb question, but want to confirm. I don't regularly update shlink on docker, but given that I'm NOT using an external database, is it expected that my links will be removed since in order to update the container, I need to remove it and then recreate it with the newer image? 

My assumption is that because SQLite is part of the running container, removing the container obviously removes the database. My only option is to use an external database, correct? Or am I missing something in my image upgrade? I'm currently running v2.9.2 for the server.

I'm using the following to create the container:

```
sudo docker run -d --name Shlink -p 8002:8080 -e DEFAULT_DOMAIN=mydomain.com -e USE_HTTPS=true -e GEOLITE_LICENSE_KEY=mykey shlinkio/shlink:stable
```

Thank you.

**Comment by acelaya** [comment]
Correct, the SQLite database gets deleted.
