### ISSUE TITLE
Implement a path which returns a 1px image instead of a redirection

### ISSUE THREAD

**Issue by acelaya** [shlinkio/shlink#125]
This feature could be used to track emails, but needs to be thought carefully

**Comment by VijendraMalhotra** [comment]
Is there any documentation on it's usage?

**Comment by acelaya** [comment]
Yes https://shlink.io/swagger-ui/index.html#/URL%20Shortener/trackShortUrl

Basically, take any short URL and append `/track`. That URL will return the image.
