### ISSUE TITLE
Unable to access the Web interface at Shlink address

### ISSUE THREAD

**Issue by asitemade4u** [shlinkio/shlink#1251]
#### How Shlink is set-up

* Shlink Version: stable
* PHP Version: in the current docker stack, as of 20211206
* How do you serve Shlink: Docker image using docker-compose.yml
* Database engine used: PostgreSQL

#### Summary

1. I installed Shlink using the provided script, which I converted to docker-compose
2. Shlink connects to a self hosted Postgres database: I checked, the database is populated
3. I have provided a license for Geolite2: I checked in Shlink's log and the geolocation database has been imported
4. I have made one change: the port on which Shlink is published, `7099`
5. I have not activated `https` because, for now, Shlink is to be tested in-house

When I connect to Shlink at the server's address, using http, I get a `404`
Here is the connection log from a workstation at `192.168.1.5`:
```
[2021-12-06T21:44:46.041113+00:00] [NULL] Access.ERROR - 192.168.1.5 - - "GET / HTTP/1.1" 404 979
[2021-12-06T21:44:46.051359+00:00] [NULL] Shlink.NOTICE - Task 5 has finished
[2021-12-06T21:44:46.058041+00:00] [NULL] Shlink.NOTICE - Task 4 has finished
[2021-12-06T21:44:46.081605+00:00] [NULL] Shlink.NOTICE - Task 3 has finished
[2021-12-06T21:44:46.162722+00:00] [NULL] Access.INFO - 192.168.1.5 - - "GET /favicon.ico HTTP/1.1" 200 16958
```

**Comment by Greennetherking** [comment]
I also have the exact same problem, I just tried it out today for the first time and I'm also using docker.

![image](https://user-images.githubusercontent.com/64925440/144974333-5c9b3fb5-f9e6-46ba-97ee-e01983e8dabc.png)

**Comment by acelaya** [comment]
That is expected. Shlink itself does not come with a user interface.

You need to use shlink-web-client, which provides a web UI on top of Shlink's API.

You can use the existing instance at https://app.shlink.io, or host it yourselves as well.

You can find more information here  https://shlink.io/documentation/shlink-web-client/
