### ISSUE TITLE
Expressive 2.2 causes failures by triggering E_USER_DEPRECATED errors

### ISSUE THREAD

**Issue by weirdan** [shlinkio/shlink#126]
Since Zend Expressive 2.2 (which is transitional release to get people prepared for Expressive 3.0) if `error_reporting` includes E_USER_DEPRECATED (and it's set to E_ALL, which does, at least in development mode), shlink will fail some tests and all http requests. Shlink allows any 2.* version of Zend Expressive, including 2.2. You can trigger a build on travis to see test failures for yourself.

There are several options:
- [x] Tighten version constraints to forbid Expressive 2.2 from being used with Shlink (going to submit PR for that soon)
- [x] Fix the code and do not use deprecated functionality. See [Upgrading to 2.2 guide](https://docs.zendframework.com/zend-expressive/v2/reference/migration-to-v2-2/)
- [ ] Upgrade to Expressive 3.0 (includes point 2). See [Upgrading to 3.0 guide](https://docs.zendframework.com/zend-expressive/v3/reference/migration/#upgrading)

**Comment by acelaya** [comment]
I see you have created two pull requests. I appreciate that :)

Let me take a look at them later today. I'll merge one of them.

Also, I plan to update to expressive 3 in the next days, but there's one dependency which needs to be checked first.

**Comment by acelaya** [comment]
Closed via #128
