### ISSUE TITLE
Any way to get full referrers?

### ISSUE THREAD

**Issue by RyanNutt** [shlinkio/shlink#1261]
#### How Shlink is set-up

* Shlink Version: 2.9.3
* PHP Version: 8.0.3
* How do you serve Shlink: Self-hosted Apache
* Database engine used: SQLite

#### Summary
First, amazing interface. I looked at several different shorteners, and used a different one for a while, before finding shlink. It's one of the few that I've found that looks to stay current. 

Is there any way to get the full referrer? Instead of example.com, get example.com/pagename.html?  I looked in the database, and it appears that only the domain is stored.

**Comment by acelaya** [comment]
Hey!

I'm afraid Shlink has nothing to say on what is sent as Referrer. It just saves whatever has been sent in the header.

**Comment by RyanNutt** [comment]
Guess, today I learned. Didn't realize my server wasn't sending the full referrers. Thanks.
