### ISSUE TITLE
Geolite 2 not wkring

### ISSUE THREAD

**Issue by Bxnnet** [shlinkio/shlink#1266]
#### How Shlink is set-up

* Shlink Version: 2.6.2
* PHP Version: 8.0.13
* How do you serve Shlink: Self-hosted Apache|
* Database engine used: MySQL

#### Summary
Hey installation worked well and I also gave a Geolite 2 License key for tracking but for every visit the locations are unknown. Table visits contains correct remote_addr so i dont get why the locations cant ge tracked. 
Happy for any ideas!

**Comment by acelaya** [comment]
Hey!

This explains how to fix it https://shlink.io/documentation/troubleshooting/#my-visits-location-is-always-unknown

You probably didn't configure the scheduling that locates the visits https://shlink.io/documentation/long-running-tasks/#locate-visits

**Comment by acelaya** [comment]
Also, if you update to at least Shlink 2.7, you will get visits located in real time.

**Comment by Bxnnet** [comment]
oh thank you so much sir sorry for asking a well documented problem :/
have a nice one
