### ISSUE TITLE
Shlink default domain redirect env vars not taken into account

### ISSUE THREAD

**Issue by jonathandhn** [shlinkio/shlink#1271]
> Server: v2.10.0 on Docker

Hi, setting Shlink with docker does not use the new env vars ( https://github.com/shlinkio/shlink/issues/1163 )as expected with the release v2.10.0
(shlink default error page  instead of mine on default domain) 
```
-e "DEFAULT_INVALID_SHORT_URL_REDIRECT_TO=https://cdn.xxx.xx/404/" \
-e "DEFAULT_REGULAR_404_REDIRECT_TO=https://cdn.xxx.xx/404/" \
-e "DEFAULT_BASE_URL_REDIRECT_TO=https://cdn.xxx.xx/" \
```
base url = shlink default
404 = shlink default
invalid = shlink default

Workaround : 

Use https://api-spec.shlink.io/#/Domains/setDomainRedirects to set working redirects to default domain after upgrading to  v2.10.0

**Comment by acelaya** [comment]
You set the wrong env vars. New ones no longer have the `_TO` suffix
