### ISSUE TITLE
After install returns 404 page

### ISSUE THREAD

**Issue by erikperin** [shlinkio/shlink#129]
-------------------------------------------------------------------
404
Page not found.

The page you requested could not be found.
-------------------------------------------------------------------

**Comment by acelaya** [comment]
I'll need more information

**Comment by erikperin** [comment]
Apache 2.4
Ubuntu 16.04
PHP 7.0
MySQL 5.6

**Comment by acelaya** [comment]
I mean that I need more information on what's what you are doing which is
resulting in a 404 page.

I mean, shlink does not provide a management web interface. You need to use
the CLI interface or an API client.
If you access the bare short domain you are always going to get a 404.

Could that be the case?


--
Alejandro Celaya Alastrué

**Comment by erikperin** [comment]
kkkkk
OMG.... sorry... rs

**Comment by acelaya** [comment]
If you need a front end to manage shortened URLs, you can use this one
https://app.shlink.io.
You can add your own shlink instance and manage it from there.


--
Alejandro Celaya Alastrué

**Comment by erikperin** [comment]
thanks... :D
