### ISSUE TITLE
YOURLS Import: SQL errors 'Invalid datetime format'

### ISSUE THREAD

**Issue by enoversum** [shlinkio/shlink#1293]
Hi there again,

just tried to re-setup shlink (latest version) and finally get my old YOURLS installation imported. I had already successfully test-imported another YOURLS instance some weeks ago with your plugin enabled, which didn't produce those errors. Unfortunately the import now seems to go through, but at the end of importing there are three error messages thrown by the importer concerning datetime format:

> In ExceptionConverter.php line 119:
> 
>   An exception occurred while executing a query: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string valu
>   e: '\xF0\x9F\xA6\x94' for column `shlink`.`short_urls`.`title` at row 1
> 
> 
> In Exception.php line 26:
> 
>   SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xF0\x9F\xA6\x94' for column `shlink`.`shor
>   t_urls`.`title` at row 1
> 
> 
> In Statement.php line 95:
> 
>   SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xF0\x9F\xA6\x94' for column `shlink`.`shor
>   t_urls`.`title` at row 1

Here is what I do:
1. Install shlink and set my future shlink main domain, e.g. myshorts.com (currently pointed to a YOURLS instance), as the default domain. No errors.
2. Point a different domain to the shlink installation and add it to your web interface, e.g. tempdomain.com. Adds successfully.
3. Starting the import. Import seems to get and import all URLs, only to stop with above error messages. Database as well as the web interface show that none of the URLs and visits have been imported.

Did I do something wrong along the way?

**Comment by acelaya** [comment]
I cannot confirm it for sure, but I think the problem might be that some of the URLs (apparently just one of them) is returning a title with invalid characters that cannot be stored in the database.

**Comment by enoversum** [comment]
@acelaya Oh, hell. I'll try and see which one it could be. Judging from what you wrote, it's the actual title for a short link stored in YOURLS, not one that Shlink tries to get from a long URL automatically?

**Comment by acelaya** [comment]
Yes, exactly, the title in the original YOURLS.

Shlink should probably be smarter and filter out those characters, but as a short term solution, I would start by checking the source.

**Comment by enoversum** [comment]
@acelaya Thanks for confirming, finally had a moment to check it out. I had %20, @, apostrophes and 🦔 in my titles. But even removing at least the ones I found quickly didn't solve it. With 400 URLs this is a bit tedious to go through every possible character candidate. 
Could this be a clash of database collations? The URLs in YOURLS are saved with utf8mb4_bin, I just read something about this error showing up when characters are wrongly interpreted via SQL. Not much of a database geek here though.

**Comment by acelaya** [comment]
The xF0\x9F\xA6\x94 characters most probably belong to an emoji, and the problem could be the collation, yes.

**Comment by enoversum** [comment]
@acelaya Yes, I already updated my message above, it's the 🦔 emoticon I used. After removing it from titles, the above new error messages now unfortunately appear, claiming titles to be too long. Having no idea which ones are affected among my 400 URLs, that's harder to solve..

**Comment by acelaya** [comment]
Hmm. I thought I had that covered, but obviously, I didn't 😅

The titles cannot be longer than 512 characters.

**Comment by enoversum** [comment]
Oh oh, I don't believe any of my titles are longer than that's. That's the length of three SMS/text messages!

**Comment by acelaya** [comment]
While investigating this, I have realized these two errors (the empji and title length) are affecting any short URL creation, wheter the source. It's not just when importing from YOURLs.

The title one is the easiest to fix, as I just need to strip out all characters above 512.

I'm investigating how to solve the emojis issue.

**Comment by acelaya** [comment]
> Oh oh, I don't believe any of my titles are as long as that. That's the length of three SMS/text messages!

BTW, I have reproduced this by manually editing one of the links in YOURLs with a title longer than 512 characters, so I would double check.

Links with a long title have `[...]` on them, like this 
![image](https://user-images.githubusercontent.com/2719332/148541449-85448e8b-fcc3-4ded-a29e-317396d680e8.png)

**Comment by acelaya** [comment]
Can confirm solving the emojis issue is going to be tricky, as it will most probably require a big database migration, with high chances to mess something up, so I'm going to leave it out of this hotfix and try to tackle it separately.

Also, supposedly movig from utf8 to utf8mb4 should solve the issue (that's what I can see everywhere and what YOURLS is using), and yet, I keep getting the error, so I'm missing something.

Anyway, the title length issue is fixed, and the emoji support will be tackled for v3.1.0 as part of #767

**Comment by enoversum** [comment]
@acelaya Thanks for the updates. Sounds like a lot of checking and adjusting. I get the trouble, and I believe since YOURLS is indeed running on utf8mb4, that would have solved the trouble with the emoticon. 

As for the long URLs, being a long-time YOURLS user, I know about the ellipsis and the longer titles—since YOURLS is doing that at a very low number of characters, I have about 80% of links with truncated titles. 
In my case I found the culprits. When YOURLS cannot determine a title tag for a URL, it uses the URL itself and stores it as title. This way, very long URLs (in my case from Deezer and Spotify APIs) are breaking your character limit. 
I could now, without emojis and excessive titles, import my first YOURLS instance into Shlink. Thanks for the help!
Looking forward to getting some kind of shortlink domain setting for imports, so I can transfer my other YOURLS instance/domain as well 🙂.

**Comment by acelaya** [comment]
> I could now, without emojis and excessive titles, import my first YOURLS instance into Shlink. Thanks for the help!

Super happy to hear that 🙂

Thank you for your help chasing these bugs.

**Comment by enoversum** [comment]
Absolutely grateful for _your_ hard work on Shlink. It just seems like a very solid link shortener, and is obviously constantly getting better 🙂.

**Comment by acelaya** [comment]
Super weird. I was going to investigate the issue with the emojis yesterday, but I only had access to my laptop, where I also have a Shlink dev enviornment.

Surprisingly, I was able to create several URLs where the title included emojis, even some that fail on my main workstation.

![image](https://user-images.githubusercontent.com/2719332/148741579-c2dd4ae6-1709-439c-b76f-48f384e320d4.png)

What's even weirder, is that I'm using MySQL in both of them, and they both use utf8 collation, and not utf8mb4.

In my workstation and my production environment, I get the error you reported for most of the emojis. In my laptop, all the emojis I have tried, work.

I need to find what I'm missing 😅

**Comment by enoversum** [comment]
Ah, so you're saying, not only importing, but also creating titles with emoji brings up the error? I suspected it was some kind of conversion issue.
I don't know what kind of issue that is based on. Only thing that comes to mind here, if you're using Windows on your machines, is that there is a setting for Windows that enables UTF-8 as a beta (so you can use it with Segoe even in file names and such), which may change the way an emoticon is entered on screen? Maybe it's enabled on one, and disabled on the other machine. I absolutely don't know, just a shot in the dark.

**Comment by acelaya** [comment]
> Ah, so you're saying, not only importing

Yes, this can potentially happen when trying to save an emoji on any field.

> if you're using Windows

That was a good idea, but sadly, I'm using the same version of Ubuntu in both of them.

However, I'm not sure if I'm using the same version of MySQL. I'll check that.

**Comment by acelaya** [comment]
I have found the way to fix it. Emojis will be fully supported in Shlink 3.0.0 😎

**Comment by enoversum** [comment]
That’s 🔥🔥🔥!
