### ISSUE TITLE
YOURLS Import: Allow for setting a shortlink domain for imported URLs

### ISSUE THREAD

**Issue by enoversum** [shlinkio/shlink#1294]
We discussed this on the YOURLS import thread already, just thought this makes it easier to track for you by setting up a different 'issue'. 

It would be gold, for those who use multiple shortlink domains, to provide a setting when importing from YOURLS to shlink to specify for which shortlink domain the links should be imported. I for one have two YOURLS instances and currently couldn't properly import URLs and visits from my two YOURLS instances.

**Comment by acelaya** [comment]
This is now implemented and will be released with Shlink 3.1.0

**Comment by enoversum** [comment]
@acelaya Just updated, working like a charm. I love my new complete Shlink instance! Thanks for implementing this feature!

**Comment by acelaya** [comment]
Thanks for the kind words 🙂
