### ISSUE TITLE
Option to not log IP address

### ISSUE THREAD

**Issue by simonft** [shlinkio/shlink#1306]
Thanks for this project! I was wondering if it would be possible to add an option to not log IP addresses. I have DISABLE_IP_TRACKING set to true, but the address are still showing up in the stdout output from process running in docker. I can probably build on top of the image and add something that filters the logs and removes them, but a configuration option passed to shlink would be even better. 

If there's an Open Swoole flag that is able to do this that would also be great, but I haven't found any docs on how to do that.

**Comment by acelaya** [comment]
This is actually a bug. Providing the DISABLE_IP_TRACKING env var disables the tracking at the database level, but I completely forgot the IP address has been included in the access logs since forever, in a non-anonymized way.

This is kind of critical, so I'll have to publish a hotfix.

**Comment by acelaya** [comment]
I have completely removed the IP address from the logs. Usually it is not needed, as you will probably have a reverse proxy in front of Shlink, with its own logging where you can enable it if wanted.

If I see other people find it useful to have it, I will add a new config option/env var to enable IP address logging.

**Comment by acelaya** [comment]
Shlink 2.10.2 is already available. It no longer logs the IP addresses.

**Comment by simonft** [comment]
Thanks for the quick resolution!
