### ISSUE TITLE
Allow basic SSL connections to mysql using PDO

### ISSUE THREAD

**Issue by icsy7867** [shlinkio/shlink#1342]
#### Summary

Running the latest shlink in docker.  My organization requies the use of SSL connection.  On the command link this is really easy to facilitate, simply include --ssl in the line and everything works.

With PHP and the PDO driver, the SQL connection tries to verify the SSL CA Cert by default.  You should be able to  allow SSL encryption, and not verify the certificates fairly easily using these PDO options:
PDO::MYSQL_ATTR_SSL_CA => false,PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT => false,

I THINK this could be added here:
https://github.com/shlinkio/shlink/blob/8cfb14198b523575cc3093bed2171a1bde4c7b67/module/Core/functions/functions.php

But I am still testing.

If you want to do it the more "Secure" way, you should be able to also add the capability to specify a CA cert for verification:
PDO::MYSQL_ATTR_SSL_CA=> "/path/to/cert"

You should be able to do a faily simple:
if "ca.crt" exists, use this PDO string, else use this.  However I am currently trying to build and test to experiement.

**Comment by acelaya** [comment]
Duplicates #1167

See comments there

**Comment by icsy7867** [comment]
I believe Doctrine does support this:
https://github.com/doctrine/dbal/issues/4013

**Comment by acelaya** [comment]
Only with mysqli
