### ISSUE TITLE
SQLITE error while installing

### ISSUE THREAD

**Issue by afzl-wtu** [shlinkio/shlink#1354]
There is no proper documentaion or tutorial. So please help me to answer my three questions.
3. I can not see my visters ip adresses on web app (app.shlink.io) it only show their location and time and OS, even I have turned off Annonymization (all other settings are default):
![image](https://user-images.githubusercontent.com/64379149/151556213-b730d640-ebe1-4be3-b27b-7cb5ce0e6b5b.png)

2. Is it possible to use my domain.tld to host another webiste while using domain.tld also root domain for shlink?
currently if some user hit domain.tld I am redirecting h to app.domain.tld.

1. I installed shlink by following tutorial mariadb with nginx.
And it worked. 
But I want to use sqlite3 or sqlite database for it becuase I do not want any heavy setup. So when I update Shlink:
I get:

 Custom configuration properly generated!

Updating database... [Running "/usr/bin/php8.1 bin/cli db:migrate"]   RUN  '/usr/bin/php8.1' 'bin/cli' 'db:migrate'
  OUT  Migrating database...
  OUT
  ERR    RUN  '/usr/bin/php8.1' 'vendor/doctrine/migrations/bin/doctrine-migrations.php' 'migrations:migrate' '--no-interaction'
  ERR    ERR
  ERR    ERR  In SchemaException.php line 35:
  ERR    ERR
  ERR    ERR    [Doctrine\DBAL\Schema\SchemaException (10)]
  ERR    ERR    There is no table with name 'public.short_urls' in the schema.
  ERR    ERR
  ERR    ERR
  ERR    ERR  Exception trace:
  ERR    ERR    at /var/www/html/shlink/vendor/doctrine/dbal/src/Schema/SchemaException.php:35
  ERR    ERR   Doctrine\DBAL\Schema\SchemaException::tableDoesNotExist() at /var/www/html/shlink/vendor/doctrine/dbal/src/Schema/Schema.php:189
  ERR    ERR   Doctrine\DBAL\Schema\Schema->getTable() at /var/www/html/shlink/vendor/friendsofphp/proxy-manager-lts/src/ProxyManager/GeneratorStrategy/EvaluatingGeneratorStrategy.php(54) : eval()'d code:49
  ERR    ERR   ProxyManagerGeneratedProxy\__PM__\Doctrine\DBAL\Schema\Schema\Generated83d21ccf7853cfc07dce9110515971db->getTable() at /var/www/html/shlink/vendor/friendsofphp/proxy-manager-lts/src/ProxyManager/GeneratorStrategy/EvaluatingGeneratorStrategy.php(54) : eval()'d code:49
  ERR    ERR   ProxyManagerGeneratedProxy\__PM__\Doctrine\DBAL\Schema\Schema\Generated83d21ccf7853cfc07dce9110515971db->getTable() at /var/www/html/shlink/data/migrations/Version20160819142757.php:27
  ERR    ERR   ShlinkMigrations\Version20160819142757->up() at /var/www/html/shlink/vendor/doctrine/migrations/lib/Doctrine/Migrations/Version/DbalExecutor.php:167
  ERR    ERR   Doctrine\Migrations\Version\DbalExecutor->executeMigration() at /var/www/html/shlink/vendor/doctrine/migrations/lib/Doctrine/Migrations/Version/DbalExecutor.php:102
  ERR    ERR   Doctrine\Migrations\Version\DbalExecutor->execute() at /var/www/html/shlink/vendor/doctrine/migrations/lib/Doctrine/Migrations/DbalMigrator.php:112
  ERR    ERR   Doctrine\Migrations\DbalMigrator->executePlan() at /var/www/html/shlink/vendor/doctrine/migrations/lib/Doctrine/Migrations/DbalMigrator.php:76
  ERR    ERR   Doctrine\Migrations\DbalMigrator->executeMigrations() at /var/www/html/shlink/vendor/doctrine/migrations/lib/Doctrine/Migrations/DbalMigrator.php:162
  ERR    ERR   Doctrine\Migrations\DbalMigrator->migrate() at /var/www/html/shlink/vendor/doctrine/migrations/lib/Doctrine/Migrations/Tools/Console/Command/MigrateCommand.php:210
  ERR    ERR   Doctrine\Migrations\Tools\Console\Command\MigrateCommand->execute() at /var/www/html/shlink/vendor/symfony/console/Command/Command.php:298
  ERR    ERR   Symfony\Component\Console\Command\Command->run() at /var/www/html/shlink/vendor/symfony/console/Application.php:1005
  ERR    ERR   Symfony\Component\Console\Application->doRunCommand() at /var/www/html/shlink/vendor/symfony/console/Application.php:299
  ERR    ERR   Symfony\Component\Console\Application->doRun() at /var/www/html/shlink/vendor/symfony/console/Application.php:171
  ERR    ERR   Symfony\Component\Console\Application->run() at /var/www/html/shlink/vendor/doctrine/migrations/lib/Doctrine/Migrations/Tools/Console/ConsoleRunner.php:97
  ERR    ERR   Doctrine\Migrations\Tools\Console\ConsoleRunner::run() at /var/www/html/shlink/vendor/doctrine/migrations/bin/doctrine-migrations.php:45
  ERR    ERR   Doctrine\Migrations\{closure}() at /var/www/html/shlink/vendor/doctrine/migrations/bin/doctrine-migrations.php:46
  ERR    ERR
  ERR    ERR  migrations:migrate [--write-sql [WRITE-SQL]] [--dry-run] [--query-time] [--allow-no-migration] [--all-or-nothing [ALL-OR-NOTHING]] [--configuration CONFIGURATION] [--em EM] [--conn CONN] [--] [<version>]
  ERR    ERR
  ERR    ERR
  ERR  In Process.php line 267:
  ERR                                                                           
  ERR    [Symfony\Component\Process\Exception\ProcessFailedException]           
  ERR    The command "'/usr/bin/php8.1' 'vendor/doctrine/migrations/bin/doctrine-mig
  ERR    rations.php' 'migrations:migrate' '--no-interaction'" failed.          
  ERR                                                                           
  ERR    Exit Code: 10(Unknown error)                                           
  ERR                                                                           
  ERR    Working directory: /var/www/html/shlink                                
  ERR                                                                           
  ERR    Output:                                                                
  ERR    ================                                                       
  ERR                                                                           
  ERR                                                                           
  ERR    Error Output:                                                          
  ERR    ================                                                       
  ERR                                                                           
  ERR    In SchemaException.php line 35:                                        
  ERR                                                                           
  ERR      [Doctrine\DBAL\Schema\SchemaException (10)]                          
  ERR      There is no table with name 'public.short_urls' in the schema.       
  ERR                                                                           
  ERR                                                                           
  ERR    Exception trace:                                                       
  ERR      at /var/www/html/shlink/vendor/doctrine/dbal/src/Schema/SchemaException.p
  ERR    hp:35                                                                  
  ERR     Doctrine\DBAL\Schema\SchemaException::tableDoesNotExist() at /var/www/html
  ERR    /shlink/vendor/doctrine/dbal/src/Schema/Schema.php:189                 
  ERR     Doctrine\DBAL\Schema\Schema->getTable() at /var/www/html/shlink/vendor/fri
  ERR    endsofphp/proxy-manager-lts/src/ProxyManager/GeneratorStrategy/EvaluatingGe
  ERR    neratorStrategy.php(54) : eval()'d code:49                             
  ERR     ProxyManagerGeneratedProxy\__PM__\Doctrine\DBAL\Schema\Schema\Generated83d
  ERR    21ccf7853cfc07dce9110515971db->getTable() at /var/www/html/shlink/vendor/fr
  ERR    iendsofphp/proxy-manager-lts/src/ProxyManager/GeneratorStrategy/EvaluatingG
  ERR    eneratorStrategy.php(54) : eval()'d code:49                            
  ERR     ProxyManagerGeneratedProxy\__PM__\Doctrine\DBAL\Schema\Schema\Generated83d
  ERR    21ccf7853cfc07dce9110515971db->getTable() at /var/www/html/shlink/data/migr
  ERR    ations/Version20160819142757.php:27                                    
  ERR     ShlinkMigrations\Version20160819142757->up() at /var/www/html/shlink/vendo
  ERR    r/doctrine/migrations/lib/Doctrine/Migrations/Version/DbalExecutor.php:167
  ERR     Doctrine\Migrations\Version\DbalExecutor->executeMigration() at /var/www/h
  ERR    tml/shlink/vendor/doctrine/migrations/lib/Doctrine/Migrations/Version/DbalE
  ERR    xecutor.php:102                                                        
  ERR     Doctrine\Migrations\Version\DbalExecutor->execute() at /var/www/html/shlin
  ERR    k/vendor/doctrine/migrations/lib/Doctrine/Migrations/DbalMigrator.php:112
  ERR     Doctrine\Migrations\DbalMigrator->executePlan() at /var/www/html/shlink/ve
  ERR    ndor/doctrine/migrations/lib/Doctrine/Migrations/DbalMigrator.php:76   
  ERR     Doctrine\Migrations\DbalMigrator->executeMigrations() at /var/www/html/shl
  ERR    ink/vendor/doctrine/migrations/lib/Doctrine/Migrations/DbalMigrator.php:162
  ERR     Doctrine\Migrations\DbalMigrator->migrate() at /var/www/html/shlink/vendor
  ERR    /doctrine/migrations/lib/Doctrine/Migrations/Tools/Console/Command/MigrateC
  ERR    ommand.php:210                                                         
  ERR     Doctrine\Migrations\Tools\Console\Command\MigrateCommand->execute() at /va
  ERR    r/www/html/shlink/vendor/symfony/console/Command/Command.php:298       
  ERR     Symfony\Component\Console\Command\Command->run() at /var/www/html/shlink/v
  ERR    endor/symfony/console/Application.php:1005                             
  ERR     Symfony\Component\Console\Application->doRunCommand() at /var/www/html/shl
  ERR    ink/vendor/symfony/console/Application.php:299                         
  ERR     Symfony\Component\Console\Application->doRun() at /var/www/html/shlink/ven
  ERR    dor/symfony/console/Application.php:171                                
  ERR     Symfony\Component\Console\Application->run() at /var/www/html/shlink/vendo
  ERR    r/doctrine/migrations/lib/Doctrine/Migrations/Tools/Console/ConsoleRunner.p
  ERR    hp:97                                                                  
  ERR     Doctrine\Migrations\Tools\Console\ConsoleRunner::run() at /var/www/html/sh
  ERR    link/vendor/doctrine/migrations/bin/doctrine-migrations.php:45         
  ERR     Doctrine\Migrations\{closure}() at /var/www/html/shlink/vendor/doctrine/mi
  ERR    grations/bin/doctrine-migrations.php:46                                
  ERR                                                                           
  ERR    migrations:migrate [--write-sql [WRITE-SQL]] [--dry-run] [--query-time] [--
  ERR    allow-no-migration] [--all-or-nothing [ALL-OR-NOTHING]] [--configuration CO
  ERR    NFIGURATION] [--em EM] [--conn CONN] [--] [<version>]                  
  ERR                                                                           
  ERR
  ERR  Exception trace:
  ERR    at /var/www/html/shlink/vendor/symfony/process/Process.php:267
  ERR   Symfony\Component\Process\Process->mustRun() at /var/www/html/shlink/module/CLI/src/Util/ProcessRunner.php:48
  ERR   Shlinkio\Shlink\CLI\Util\ProcessRunner->run() at /var/www/html/shlink/module/CLI/src/Command/Db/AbstractDatabaseCommand.php:30
  ERR   Shlinkio\Shlink\CLI\Command\Db\AbstractDatabaseCommand->runPhpCommand() at /var/www/html/shlink/module/CLI/src/Command/Db/MigrateDatabaseCommand.php:30
  ERR   Shlinkio\Shlink\CLI\Command\Db\MigrateDatabaseCommand->lockedExecute() at /var/www/html/shlink/module/CLI/src/Command/Util/AbstractLockedCommand.php:35
  ERR   Shlinkio\Shlink\CLI\Command\Util\AbstractLockedCommand->execute() at /var/www/html/shlink/vendor/symfony/console/Command/Command.php:298
  ERR   Symfony\Component\Console\Command\Command->run() at /var/www/html/shlink/vendor/symfony/console/Application.php:1005
  ERR   Symfony\Component\Console\Application->doRunCommand() at /var/www/html/shlink/vendor/symfony/console/Application.php:299
  ERR   Symfony\Component\Console\Application->doRun() at /var/www/html/shlink/vendor/symfony/console/Application.php:171
  ERR   Symfony\Component\Console\Application->run() at /var/www/html/shlink/bin/cli:10
  ERR
  ERR  db:migrate
  ERR
  ERR
  RES  1 Command did not run successfully

**Comment by acelaya** [comment]
Updating Shlink means moving your current set-up to a newer version, not changing the database engine. Changing the database engine is not supported.

The only thing you can do is update the database driver by running `vendor/bin/shlink-installer set-option`, and follow the instructions, but the existing data won't be migrated, you's start with an empty database.

**Comment by acelaya** [comment]
Sorry, I just noticed you edited the message with two extra questions. I was answering based on the preview from the email notification:

> 3. I can not see my visters ip adresses on web app (app.shlink.io) it only show their location and time and OS, even I have turned off Annonymization (all other settings are default)

The IP address is not exposed by Shlink, just used internally for geolocation.

> Is it possible to use my domain.tld to host another webiste while using domain.tld also root domain for shlink?
currently if some user hit domain.tld I am redirecting h to app.domain.tld.

Probably not the best idea, unless you make sure they are served in different subpaths, but I would strongly recommend using subdomains.

**Comment by afzl-wtu** [comment]
Thanks a lot. 
> The IP address is not exposed by Shlink, just used internally for geolocation.

Can I get ip adresses list through CLI or API?


> Probably not the best idea, unless you make sure they are served in different subpaths, but I would strongly recommend using subdomains.

The disadvantage of this method is that we sacrifice our main domain, we can not use maindomain.tld instead depend on subdomain. please allow to use maindomain.tld to host webpage still using it as root domain.

**Comment by acelaya** [comment]
> please allow to use maindomain.tld

I'm not disallowing it in any way 😅. In fact Shlink supports being served under a subpath precisely for these cases. Feel free to use that approach.

> Can I get ip adresses list through CLI or API?

No, IP addresses are not exposed in any way.

**Comment by afzl-wtu** [comment]
> I'm not disallowing it in any way 😅. In fact Shlink supports being served under a subpath precisely for these cases. Feel free to use that approach.
>
If allowed in sub path it will make urls long. major disadvantage

**Comment by acelaya** [comment]
Then use the subpath for the other application

**Comment by afzl-wtu** [comment]
Please let me know if YoUrls allow exposing ip adresses.

**Comment by acelaya** [comment]
How would I know.

**Comment by afzl-wtu** [comment]
> Then use the subpath for the other application

hahahah... That is not the solution. Anyway thanks for help..

**Comment by afzl-wtu** [comment]
> How would I know.

Becuase These two best products. So I thought you world know it.. But no problem thannks. And last question when Shlink was first releaed?

**Comment by acelaya** [comment]
> hahahah... That is not the solution. Anyway thanks for help..

Well, you are trying to serve two web apps from the same domain. No matter what you do, you will have to find some workaround, but that's not related with Shlink in any way, you would be facing the same issue with any other two web apps 🤷🏼‍♂️

**Comment by acelaya** [comment]
> And last question when Shlink was first releaed?

2016 https://github.com/shlinkio/shlink/releases/tag/v0.1.0

**Comment by afzl-wtu** [comment]
> Updating Shlink means moving your current set-up to a newer version, not changing the database engine. Changing the database engine is not supported.
> 
> The only thing you can do is update the database driver by running `vendor/bin/shlink-installer set-option`, and follow the instructions, but the existing data won't be migrated, you's start with an empty database.

Sorry to disturb you again... the command you mention just left me alone again without any guide. It just show a long list of config variable... WHat I am supposed to do there?

**Comment by afzl-wtu** [comment]
> > Updating Shlink means moving your current set-up to a newer version, not changing the database engine. Changing the database engine is not supported.
> > The only thing you can do is update the database driver by running `vendor/bin/shlink-installer set-option`, and follow the instructions, but the existing data won't be migrated, you's start with an empty database.
> 
> Sorry to disturb you again... the command you mention just left me alone again without any guide. It just show a long list of config variable... WHat I am supposed to do there?

I pressed 0 and selected sqlite.. and showed my green message.. configuration updated successful. But it is not working now even I can not generate api key
