### ISSUE TITLE
Error while installing on php 8.0

### ISSUE THREAD

**Issue by afzl-wtu** [shlinkio/shlink#1356]
I have installed all required  php extensions. 
php8.0-apcu recommended to install php7.4 packages so installed it with 

> sudo apt-get install --no-install-recommends php8.0-apcu

I am using mariadb-server. So chossed option 1 for database driver.

 Custom configuration properly generated!

Initializing database... [Running "/usr/bin/php8.0 bin/cli db:create"]   RUN                                           '/usr/bin/php8.0' 'bin/cli' 'db:create'
  ERR
  ERR  In ExceptionConverter.php line 119:
  ERR
  ERR    [Doctrine\DBAL\Exception\DriverException]
  ERR    An exception occurred in the driver: could not find driver
  ERR
  ERR
  ERR  Exception trace:
  ERR    at /var/www/html/shlink/vendor/doctrine/dbal/src/Driver/API/MySQL/Ex                                         ceptionConverter.php:119
  ERR   Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert() at /var/                                         www/html/shlink/vendor/doctrine/dbal/src/Connection.php:1815
  ERR   Doctrine\DBAL\Connection->handleDriverException() at /var/www/html/sh                                         link/vendor/doctrine/dbal/src/Connection.php:1758
  ERR   Doctrine\DBAL\Connection->convertException() at /var/www/html/shlink/                                         vendor/doctrine/dbal/src/Connection.php:344
  ERR   Doctrine\DBAL\Connection->connect() at /var/www/html/shlink/vendor/do                                         ctrine/dbal/src/Connection.php:406
  ERR   Doctrine\DBAL\Connection->getDatabasePlatformVersion() at /var/www/ht                                         ml/shlink/vendor/doctrine/dbal/src/Connection.php:368
  ERR   Doctrine\DBAL\Connection->detectDatabasePlatform() at /var/www/html/s                                         hlink/vendor/doctrine/dbal/src/Connection.php:285
  ERR   Doctrine\DBAL\Connection->getDatabasePlatform() at /var/www/html/shli                                         nk/module/CLI/src/Command/Db/CreateDatabaseCommand.php:64
  ERR   Shlinkio\Shlink\CLI\Command\Db\CreateDatabaseCommand->checkDbExists()                                          at /var/www/html/shlink/module/CLI/src/Command/Db/CreateDatabaseCommand.php:                                         47
  ERR   Shlinkio\Shlink\CLI\Command\Db\CreateDatabaseCommand->lockedExecute()                                          at /var/www/html/shlink/module/CLI/src/Command/Util/AbstractLockedCommand.ph                                         p:35
  ERR   Shlinkio\Shlink\CLI\Command\Util\AbstractLockedCommand->execute() at                                          /var/www/html/shlink/vendor/symfony/console/Command/Command.php:291
  ERR   Symfony\Component\Console\Command\Command->run() at /var/www/html/shl                                         ink/vendor/symfony/console/Application.php:989
  ERR   Symfony\Component\Console\Application->doRunCommand() at /var/www/htm                                         l/shlink/vendor/symfony/console/Application.php:299
  ERR   Symfony\Component\Console\Application->doRun() at /var/www/html/shlin                                         k/vendor/symfony/console/Application.php:171
  ERR   Symfony\Component\Console\Application->run() at /var/www/html/shlink/                                         bin/cli:10
  ERR
  ERR  In Exception.php line 26:
  ERR
  ERR    [Doctrine\DBAL\Driver\PDO\Exception]
  ERR    could not find driver
  ERR
  ERR
  ERR  Exception trace:
  ERR    at /var/www/html/shlink/vendor/doctrine/dbal/src/Driver/PDO/Exceptio                                         n.php:26
  ERR   Doctrine\DBAL\Driver\PDO\Exception::new() at /var/www/html/shlink/ven                                         dor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:34
  ERR   Doctrine\DBAL\Driver\PDO\MySQL\Driver->connect() at /var/www/html/shl                                         ink/vendor/doctrine/dbal/src/Connection.php:342
  ERR   Doctrine\DBAL\Connection->connect() at /var/www/html/shlink/vendor/do                                         ctrine/dbal/src/Connection.php:406
  ERR   Doctrine\DBAL\Connection->getDatabasePlatformVersion() at /var/www/ht                                         ml/shlink/vendor/doctrine/dbal/src/Connection.php:368
  ERR   Doctrine\DBAL\Connection->detectDatabasePlatform() at /var/www/html/s                                         hlink/vendor/doctrine/dbal/src/Connection.php:285
  ERR   Doctrine\DBAL\Connection->getDatabasePlatform() at /var/www/html/shli                                         nk/module/CLI/src/Command/Db/CreateDatabaseCommand.php:64
  ERR   Shlinkio\Shlink\CLI\Command\Db\CreateDatabaseCommand->checkDbExists()                                          at /var/www/html/shlink/module/CLI/src/Command/Db/CreateDatabaseCommand.php:                                         47
  ERR   Shlinkio\Shlink\CLI\Command\Db\CreateDatabaseCommand->lockedExecute()                                          at /var/www/html/shlink/module/CLI/src/Command/Util/AbstractLockedCommand.ph                                         p:35
  ERR   Shlinkio\Shlink\CLI\Command\Util\AbstractLockedCommand->execute() at                                          /var/www/html/shlink/vendor/symfony/console/Command/Command.php:291
  ERR   Symfony\Component\Console\Command\Command->run() at /var/www/html/shl                                         ink/vendor/symfony/console/Application.php:989
  ERR   Symfony\Component\Console\Application->doRunCommand() at /var/www/htm                                         l/shlink/vendor/symfony/console/Application.php:299
  ERR   Symfony\Component\Console\Application->doRun() at /var/www/html/shlin                                         k/vendor/symfony/console/Application.php:171
  ERR   Symfony\Component\Console\Application->run() at /var/www/html/shlink/                                         bin/cli:10
  ERR
  ERR  In Driver.php line 28:
  ERR
  ERR    [PDOException]
  ERR    could not find driver
  ERR
  ERR
  ERR  Exception trace:
  ERR    at /var/www/html/shlink/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Dr                                         iver.php:28
  ERR   PDO->__construct() at /var/www/html/shlink/vendor/doctrine/dbal/src/D                                         river/PDO/MySQL/Driver.php:28
  ERR   Doctrine\DBAL\Driver\PDO\MySQL\Driver->connect() at /var/www/html/shl                                         ink/vendor/doctrine/dbal/src/Connection.php:342
  ERR   Doctrine\DBAL\Connection->connect() at /var/www/html/shlink/vendor/do                                         ctrine/dbal/src/Connection.php:406
  ERR   Doctrine\DBAL\Connection->getDatabasePlatformVersion() at /var/www/ht                                         ml/shlink/vendor/doctrine/dbal/src/Connection.php:368
  ERR   Doctrine\DBAL\Connection->detectDatabasePlatform() at /var/www/html/s                                         hlink/vendor/doctrine/dbal/src/Connection.php:285
  ERR   Doctrine\DBAL\Connection->getDatabasePlatform() at /var/www/html/shli                                         nk/module/CLI/src/Command/Db/CreateDatabaseCommand.php:64
  ERR   Shlinkio\Shlink\CLI\Command\Db\CreateDatabaseCommand->checkDbExists()                                          at /var/www/html/shlink/module/CLI/src/Command/Db/CreateDatabaseCommand.php:                                         47
  ERR   Shlinkio\Shlink\CLI\Command\Db\CreateDatabaseCommand->lockedExecute()                                          at /var/www/html/shlink/module/CLI/src/Command/Util/AbstractLockedCommand.ph                                         p:35
  ERR   Shlinkio\Shlink\CLI\Command\Util\AbstractLockedCommand->execute() at                                          /var/www/html/shlink/vendor/symfony/console/Command/Command.php:291
  ERR   Symfony\Component\Console\Command\Command->run() at /var/www/html/shl                                         ink/vendor/symfony/console/Application.php:989
  ERR   Symfony\Component\Console\Application->doRunCommand() at /var/www/htm                                         l/shlink/vendor/symfony/console/Application.php:299
  ERR   Symfony\Component\Console\Application->doRun() at /var/www/html/shlin                                         k/vendor/symfony/console/Application.php:171
  ERR   Symfony\Component\Console\Application->run() at /var/www/html/shlink/                                         bin/cli:10
  ERR
  ERR  db:create
  ERR
  ERR
  RES  1 Command did not run successfully

**Comment by acelaya** [comment]
You need to install pdo-mysql in order to connect to mariadb

**Comment by afzl-wtu** [comment]
> You need to install pdo-mysql in order to connect to mariadb

Thanks. it solved the problem

**Comment by acelaya** [comment]
I'll update the docs. I think it's not completely clear that you need to install the corresponding pdo variation for the database you intend to use.

**Comment by afzl-wtu** [comment]
> I'll update the docs. I think it's not completely clear that you need to install the corresponding pdo variation for the database you intend to use.

Please one last question: I just installed shlink i never shared my url but it show me this:
![image](https://user-images.githubusercontent.com/64379149/151668382-60a72026-d0c5-48c7-ad3e-2e95ed6f8168.png)
what is orphan visit

**Comment by acelaya** [comment]
https://shlink.io/documentation/tracking-visits/#orphan-visits

**Comment by afzl-wtu** [comment]
> https://shlink.io/documentation/tracking-visits/#orphan-visits

But it is showing wrong statics I just installed shlink. I never shared my url excet you now. and I am on Windows and server on ubuntu. But it is showing macos and locations from other countries. I am in pakistan and server in germany.
![image](https://user-images.githubusercontent.com/64379149/151669132-4f247f3c-200c-48cb-8461-b77858318720.png)

**Comment by acelaya** [comment]
That's how the internet works, haha.
