### ISSUE TITLE
AUTO_RESOLVE_TITLES=false ignored when validating URLs during creation

### ISSUE THREAD

**Issue by wfjsw** [shlinkio/shlink#1363]
#### How Shlink is set-up

* Shlink Version: 3.0.0
* PHP Version: 8.1.2
* How do you serve Shlink: Self-hosted nginx
* Database engine used: PostgreSQL

#### Summary

I have `AUTO_RESOLVE_TITLES` set to false and now the instance is resolving the title for me anyway.

#### Current behavior

It is automatically resolving the titles

#### Expected behavior

It should not resolve the title.

#### How to reproduce

Create a new shortlink with `shlink-php-sdk`.

**Comment by wfjsw** [comment]
UPDATE: when I use the `shlink-web-client` the title does not resolve. Might be an SDK issue? I'm not explicitly instructing the SDK to resolve it. 
These record have `title_was_auto_resolved` set to true.

**Comment by acelaya** [comment]
It's not a bug on the SDK, but on Shlink. It happens when you send `"validateUrl": true`, which is the SDK's behavior when you create the short URL calling `->validatingTheLongUrl()`.

This bug was present in Shlink 2 as well, so I'll probably backport it to 2.10.x once I have fixed it.

**Comment by acelaya** [comment]
Just realized why you experienced this with the SDK. It will happen even if you don't use `->validatingTheLongUrl()`.

Shlink 2 used to have a global validation flag that could be overriden via request params, but it was confusing, so it was removed in Shlink 3. Well, at least that was the intention, but some traces wereleft bymistake.

Now, if you don't explicitly send either `"validateUrl": true` or `"validateUrl": false`, it tries to validate it, causing the second bug I mentioned above.

**Comment by acelaya** [comment]
Add a temporary workaround, you can create short URLs with the SDK passing `->notValidatingTheLongUrl()`

**Comment by acelaya** [comment]
I already have the fix prepared, but since it's not super critical and there's a simple workaround, I'll wait for a couple of days before releasing v3.0.1, to see if some other bug is reported.

I'll probably release it around the weekend.
