### ISSUE TITLE
Slow rewrite rule in `.htaccess`

### ISSUE THREAD

**Issue by Roy-Orbison** [shlinkio/shlink#1369]
You're using a rule with a lot of backtracking in [the `.htaccess` file](https://github.com/shlinkio/shlink/blob/af1ae0399cd58e785fd479095cb522c5ecf26ee9/public/.htaccess#L15), which has been optimised upstream in [Mezzio Skeleton #40](https://github.com/mezzio/mezzio-skeleton/pull/40).

**Comment by acelaya** [comment]
Thanks!

Feel free to provide a pull request.
