### ISSUE TITLE
Review case sensitivity inconsistencies

### ISSUE THREAD

**Issue by jhogendorn** [shlinkio/shlink#1389]
#### Summary

If shlink can be put into a case insensitive mode (global or per url?) and the automatic generation uses base36 (A-Z0-9) then qrcodes can be generated in L error correction in alphanumeric mode, and will allow 25 characters in the url before the qrcode will generate an alignment marking. 

If you have https:// and a 5 char short url + 1 for the period + 1 for forward slash, thats 10 chars for the identifier, or 3656158440062975 combinations (ZZZZZZZZZZ). ie `https://my.url/shlink1234` vs `HTTPS://MY.URL/SHLINK1234`. If you're doing http to https redirection you can eke out another char if needed. You can't really drop the the protocol prefix as not all readers assume a url.

You could get more if you allow symbols that are allowed in the alphanumeric set `0–9, A–Z (upper-case only), space, $, %, *, +, -, ., /, :` but its not really needed and makes urlencoding issues.

Doing this lets you create the simplest possible qrcode, which makes them as readable as possible on the worst cameras. They are slightly less resilient to damage but intact codes read fast in the worst conditions.

(I used to have a startup around this stuff, trying to get <2mp terrible cheap android tablet front cameras to read small qrcodes at distance fast).

Compare:

#### Alphanumeric mode
![image](https://user-images.githubusercontent.com/253048/155043936-8e04b564-bcc9-42f8-a1be-e1420fa4d0b2.png)

#### Binary mode
![image](https://user-images.githubusercontent.com/253048/155044153-a837e81f-2114-4d48-b3d5-6d7cf8831fb2.png)

You can play with a demo here:

https://jsfiddle.net/jhogendorn/kfLyu1hg/

**Comment by jhogendorn** [comment]
Quick extra note, if you trust your readers, `HTTPS://` can be swapped for `WWW.`, gives 4 extra chars of namespace.

**Comment by acelaya** [comment]
This is super interesting, but I'm not completely sure what's your point here 😅

I guess you are trying to request a feature somehow?

**Comment by jhogendorn** [comment]
The feature would be shlink being case sensitive or insensitive.

As far as i can tell at the moment, it forces all urls to lowercase and then does case sensitive checks. So i cant put in my slug as MYSLUG, because shlink turns it into myslug and wont match https://my.url/MYSLUG. It's kind of in this no mans land where its both case sensitive and case insensitive.

**Comment by acelaya** [comment]
Ooohhh. Ok, now I get it.

Yeah, there's some inconsistency there. I need to give it a thought.

I got confused by all the information regarding QR codes specifically, but I guess that's more of a side effect, or if anything, extra improvement for once the uppercase/lowercase inconsistency has been tackled.

**Comment by jhogendorn** [comment]
Apologies, the QR Code stuff is more like 'why this is worth getting right'. Because otherwise it seems like a pointless improvement for no gain.

**Comment by acelaya** [comment]
Related https://github.com/shlinkio/shlink/issues/706

**Comment by acelaya** [comment]
I have just finished implementing case-insensitive support for short URLs: See https://github.com/shlinkio/shlink/issues/706#issuecomment-1407355167
