### ISSUE TITLE
Updating: Error writing […] No such file or directory — when using dash in old directory

### ISSUE THREAD

**Issue by enoversum** [shlinkio/shlink#1392]
Hi @acelaya ,

just tried to update to the latest Shlink version from 2.10.x (php8.0 without swoole), but on importing the old configuration, the installer stops. The error is as follows:

```
In PhpArray.php line 121:

  Error writing to "config/params/generated_config.php": file_put_contents(config/params/generated_config.php): Failed to open stream: No such file
   or directory
```
Now it's getting a biiiiit complicated.
1. This error occurs if I try to upgrade from 2.10.x to 3.0.3, no matter what.
2. I tried to upgrade from 2.10.x to 3.0 instead, removing the dash from the old directory name (I just had a hunch and tried it out) lets me upgrade successfully.
3. Trying to upgrade from 3.0 to 3.0.3, I get the same error, plus three PHP warnings right after starting the upgrade via CLI:
```
PHP Warning:  Undefined array key "url_shortener" in /xxx/shlink/module/Core/src/Config/BasePathPrefixer.php on line 16
PHP Warning:  Undefined array key "domain" in /xxx/shlink/module/Core/src/Config/BasePathPrefixer.php on line 16
PHP Warning:  Undefined array key "hostname" in /xxx/shlink/module/Core/src/Config/BasePathPrefixer.php on line 16
```
xxx = my server path. 

Updating to 3.0.3 thus doesn't work for me. Any ideas what may be causing this?

**Comment by acelaya** [comment]
Check if this helps https://github.com/shlinkio/shlink/issues/1357

**Comment by acelaya** [comment]
It's hard to tell at this point. Basically, the tool is designed to be run from Shlink's folder, other approaches are not supported.

That doesn't mean it won't work, just that it is not the intended approach and therefore, it's not actively tested.
