### ISSUE TITLE
Add a name or username to the API key

### ISSUE THREAD

**Issue by fredericsimard** [shlinkio/shlink#1393]
#### Summary

We have multiple users using this service and I created one API key per person, if someone leaves the organization all I have to do is disable their API Key in the server. Issue is, there are no names associated with each key when I list them. Would it be possible to add names to existing keys and have the option to add one when a key is being generated? Thanks.

**Comment by acelaya** [comment]
Having a name/title/description/whatever optional field on the API keys, where you can dump arbitrary information that helps you manage the keys, is probably something useful and easy to do.

In fact I have considered it myself, and I even think it was suggested in the past but got lost for some reason.

**Comment by acelaya** [comment]
Ok, yeah. I knew this was dicussed in the past, and I forgot it's already supported 😅 

The `api-key:generate` command supports the `--name` flag for this precise purpose.

```
root:~# shlink api-key:generate --help
Description:
  Generates a new valid API key.

Usage:
  api-key:generate [options]

Options:
  -m, --name=NAME                        The name by which this API key will be known.
  -e, --expiration-date=EXPIRATION-DATE  The date in which the API key should expire. Use any valid PHP format.
  -a, --author-only                      Adds the "AUTHORED_SHORT_URLS" role to the new API key.
  -d, --domain-only=DOMAIN-ONLY          Adds the "DOMAIN_SPECIFIC" role to the new API key, with the domain provided.
  -h, --help                             Display help for the given command. When no command is given display help for the list command
  -q, --quiet                            Do not output any message
  -V, --version                          Display this application version
      --ansi|--no-ansi                   Force (or disable --no-ansi) ANSI output
  -n, --no-interaction                   Do not ask any interactive question
  -v|vv|vvv, --verbose                   Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Help:
  The api-key:generate generates a new valid API key.
  
      /usr/local/bin/shlink api-key:generate
  
  You can optionally set its name for tracking purposes with --name or -m:
  
      /usr/local/bin/shlink api-key:generate --name Alice
```
