### ISSUE TITLE
Password-protected short URLs - happy to contribute

### ISSUE THREAD

**Issue by fmestrone** [shlinkio/shlink#1395]
#### Summary

Other URL shorteners, such as kutt.it, offer a protected shortcut feature, that requires a password before the short url is expanded and redirected to the full URL. I think this is a really useful feature and I do need it myself.

I would be happy to contribute to coding for this, but I need some help and guidance, to get started more quickly.

**Comment by acelaya** [comment]
Can you explain what's the use case for this?

**Comment by fmestrone** [comment]
Here's a couple of examples:

I am teaching a class, I want to share material with the students. I have a fixed URL like /my-class that I use for the course.
I set a password for the students of the current class, they download the material using the password.
When the class is over, I change the password for the next class, but I can keep the URL there...

I want to share material but making sure it is only downloaded by the intended recipients. The long URL cannot be protected, or would require registration and authentication, which I don't want to force. I can simply password-protect the short URL to provide a minimum level of protection.

**Comment by fmestrone** [comment]
As I pointed out in my follow-up comment, the idea here is protecting the resolution of the short URL into the long URL, not protecting the long URL itself. However, I am happy to do it for myself, you don't have to add it to your repo if you don't like it.

Do you have a document that explains the data access layer? Or maybe just direct me to the parts of your code that deal with the creation, persistence and resolution of URLs?

**Comment by mxafi** [comment]
I thought of a use case for this feature with a twist:

1. User wants to share a link that requires an access key that is passed in the parameters (api key, decryption key or similar).
2. The user creates a short url with a password from the long url containing the special codes that are not public by any means.
3. The recipient receives the short url through a non-private channel, and the password through a private channel (e.g. word of mouth)
4. The recipient opens the short url, types the password, and gets forwarded to the link with private parameters.

A possible downside or disclaimer could be that the private information contained in the parameters of a link are stored in the shlink instance and are viewable by the shlink instance admins.

Would this use case be worth considering? @acelaya

**Comment by mdrxy** [comment]
Are there any forks that implement this?
