### ISSUE TITLE
Installation failed. Warning thrown while trying to include doctrine script

### ISSUE THREAD

**Issue by Backpackstudio** [shlinkio/shlink#140]
Installation failed.

Warning: include(doctrine.php): failed to open stream: No such file or directory

**Comment by acelaya** [comment]
Which version are you trying to install?

I would say I fixed that...

**Comment by acelaya** [comment]
I remember now it wasn't exactly this. It was related though.

I'll try to fix it.

**Comment by acelaya** [comment]
I have just released v1.8.1, which should fix this issue.

If you have any problem, let me know.
