### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by erikperin** [shlinkio/shlink#144]
I've configurated a new server... but now returns:
`Oops! We encountered a 500 Internal Server Error error.`

I copy the apache config equaly.

**Comment by acelaya** [comment]
When an internal server error occurs, a log file is created inside data/log. Could you send me the log file which corresponds to the day you got the error? Send it to [alejandro at alejandrocelaya.com]

**Comment by erikperin** [comment]
Sent it

**Comment by acelaya** [comment]
Sorry for the delay, but I've been very beasy lately.

The log file is full of database connection errors (Access denied for user 'root'@'localhost'), so I would say any of the connection params is incorrect.

You can fix it by manually editing the `config/params/generated_config.php` file (if you feel confident enough).

You can also just delete that file and run the update script as if you were updating from an older shlink instance (`./bin/update`). It will ask you to import config from a previous instance (where you have to point it to your current instance), and then ask you to import previous config block.

When it asks you to import the database config, tell it not to do it, and provide the config data again.

**Comment by acelaya** [comment]
I'm closing this because of the lack of activity
