### ISSUE TITLE
Unlink a short url from a domain

### ISSUE THREAD

**Issue by astrodad** [shlinkio/shlink#1447]
#### Summary

I'd like an option in the UI to "unlink" a short url from a domain. My use case is that we've created a new short url that we prefer to use over our previous URL. All of our current domains are linked to this short url (this was before I understood the reasons to do or not do that), and I'd like to use the new URL with all of the existing short url's.

**Comment by acelaya** [comment]
I'm not completely sure if I follow what you mean, because you are using "short URL" for two different things.

Can you give an example?

**Comment by astrodad** [comment]
Sure, sorry for not being clear. I create a short URL to https://www.google.com that has a custom slug and is linked to a short domain: (eg) shortco.de/google but I want to unlink the short url from "shortcod.de" to "sh.de" so that sh.de/google also works for the same target. If I don't specify a domain at creation time, then it works. I have existing short urls that I want to work with a different domain.
