### ISSUE TITLE
visit:locate options broken

### ISSUE THREAD

**Issue by Sylonin** [shlinkio/shlink#1471]
#### How Shlink is set-up

* Shlink Version: `shlink --version` says `--latest`, I use this container: https://hub.docker.com/layers/shlink/shlinkio/shlink/latest/images/sha256-476514540f1587b598c146f27b5a8393144044652c1f53dedd4917c674f9247e?context=explore
* PHP Version: x.y.z
* How do you serve Shlink: Docker image
* Database engine used: PostgreSQL

#### Summary

The `-a` and `-r` options for visit:locale are unrecognised despite being present in `--help`

```
/etc/shlink # shlink visit:locate -a -r


 [WARNING] You are about to process the location of all existing visits your short URLs received.

           Since shlink saves visitors IP addresses anonymized, you could end up losing precision on some of your
           visits.

           Also, if you have a large amount of visits, this can be a very time consuming process. Continue at your own
           risk.


 Do you want to proceed? (yes/no) [no]:
 > yes


 [ERROR] The "-a" option does not exist.


/etc/shlink # shlink visit:locate -r -a


 [WARNING] You are about to process the location of all existing visits your short URLs received.

           Since shlink saves visitors IP addresses anonymized, you could end up losing precision on some of your
           visits.

           Also, if you have a large amount of visits, this can be a very time consuming process. Continue at your own
           risk.


 Do you want to proceed? (yes/no) [no]:
 > yes


 [ERROR] The "-r" option does not exist.


/etc/shlink # shlink visit:locate --retry --all


 [WARNING] You are about to process the location of all existing visits your short URLs received.

           Since shlink saves visitors IP addresses anonymized, you could end up losing precision on some of your
           visits.

           Also, if you have a large amount of visits, this can be a very time consuming process. Continue at your own
           risk.


 Do you want to proceed? (yes/no) [no]:
 > yes


 [ERROR] The "--retry" option does not exist.



```

#### Expected behavior

The `--all` and `--retry` options for `visit:locate` work

#### How to reproduce

Try and use `-a` and `-r` options

**Comment by acelaya** [comment]
Hmm, this is weird. The CLI flags are handled by a framework, and the warning message you see means it was able to detect them as known just before throwing an error.

The error is also thrown by the framework itself, when you pass unknown options or flags.

I will investigate.

**Comment by acelaya** [comment]
I found the issue.

This command internally runs the `visit:download-db` command, in order to make sure the database isupdated before trying to locate the visits. When doing so, it was passing its own options to this one by mistake.

Since the second command was not expecting any option, this combination worked as long as you were not passing any argument/flag to `visit:locate`, but failed as soon as any param was provided, like `--retry` and `--all`.
