### ISSUE TITLE
maximindb lookup results in a memory error

### ISSUE THREAD

**Issue by eleith** [shlinkio/shlink#1487]
#### How Shlink is set-up

* Shlink Version: 3.1.2
* How do you serve Shlink: docker
* Database engine used: pg

#### Summary

maximindb lookup results in a memory error

#### Current behavior

occasionally when redirection from a short URL, a maximind lookup will result in a 500 with the following in the logs

```
Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 8192 bytes) in /etc/shlink/vendor/maxmind-db/reader/src/MaxMind/Db/Reader/Decoder.php on line 80
```

#### Expected behavior

no 500s on URL lookups. if a maximind lookup is going to fail, i would expect the URL to still redirect and no location to be associated with the visit

#### How to reproduce

i haven't reproduced it, but it does happen about once a day or every few days and usually when the user is behind a VPN (maybe causing a maximind lookup that doesn't result in a find?)

**Comment by acelaya** [comment]
Let me know when you manage to reproduce it, and I will take a look.

**Comment by eleith** [comment]
haven't replicated since posting.
