### ISSUE TITLE
[ERROR] Error generating database.  Run this command with -vvv to see specific error info.

### ISSUE THREAD

**Issue by juragandotid** [shlinkio/shlink#149]
setup installation error i'm got this message : 

[ERROR] Error generating database.  Run this command with -vvv to see specific error info.

**Comment by acelaya** [comment]
Have you tried doing what the message says? There's not much I can do with so little information...

**Comment by juragandotid** [comment]
insttallation setup, i'm wanna install this on the setup installlation i got this error.

**Comment by acelaya** [comment]
I don't follow you.

If you run the install script with -vvv flag, what's the output?

**Comment by juragandotid** [comment]
`Custom configuration properly generated!

Initializing database...  RUN  php vendor/doctrine/orm/bin/doctrine.php orm:schema-tool:create
  OUT
  OUT  Fatal error: Uncaught Symfony\Component\Dotenv\Exception\PathException: Unable to read the "F:\shlink\config/../.env" environment file. in F:\shlink\vendor\symfony\dotenv\Dotenv.php:54
  OUT  Stack trace:
  OUT  #0 F:\shlink\config\container.php(16): Symfony\Component\Dotenv\Dotenv->load('F:\\shlink\\confi...')
  OUT  #1 F:\shlink\config\cli-config.php(19): include('F:\\shlink\\confi...')
  OUT  #2 F:\shlink\vendor\doctrine\orm\bin\doctrine.php(58): require('F:\\shlink\\confi...')
  OUT  #3 {main}
  OUT    thrown in F:\shlink\vendor\symfony\dotenv\Dotenv.php on line 54
  OUT
  ERR  PHP Fatal error:  Uncaught Symfony\Component\Dotenv\Exception\PathException: Unable to read the "F:\shlink\config/../.env" environment file. in F:\shlink\vendor\symfony\dotenv\Dotenv.php:54
  ERR  Stack trace:
  ERR  #0 F:\shlink\config\container.php(16): Symfony\Component\Dotenv\Dotenv->load('F:\\shlink\\confi...')
  ERR  #1 F:\shlink\config\cli-config.php(19): include('F:\\shlink\\confi...')
  ERR  #2 F:\shlink\vendor\doctrine\orm\bin\doctrine.php(58): require('F:\\shlink\\confi...')
  ERR  #3 {main}
  ERR    thrown in F:\shlink\vendor\symfony\dotenv\Dotenv.php on line 54
  ERR
  RES  255 Command did not run successfully`

**Comment by acelaya** [comment]
How did you download shlink? It seems you are using the development source
files instead of the distributable build.

Every release has a dist file attached. That's the one you should be using.

For example, this is the last one:
https://github.com/shlinkio/shlink/releases/download/v1.8.1/shlink_1.8.1_dist.zip

Try with that one and let me know the result.

--
Alejandro Celaya Alastrué
https://www.alejandrocelaya.com

**Comment by juragandotid** [comment]
add feature installation with composer, you can update comite to your composer.and easy to install easy to update. thank you.

**Comment by juragandotid** [comment]
this output distibutable build : 

`Custom configuration properly generated!

Initializing database...  RUN  php vendor/doctrine/orm/bin/doctrine.php orm:schema-tool:create
  OUT
  OUT  Fatal error: Uncaught Error: Call to undefined function Doctrine\Common\Cache\apcu_fetch() in F:\xampp\htdocs\shlink\vendor\doctrine\cache\lib\Doctrine\Common\Cache\ApcuCache.php:36
  OUT  Stack trace:
  OUT  #0 F:\xampp\htdocs\shlink\vendor\doctrine\cache\lib\Doctrine\Common\Cache\CacheProvider.php(221): Doctrine\Common\Cache\ApcuCache->doFetch('DoctrineNamespa...')
  OUT  #1 F:\xampp\htdocs\shlink\vendor\doctrine\cache\lib\Doctrine\Common\Cache\CacheProvider.php(194): Doctrine\Common\Cache\CacheProvider->getNamespaceVersion()
  OUT  #2 F:\xampp\htdocs\shlink\vendor\doctrine\cache\lib\Doctrine\Common\Cache\CacheProvider.php(79): Doctrine\Common\Cache\CacheProvider->getNamespacedId('Shlinkio\\Shlink...')
  OUT  #3 F:\xampp\htdocs\shlink\vendor\doctrine\common\lib\Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory.php(211): Doctrine\Common\Cache\CacheProvider->fetch('Shlinkio\\Shlink...')
  OUT  #4 F:\xampp\htdocs\shlink\vendor\doctrine\common\lib\Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory.php(115): Doctrine\Common\Persistence\M in F:\xampp\htdocs\shlink\vendor\doctrine\cache\lib\Doctrine\Common\Cache\ApcuCache.php on line 36
  OUT
  ERR  PHP Fatal error:  Uncaught Error: Call to undefined function Doctrine\Common\Cache\apcu_fetch() in F:\xampp\htdocs\shlink\vendor\doctrine\cache\lib\Doctrine\Common\Cache\ApcuCache.php:36
  ERR  Stack trace:
  ERR  #0 F:\xampp\htdocs\shlink\vendor\doctrine\cache\lib\Doctrine\Common\Cache\CacheProvider.php(221): Doctrine\Common\Cache\ApcuCache->doFetch('DoctrineNamespa...')
  ERR  #1 F:\xampp\htdocs\shlink\vendor\doctrine\cache\lib\Doctrine\Common\Cache\CacheProvider.php(194): Doctrine\Common\Cache\CacheProvider->getNamespaceVersion()
  ERR  #2 F:\xampp\htdocs\shlink\vendor\doctrine\cache\lib\Doctrine\Common\Cache\CacheProvider.php(79): Doctrine\Common\Cache\CacheProvider->getNamespacedId('Shlinkio\\Shlink...')
  ERR  #3 F:\xampp\htdocs\shlink\vendor\doctrine\common\lib\Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory.php(211): Doctrine\Common\Cache\CacheProvider->fetch('Shlinkio\\Shlink...')
  ERR  #4 F:\xampp\htdocs\shlink\vendor\doctrine\common\lib\Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory.php(115): Doctrine\Common\Persistence\M in F:\xampp\htdocs\shlink\vendor\doctrine\cache\lib\Doctrine\Common\Cache\ApcuCache.php on line 36
  ERR
  RES  255 Command did not run successfully`

**Comment by juragandotid** [comment]
this my php versions

PHP 7.1.16 (cli) (built: Mar 28 2018 21:27:36) ( ZTS MSVC14 (Visual C++ 2015) x86 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies

**Comment by acelaya** [comment]
I'm closing this because of the lack of activity

**Comment by acelaya** [comment]
Actually, it is listed in the installation page. The first requirements line states the minimum required PHP version and the required extensions, including APCu.

I have tried to check those requirements in the past during the installation process, but with no luck. Since it is required during the app bootstrapping, the error is thrown before being able to actually run any code which checks it. I will keep trying to find a way though https://github.com/shlinkio/shlink/issues/152

The APCu extension is a pretty basic caching extension, used by many PHP projects. For example, composer https://getcomposer.org/doc/articles/autoloader-optimization.md#optimization-level-2-b-apcu-cache
