### ISSUE TITLE
Searching for the default domain does not return any results in the short URL list

### ISSUE THREAD

**Issue by bildschirmartist** [shlinkio/shlink#1519]
#### Shlink web client version

* Version: 3.7.2
* How do you use shlink-web-client: Docker image

#### Summary
The list of short urls cannot be filtered by default domain using search.

#### Current behavior

Currently I run shlink with one shlink container and several domains. When I now search for links to the default domain in the short URL list, I unfortunately get no results. For all other domains the search works fine in this respect.

#### Expected behavior

Wenn ich in der Suche die Default Domain eingebe, sollten auch sämtliche Short URLs der Default Domain aufgelistet sein

##### Setup the following:
- Default Domain: shlink.dev
- Other Domains: shlink01.dev, shlink02.dev
- Create short links for each of the specified domains.

Afterwards: If you enter "shlink01.dev" or "shlink02.dev" in the search bar, you get the Short URL list filtered accordingly. On the other hand, if you type "shlink.dev", no short URLs are displayed in the list.

**Comment by acelaya** [comment]
Yes, this is a known limitation.

The reason for this is that the default domain is not actually saved in the database. URLs linked to the default domain are actually not linked to anything (for historical reasons, and to keep compatibility when multi-domain support was introduced).

This makes search queries not possible for the default domain.

I have considered a couple of workarounds for this, but I'm not sure how effective would they be. I have to test a bit.

A possible workaround would be to add an explicit filtering option based on the domain, in the same way that happens with tags. That would make it easier to translate "default domain" into "no domain".

**Comment by acelaya** [comment]
I have managed to find a way to make search work when introducing the default domain, withou needing to add a new filtering option which would make things more complicated.
