### ISSUE TITLE
Read only API keys

### ISSUE THREAD

**Issue by kenske** [shlinkio/shlink#1521]
#### Summary

It would be nice to have the option to generate API keys that are read only. This would be useful to grant some users visibility into our URL list and stats, without allowing them to modify/delete/create URLs.

**Comment by acelaya** [comment]
Hey.

There are no plans to add any further logic to Shlink to control end-user permissions.

Instead, an advanced web client will be provided eventually, with its own BFF that will let configuring advanced permissions for local user accounts: https://github.com/shlinkio/shlink-web-client/issues/338
