### ISSUE TITLE
multi-segment slugs return 404 when ending in a /

### ISSUE THREAD

**Issue by eleith** [shlinkio/shlink#1531]
#### How Shlink is set-up

* Shlink Version: 3.2.1
* PHP Version: x.y.z
* How do you serve Shlink: docker / pg

#### Summary

https://shlink.io/documentation/some-features/#multi-segment-custom-slugs

in the considerations section, it might be worth documenting that you get a 404 on slugs that end with a `/`

this happens already to any slug, but with multi-segement slugs, if you have the following

`http://example.com/store/donut` and `http://example.com/store`

it becomes a bit more common to accidentally leave the `/` on the shorter slug

#### Current behavior

you get a 404 on any short URL that ends with a forward slash

#### Expected behavior

either this is documented, particularly in the multi-segment docs or a feature is introduced to assume when a request ends in a `/`, the `/` can safely be ignored

**Comment by eleith** [comment]
related: https://github.com/shlinkio/shlink/issues/1090

perhaps it's already documented elsewhere and i missed it.

**Comment by acelaya** [comment]
I will try to document it better

**Comment by acelaya** [comment]
I have actually realized that supporting trailing slashes is quite easy. I don't remember what was the challenge back in the day when I investigated it. Could be that something has changed in the codebase that makes it easier now.

I will add a new env var/config option that will allow enabling support for trailing slashes, and document the considerations, being:

* If you enable multi-segment slugs and ecplicitly create a URL with the slug `whatever/`, Shlink will try to match only `whatever` as the slug, resulting in a 404 (considering you enable support for triling slashes, of course).

These are quite edge cases though, so I think its ok.

**Comment by eleith** [comment]
lovely!

i'm glad that as shlink has evolved with the support of multi-segment slugs, handling of trailing forward slash may be facilitated.

enabling as an opt-in config feels like a good match, since that is the approach used for multi-segment as well.

looking forward to it!
