### ISSUE TITLE
Allow bringing my own GeoIP database

### ISSUE THREAD

**Issue by wfjsw** [shlinkio/shlink#1533]
#### Summary

To reduce requests to MaxMind server, `geoipupdate` is set up to fetch MaxMind database periodically for all GeoIP database consumption on my server. With this configuration, I'd like to prevent Shlink from downloading the database for me and just use the provided instead.

#### Workaround

Currently, I accomplished this by commenting out `UpdateGeoLiteDb::class` from `module/Core/config/event_dispatcher.config.php`:

```php
    'events' => [
        'regular' => [
            EventDispatcher\Event\UrlVisited::class => [
                EventDispatcher\LocateVisit::class,
            ],
        ],
        'async' => [
            EventDispatcher\Event\VisitLocated::class => [
                EventDispatcher\NotifyVisitToMercure::class,
                EventDispatcher\NotifyVisitToRabbitMq::class,
                EventDispatcher\NotifyVisitToWebHooks::class,
                // EventDispatcher\UpdateGeoLiteDb::class,
            ],
        ],
    ],
```

And then set up a symlink to my `GeoLite2-City.mmdb` in the `data` folder.

**Comment by acelaya** [comment]
What's the point? Shlink only downloads the database file when it is outdated or it does not exist, so you don't need to do the scheduling yourself.

**Comment by wfjsw** [comment]
There are a few possible scenario:
- To use a local mirror of GeoIP database, in order to reduce the unnecessary load to MaxMind server and to prevent the situation described in #1528
- There is already many copies of database file on the server and I'd avoid downloading another one.
- With this I no longer have to rely on `visit:locate` cronjob because a database is always present.
- To use together with #1534 so the web server would not spend a lot of time downloading the database.

**Comment by acelaya** [comment]
> - To use a local mirror of GeoIP database, in order to reduce the unnecessary load to MaxMind server and to prevent the situation described in #1528

Providing files to a docker container is difficult, so this wouldn't be a good solution for that issue. It's a different use case that will have a different solution.

I don't see the benefit of reducing vale to a server which is called once per month.

> - There is already many copies of database file on the server and I'd avoid downloading another one.
> - With this I no longer have to rely on `visit:locate` cronjob because a database is always present.
> - To use together with #1534 so the web server would not spend a lot of time downloading the database.

These are all biased arguments.

The truth is that the only reason you want this is to be able to enable real-time updates while using php-fpm, without a high performance impact, while most of the users want precisely the opposite, forget about it an let Shlink handle everything behind the scenes.

It would add complexity to Shlink, which would have to do extra checks, making it harder to maintain, for an edge case which can be solved by serving Shlink differently.

**Comment by wfjsw** [comment]
I see no point in having to do the GeoIP update at the application server, while we have an active cronjob requirement. Why the real-time updates have to stay off the hot path while this time-consuming job get to stay at the edge? 

If it is for the reduction of complexity I'd move the GeoIP update job to the cron.

Using Swoole or RoadRunner would be a no-go for me because I'd have to maintain separate PHP application server, their memory allocation, and the security policies for no real gain.
