### ISSUE TITLE
Provide an option to publish to Mercure on PHP-FPM setup

### ISSUE THREAD

**Issue by wfjsw** [shlinkio/shlink#1534]
#### Summary

As the Mercure server is hosted locally, I observe no issue enabling it together with PHP-FPM configuration. I understand that there is a performance impact, but to me it is negligable and worths the tradeoff.

On a side note, I was quite surprised at the lack of periodic refresh on shlink-web-client, but more confused at the same time as there was an `updates frequency` setting and it requires Mercure.

#### Workaround

Add `'fallback_async_to_regular' => true,` to `module/Core/config/event_dispatcher.config.php`: 

```php
    'events' => [
        'regular' => [
            EventDispatcher\Event\UrlVisited::class => [
                EventDispatcher\LocateVisit::class,
            ],
        ],
        'async' => [
            EventDispatcher\Event\VisitLocated::class => [
                EventDispatcher\NotifyVisitToMercure::class,
                EventDispatcher\NotifyVisitToRabbitMq::class,
                EventDispatcher\NotifyVisitToWebHooks::class,
                // EventDispatcher\UpdateGeoLiteDb::class,
            ],
        ],

        'fallback_async_to_regular' => true,
    ],
```

**Comment by acelaya** [comment]
It has more implications than it looks. The best option is to move to openswoole or RoadRunner (available for Shlink 3.3.0)

**Comment by wfjsw** [comment]
Is there any detail about the implications? I have not noticed any lag or errors since the patch was deployed a few months back then.

**Comment by acelaya** [comment]
The main implication is the download of the GeoLite2 db file.

There's already a way to serve Shlink that supports real-time updates, so my recommendation would be for you to migrate there.
