### ISSUE TITLE
Different long URL based on device type.

### ISSUE THREAD

**Issue by snorkrat** [shlinkio/shlink#1557]
I would love it if we could specify different (long) URLS based on device type.
This would be super useful for setting up a short url to download an app.  Shlink would detect the device the user visits from, redirect on android would go to the play store, and the redirect on iOS would go to the app store.
A 3rd URL could be added for any device that isn't iOS or android - which could go to a landing page.  Perhaps this could even be built into Shlink.  We could specify a message to be displayed if the user is visiting from an "unsupported" device. These settings could all be in the "advanced options".

---

> Added by maintainer to track progress

- [x] Persistence of device long URLs.
- [x] Define API contract for read operations.
- [x] Define API contract for write operations (creation and edition).
- [x] Document API contract changes.
- [x] Allow "deleting"/"detaching" device URLs during edition, if explicitly provided with value `null` (or whatever is suitable).
- [x] Conditionally redirect to proper long URL, based on user agent.
- [x] ~Validate every device long URL if requested, during creation/edition.~ Not for now (https://twitter.com/shlinkio/status/1617113528162308097 and https://fosstodon.org/@shlinkio/109732478541676141)
- [x] API tests
    - [x] Short URL creation
    - [x] Short URL edition (including "detaching" device long URLs)
    - [x] Redirect to proper place based on user agent (including fallback to regular long URL if impossible to match)
- [ ] Document feature in website (https://github.com/shlinkio/shlink.io/issues/342)

**Comment by acelaya** [comment]
This would definitely be something nice to have. I can think on many services which do something similar.

As a starting point, I would support "android", "ios", "desktop" and "default", leaving the door open to make it smarter in the future.

In order to support this, I would extend the short URL creation to allow something like this:

```json
{
    "longUrl": {
        "android": "optional string",
        "ios": "optional string",
        "desktop": "optional string",
        "default": "required string",
    }
}
```

The only one required would be the default one, which would be the one used if the visitor is not identified as none of the other explicitly provided ones.

Current approach of `{ "longUrl": "whatever" }` would continue working for backwards compatibility, and behave as of only default was provided.

Then redirects would also change. Shlink would try to identify the visitor and determine the proper redirect to use. This part is tricky, but there are promising libraries focused on this topic.

Apart from this, the database would also need changes, validation would be affected, and a couple of other things, but in general, I think it's doable and useful.

**Comment by snorkrat** [comment]
Thanks for checking this out and putting it on the roadmap.  I think it would definitely fit in with, and improve what Shlink has to offer.  The only other (self-hosted) solution that I found that does this is Yourls.  However the UI and workflow is not half as nice as Shlink.  And the functionality is only added by way of a plugin so it's a bit fiddly and not very smooth.

The proposed solution is perfect, and your right; it leaves the door open to make it smarter in the future.  Eg: you could have "Microsoft, Amazon, Apple (instead of iOS), etc"

Looking forward to seeing this implemented, and thanks for the hard work.  Shlink is definitely the best self-hosted URL shortener that I've tried!

**Comment by ouquoi** [comment]
This feature will be highly appreciate !
Thanks

**Comment by acelaya** [comment]
I need to look for an alternative to https://github.com/WhichBrowser/Parser-PHP, as it is not compatible with PHP 8.2, and [the PR to fix it](https://github.com/WhichBrowser/Parser-PHP/pull/673) that someone provided is stuck with no review, which makes me think the project is not very much maintained.

**Comment by acelaya** [comment]
This one is better maintained, and more up to date https://github.com/serbanghita/Mobile-Detect

**Comment by acelaya** [comment]
After some considerations, I have decided to implement this in a slightly different way.

When creating the short URL, the request will look like this:

```json
{
    "longUrl": "required string",
    "deviceLongUrls": {
        "android": "optional string",
        "ios": "optional string",
        "desktop": "optional string"
    }
}
```

being `deviceLongUrls` and everything inside of it completely optional.

The reasons are:

* It's easier to model in a backwards compatible way, both at domain level and at persistence level.
* The device long URLs will have to be exposed also in some endpoint (I haven't decided yet if there will be a new dedicated endpoint, or if I will include this in some existing one).

**Comment by acelaya** [comment]
This feature is now implemented and will be released with Shlink 3.5.0

Right after, I will start working to integrate it in the next version of shlink-web-client.

**Comment by klinux** [comment]
When do you think that this feature will be in the shlink-web-client? 

Thank you.

**Comment by acelaya** [comment]
Already implemented https://github.com/shlinkio/shlink-web-client/pull/813

It will be released when this list is completed https://github.com/shlinkio/shlink-web-client/milestone/49

**Comment by acelaya** [comment]
shlink-web-client 3.10 has just been released supporting this feature. It's already applied on https://app.shlink.io
