### ISSUE TITLE
Preview the long URL a short URL resolves to

### ISSUE THREAD

**Issue by xathon** [shlinkio/shlink#1562]
#### Summary

As a user receiving a link shortened with shlink, I want to be able to preview where the link will redirect me to. When I receive a shortened link, I currently have no way of verifying what it resolves to, without actually opening it and the website it redirects to. This can be a security concern.

As an example, bit.ly provides this info, when I add a `+` to the bit.ly URL. It won't visit the site, but instead show the long URL and provide me with a link to visit the site, should I so choose. Searching the docs, I couldn't find a way to do this with shlink currently. It would be great if something like this could be implemented.

**Comment by acelaya** [comment]
Because of the nature of this project, end users would never be able to tell there's a Shlink instance behind certain short URL, driving something like this useless in 99% of cases.
