### ISSUE TITLE
Background commands executed by installation process do not respect the used php binary

### ISSUE THREAD

**Issue by lennartjuette** [shlinkio/shlink#157]
When Running bin/install -vvv i get this result:

```
Custom configuration properly generated!

Initializing database...  RUN  php vendor/doctrine/orm/bin/doctrine.php orm:schema-tool:create
  OUT
  OUT  Warning: Unsupported declare 'strict_types' in /httpdocs/shlink_1.9.0_dist/vendor/zendframework/zend-stratigility/src/functions/double-pass-middleware.php on line 8
  OUT
  OUT  Parse error: syntax error, unexpected ':', expecting '{' in /httpdocs/shlink_1.9.0_dist/vendor/zendframework/zend-stratigility/src/functions/double-pass-middleware.php on line 39
  OUT
  RES  255 Command did not run successfully
```

Command: `bash-4.3$ /usr/local/php71/bin/php bin/install -vvv`
PHP Version:
```
bash-4.3$ /usr/local/php72/bin/php --version
PHP 7.2.1 (cli) (built: Jan  5 2018 09:57:39) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2017 Zend Technologies
```
The same goes for PHP 7.1.13 /Zend 3.1.0
shlink version: shlink_1.9.0_dist

**Comment by acelaya** [comment]
It is throwing a syntax error on a vendor. Let me check it.

**Comment by acelaya** [comment]
I see you are manually defining the absolute path to the PHP binary.

The installation process runs a few background processes. My guess is that those are using the php binary in your path, and that that binary is an older PHP version, otherwise that error makes no sense.

Could that be possible? Could you try by setting the PHP binary in your path pointing to a 7.1 or 7.2 binary?

**Comment by acelaya** [comment]
I can confirm this happens. Could you check it too in order to make sure that's the only problem?

**Comment by acelaya** [comment]
This is already fixed and published in [v1.9.1](https://github.com/shlinkio/shlink/releases/tag/v1.9.1)

**Comment by lennartjuette** [comment]
I can confirm that 1.9.1 fixes the problem.

Now I'm stuck because by hosting provider doesn't provide APCu. Well, then... back to YOURLS.

**Comment by marvinpoo** [comment]
> I can confirm that 1.9.1 fixes the problem.
> 
> Now I'm stuck because by hosting provider doesn't provide APCu. Well, then... back to YOURLS.

Never give up. Switch your host if it isn't modern enough to fullfill your technical needs. ;)
