### ISSUE TITLE
Find links by tag

### ISSUE THREAD

**Issue by JKamsker** [shlinkio/shlink#1573]
#### Summary

I find this project is very awesome and almost what i need. 
The only thing thats missing is to search by tags. Can we get such a functionality?

Thank you 😊

**Comment by acelaya** [comment]
That's already supported 😄

Unless I'm not getting what you mean.

**Comment by JKamsker** [comment]
Oh, nice!
In the api, it doesnt mention anything about such a support...
Can you give me an example how to call the rest api to get such a filtering?

**Comment by JKamsker** [comment]
Ok i imported the api docs json into postman and it shows me actually good samples.
Thank you for everything. You save me alot of work <3

**Comment by acelaya** [comment]
Yep. It seems to be a bug in the swagger.ui version in https://api-spec.shlink.io

I'll check it.
