### ISSUE TITLE
Do not allow short URLs to be created with an empty string as the domain

### ISSUE THREAD

**Issue by sxjeru** [shlinkio/shlink#1578]
#### How Shlink is set-up

* Shlink Version: 3.3.2
* PHP Version: 8.1
* How do you serve Shlink: Docker image
* Database engine used: MariaDB

#### Summary

Some short URLs without domain cannot be deleted.

![image](https://user-images.githubusercontent.com/20513115/196712002-a45afe99-9b42-4ece-ab59-593adbdc4036.png)

![image](https://user-images.githubusercontent.com/20513115/196712072-3da2f984-5060-45c4-bb5b-7670d8935fb3.png)

#### How to reproduce

These short URLs are generated by api with "" domain parameters. (not null)

**Comment by acelaya** [comment]
What's the point of passing "" as domain? The way I see it, if there's a bug here, it is the fact that Shlink allows that or even treats it differently than null.

**Comment by sxjeru** [comment]
This is the mistake I made when learning the API. I confused "" with null. 
It's really meaningless. So how can I delete it? Web-client and cli didn't work.

**Comment by acelaya** [comment]
Oh, got it.

When you want to delete a short URL which has been explicitly set to a domain, the API expects it to be provided during deletion.

Most probably there's a loosely check somewhere (ether Shlink itself or shlink-web-client), which is treating "" as not provided, but this is not the case while creating the short URL, driving it to an inconsistent state.

At this point, I'm afraid you can only delete them from the database.

In the meantime I will treat this as a bug, as there are inconsistencies in a couple of places.

**Comment by acelaya** [comment]
I'm altering the behavior, so that providing `""` as the domain during short URL creation, is treated as if the domain was not provided at all. That will prevent the incosistency.
