### ISSUE TITLE
Copyright

### ISSUE THREAD

**Issue by JKamsker** [shlinkio/shlink#1579]
Hey, im currently doing an api client lib  in  c# .net  (at  https://github.com/JKamsker/shlink-dotnet) for your awesome project!
Can i use a  modified version of your icon for this project? (https://github.com/JKamsker/shlink-dotnet/blob/master/resources/icon.png)
And  - is it okay to have "shlink" in the name  of my repository?

**Comment by acelaya** [comment]
Hey!

Yeah, sure. I'm fine with both the name and the icon

**Comment by JKamsker** [comment]
Thanks 👍
