### ISSUE TITLE
Short link created from web interface (https://app.shlink.io) doesn't work

### ISSUE THREAD

**Issue by Ext7** [shlinkio/shlink#1588]
#### How Shlink is set-up

* Shlink Version: 3.3.2
* PHP Version: 8.1
* How do you serve Shlink: Self-hosted nginx
* Database engine used: MySQL (8.0.29-21 Percona Server)

#### Summary

Short link created from web interface (https://app.shlink.io) doesn't work and returns "An unexpected error occurred" when opening url

#### Current behavior

What I found that 

- link created from app.shlink.io has author_api_key_id in DB
- link created from cli has author_api_key_id == null and it works fine

When I run 
$ bin/cli short-url:list

Get: 
`PHP Warning:  require(data/proxies/__CG__ShlinkioShlinkRestEntityApiKey.php): Failed to open stream: No such file or directory in /var/www/73n.ru/vendor/doctrine/common/src/Proxy/AbstractProxyFactory.php on line 197
PHP Fatal error:  Uncaught Error: Failed opening required 'data/proxies/__CG__ShlinkioShlinkRestEntityApiKey.php' (include_path='.:/usr/share/php') in /var/www/73n.ru/vendor/doctrine/common/src/Proxy/AbstractProxyFactory.php:197
Stack trace:
#0 /var/www/73n.ru/vendor/doctrine/common/src/Proxy/AbstractProxyFactory.php(109): Doctrine\Common\Proxy\AbstractProxyFactory->getProxyDefinition()
#1 /var/www/73n.ru/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(2873): Doctrine\Common\Proxy\AbstractProxyFactory->getProxy()
#2 /var/www/73n.ru/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php(266): Doctrine\ORM\UnitOfWork->createEntity()
#3 /var/www/73n.ru/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php(492): Doctrine\ORM\Internal\Hydration\ObjectHydrator->getEntity()
#4 /var/www/73n.ru/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php(148): Doctrine\ORM\Internal\Hydration\ObjectHydrator->hydrateRowData()
#5 /var/www/73n.ru/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php(270): Doctrine\ORM\Internal\Hydration\ObjectHydrator->hydrateAllData()
#6 /var/www/73n.ru/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(1224): Doctrine\ORM\Internal\Hydration\AbstractHydrator->hydrateAll()
#7 /var/www/73n.ru/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(1165): Doctrine\ORM\AbstractQuery->executeIgnoreQueryCache()
#8 /var/www/73n.ru/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(901): Doctrine\ORM\AbstractQuery->execute()
#9 /var/www/73n.ru/module/Core/src/ShortUrl/Repository/ShortUrlRepository.php(45): Doctrine\ORM\AbstractQuery->getResult()
#10 /var/www/73n.ru/module/Core/src/ShortUrl/Paginator/Adapter/ShortUrlRepositoryAdapter.php(26): Shlinkio\Shlink\Core\ShortUrl\Repository\ShortUrlRepository->findList()
#11 /var/www/73n.ru/vendor/pagerfanta/core/Pagerfanta.php(260): Shlinkio\Shlink\Core\ShortUrl\Paginator\Adapter\ShortUrlRepositoryAdapter->getSlice()
#12 /var/www/73n.ru/vendor/pagerfanta/core/Pagerfanta.php(246): Pagerfanta\Pagerfanta->getCurrentPageResultsFromAdapter()
#13 /var/www/73n.ru/vendor/pagerfanta/core/Pagerfanta.php(415): Pagerfanta\Pagerfanta->getCurrentPageResults()
#14 /var/www/73n.ru/vendor/lstrojny/functional-php/src/Functional/Map.php(31): Pagerfanta\Pagerfanta->getIterator()
#15 /var/www/73n.ru/module/CLI/src/Command/ShortUrl/ListShortUrlsCommand.php(173): Functional\map()
#16 /var/www/73n.ru/module/CLI/src/Command/ShortUrl/ListShortUrlsCommand.php(147): Shlinkio\Shlink\CLI\Command\ShortUrl\ListShortUrlsCommand->renderPage()
#17 /var/www/73n.ru/vendor/symfony/console/Command/Command.php(308): Shlinkio\Shlink\CLI\Command\ShortUrl\ListShortUrlsCommand->execute()
#18 /var/www/73n.ru/vendor/symfony/console/Application.php(1002): Symfony\Component\Console\Command\Command->run()
#19 /var/www/73n.ru/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand()
#20 /var/www/73n.ru/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#21 /var/www/73n.ru/bin/cli(10): Symfony\Component\Console\Application->run()
#22 {main}
  thrown in /var/www/73n.ru/vendor/doctrine/common/src/Proxy/AbstractProxyFactory.php on line 197`

Also some other commands return errors in CLI:

$bin/cli visit:non-orphan

`PHP Warning:  require(data/proxies/__CG__ShlinkioShlinkCoreShortUrlEntityShortUrl.php): Failed to open stream: No such file or directory in /var/www/73n.ru/vendor/doctrine/common/src/Proxy/AbstractProxyFactory.php on line 197
PHP Fatal error:  Uncaught Error: Failed opening required 'data/proxies/__CG__ShlinkioShlinkCoreShortUrlEntityShortUrl.php' (include_path='.:/usr/share/php') in /var/www/73n.ru/vendor/doctrine/common/src/Proxy/AbstractProxyFactory.php:197`

Something hasn't installed properly I guess, but how to finish this set up?

**Comment by Ext7** [comment]
One more question: is it right that server opened with api key on app.shlink.io shows all links - with other api key or with author_api_key_id == NULL?

Is there a way to alter this behavior and choose what to show on certain server with this api key - all urls or only urls with this api key?

**Comment by acelaya** [comment]
> `PHP Warning:  require(data/proxies/__CG__ShlinkioShlinkRestEntityApiKey.php): Failed to open stream: No such file or directory `

This error means you did not run the initial installation/update.

**Comment by acelaya** [comment]
Check https://shlink.io/documentation/command-line-interface/installation-tool/#install or https://shlink.io/documentation/command-line-interface/installation-tool/#update (whichever applies for you)
