### ISSUE TITLE
Take a CRQS+ES approach to help audit trails via non-destructive editions

### ISSUE THREAD

**Issue by xmontero** [shlinkio/shlink#1593]
I see in the mysql tables that there's no history of changes.

This implies that having a link https://sho.rt/checklist pointing to https://my.long.url/documents/checklist/download and then one day editing the URL to point to https://another.long.site/the/document-location/has-changed will loose the information about that change.

Same with tag renaming, deletions, and so.

I've been using CRQS+ES for several years now and I'd be super happy to be able to discuss how to implement a non-destructive base and help develop it.

**Comment by acelaya** [comment]
That's something 99% of Shlink users don't need, and would require an insanely massive refactor.

Shlink can be improved in multiple places and aspects, but considering it's something I maintain in my free time, this is something I'm afraid I can't afford.

I appreciate the intention though 🙂.

**Comment by xmontero** [comment]
I see and I understand.

Related to this... Does shlink support "plugins"? I mean... If yes, maybe I might develop a plugin that, while not converting it to a full CQRS+ES system, at least does the "write side" collecting all the events for furhter processing in another separate project.
