### ISSUE TITLE
Support credentials on redis servers connection

### ISSUE THREAD

**Issue by khanhtranchi** [shlinkio/shlink#1599]
#### How Shlink is set-up

* Shlink Version: v3.3.2
* How do you serve Shlink: Docker image - roadrunner
* Database engine used: PostgreSQL

#### Summary

Can not input Redis URI with password

#### Current behavior
It show this error:

![image](https://user-images.githubusercontent.com/10261012/200774900-48b1cfcf-ee00-41de-9c6a-1b4fe8a5e5b5.png)

#### Expected behavior

Could input the password and database to the uri of Redis

#### How to reproduce

Create a docker compose file with service like this:

shlink:
    container_name: shlink
    image: shlinkio/shlink:latest-roadrunner
    restart: always
    environment:
      - DEFAULT_DOMAIN:$SHORT_LINK
      - IS_HTTPS_ENABLED:false
      - GEOLITE_LICENSE_KEY:$SHLINK_GEOLITE_LICENSE_KEY
      - DB_DRIVER=postgres
      - DB_USER=$SHLINK_DB_USER
      - DB_PASSWORD=$SHLINK_DB_PASSWORD
      - DB_HOST=postgres
      - DB_PORT=5432
      - ENABLE_PERIODIC_VISIT_LOCATE=true
      # - REDIS_SERVERS=$SHLINK_REDIS_SERVERS
      - REDIS_SERVERS=redis://my_password@redis:6379/2

**Comment by acelaya** [comment]
Yes, this is actually a missing feature. It requires some changes to be supported.

**Comment by sedadas** [comment]
Hi, it's also worth mentioning the support for ACLs.
So, I think that username+password combinations should also be supported (in older versions, there is a default user that only uses a password).

Reference:
https://redis.io/docs/management/security/acl/

**Comment by acelaya** [comment]
Even if that does not work, the next patterns will work yet, on Shlink 3.4.0

* `tcp://password@server:port`
* `tcp://username:password@server:port`
