### ISSUE TITLE
Add ability to exclude bots from visitCount in short-urls endpoint

### ISSUE THREAD

**Issue by simonft** [shlinkio/shlink#1613]
#### Summary

For each short url, the short-urls endpoint returns a count of the number of visits a redirect has seen, in `visitsCount`. We created a short url and posted it to Mastodon. The way Mastodon works is each individual instance that sees a post goes and fetches the metadata for links in the post for itself. So a link posted to a reasonably popular account can immediately see >1k visits to a link from automated crawlers, and the number short-urls returns ends up being way higher than the number of humans that have clicked on the link.

The user agent of these requests makes it pretty clear they're from Mastodon, and Shlink correctly identifies the requests as `potentialBot` in the visits list.

It would be great if it were possible to pass a parameter, maybe reusing `excludeBots` from the visits api endpoint, to a GET request to the short-urls endpoint that would cause shlink to to ignore the potential bots when calculating the returned visitsCount. Alternately, a 2nd number could be calculated and returned, e.g. `potentialNonBotVisitsCount`.

---

Considerations:

- [x] Add both amount of bots, non-bots and total per short URL.
- [x] Allow to order by visits, and non-bot visits (probably order by bot visits is not that useful).
- Do the same for tags? (probably extract to separated issue). https://github.com/shlinkio/shlink/issues/1633
- Do the same for visits summary? (probably extract to separated issue). https://github.com/shlinkio/shlink/issues/1632
- Afterwards, for shlink-web-client. Allow to "exclude" bots by default, from "everywhere", via settings.

**Comment by acelaya** [comment]
I'm considering the second approach, which is returning both values, as this gives more flexibility to the web client, allowing to display just one of them, or even both.

As a side effect, this means the short URL list has to allow ordering by "visits" (in general) or "nonBotVisits", as a URL could have a lot of visits but all from bots. If the front-end decides to "hide" bots, the ordering might be affected and Shlink should be able to do it accordingly.

Also, while doing the changes I realized there's an endpoint returning visits per tag, and another one returning an overview of visit stats. Probably both should support this same behavior (all visits vs bots vs non-bots), but I will most probably extract those to separated tasks for futureversions.
