### ISSUE TITLE
Invalid elements: [longUrl]

### ISSUE THREAD

**Issue by Vic51993** [shlinkio/shlink#1638]
* Shlink Version: 2.6.2
* PHP Version: 8.0.26
* How do you serve Shlink: Self-hosted Apache
* Database engine used: MySQL

#### Summary

Hi, I am just a newbie to this and would like to ask for your advise on this. :) 

When I create a short url via the web client it always says like this

![image](https://user-images.githubusercontent.com/120757843/208201118-7fd85578-4389-4b54-81c7-3a4742b9b66a.png)

These are the console errors I get when I try to create a short url

![image](https://user-images.githubusercontent.com/120757843/208201429-0cab6b6f-6994-4eaf-a52d-9a2054607806.png)

![image](https://user-images.githubusercontent.com/120757843/208201475-5c4921b0-1f29-409e-bb39-38c289e8a57c.png)

On the server side, when I try to create a shortlink, it is succesfull  as shown

![image](https://user-images.githubusercontent.com/120757843/208201278-302d4a9a-bfc9-4282-a23d-80f4868c4937.png)

Hoping for your help! 

Thank you very much!

**Comment by acelaya** [comment]
Shlink 2.6.2 is a very old version. Latest versions of shlink-web-client no longer support it.

Please update to a newer version.

**Comment by acelaya** [comment]
My mistake. Shlink 2.6 is still supported, so I will take a look.

It's the oldest supported version, so I would still try to update it ADAP.
