### ISSUE TITLE
importing

### ISSUE THREAD

**Issue by Stunt0265** [shlinkio/shlink#1641]
Question about importing:

https://shlink.io/documentation/advanced/import-short-urls/

If I want to setup a new instance but using the same custom domain, will this process still work?  In other words, the importer asks for the domain and api key.  So I want to import urls from "something.link" to a new instance that also uses "something.link".

Or should I have an instance under a different domain, like "something.info" and the import will just add another domain under that instance with the urls from "something.link"?

Thanks

**Comment by raldridgenctm** [comment]
I was able to do this successfully and understand better what it's doing.  It converts the domain of the urls to whatever domain the new instance is on.  I'll need to see if there's a way to change the domain without installing a new instance.
