### ISSUE TITLE
Show message before redirect / Ask for confirmation before redirect

### ISSUE THREAD

**Issue by CodeAlDente** [shlinkio/shlink#1643]
(I'm not quite sure if the web client repo is the right place for this, so please feel free to transfer! )

#### Summary

Wouldn't it be a neat feature to set an option for certain shortlinks so the user who clicks on them needs to actively confirm he wants to get redirected? Not only for possible NSFW related content. But also for affiliate links where you need some sort of consent from the user (mostly because of GDPR).

**Comment by acelaya** [comment]
I'll leave this open for now, to give others the opportunity to react, but it's unlikely this happens.

Something like this would require a relatively advanced templating system, with logic in the client (redirect based on user actions), which would add a lot of complexity for something I would consider an edge case.
