### ISSUE TITLE
Create domain specific links through GET endpoint

### ISSUE THREAD

**Issue by minholi** [shlinkio/shlink#1660]
#### Summary

I'm using Shlink with Mautic but I need to generate shortened urls for different domains.

Is it possible to include support to GET endpoint for custom domains?

Example:

https://doma.in/rest/v3/short-urls/shorten?apiKey=xxxxxxxx-xxxx-xxxx-xxxx-b8e57fa0f610&domain=anotherdoma.in&format=txt&longUrl=

Would be nice to have this working: &domain=anotherdoma.in

**Comment by acelaya** [comment]
That endpoint is only there for historical reasons, but there won't be any changes applied to it.

The right way to create short URLs with extra configuration is the POST endpoint https://api-spec.shlink.io/#/Short%20URLs/createShortUrl

**Comment by acelaya** [comment]
I would suggest opening a request on their end to support proper integration with URL shortener APIs which is not insecure and allows for other params to be sent.

https://github.com/mautic/mautic
