### ISSUE TITLE
Possibility to exclude letter combinations

### ISSUE THREAD

**Issue by knstntnb** [shlinkio/shlink#1667]
#### Summary of feature request

As discussed in https://github.com/shlinkio/shlink/discussions/1666 I think an option to exclude specific letter-combination would be very helpful to avoid combinations, like "FCK3v" or "PsY1l", which I got during testing.

Options could be defined via an env for docker, such as defining specific combinations or reference an external file, but also open for discussion and/or ideas.

**Comment by acelaya** [comment]
Closing, due to lack of capacity and other priorities.
