### ISSUE TITLE
Change original_url field size to use one which allows bigger sizes

### ISSUE THREAD

**Issue by Zaczero** [shlinkio/shlink#1674]
#### Summary

I need to shorten VERY long URLs (which work fine in Firefox/Chromium).
However, I face a Shlink limitation because it doesn't allow for URLs longer than 2048 characters (2KB).
I would love to be able to lift this limitation, for example, during database creation (ENV parameter?).

#### References

* [Chrome limits URLs to a maximum length of **2MB**](https://chromium.googlesource.com/chromium/src/+/master/docs/security/url_display_guidelines/url_display_guidelines.md#url-length)
* [Postgres TEXT for variable **unlimited length**](https://www.postgresql.org/docs/current/datatype-character.html)
* #507

**Comment by acelaya** [comment]
I'm afraid it's not easy to set database params dynamically, in a way that it's not confusing for users which would expect to be able to change that at any point in time (as it happens with the rest of the config options).

I could explore making it the biggest possible text type on every database, but that could have some impact, specially on existing instances, so I need to investigate it a bit further.

**Comment by Zaczero** [comment]
Major database solutions will only allocate as much space as needed. For example check out this MySQL documentation: https://dev.mysql.com/doc/refman/8.0/en/char.html. The only thing for consideration would be the possibility for abuse.

**Comment by acelaya** [comment]
Column type for long URLs has been changed to TEXT, allowing for much longer values.

This change will be released with Shlink 4.0.0

**Comment by Zaczero** [comment]
Thank You!
