### ISSUE TITLE
Consider using supercronic for Cron in Docker container

### ISSUE THREAD

**Issue by onedr0p** [shlinkio/shlink#1689]
@acelaya you could use https://github.com/aptible/supercronic instead. It's even in the alpine pkg registry and can run as a user instead of root.

```
apk add --no-cache supercronic
```

then in your entrypoint

```bash
echo "$CRON_SCHEDULE /whatever.sh" > /tmp/crontab
supercronic -passthrough-logs /tmp/crontab &
```

_Originally posted by @onedr0p in https://github.com/shlinkio/shlink/issues/1132#issuecomment-1409308561_

**Comment by acelaya** [comment]
This will be addressed differently in the end. See https://github.com/shlinkio/shlink/pull/1763#issuecomment-1531972820
