### ISSUE TITLE
The domain in the short URL is gone, and the URL is not working

### ISSUE THREAD

**Issue by AbelLin1214** [shlinkio/shlink#1695]
#### How Shlink is set up

* Shlink Version: 2.8.1
* PHP Version: 3.9.1
* How do you serve Shlink: Openswoole Docker image|RoadRunner Docker image
* Database engine used: MariaDB
#### Summary

Hi, thank you very much for your open source project, it works very well.
Before the day before yesterday, my project was working fine. But after restarting the container, a bug appeared that puzzled me. The domain in the short url is missing!
I've searched a lot of documentation, but couldn't find a solution. Hope you can help me.

A screenshot of the problem bellow.
<img width="329" alt="image" src="https://user-images.githubusercontent.com/32711957/217194876-73d8fd5a-f7dc-48fd-834a-df32c9882715.png">

**Comment by acelaya** [comment]
I'm afraid you are using a very old Shlink version. I would recommend trying to update it (in steps. Don't jump directly to the last one).

Make sure you read this https://github.com/shlinkio/shlink/blob/develop/UPGRADE.md#from-v2x-to-v3x

**Comment by AbelLin1214** [comment]
> 

Thanks for your answer, I will try it now.

**Comment by AbelLin1214** [comment]
Thanks for your answer, I have solved the problem. The docker-compose version I installed on the Centos7 server is too old, so the pulled shlink image is also too old. The environment variable name of V2 is different from that of V3, so this problem occurs.
