### ISSUE TITLE
QR Code Tracking

### ISSUE THREAD

**Issue by antwonw** [shlinkio/shlink#1709]
I'd love to suggest an enhancement to Shlink in the form of QR code tracking.

There are numerous times use cases where a short URL is used in conjunction with it's generated QR code. However, for analytical purposes, one might want to see how users are coming to that short URL beyond user-agent, referral and location information. Specifically, they might want to see and track QR code visits vs direct short URL vists.

This could be setup as an enviroment variable globally, or via a short URL specific configuration behavior.

Potential example of URL specific configuration with web GUI.
![Screenshot 2023-02-22 at 1 36 17 PM](https://user-images.githubusercontent.com/519934/220768226-d885dffb-1020-4f91-8990-cee410138225.png)

Implamenting this might take some thought to provide that URL distinction.

One thought would be to have the QR code contain a query paramater (i.e. `https://exam.ple/abc123?source=qr-code`). Though this might conflict with the existing query param forwarding. However, it might be possible for Shlink to strip that parameter before processing the query param forwarding.

Another option might be in the existing QR code path for the URL, `https://exam.ple/abc123/qr-code`, with a param. However, this would change the whole structure of that path, as that is the generated image and not a URL.

As a reference, and in regards to tracking, this can be done in the Referrers panel, and denoted as a `QR code`. This is very similar to how Bitly does it:

```When someone scans a QR Code for your website, it’s tracked as a click. Bitly breaks down your referral traffic by channel, so you can see how your QR Code is performing up against channels like email and social media.```
_[Viewing Your QR Code Metrics](https://bitly.com/blog/how-to-make-a-qr-code-using-bitly/) on Bitly_

Regardless, this would be an added extra feature to Shlink.

**Comment by acelaya** [comment]
I kind of like the ability to break down "channels" for all the visits of a specific short URL, to know which mechanism is more successful on driving people there.

I would need to put some thought on it though, haha.

However, I would not limit this specifically to the QR code, as it seems too specific and hard to evolve. But as I said. I would need to give it a thought first.

In the meantime, this could be more or less covered by creating two different short URLs pointing to the same location. One of them you use to distribute as a regular short URL, for people to "click" on it, and the other one you share as QR code.

Of course this is not pullet proof, but most real users won't try to mess with those URLs as they get not benefit from it.

In any case, comparing the traffic will require some manual work, as this is not supported by shlink-web-client. See https://github.com/shlinkio/shlink-web-client/issues/376

If the "channels" thing is implemented, it could benefit from a similar comparison capability.

**Comment by antwonw** [comment]
I'll expand on my specific use case a bit more:

We use Shlink's API to integrate into a Drupal module we built. Our Drupal setup runs both a print and digital news publication. The short URL and QR code are exported for print and used in the printed publication that is mailed to roughly 34,000 addresses. That same short URL is also printed in text right next to the QR code in print, and it's also used elsewhere on the Drupal node and Drupal sharing mechanisms.

Viewing it's pretty easy to see the statistics on Shlink Client of those convert and who enter the URL directly into a web browser from print. The digital refers are also to interoperate. The QR code scans are another matter.

We could obviously modify our module to generate multiple short URLs, one for the QR code and another for text printing, but that seems redundant and unnecessary.

I appreciate the thought, @acelaya, and I'm open to dialoguing more on how to best approach this. We've (@nwadventists/@npuc) been fans of this, and even sponsored you/this project for a while in the past.

**Comment by acelaya** [comment]
Closing for now, since there's a reasonable work around described in https://github.com/shlinkio/shlink/issues/1709#issuecomment-1510213799, and not a lot of time available to work on all pending features.

That comment also describes a feature that was missing in shlink-web-client then, but is now available.
