### ISSUE TITLE
Create a new API endpoint to pull all short and long URLs with specific tag value. 

### ISSUE THREAD

**Issue by vijaychhuttani** [shlinkio/shlink#173]
### **GET** `/v1/tags/{tag}/short-code`

This API will return an array of all the shortcodes, ShortURLs and LongUrls which has the `{tag}` assigned to them. It is like a reverse search for a tag. 

This can be helpful in the following scenarios:

1. To fetch short URLs & Long URLs of a specific category
2. To check the assignment of a tag before deleting it. (showing warnings to users of the application)
3. To categorize shortcodes based on target domain names. 
4. To assign shortcodes to specific user (using a seceret user tag generated for each user at application end). etc
5. Get tags created by a specific user (using a seceret user tage generated for each user at application end) and then allowing him to see short-codes associated with it. 

> This can be creatively used in a lot of scenarios.

**Comment by acelaya** [comment]
It is already possible to filter by tag in the list short codes endpoint. You can even filter by multiple tags at the same time.

No need to implement anything.

https://shlink.io/swagger-ui/index.html#/ShortCodes/get_v1_short_codes
