### ISSUE TITLE
Invalid elements: [longUrl] with mailto: URL - 3.5.3 update breaks feature

### ISSUE THREAD

**Issue by cwldev** [shlinkio/shlink#1742]
Shlink running on docker more than a year.

I reference the update in 3.5.3 that breaks my use: https://github.com/shlinkio/shlink/issues/1715

So, I've been using shlink for **mailto:** links and quite successfully so - up to version 3.5.2 - but with this update in 3.5.3, editing or creating mailto: links throws an "ACCESS:ERROR" on the docker log and the following error: "Invalid elements: [longUrl]" - to get around this, I've reverted to 3.5.2

It may be an unintended use or out-of-band to to use mailto:, but if there's a way I can continue doing it while continuing to stay updated, I would love to. Shlink has been great for my small use case and I appreciate the hard work.

Example long url:
mailto:kevin@cwl.cc?subject=Test&body=Test%20Subject%0D%0A%0D%0AThank%20You%2C

Thanks,
Kevin

**Comment by acelaya** [comment]
This is an unintended regression. Will get it sorted out for version 3.5.4

**Comment by acelaya** [comment]
I have just released Shlink 3.5.4, which should fix this. Feel free to skip 3.5.3

The docker images will be available once this has finished https://github.com/shlinkio/shlink/actions/runs/4680956792

**Comment by cwldev** [comment]
That is great.. Thanks so much! I will test when available and update.
