### ISSUE TITLE
Use `docker/metadata-action` to add OpenContainer labels to the container image

### ISSUE THREAD

**Issue by onedr0p** [shlinkio/shlink#1810]
#### Summary

Hi 👋🏼 

It would be awesome if you could use the https://github.com/docker/metadata-action action to apply [opencontainer labels](https://specs.opencontainers.org/image-spec/annotations/) on the container images built here. Alternatively you can add these labels without the action, but the action does make things easier.

Renovate supports pulling in the changelog from applications if these are set. For example, you can read this changelog on this PR
https://github.com/onedr0p/home-ops/pull/5465

**Comment by acelaya** [comment]
I'm open to accept a contribution here
