### ISSUE TITLE
Add "How-to-build" and "How-to-install" info on README

### ISSUE THREAD

**Issue by filfreire** [shlinkio/shlink#183]
I suggest adding to the README file "how to build" the project locally and how to maybe install it (similarly to info on [website](https://shlink.io/installation)), for any newcomers to find that info right on the README.

/cc @acelaya

**Comment by acelaya** [comment]
That's a really good idea (improving the docs has been in the ToDo list since forever)

**Comment by mclendening** [comment]
Greetings,

Following the installation instructions on shlink.io, I am getting some interesting errors when running the bin/install script in Ubuntu 16.04 with Nginx, PHP 7.1.12 (all required PHP modules are loaded):

# bin/install
PHP Fatal error:  Uncaught TypeError: Return value of Shlinkio\Shlink\CLI\Command\Install\InstallCommand::configure() must be an instance of Shlinkio\Shlink\CLI\Command\Install\void, none returned in /home/shlink_1.11.0_dist/module/CLI/src/Command/Install/InstallCommand.php:90
Stack trace:
#0 /home/shlink_1.11.0_dist/vendor/symfony/console/Command/Command.php(77): Shlinkio\Shlink\CLI\Command\Install\InstallCommand->configure()
#1 /home/shlink_1.11.0_dist/module/CLI/src/Command/Install/InstallCommand.php(77): Symfony\Component\Console\Command\Command->__construct()
#2 /home/shlink_1.11.0_dist/module/CLI/src/Factory/InstallApplicationFactory.php(50): Shlinkio\Shlink\CLI\Command\Install\InstallCommand->__construct(Object(Zend\Config\Writer\PhpArray), Object(Symfony\Component\Filesystem\Filesystem), Object(Shlinkio\Shlink\CLI\Install\ConfigCustomizerManager), false)
#3 /home/shlink_1.11.0_dist/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(764): Shlinkio\Shlink\CLI\Factory\InstallApplicationFactory->__invoke(Objec in /home/shlink_1.11.0_dist/module/CLI/src/Command/Install/InstallCommand.php on line 90

Thank you.

**Comment by mclendening** [comment]
`/home/shlink_1.11.0_dist# php -v
PHP 7.1.21 (cli) (built: Aug 20 2018 11:53:44) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with the ionCube PHP Loader (enabled) + Intrusion Protection from ioncube24.com (unconfigured) v10.2.1, Copyright (c) 2002-2018, by ionCube Ltd.
    with Zend OPcache v7.1.21, Copyright (c) 1999-2018, by Zend Technologies`

**Comment by robwent** [comment]
I was just searching for something similar.

As someone new to this, I'm getting stuck at a few points.

I've got the application installed (After installing apcu).

I assumed it had a backend but I see now that it's cli/rest only, but I have no idea how to create an api key.

I installed the react app in a subfolder which didn't work until I edited the file and corrected the paths to where I installed it.
Then trying to add a server, I realised I have no idea how to create an api key and can't find any docs on the available commands or how to list them.

**Comment by acelaya** [comment]
Thanks for your insterest @robwent.

The docs need improvement, yes. I will work on it as soon as I have the time.

API keys can only be created from the CLI. Just run `bin/cli api-key:generate`. The command will output the generated API key.

You can see any available commands by simply running `bin/cli` with no arguments.

**Comment by robwent** [comment]
Yep, I feel a bit dumb now.

I just ran /bin/cli and got a list of all the commands!
