### ISSUE TITLE
Robots.txt and logs

### ISSUE THREAD

**Issue by robwent** [shlinkio/shlink#185]
I just had a check of the logs and it looks like bots are looking for the robots.txt file.

Shlink then checks for a shortcode of `robots.txt` to see if it exists.

I would suggest adding a robots.txt file which tells search engines not to index anything so that the file is served without the application having to do any work.

**Comment by acelaya** [comment]
That's actually a pretty good idea!

I see you already provided a PR. Thanks!

**Comment by acelaya** [comment]
Closed via #186
