### ISSUE TITLE
Cannot open links on iOS device. Windows does.

### ISSUE THREAD

**Issue by PlanetDyna** [shlinkio/shlink#1854]
### Shlink version

Latest

### PHP version

Latest

### How do you serve Shlink

Self-hosted Apache

### Database engine

MySQL

### Database version

Latest

### Current behavior

Page opens with not found or:

Page cannot be opened because Safari could not establish a secure connection to the server.

Running behind NGINX proxy manager. Something to add?

### Expected behavior

Open Privatebin Docker

### How to reproduce

---

**Comment by acelaya** [comment]
Not enough info provided to reproduce

**Comment by PlanetDyna** [comment]
@acelaya: What info do you need?
