### ISSUE TITLE
Allow minimum length to 1 for custom slug to make it real url shortener

### ISSUE THREAD

**Issue by afzl-wtu** [shlinkio/shlink#1859]
### Summary

I want to generate y custom slug with length of 1 how to do that? Currently it is allowing me to generate minimum of 4. But it make url long I want it to make as short as I can. I am using docker image with ENvironmental variable.

**Comment by afzl-wtu** [comment]
Ok SO I just tried I can generate afzal.website/o , even it is not documented. So closing issue now.

**Comment by acelaya** [comment]
Custom slugs don't have a limit, as you can provide whatever value you want.

Auto-generated short codes, on the other hand, cannot have less that 4 characters because otherwise the entropy is not big enough, and would increase the chances of generating duplicated values.
