### ISSUE TITLE
Change the SQLite database path to support volume

### ISSUE THREAD

**Issue by gera2ld** [shlinkio/shlink#1876]
### Shlink version

3.6.3

### PHP version

8.2

### How do you serve Shlink

RoadRunner Docker image

### Database engine

SQLite

### Database version

built-in

### Current behavior

SQLite database does not work with docker volume well. I found [the issue](https://github.com/shlinkio/shlink-docker-image/issues/40#issuecomment-491924262) from the documentation suggesting not to do it.

But actually it is quite simple to support SQLite in a volume as long as `database.sqlite` is in a separate directory.

### Expected behavior

Put `database.sqlite` in a separate directory so we can mount the directory to a volume.

For example, change the current hard-coded path `/etc/shlink/data/database.sqlite` to `/data/database.sql`, then we can mount `/data` to a volume.

The path is hard-coded here:

https://github.com/shlinkio/shlink/blob/bc4156ca3c83ee64c3a7bcdbd653aa84c67ce9c0/config/autoload/entity-manager.global.php#L34

Maybe it should be allowed to change in the docker, e.g. to `/data`, then we mount the folder with `-v ./data:/data`.

### How to reproduce

Follow the official documentation.

**Comment by acelaya** [comment]
This has been discussed in the past. The short story is that SQLite is not meant to be used in production, so you don't need to mount it in a volume.

See these for context:

• https://shlink.io/documentation/supported-db-engines/#sqlite-limitations
• https://github.com/shlinkio/shlink-docker-image/issues/40#issuecomment-491924262
• https://github.com/shlinkio/shlink/pull/1522#issuecomment-1229219312
