### ISSUE TITLE
Alternative IP resolution services

### ISSUE THREAD

**Issue by robwent** [shlinkio/shlink#189]
I was looking into how ip addresses are resolved when looking at the gdpr issue.

I see that ip-api.com is being used but has limits on the api (#175).

I have recently been using some marketing automation software which has some different options for this (https://github.com/mautic).

The standard option downloads a copy of maxmind geolite2 so you can perform unlimited lookups locally.
It has a cron command to download a fresh copy of the db which is set  to about once a month (Usually, I don't think they update it any more frequently than that anyway).
https://dev.maxmind.com/geoip/geoip2/geolite2/

These are the options that are available by default:

Freegeoip.net
Geobytes
GeoIPs
IP2Location Local Bin File
IP2Location Web Service
IPInfoDB
MaxMind - Country Geolocation
MaxMind - GeoIP2 Precision
MaxMind - GeoLite2 City Download
MaxMind - Insights (formerly Omni]
Telize

This is just really for reference incase you were still looking into alternative options.
Geolite2 is also used by a firewall extension I use on a lot of websites.

**Comment by acelaya** [comment]
Hey @robwent
I have managed to integrate GeoLite2 in shlink and it will be included in v1.14. It is really cool and I think it is going to be a great improvement :-)

The system still falls back to the old service in case the IP is not found in GeoLite.

**Comment by robwent** [comment]
Awesome, good work!
