### ISSUE TITLE
Disable logs for health check endpoint

### ISSUE THREAD

**Issue by d-uzlov** [shlinkio/shlink#1896]
### Summary

Either disable logs for health check endpoint completely or add an environment variable to disable it.

### Use case

I want to setup frequent health checks.
However, each health check generates a new log line `Access.INFO - GET /rest/health 200 120`. It's hard to find anything in logs when they are filled with health check entries.

**Comment by acelaya** [comment]
Yep, this makes sense. It's a common practice.

I think it should be ok to just disable the logs for this endpoint. No need for an env var.

**Comment by acelaya** [comment]
This is now implemented and will be released with v3.7.0
