### ISSUE TITLE
Allow setting a single DB url environment variable

### ISSUE THREAD

**Issue by savager** [shlinkio/shlink#1899]
### Summary

Perhaps I'm doing something else wrong, but I thought I'd spin up a test instance of Shlink to evaluate, and having to set many environment variables instead of simply a typical postgres url seems unnecessary. 

Especially in my circumstance where I'm using Google Cloud SQL Proxy's url formatting:

<DB_TYPE>://<USER>:<PASSWORD>@/dbname?host=/cloudsql/<PROJECT_ID>:<REGION>:<INSTANCE_NAME>

I've tried putting dbname?host=/cloudsql/<PROJECT_ID>:<REGION>:<INSTANCE_NAME> as the DB_NAME environment variable, but am still getting an error.

Initializing database if needed...
 [ERROR] Error generating database.. Run with -vvv to see specific error info.  

### Use case

Setting a database url as one environment variable is easier, and cleaner.

**Comment by acelaya** [comment]
Since this adds very little value (small convenience for a one-time task), and considering it is more error-prone and adds complexity to how database connection config is built, I'm closing this.
