### ISSUE TITLE
option to customize QR code color/design

### ISSUE THREAD

**Issue by A2D-Ankit-Dangi** [shlinkio/shlink#1904]
### Summary

Currently, the system offers good short link generation along with QR code generation But it lacks customising the QR code design like changing colour or changing designs etc. if we can have that, it will be a complete package.

### Use case

Currently, it generates QR Code in various sizes and format but it lacks changing colour So if we are planning to use it on website with a theme colour then black qr looks odd So colour customisation will help fit in anything.

**Comment by acelaya** [comment]
Can you elaborate on what you mean by "design"?

Also, this was [already requested](https://github.com/shlinkio/shlink/issues/944) in the past and I ended up closing it due to the limited time I can spend on this project, to focus on more useful features. However it always felt like something that should be supported.

I think that at least the color customization should be a simple enough addition.

**Comment by A2D-Ankit-Dangi** [comment]
Customization means Adding frame logos on qr, For QR design refer this
https://www.the-qrcode-generator.com/
It has so many different designs, although it's a fancy feature, but color custiomization will help a lot.

**Comment by acelaya** [comment]
(I closed this by mistake, by referencing it from a PR that was supposed to close something else. Reopening)

**Comment by acelaya** [comment]
This is now implemented. Changing QR codes foreground and background colors is now fully supported.

Experimental support for logos has also been added. See https://github.com/shlinkio/shlink/pull/2014 for more details.

**Comment by ronindesign** [comment]
> Experimental support for logos has also been added. See [#2014](https://github.com/shlinkio/shlink/pull/2014) for more details.

This is so great, thank you for implementing logo support!! I've been tracking this since the original feature request on #944 back in Dec. 2020. Really appreciate all your work on this app!
