### ISSUE TITLE
Feature Request: Option for URL Masking / URL Cloaking. Hide destination URL.

### ISSUE THREAD

**Issue by chrislawso** [shlinkio/shlink#1954]
### Summary

Option for URL Masking / URL Cloaking. Hide destination URL.

### Use case

An example use case: For marketing and branding purposes a nice to have feature would be ability to choose not to always redirect to the long URL. 
"Revealing" the destination url of 3rd party web services ie hosted forms moves users to unrelated fqdns.
The option to hide destination URL and only display the shortened url using a branded domain would offer more consistent branding.

**Comment by acelaya** [comment]
I know this feature sounds useful, but it would require Shlink to proxy websites, which is very difficult to get done right, from a technical point of view.

See https://github.com/shlinkio/shlink/issues/1170#issuecomment-917453815
