### ISSUE TITLE
Update GeoLite2 database with http request

### ISSUE THREAD

**Issue by mvandenabeele** [shlinkio/shlink#1959]
### Summary

I'd like to update the GeoLite2 database using a HTTP request instead of with bin/cli

### Use case

The shared webhosting company that I use to host has corn functionality builtin to there dashboard, but you can only do a get-request to an URL in the package. CLI is not available.

**Comment by acelaya** [comment]
Manually updating the GeoLite db is only needed if you serve Shlink with a classic web server, which is not the recommended runtime.

On top of that, shared hostings are not the primary focus for Shlink.

This feature would be complex to get right (access control, limiting requests, etc), so I'm afraid I have to say no to this.
