### ISSUE TITLE
Custom Pixels/Analytics for Enhanced Remarketing Capabilities

### ISSUE THREAD

**Issue by ZYB7942** [shlinkio/shlink#1978]
### Summary

Custom Pixels/Analytics for Enhanced Remarketing Capabilities before redirect

### Use case

Dear Shlink Developers,

I hope this message finds you well. I want to express my appreciation for the outstanding work you've done with the Shlink project, establishing it as a reliable and feature-rich URL shortening tool.

I am writing to propose a feature enhancement that could significantly elevate Shlink's capabilities, specifically in the domains of marketing and analytics. I've taken note of a past feature request (#814) concerning the integration of custom pixels/analytics, and I believe revisiting this concept could bring considerable value to the project.

**Overview of the Proposed Feature:**
Enabling the integration of custom pixels/analytics scripts into short URLs would unlock a myriad of possibilities for marketers. This feature would empower these scripts to load and track visits before initiating the redirect function. The primary objective of this enhancement is to facilitate advanced remarketing strategies.

**Significance of Remarketing:**
Remarketing stands as a potent digital marketing strategy that involves targeting users who have previously engaged with your website or content. By incorporating remarketing pixels into redirect pages, Shlink could simplify the creation of custom retargeting audiences. Users clicking on a short link would be seamlessly added to remarketing lists, enabling targeted advertising campaigns without requiring control over the final landing page.

**Reference to Previous Request (Issue #814):**
I noticed that a previous request for a similar feature (Issue #814) was closed in January 2021. While I acknowledge the complexity of such a feature, I believe its implementation would set Shlink apart in the URL shortening landscape, particularly given the scarcity of free alternatives offering similar capabilities.

**Considerations and Proposed Solutions:**
During the discussion of Issue #814, no potential drawbacks were mentioned regarding redirection with an intermediary page. However, it's crucial to consider the following possible drawbacks associated with the introduction of an intermediary page:

1. **Possible Latency Increase:**
   The introduction of an intermediary page may lead to a perceived increase in loading time for users, potentially impacting the overall browsing experience.

2. **Reduced Transparency:**
   Redirecting through an intermediary page might make the navigation process less transparent for end-users, as they may not immediately understand the purpose of the intermediary page.

3. **Engagement Loss Risk:**
   If the intermediary page fails to provide clear value or relevant content, there is a risk of users losing interest or abandoning the navigation altogether.

4. **Additional Complexity:**
   Implementing an intermediary page could add complexity to the redirection flow, requiring more development and maintenance resources.

5. **Potential SEO Impact:**
   Depending on the implementation, redirections through intermediary pages may have consequences for search engine optimization (SEO).

To address these potential concerns, I recommend exploring alternative methods, such as HTTP redirects via headers, and identifying efficient ways to set cookies and pixels. This approach aims to find a balance between achieving remarketing goals and ensuring a fast and transparent user experience.

**Implementation of HTTP Redirects via Headers:**
Using HTTP headers for redirection, instead of an intermediary page, offers several advantages. It ensures a faster and more seamless user experience by avoiding an additional page load. Additionally, it allows for the capture of user data and the setting of pixels, including those for Facebook and Google, before the redirection takes place.

Incorporating a option that allows users to provide their consent for the use of remarketing pixels would be a valuable addition, aligning with the legal privacy requirements of GDPR, it would be optional and could be deactivated in certain campaigns.

I firmly believe that the addition of this feature would not only meet the needs of marketers but also enhance Shlink's reputation as a versatile and forward-thinking URL shortening tool.

Thank you for considering this request, and I eagerly anticipate witnessing the continued success and evolution of the Shlink project.

Best regards, ZYB7942

**Comment by acelaya** [comment]
Closing as Spam.

Probably a bot. Just check the author's profile
