### ISSUE TITLE
Redirection

### ISSUE THREAD

**Issue by AFCC** [shlinkio/shlink#1980]
Hi team, it is RSA security.

Your URL link : https://debary.pro/Ub30U - does a REDIRECTION to a Phishing website(our client named
![p1](https://github.com/shlinkio/shlink/assets/1181115/17579566-7fc0-4b5e-9c69-57c827f1d8b9)
 MyGov).

please shut it down ASAP.

Anti-Fraud Command Center
Outseer, an RSA Company
UK Phone: +44-800-260-6644
US/CA Phone: +1-800-635-8482
AU Phone: +61-1800-950-824
E-mail: afcc@outseer.io
www.outseer.com 105

**Comment by acelaya** [comment]
This project is not endorsed in any way with that domain
