### ISSUE TITLE
URL placeholders are not replaced

### ISSUE THREAD

**Issue by B3QL** [shlinkio/shlink#1992]
### Shlink version

3.7.3

### PHP version

8.2.13

### How do you serve Shlink

RoadRunner Docker image

### Database engine

PostgreSQL

### Database version

15.4

### Current behavior

Hey @acelaya thanks for building the shlink it's an awesome project! 

While playing with it I encountered a problem with placeholders I stuck to resolve.
According to the [docs](https://shlink.io/documentation/advanced/special-redirects/#placeholders) shlink should resolve `{ORIGINAL_PATH}` and `{DOMAIN}` strings before redirect.

I've tested examples from the docs in two scenarios (creating a new link/editing an existing link) and none of them was working as expected. The placeholders were not replaced.

### Expected behavior

Placeholders should be replaced before the redirect.

### How to reproduce

Create a new link with a placeholder token and visit it.

**Comment by acelaya** [comment]
Placeholders are replaced only on special redirects (AKA not-found redirects), not on regular short URLs.

Everything is explained at the beginning of the documentation page you linked.

**Comment by B3QL** [comment]
Thanks for the quick response!
