### ISSUE TITLE
Shlink v3.7.4 docker image is tagged as stable and latest instead of v4.0.2 version

### ISSUE THREAD

**Issue by fab120** [shlinkio/shlink#2054]
### Shlink version

v4.0.2

### PHP version

n/a

### How do you serve Shlink

Docker image

### Database engine

MySQL

### Database version

n/a

### Current behavior

On docker hub `shlinkio/shlink:stable` and `shlinkio/shlink:latest` images refer to version `v3.7.4` instead of `v4.0.2`.
Before the `v3.7.4`/`v4.0.2`. update both image tags where referring to version `v4.0.1`.

### Expected behavior

On docker hub `shlinkio/shlink:stable` and `shlinkio/shlink:latest` should refer to version `v4.0.2`.

### How to reproduce

n/a

**Comment by fab120** [comment]
![Screenshot 2024-03-09 alle 10 43 54](https://github.com/shlinkio/shlink/assets/293368/d9c5cdd4-2889-4439-92f6-9954548aa194)
![Screenshot 2024-03-09 alle 10 45 48](https://github.com/shlinkio/shlink/assets/293368/2c681530-df92-4026-a4ae-e06d5812398e)
![Screenshot 2024-03-09 alle 10 44 10](https://github.com/shlinkio/shlink/assets/293368/65421775-00f3-48f2-8c50-f2b117ddc97f)

**Comment by acelaya** [comment]
Oops! Thanks for the heads-up

**Comment by acelaya** [comment]
Should be fixed now
