### ISSUE TITLE
Allow ordering short URL lists by most recently visited date

### ISSUE THREAD

**Issue by ejohb** [shlinkio/shlink#2061]
### Summary

Hi,

I might be missing something, but I can't find a way of sorting links by the most recent click. The `/non-orphan-visits/list` page lets me sort by clicks, but doesn't show which link the click came from - and the `/list-short-urls/1` shows the links, but doesn't let me sort by click.

Is there really no way to do so?

### Use case

Monitoring recent clicks seems like an obvious omission - and is essential for my use-case.

**Comment by ejohb** [comment]
Thank for the info.

Little hard to sum up, but imagine I send a out a newsletter, which contains multiple short links. I need to see where the clicks are going, in a semi-realtime way, so I need where to devote my attention.

**Comment by ejohb** [comment]
Just to add, literally he only thing missing from the `/non-orphan-visits/list` page is a column showing the short link. Not sure I made that clear.

**Comment by acelaya** [comment]
> Just to add, literally the only thing missing from the `/non-orphan-visits/list` page is a column showing the short link. Not sure I made that clear.

Yes, that's the part I meant it's covered by this https://github.com/shlinkio/shlink/issues/1330

**Comment by ejohb** [comment]
Oh yes, I see now.

I should add I've _partially_ solved the issue with tags (hadn't been using them at all before) which at least lets me isolate clicks on a per-newsletter basis.

**Comment by acelaya** [comment]
Shlink 4.1.0 has just been released, which now exposes the visited URL for non-orphan visits.

Feel free to subscribe to https://github.com/shlinkio/shlink-web-component/issues/244
