### ISSUE TITLE
Wrong type property for Dynamic Redirection's Docs

### ISSUE THREAD

**Issue by davidpiccinini** [shlinkio/shlink#2111]
### Shlink version

4.x

### PHP version

n/a

### How do you serve Shlink

Docker image

### Database engine

MySQL

### Database version

5.7.39

### Current behavior

Sample body for Dynamic Redirects is wrong, APi specs sample for that endpoint is wrong too. Condition property inside rule show JSON: { "type": "query", "matchKey": "hello", "matchValue": "world" } for a query key "hello" with value "world". API query returns 400 for that body. 

Correct "type" property's value for queries is "query-param", discovered using CLI commands. 

Please change to { "type": "query-param", "matchKey": "hello", "matchValue": "world" }

### Expected behavior

-

### Minimum steps to reproduce

-

**Comment by acelaya** [comment]
The schema definition is actually correct: https://github.com/shlinkio/shlink/blob/develop/docs%2Fswagger%2Fdefinitions%2FSetShortUrlRedirectRule.json#L18

What's wrong are the examples: 

* https://github.com/shlinkio/shlink/blob/develop/docs%2Fswagger%2Fpaths%2Fv3_short-urls_%7BshortCode%7D_redirect-rules.json#L80
* https://github.com/shlinkio/shlink/blob/develop/docs%2Fswagger%2Fpaths%2Fv3_short-urls_%7BshortCode%7D_redirect-rules.json#L85

Do you want to provide a pull request?
