### ISSUE TITLE
IP based redirection

### ISSUE THREAD

**Issue by noahboegli** [shlinkio/shlink#2120]
### Summary

For a given link, allow a conditional redirect based on the IP address & ranges of the person viewing the link.

For example
| IP Addresses | Redirect |
| --- | --- |
| 134.134.132.131, 134.14.124.56 | https://linka.com |
| 44.44.132.131, 56.89.12.0/24 | https://linkb.com |
| default | https://defaultlink.com | 

### Use case

In my company, we have several internal software that is not accessible from the internet. 

For some important communications or tasks to complete, we provide the same "feature" on an external service or some of our software that is available on the internet.

For example, we want to collect feedback from employees. We create the survey on our intranet and in a forms provider (Google, Microsoft, etc.). 
We'd like to be able to send an e-mail with one link, that would redirect the user to the correct form based on where he's accessing it from

- Company public IP (our shlink is hosted in a 3rd party hosting provider, thus it's accessed by the internet even from the inside)
    -  Redirect to intranet
- External IP (mobile phones, home computer, etc.) 
    - Redirect to 3rd party forms provider   

I've looked at the code and with some time, I might be able to offer a pull request. Is that something that the project would benefit from in the upstream ?

**Comment by acelaya** [comment]
This sounds like a good use case for dynamic rule-based redirects. 

Feel free to up-vote here https://github.com/shlinkio/shlink/discussions/2101#discussioncomment-9374104
