### ISSUE TITLE
Auto generate a url

### ISSUE THREAD

**Issue by Acemavie234** [shlinkio/shlink#2126]
### Summary

Make it so when you paste a url to be shortened it would automatically generate you a url with 6 characters for example. And if you want to make a custom you could type in the custom slug box and it would override the automatic one

### Use case

It would be useful for quick link shortening. Currently I am just spamming my keyboard when shortening urls. And sometimes it is the same as a previous one so I need to spam again

**Comment by acelaya** [comment]
This is exactly how Shlink works. Have you found any problem with auto-generated short codes?

**Comment by Acemavie234** [comment]
I  just noticed that. I  thought that you  need to always use your own slug, thanks for clarifying!
