### ISSUE TITLE
A + after the short url shows the destination

### ISSUE THREAD

**Issue by PinguDEV-original** [shlinkio/shlink#2145]
### Summary

At bitly for example, if you just add a plus after the short url it will show you where it goes.

### Use case

This would be awesome if someone wants to know where they'll go but do not want to use curl or something.

**Comment by acelaya** [comment]
Could you elaborate how something like this would be beneficial for the average Shlink user, and why existing methods are not enough?

**Comment by acelaya** [comment]
I'll close this as it would require Shlink to be able to render more templates, for a small benefit.

Resolving the long URL can be done in a couple different ways, like using an HTTP client but disabling redirects, using the CLI or using the REST API.
