### ISSUE TITLE
Unable to connect app.shlink.io

### ISSUE THREAD

**Issue by MediaBoothKrish** [shlinkio/shlink#2152]
I am trying to setup a shlink on one of my subdomain as shlink.abc.com and followed the below steps:

[Install using a dist file](https://shlink.io/documentation/install-dist-file/#install-using-a-dist-file)
Download the latest distributable file and decompress it at the location of your choice (you will find a dist file for every supported PHP version).
Create an empty database (not necessary if you are going to use SQLite).
Recursively grant write permissions to the data directory.
Set-up and customize Shlink by either:
Running the [installation tool](https://shlink.io/documentation/command-line-interface/installation-tool) (vendor/bin/shlink-installer install). It’s an interactive tool that will guide you through the installation process.
Providing your configuration via [env vars](https://shlink.io/documentation/environment-variables) (since v2.9.0). Useful to pre-define the configuration or if you don’t have shell access to the server.
Optionally, you can create a symlink to the bin/cli script in a folder which is in your path.
For example /usr/local/bin for linux systems. This will allow you to easily run Shlink from anywhere in the command line.
Generate your first API key (you will need it in order to interact with Shlink’s API):
For Shlink older than 3.3.0, run bin/cli api-key:generate.
For Shlink 3.3.0 or newer, the installation tool will create an API key for you. Just copy-paste it.
Set-up Shlink’s runtime:
[Serve Shlink using RoadRunner](https://shlink.io/documentation/supported-runtimes/serve-with-roadrunner/).
[Serve Shlink with a classic web server](https://shlink.io/documentation/supported-runtimes/classic-web-server/).

But unable to do this step: Finally, access to https://app.shlink.io/ and configure your server to start creating short URLs.
Got an error: 
<img width="1129" alt="Screenshot 2024-07-08 at 1 26 29 PM" src="https://github.com/shlinkio/shlink/assets/136290746/ecf4c6d2-ac61-4e0d-90ce-86642eff824b">

Also, I need help to fill this field too
<img width="1371" alt="Screenshot 2024-07-08 at 1 26 59 PM" src="https://github.com/shlinkio/shlink/assets/136290746/08533821-10df-4d6b-86da-a23bd23fb616">

**Comment by acelaya** [comment]
Issue/discussion templates are mandatory. Please provide all this information so that it's possible to help you. 

https://github.com/shlinkio/shlink/discussions/new?category=help-wanted
