### ISSUE TITLE
HTTP status code per short URL

### ISSUE THREAD

**Issue by JasonHK** [shlinkio/shlink#2155]
### Summary

I hope HTTP status code for each short URL could be configured in a case-by-case fashion.

### Use case

For example, I would like to use Shlink to redirect from old-domain.com to new-domain.com with HTTP 301, but short URLs in short.tld keep using HTTP 302.

**Comment by acelaya** [comment]
This granularity would add too much complexity to Shlink.

For this particular need, I would recommend setting-up different Shlink instances.
