### ISSUE TITLE
Can't install from docker-compose.ylm : resolve : lstat /root/data: no such file or directory

### ISSUE THREAD

**Issue by aquatic7** [shlinkio/shlink#2167]
### Shlink version

4.1.1

### PHP version

x

### How do you serve Shlink

Docker image

### Database engine

MySQL

### Database version

x

### Current behavior

```
root@shlink-url-shortener:~# docker compose up -d
[+] Building 0.0s (0/0)                                                         docker:default
resolve : lstat /root/data: no such file or directory
```

### Expected behavior

It should build and run. :)

### Minimum steps to reproduce

download docker-compose.ylm file to server
run command: docker compose up -d

**Comment by acelaya** [comment]
> download docker-compose.ylm file to server

Waiting for the file to be provided.

**Comment by aquatic7** [comment]
> > download docker-compose.ylm file to server
> 
> Waiting for the file to be provided.

File is https://github.com/shlinkio/shlink/blob/develop/docker-compose.yml

**Comment by acelaya** [comment]
That's only meant to be used while developing Shlink itself.

Follow the documentation in order to use Shlink with docker in production https://shlink.io/documentation/install-docker-image/
