### ISSUE TITLE
[Feature Request] Supporting IPinfo's free IP to Country ASN/ISP database

### ISSUE THREAD

**Issue by abdullahdevrel** [shlinkio/shlink#2176]
### Summary

I am requesting to add support for [IPinfo's IP to Country database](https://ipinfo.io/products/free-ip-database) to the project. The database has the following features:

- It includes country and ASN information in the same database.
- It is updated daily, with zero compromise to accuracy. There is no range clustering, and the database provides full accuracy.
- The data granularity reaches individual IP level.
- The database comes in MMDB database format.
- It is licensed under CC-BY-SA 4.0, permitting commercial usage.
- Available file formats include: CSV, MMDB, JSON
- The data is tabular and unnested, making it very easy to use. The dataset includes both IPv4 and IPv6 in a single file.

## Database schema

| Field Name       | Example                      | Data Type | Description                                       |
|------------------|------------------------------|-----------|---------------------------------------------------|
| `start_ip`       | 1.0.16.0                     | TEXT      | Starting IP address of an IP address range        |
| `end_ip`         | 1.0.31.255                   | TEXT      | Ending IP address of an IP address range          |
| `country`        | JP                           | TEXT      | ISO 3166 country code of the location             |
| `country_name`   | Japan                        | TEXT      | Name of the country                               |
| `continent`      | AS                           | TEXT      | Continent code of the country                     |
| `continent_name` | Asia                         | TEXT      | Name of the continent                             |
| `asn`            | AS2519                       | TEXT      | Autonomous System Number                          |
| `as_name`        | ARTERIA Networks Corporation | TEXT      | Name of the AS (Autonomous System) organization   |
| `as_domain`      | arteria-net.com              | TEXT      | Official domain or website of the AS organization |

Documentation: https://ipinfo.io/developers/ip-to-country-asn-database

Samples are available here: https://github.com/ipinfo/sample-database/tree/main/IP%20to%20Country%20ASN

The database can be downloaded simply by accessing the [storage URI with an access token](https://ipinfo.io/developers/database-filename-reference).

```bash
curl -L https://ipinfo.io/data/free/country_asn.mmdb?token=<YOUR_TOKEN> -o country_asn.mmdb
```

### Use case

The project currently requires users to pass their geo-ip download keys. If you integrate IPinfo's IP to Country ASN database, you can include a project-specific access token that will take care of the download mechanism itself without the user needing to provide their access token. The download mechanism is quite simple as well as you can download the database via a storage URI.

**Comment by acelaya** [comment]
Thanks! 

Simplifying the installation and setup process would definitely be nice. 

I'll take a look and see how hard it would be to integrate.

**Comment by abdullahdevrel** [comment]
Thank you very much for reviewing the request.

Most projects have their own project-specific access token and offer users the option to bring their access token as well. However, in Shlink's case, I do not believe that bringing your own token is necessary. The database is updated daily so users can get the most accurate data. I believe the project downloads the IP database every 35 days. IPinfo's database download happens via storage URI, so there is no complexity involved in downloading. The database is not zipped or anything as well.

Please let me know if you need any help.

**Comment by acelaya** [comment]
When I first read this issue, I somehow came with the idea that IPinfo did not really require authentication, but I see you were actually suggesting for Shlink to include a token for all users to use.

I'm afraid this is not going to be an option, for a couple of reasons:

* Being Shlink an open source project, anyone would have access to the token, which could end up being used with malicious purposes. That could lead to the token being revoked, breaking all users installations.
* It may be possible for the token to work for everyone today, but IPinfo could decide to change their policies in future, again, breaking everyone's installations. This happened some years ago with GeoLite: https://github.com/shlinkio/shlink/issues/596

So if this were implemented, it would have the same requirements as GeoLite, where every user would have to provide their own token.

Because of that, I no longer see a clear benefit on adding support for IPinfo. At the end of the day it will work the same for end users, and it will introduce one extra thing to work on and maintain, so I'm going to close this.

**Comment by abdullahdevrel** [comment]
@acelaya I appreciate you taking a closer look at the request, but these are non-issues. Let me explain.

> Being Shlink an open source project, anyone would have access to the token, which could end up being used with malicious purposes. That could lead to the token being revoked, breaking all users installations.

Well, we've got it covered here :) Each access token is granted X amount of data downloads from each unique IP address. The default is 10 downloads per IP address. Read about it here: https://community.ipinfo.io/t/announcement-we-are-adding-rate-limits-to-data-downloads/358

When a project uses our data, they can either package the access token with the repo. For the end user, they are downloading the database using the repo-specific project, but since their IP address is unique, they get their own X amount of downloads using the same token.

We processed two trillion requests last year. We are comfortable with egress costs of the free database. The intention of the database is purely about giving back. Open-source projects keep us and the world moving forward, so it is our duty to give back.

> It may be possible for the token to work for everyone today, but IPinfo could decide to change their policies in future, again, breaking everyone's installations. This happened some years ago with GeoLite: https://github.com/shlinkio/shlink/issues/596

This is nearly impossible. Anything can happen in the future, but the framework of the free database is that it is the minimum we can do for the open source community. We do not have a monetization plan for open source projects. I am extremely familiar with our competitors' policies, changes and history. We have taken them as lessons to produce the best developer experience possible. 

So, it all sounds great. You might still be wondering what the catch is? Being picky here, we do not have a city location database for free. We provide the best possible country-level data that is out there even better than paid databases. We have been operating for more than a decade, and you will be extremely hard-pressed to find any critical concerns from developers about our policies, data, or company. We are stable, and we are happy to support open source projects.

Please consider my opinion and look into us, as well as other projects that are using our data. I would really appreciate hearing from you again.
