### ISSUE TITLE
fixed short name

### ISSUE THREAD

**Issue by petrmalkov** [shlinkio/shlink#2182]
### Summary

Could you please make fixed short names, so they could be bookmarked and only on server side refreshed by new target link.
I guess "fixed" means "typed name", i.e. "domain.com/my_favourite_link" which goes to long link.
If this feature exists, please share info how to do this.

### Use case

I also use streaming and for clients I want to have only readable link, not some code in it. And abbility to refresh target only on server.

**Comment by acelaya** [comment]
Already supported. Search for "custom slug".
