### ISSUE TITLE
Disable geolite2

### ISSUE THREAD

**Issue by apixandru** [shlinkio/shlink#2189]
### Summary

It doesn't seem like you can disable geolite2 unless you disable tracking.

### Use case

I think that there's still value of tracking access even if we don't consult with geolite2 to figure probe the ip location access.

The feature is nice and all but it really should not be a dependency to run a url shortener.

**Comment by acelaya** [comment]
Shlink still tracks visits even if you don't provide a GeoLite license key. They will just show as unlocated.
