### ISSUE TITLE
machine parsable output format from Shlink CLI

### ISSUE THREAD

**Issue by theofficialgman** [shlinkio/shlink#2196]
### Summary

Shlink's CLI outputs (most) commands using the following format

```shell
+----+----+-----+
column1|column2|column3|
+----+----+-----+
stuff|stuff|stuff|
stuff|stuff|stuff|
stuff|stuff|stuff|
+----+----+-----+
```
this format is good for human interface but not for consumption by other processes.
it would be helpful if the output formatting could be customized by the user (eg: delimited list, xml, json, etc).

### Use case

Currently one of the simplest ways to obtain the detailed visits information for all shortcodes is to use the shlink CLI. The REST api is also an option.

A user may want to consume the Shlink CLI output but (currently) needs to do some data cleanup in order to make it usable.
It would be beneficial if an additional command line arg could be supplied to change the output format from the current to something similar to a delimiter (ideally customizable) separated list (or xml, json, etc).
eg:
```
column1,column2,column3
stuff,stuff,stuff
stuff,stuff,stuff
stuff,stuff,stuff
```

**Comment by acelaya** [comment]
It is tricky to make the CLI generate machine-parseable output, at least for some more complex commands, as they deal with pagination and still require human interaction in many cases.

If you really need to automate something, I'd recommend using the API instead.
