### ISSUE TITLE
404 Error When Accessing Shlink URL

### ISSUE THREAD

**Issue by taleemhussain** [shlinkio/shlink#2205]
I am experiencing a 404 error when trying to access the Shlink application after following the installation steps. Despite completing the setup, the public URL returns a "Not Found" response.

**Steps to Reproduce**
Set up a local server environment using XAMPP
Installed Shlink following the official installation guide.
Attempted to access the application via the URL http://localhost:8080/shlink/public/.

**Expected Behavior**
The Shlink application should load successfully, allowing me to create and manage short URLs.

**Actual Behavior**
The application returns a 404 error with the message "Not Found."

**Comment by acelaya** [comment]
That's the expected behavior. You can customize a redirect by following this https://shlink.io/documentation/advanced/special-redirects/

If you were expecting to see an admin UI, this is what you want https://app.shlink.io

**Comment by acelaya** [comment]
Duplicates https://github.com/shlinkio/shlink/discussions/1924
