### ISSUE TITLE
Query params replacing space (%20) with underscore (_)

### ISSUE THREAD

**Issue by DAVe3283** [shlinkio/shlink#2213]
### Shlink version

4.2.1

### PHP version

8.3.12

### How do you serve Shlink

Docker image

### Database engine

PostgreSQL

### Database version

13.9

### Current behavior

Spaces in query parameters are replaced by underscores.

For example, `https://internal.fqdn/F4UVN?spaces are valid=true` redirects to `http://www.example.com/?spaces_are_valid=true`
(note the underscores instead of spaces)

### Expected behavior

Spaces need to be preserved in the query parameters.

For example, in Tableau, query parameters can be used to set filters on the linked dashboard, but most filters contain spaces in their names. When the spaces are changed to underscores, it breaks the filtering.

### Minimum steps to reproduce

1. Create a short URL to any domain (`http://www.example.com` is good since it doesn't do anything with query parameters).
1. Ensure `Forward query params on redirect` is enabled.
1. Go to the short URL and add some query parameters with spaces (e.g. `?Some Filter=1`)
1. Observe they have been replaced with underscores (e.g. `?Some_Filter=1`)

**Comment by acelaya** [comment]
Yeah, I can reproduce that. That's weird. 

I'll check why this is happening.

**Comment by Fibonacci78** [comment]
Some additional information on this bug.  A subset of percent encoded characters in parameters are being replaced with the non-percent encoded versions.

Here is a test sample:

- %20 -> _
- %22 -> "
- %25 -> %25
- %2D -> -
- %2E -> _
- %3C -> <
- %3E -> >
- %5C -> %5C
- %5E -> %5E
- %5F -> _
- %60 -> %60
- %7B -> %7B
- %7C -> %7C

Space and period are placed with underscore, but others seem to be replaced with the correct equivalent character.  I don't see any particulate logic to what is or is not being replaced.

**Comment by acelaya** [comment]
This should now be fixed. I'll release v 4.2.2 soon.

**Comment by acelaya** [comment]
I have just released Shlink 4.2.2 which includes the fix for this.
