### ISSUE TITLE
Granularly disable logo in QR codes

### ISSUE THREAD

**Issue by PaulGossen** [shlinkio/shlink#2229]
### Summary

It would be very helpful if it were possible to disable the logo in the QR code per URL. This could look like this in the web client:

![](https://i.postimg.cc/jdBhQgVg/Screenshot-2024-10-18-072148.png)

Alternatively, it might be better to allow multiple logos. Then a dropdown menu would be conceivable in which the logo could be selected or no logo at all.

### Use case

There are situations in which no logo should be displayed in the QR code. It should not be necessary to set up a new instance of Shlink without a logo for this.

**Comment by acelaya** [comment]
Thanks for the suggestion.

Allowing to disable the logo should be easy enough, and I agree it is useful, so I'll get it implemented.

As per supporting multiple logos, it may be trickier, as providing a map of values via env vars/config options is very error-prone.

I'm considering [some improvements](https://github.com/shlinkio/shlink/discussions/2234) over how Shlink handles QR codes, that may make it easier to support multiple logos in future. I'll probably wait for that to be implemented first.
