### ISSUE TITLE
Config option to ignore extra paths

### ISSUE THREAD

**Issue by sutterseba** [shlinkio/shlink#2265]
### Summary

Currently, there is a config option "Append extra path", which will append extra paths in the URI to the destination, e.g. /example/blah will forward to destination.com/blah. 

A similar config option that does **not** append additional paths to the destination and instead **ignores them** would be great and should be quite simple to implement. 

```
short.com/example                -> destination.com
short.com/example/blah           -> destination.com
short.com/example/blah/blah/blah -> destination.com
```

### Use case

This would generally allow distinguishing URLs from each other outside the native tracking/tagging solutions. In my case, I have a lot of old URLs with lots of different additional paths (due to how our old URL shortener worked) which would currently all break with Shlink.

**Comment by acelaya** [comment]
Yeah, I think this shouldn't be super hard to do.

As you noted, there's currently a configuration option to tell if the extra path should be appended when redirecting. This option accepts `true` and `false` values.

I would probably deprecate this option and replace it with a more flexible one that accepts a set of values that would determine how to match short URLs when an extra path is found:

* `default`: Any extra path will result in no short URL matched (404). Equivalent of passing `false` for current `REDIRECT_APPEND_EXTRA_PATH` option.
* `append`: The extra path is appended before redirecting. Equivalent of passing `true` for current `REDIRECT_APPEND_EXTRA_PATH` option.
* `ignore`: The new behavior requested here.

The last two options would be handled in [`ExtraPathRedirectMiddleware`](https://github.com/shlinkio/shlink/blob/fef512a7a35936365bf44fc29e6c81e4b7dba389/module/Core/src/ShortUrl/Middleware/ExtraPathRedirectMiddleware.php#L78), ignoring the `$extraPath` if the options is configured as `ignore`.

**Comment by acelaya** [comment]
This feature is now implemented, but ti will still take a couple months to release with v4.4.0

**Comment by sutterseba** [comment]
Awesome, thanks for the quick initiative! I guess I can just build from the develop branch myself if I want to use it earlier. :)

**Comment by acelaya** [comment]
> Awesome, thanks for the quick initiative! I guess I can just build from the develop branch myself if I want to use it earlier. :)

Yep, you can always do that. 

I may release a smaller-than-usual v4.4.0 before the end of the year though, with some features that do not affect public API surfaces, but that will take at least a few weeks as well.
