### ISSUE TITLE
Index on short code does not work if domain is null.

### ISSUE THREAD

**Issue by marijnvandevoorde** [shlinkio/shlink#2285]
### Shlink version

4.3.0

### PHP version

8.4

### How do you serve Shlink

Self-hosted RoadRunner

### Database engine

MicrosoftSQL

### Database version

12.0

### Current behavior

Our Shlink instance holds over 1.6M records right now and redirects became really, really slow. We did some digging and noticed that we hadn't been setting a domain to the short urls. That means that the short_urls.domain_id was always null. The index that is used for the redirect spans both columns. This is correct, but because the domain_id column is first, the index is not used in our case.

### Expected behavior

The index should also be used in case no domain is set. This could be achieved by switching the two columns around, this fixes our issue. It does not degrade performance for other usecases. You now first check on the column with high cardinality (very unlikely to have multiple identical values, almost impossible). In the edge case where two identical shortcodes are present, only a few rows will be left (same shortcode but for different domains).

(Which makes me realise, by the way: What if the same shortcode is presetn with null as domain and then a specific domain. I would expect it to take the explicit one over the non explicit one as behviour, and that's probably how it works. But we don't have that usecase, so not an issue for us)

### Minimum steps to reproduce

- Enter a ton of records in your DB with null as domain_id
- do a search and check the execution plan. Notice how the index is not used.

**Comment by acelaya** [comment]
Good spot! I'll try to get it sorted.

> (Which makes me realise, by the way: What if the same shortcode is presetn with null as domain and then a specific domain. I would expect it to take the explicit one over the non explicit one as behviour, and that's probably how it works. But we don't have that usecase, so not an issue for us)

It will pick up the one corresponding to the visited domain. If the default domain is visited, it will pick up the entry where domain is `null`, if the other domain is visited, then it will pick the one explicitly set for that domain. 

There's a more detailed explanation here to know how different combinations would work, in case you are curious https://shlink.io/documentation/advanced/multiple-domains/#visits

**Comment by marijnvandevoorde** [comment]
Makes 100% sense, it's what I would expect, if we had that usecase. All good! And thanks for picking this up, much appreciated!

**Comment by acelaya** [comment]
> I need to check how long would that take for instances with a lot of short URLs like in your case.

It takes milliseconds for 1M short URLs, so i think it's fine.

**Comment by acelaya** [comment]
I have just released v4.3.1 which includes a fix for this.

**Comment by marijnvandevoorde** [comment]
Oh dear, this is turning into a little saga here.

The create for the new index looks like this:
`SET ANSI_PADDING ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [unique_short_code_plus_domain] ON [dbo].[short_urls]
(
	[short_code] ASC,
	[domain_id] ASC
)
WHERE ([short_code] IS NOT NULL AND [domain_id] IS NOT NULL)
WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
`

Notice the part where it says " **AND [domain_id] IS NOT NULL**". In our case, all the records have a domain_id = null. So it can't use the index to search those. But even if that were not the case, the query that is built by the url forwarding endpoint, checks for it.
`WHERE s0_.short_code = 'xxxxxxxxxxxxxx' AND (s0_.domain_id IS NULL OR d1_.authority = 'mydomain.com')`

So... the query optimizer decideds to go over all our 1.6M records... Resulting in a query time of 4 seconds... 
Adding an index on just the shortcode (not unique) = query of 0.0.036 seconds...


I do understand that you require the unique index on the combo, so the index has to stay I guess. But be aware that shlink is not using the index on ms sql to find the original url for a given short url.

**Comment by acelaya** [comment]
Thanks! 

I have created a new issue to make sure I don't lose track of this https://github.com/shlinkio/shlink/issues/2319

Feel free to subscribe there.
