### ISSUE TITLE
Import redirect rules when importing short URLs from another Shlink instance 

### ISSUE THREAD

**Issue by Juijote** [shlinkio/shlink#2309]
### Summary

When importing other instance data, importing redirection rules is also allowed.

### Use case

Almost all of my short links have redirect rules set up. If they cannot be imported, it would be too painful to reset them myself...

**Comment by acelaya** [comment]
Requires https://github.com/shlinkio/shlink-importer/issues/68

**Comment by acelaya** [comment]
This is now implemented. Shlink 4.4 will import redirect rules when importing short URL from another Shlink >=4.0.0 instance.

**Comment by Juijote** [comment]
very thankful
