### ISSUE TITLE
Add a custom loading page before redirection

### ISSUE THREAD

**Issue by fx-k** [shlinkio/shlink#2318]
### Summary

Hi, I consider that shlink is an extremely modern project, but i found that many URL-shortening projects have a feature for custom loading pages, which means that, when users open a shortened URL, there’s a few seconds of a loading page that allows administrators to display personalized branding or advertisements (I’d like to use it for some cool loading animations). 

I really love shlink’s modern UI, and I hope this feature can be considered. thanks!!

### Use case

when users open a shortened URL, there’s a few seconds of a loading page that allows administrators to display personalized branding or advertisements (I’d like to use it for some cool loading animations).

**Comment by acelaya** [comment]
There have been similar requests in the past. Shlink won't be shipping anything that requires dynamic template rendering, that's out of its scope.
