### ISSUE TITLE
Improper stats scaling with high number of unique countries

### ISSUE THREAD

**Issue by tivyhosting** [shlinkio/shlink#239]
When your link statistics have a high number of unique countries to be displayed, it's very difficult to read. The graph needs to scale to accommodate for this.

http://i.xq.ms/i/KZYfn.png

**Comment by acelaya** [comment]
Yes, totally true, that's a known issue to which I'm still trying to find a proper solution.

It's on shlink-web-client though, not on shlink itself, so I have created a ticket there https://github.com/shlinkio/shlink-web-client/issues/63

I will try to include a fix for this on the next release.

**Comment by acelaya** [comment]
@tivyhosting I have just releasev [shlink-web-client v1.1.1](https://github.com/shlinkio/shlink-web-client/releases/tag/v1.1.1), which addresses this issue.

It is already updated at https://app.shlink.io/, if that's what you are using.

The solution is not 100% accurate, but it makes graphs to be bigger when the amount of bars is higher.
