### ISSUE TITLE
GeoIP Recommendation

### ISSUE THREAD

**Issue by tivyhosting** [shlinkio/shlink#240]
GeoIP could make use of a local database like GeoLite from Maxmind instead of an external API, to improve the capacity of Shlinked, as there would be no API limit on a local db.

If the IP is outside of the database, it could then use an external source like it is now.

https://dev.maxmind.com/geoip/legacy/geolite/

**Comment by acelaya** [comment]
Yes definitely.

That's something which has already been discussed in the past (https://github.com/shlinkio/shlink/issues/189), and I plan to change it since there are a few interesting alternatives.

**Comment by acelaya** [comment]
I have implemented the integration with GeoLite2 and it will be part of Shlink 1.14 (to be released soon).
The old service is still used as a fallback.
