### ISSUE TITLE
Bug with certain length geni.us links

### ISSUE THREAD

**Issue by tivyhosting** [shlinkio/shlink#245]
For some reason Shlink errors when trying to make a short link for Geni.us links that have a 4 digit short code.

https://i.imgur.com/NTROYww.png

**Comment by acelaya** [comment]
That URL works for me, and the redirection loop works fine after that.

![image](https://user-images.githubusercontent.com/2719332/47601359-c87ea200-d9cf-11e8-8ca3-f0d40e3d8516.png)

Could you please check what's the response your shlink instance is returning to the `POST` request?
