### ISSUE TITLE
Insufficient length for user_agent column in MySQL db

### ISSUE THREAD

**Issue by tivyhosting** [shlinkio/shlink#253]
Seems to be a bug with the useragent of a viewer being too long for the capacity of that db table.

https://pastebin.com/DJcGb7sA

**Comment by tivyhosting** [comment]
Changed the length of the user_agent column to varchar(512) from varchar(256) and that fixed the bug.

Would recommend implementing this in the default database structure

**Comment by acelaya** [comment]
This is easy to change. I'll try to include it in the next release.
