### ISSUE TITLE
Bug with visit:process command

### ISSUE THREAD

**Issue by tivyhosting** [shlinkio/shlink#254]
Seems to hang on the attached IP, and when you have a crontab setup this creates more and more visit:process instances until you run out of memory.

Would recommend implementing a timeout to prevent the memory from being eaten up, but the root issue should also be resolved.

EDIT: Here is the IP it's hanging on: https://i.imgur.com/BQL2WWi.png

**Comment by acelaya** [comment]
Closed as of #258
