### ISSUE TITLE
Efficiency Improvement for IP Processing

### ISSUE THREAD

**Issue by tivyhosting** [shlinkio/shlink#265]
Would it be more efficient to check for duplicates before processing IPs? You'd need to then keep a count for each IP, but would speed up the processing stage.

**Comment by acelaya** [comment]
This problem should be drastically mitigated with the new IP resolution implementaron done here https://github.com/shlinkio/shlink/pull/258, which uses GeoLite2 and a local database.

It's much faster (specially when trying to resolve the same IP more than once), and has no API limit.

However, having this extra check might be worth it. I will take it into account.

The new implementation is already merged into master. I will try to finish a couple things before releasing the new version, and release it not later than the weekend.

**Comment by acelaya** [comment]
@tivyhosting I have been thinking on this, and taking into account the changes made for v1.14.1, I'm starting to think that this could be more a problem than a solution.

The biggest bottleneck while processing a lot of visits doesn't come from the IP location itself (as I said, GeoLite2 is super fast), but from having a lot of entities in memory.

The implementation made for v1.14.1 solved that problem by lazyly loading every visit into memory, locating it, and then flushing it. Trying to avoid duplicated locations will force to keep an indexed map of located IPs in memory, which would bring back the "too many things in memory" problem again.

I'm going to move this out from 1.15.0 milestone for now, and wait for you to give me some feedback about v1.14.1. If you still experience memory leaks, I will make some more tests and see how to improve the process.

**Comment by tivyhosting** [comment]
It's INSANELY fast now. Processed several thousand clicks in less than 30 seconds. I don't have exact numbers, but the output of visit:process now moves way too fast to even think about being able to read it now.

gg!

With this speed, checking for duplicates is really not necessary. Although my idea is that visit:process would run a separate process first, that would go through the queued visits, condense down any duplicates to the IP w/ the quantity and THEN AFTER WHICH the geolocation process would run, meaning you still don't have to keep it all in memory for the actual processing. Not sure how long that duplicate check process would take though, so that's up to you.

**Comment by acelaya** [comment]
I'm glad to hear that :-)
