### ISSUE TITLE
URL Validation disabled

### ISSUE THREAD

**Issue by jr-k** [shlinkio/shlink#281]
I've installed shlink with bin/install and when the prompt asked me for validate_url configuration I said "true". 

Then after some tests I finally don't need that validation so I changed validation_url to false in all these files :
- ./config/params/generated_config.php
- ./config/autoload/url-shortener.global.php
- ./data/cache/app_config.php

But I can't shorten URL like "http://192.168.1.1" or "http://unreachable.host.com" for exemple.

What am I doing wrong ? Is there something I need to do to disable that validation ?

Thanks.

**Comment by jr-k** [comment]
I'm still facing the issue. Weird.

**Comment by acelaya** [comment]
Ok, I'll make some checks and try to find the issue.

**Comment by acelaya** [comment]
I have been checking, and cannot reproduce the issue. As soon as I disable the validation, it lets me set any invalid URL :thinking: 

![image](https://user-images.githubusercontent.com/2719332/48916032-0660d000-ee81-11e8-9900-d4ab37632527.png)

I'm thinking if maybe the issue is something else. Could you check your logs (inside `data/log`) for messages like `Provided URL "http://unreachable.host.com" is not an existing and valid URL`. If you don't find that, the the issue is something else.

**Comment by acelaya** [comment]
Ok, it probably has nothing to do, but the `shortcode_chars` is not an encoding, but the set of characters to be used on short codes (the `utm4ftfm` part in your short URL has been generated from that). Usually the best idea is to let shlink generate one.

I would recommend you to change that. Run `bin/cli config:generate-charset` and copy generated value there. Any existing short URL will keep working, so it is safe to do it.

Going back to your issue, it is clearly that the flag is still `true` somewhere. The only thing I can think ofis that maybe there's some sort of opcache in place.

* First, delete the `data/cache/app_config.php` file
* Then restart the php-fpm/nginx/apache services to make sure any memory cache is released
* Then run the up somehow (access a short URL, run a command, anything should work)

After that, the `data/cache/app_config.php` file should have been regenerated. Open it and look for the `validate_url` option there. If it is `false` and you keep getting the error, let me know.

**Comment by jr-k** [comment]
I dropped my database and I re-installed it again with `cli/install` with care (validate_url to "no" in prompt) but I have the error this time again...

**Comment by jr-k** [comment]
It's working, yeah that was this. the 1.14.1 dist maybe.

I also got one small problem during installation of this repository, after the composer install, I tried to install but there was a problem with .env file not existing. I just `cp .env.dist .env` and thats it.

Thanks for your help dude.

**Comment by acelaya** [comment]
You should always use dist files. There are several things to take into account when manually building the project, which are documented at the top of the readme file.

The .env file is meant to be used during development, and not in production. That error means that you are using development dependencies, which will probably affect the application performance.

It doesn't mean it won't work though :)

**Comment by jr-k** [comment]
Yeah but, the issue you know, did you tried to reproduce that behavior with the 1.14.1 dist ?

**Comment by acelaya** [comment]
Yes, that's the version in which I did all the tests.
