### ISSUE TITLE
Return shorten url even when the slug is already in use.

### ISSUE THREAD

**Issue by jr-k** [shlinkio/shlink#283]
When I use the endpoint `/rest/v1/short-urls` in combination with `customSlug` it would be nice to return the shorten-url even if it is already in use.

'error' => string 'INVALID_SLUG' (length=12)
'message' => string 'Provided slug XXX is already in use. Try with a different one.'

That way I'm not forced to forge it myself with my short domain and the customSlug, I just send a request with the longUrl and I get the shortenUrl even if it's in use.

**Comment by acelaya** [comment]
This is basically the same as this https://github.com/shlinkio/shlink/issues/279
