### ISSUE TITLE
Automatically look for broken links

### ISSUE THREAD

**Issue by Braintelligence** [shlinkio/shlink#333]
Hi there, is it possible to incorporate a cronjob or the like to let Shlink automatically look for broken links? It could visit links with a headless browser and if the site returns 404 it would mail the creator of the shortened URL and inform about this.

**Comment by acelaya** [comment]
Yep, I think it could be an interesting feature :)
I'm even thinking on using that command to add a flag to the URL that can be later exposed in the API.

**Comment by acelaya** [comment]
Closing in order to narrow down the amount of features to maintain due to limited time.
