### ISSUE TITLE
Add links health check which verifies already created long URLs keep being valid

### ISSUE THREAD

**Issue by acelaya** [shlinkio/shlink#334]
- [ ] Create CLI command to check all existing links
- [ ] Add notifications via email with all the links which are down (it should be possible to configure how many emails to receive)
- [ ] Add step on installation to ask for checks and SMTP server params
- [ ] Add fields on short URLs telling the status (not verified, valid and failed, and the last time it was verified by the server)
- [ ] Include verification fields on REST API responses

Refs #333

**Comment by acelaya** [comment]
This feature is big enough to be on a milestone by itself. Moving out of 1.18 to not delay release.

**Comment by acelaya** [comment]
Blocked until https://github.com/acmailer/acmailer/milestone/22 is implemented

**Comment by acelaya** [comment]
Closing in order to narrow down the amount of features to maintain due to limited time.

**Comment by Clem-** [comment]
Hi, now that the milestone is implemented, will this feature be re-planned anytime soon?
Thanks!
