### ISSUE TITLE
APCu Error even with APCu enabled

### ISSUE THREAD

**Issue by tivyhosting** [shlinkio/shlink#347]
Randomly started getting the APCu error while nothing has changed in my setup. On both PHP 7.1 and 7.2 (both with APCu installed).

Have a couple hundred thousand visits worth of analytics waiting to be processed. :P

--

PHP Fatal error:  Uncaught Error: Call to undefined function apcu_fetch() in /srv/users/lmg-gg/apps/shlink-1-13-1/vendor/doctrine/cache/lib/Doctrine/Common/Cache/ApcuCache.php:26
Stack trace:
#0 /srv/users/lmg-gg/apps/shlink-1-13-1/vendor/doctrine/cache/lib/Doctrine/Common/Cache/CacheProvider.php(200): Doctrine\Common\Cache\ApcuCache->doFetch('DoctrineNamespa...')
#1 /srv/users/lmg-gg/apps/shlink-1-13-1/vendor/doctrine/cache/lib/Doctrine/Common/Cache/CacheProvider.php(177): Doctrine\Common\Cache\CacheProvider->getNamespaceVersion()
#2 /srv/users/lmg-gg/apps/shlink-1-13-1/vendor/doctrine/cache/lib/Doctrine/Common/Cache/CacheProvider.php(60): Doctrine\Common\Cache\CacheProvider->getNamespacedId('Shlinkio\\Shlink...')
#3 /srv/users/lmg-gg/apps/shlink-1-13-1/vendor/doctrine/persistence/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php(177): Doctrine\Common\Cache\CacheProvider->fetch('Shlinkio\\Shlink...')
#4 /srv/users/lmg-gg/apps/shlink-1-13-1/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(283): Doc in /srv/users/lmg-gg/apps/shlink-1-13-1/vendor/doctrine/cache/lib/Doctrine/Common/Cache/ApcuCache.php on line 26

Fatal error: Uncaught Error: Call to undefined function apcu_fetch() in /srv/users/lmg-gg/apps/shlink-1-13-1/vendor/doctrine/cache/lib/Doctrine/Common/Cache/ApcuCache.php:26
Stack trace:
#0 /srv/users/lmg-gg/apps/shlink-1-13-1/vendor/doctrine/cache/lib/Doctrine/Common/Cache/CacheProvider.php(200): Doctrine\Common\Cache\ApcuCache->doFetch('DoctrineNamespa...')
#1 /srv/users/lmg-gg/apps/shlink-1-13-1/vendor/doctrine/cache/lib/Doctrine/Common/Cache/CacheProvider.php(177): Doctrine\Common\Cache\CacheProvider->getNamespaceVersion()
#2 /srv/users/lmg-gg/apps/shlink-1-13-1/vendor/doctrine/cache/lib/Doctrine/Common/Cache/CacheProvider.php(60): Doctrine\Common\Cache\CacheProvider->getNamespacedId('Shlinkio\\Shlink...')
#3 /srv/users/lmg-gg/apps/shlink-1-13-1/vendor/doctrine/persistence/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php(177): Doctrine\Common\Cache\CacheProvider->fetch('Shlinkio\\Shlink...')
#4 /srv/users/lmg-gg/apps/shlink-1-13-1/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(283): Doc in /srv/users/lmg-gg/apps/shlink-1-13-1/vendor/doctrine/cache/lib/Doctrine/Common/Cache/ApcuCache.php on line 26

**Comment by acelaya** [comment]
That's a quite weird error.

My guess is that your server's packages have been updated, introducing some change which is producing this.

Could you please run `php -i | grep apc` and paste the result here?

**Comment by acelaya** [comment]
Also, when is that error produced? Is it when processing visits?

**Comment by tivyhosting** [comment]
```
lmg-gg@sonic:~$ php7.2-sp -i | grep apc
Additional .ini files parsed => /etc/php7.2-sp/conf.d/apcu.ini,
apcu
apc.coredump_unmap => Off => Off
apc.enable_cli => Off => Off
apc.enabled => On => On
apc.entries_hint => 4096 => 4096
apc.gc_ttl => 3600 => 3600
apc.mmap_file_mask => no value => no value
apc.preload_path => no value => no value
apc.serializer => php => php
apc.shm_segments => 1 => 1
apc.shm_size => 32M => 32M
apc.slam_defense => Off => Off
apc.smart => 0 => 0
apc.ttl => 0 => 0
apc.use_request_time => On => On
```

**Comment by tivyhosting** [comment]
Discovered it was a permission error. Now I'm having OOM issues again. Rip.

**Comment by crazymind** [comment]
@tivyhosting Running in to the same problem with apcu_fetch while installing. Could you perhaps clarify what kind of permission error it was?


APC Compatibility | 1.0.3
-- | --
APCu Version | 5.1.16
Build Date | Feb 1 2019 11:56:23


APCu Support | Enabled
-- | --
Version | 5.1.16
APCu Debugging | Disabled
MMAP Support | Enabled
MMAP File Mask | no value
Serialization Support | php
Build Date | Feb 1 2019 11:56:17


Directive | Local Value | Master Value
-- | -- | --
apc.coredump_unmap | Off | Off
apc.enable_cli | Off | Off
apc.enabled | On | On
apc.entries_hint | 4096 | 4096
apc.gc_ttl | 3600 | 3600
apc.mmap_file_mask | no value | no value
apc.preload_path | no value | no value
apc.serializer | php | php
apc.shm_segments | 1 | 1
apc.shm_size | 32M | 32M
apc.slam_defense | Off | Off
apc.smart | 0 | 0
apc.ttl | 0 | 0
apc.use_request_time | On | On



@acelaya is there no way to install without CLI?
