### ISSUE TITLE
Fix Pagination Breaking visits analytics page

### ISSUE THREAD

**Issue by tivyhosting** [shlinkio/shlink#349]
Ever since pagination was implemented into the panel I can no longer open links with large amounts of visits (anywhere from 30-100K visits). 

The page will load for a while and then will eventually freeze the tab, and will require a task manager kill to be able to close chrome. I've also tried letting it sit for an extended period of time. After about 5 minutes it would go back to the main shlink control panel screen where you select a server.

Here is an image of console/network activity when trying to load one of these link analytics.

https://i.imgur.com/rKckDbv.png

**Comment by acelaya** [comment]
I have moved this issue to the shlink-web-client repository https://github.com/shlinkio/shlink-web-client/issues/103

Maybe you want to watch that issue.

**Comment by acelaya** [comment]
(@tivyhosting I'm pinging you because I'm not sure if you are getting the notifications from the other ticket. Sorry for the spam if you are)

https://github.com/shlinkio/shlink-web-client/issues/103#issuecomment-469406355
