### ISSUE TITLE
visits:process memory limitation?

### ISSUE THREAD

**Issue by tivyhosting** [shlinkio/shlink#350]
```
lmg-gg@sonic:~$ apps/shlink-1-13-1/bin/cli visit:process
PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 4096 bytes) in /srv/users/lmg-gg/apps/shlink-1-13-1/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php on line 107

Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 4096 bytes) in /srv/users/lmg-gg/apps/shlink-1-13-1/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php on line 107
```

Regardless of what I set in the php.ini, it still shows as a 256mb memory limitation. The only way I can get it to work is by running the script directly with the php CLI and passing the memory limitation in that command.

` php7.1-sp -d memory_limit=4096M apps/shlink-1-13-1/bin/cli visit:process `

I've changed my cron job to do this as well, but its not the most elegant solution.

**Comment by acelaya** [comment]
This issue is duplicated https://github.com/shlinkio/shlink/issues/307
