### ISSUE TITLE
Is the health endpoint not working for anyone?

### ISSUE THREAD

**Issue by jasoniangreen** [shlinkio/shlink#367]
I have everything working locally, I can create short urls and go through to them and it's all great, but the health endpoint just lands on the 404 page.

<img width="765" alt="screenshot 2019-02-28 at 15 05 41" src="https://user-images.githubusercontent.com/3481367/53576047-c2115a00-3b6a-11e9-86c9-12a9df027806.png">

I also checked the same with postman and I checked with and without passing the api header.

**Comment by jasoniangreen** [comment]
Just FYI I am using the docker version of this, but I don't think that should affect anything. @acelaya

**Comment by jasoniangreen** [comment]
Sorry, I was using the older version.

**Comment by acelaya** [comment]
Oops. I was now going to check this.

I'm gald everything is working as expected :)

**Comment by jeanbez** [comment]
I am getting the same 404 error but I am using the latest version. Any suggestions?

**Comment by acelaya** [comment]
Yep, it should be working https://acel.me/rest/health

How are you calling it? What's the response you get from it? Is it an error from shlink?
