### ISSUE TITLE
Error on short-urls:visits command and associated rest endpoint

### ISSUE THREAD

**Issue by jasoniangreen** [shlinkio/shlink#368]
I recently set this all up using the official docker image and while everything else works, I get an error when I try to use the `visits` rest endpoint. It doesn't give helpful error messages, so I tried running the cli command `short-urls:visits` and it gave me this error.

```
In AbstractPostgreSQLDriver.php line 79:
                                                                               
  An exception occurred while executing 'SELECT COUNT(DISTINCT v0_.id) AS scl  
  r_0 FROM visits v0_ INNER JOIN short_urls s1_ ON v0_.short_url_id = s1_.id   
  WHERE s1_.short_code = ? ORDER BY v0_."date" DESC' with params ["2VIM"]:     
                                                                               
  SQLSTATE[42803]: Grouping error: 7 ERROR:  column "v0_.date" must appear in  
   the GROUP BY clause or be used in an aggregate function                     
  LINE 1: ...rl_id = s1_.id WHERE s1_.short_code = $1 ORDER BY v0_."date"...   
                                                               ^               
                                                                               
In PDOStatement.php line 119:
                                                                               
  SQLSTATE[42803]: Grouping error: 7 ERROR:  column "v0_.date" must appear in  
   the GROUP BY clause or be used in an aggregate function                     
  LINE 1: ...rl_id = s1_.id WHERE s1_.short_code = $1 ORDER BY v0_."date"...   
                                                               ^               
                                                                               
In PDOStatement.php line 117:
                                                                               
  SQLSTATE[42803]: Grouping error: 7 ERROR:  column "v0_.date" must appear in  
   the GROUP BY clause or be used in an aggregate function                     
  LINE 1: ...rl_id = s1_.id WHERE s1_.short_code = $1 ORDER BY v0_."date"...   
                                                               ^               
```

I realise this SQL is generated by the query builder, but it just looks plain broken.... everything else looks fine because the data is in the database, and I can get the count query to work by removing the ORDER BY, like this:
```
SELECT COUNT(DISTINCT v0_.id) AS sclr_0 FROM visits v0_ INNER JOIN short_urls s1_ ON v0_.short_url_id = s1_.id   
WHERE s1_.short_code = '2VIM';
```

**Comment by acelaya** [comment]
I suppose you are using postgres?

I remember seeing a similar error on newer versions of MySQL when configured as strict.

I will investigate which is the query causing this.

**Comment by jasoniangreen** [comment]
Yes, I'm using postgres. Thanks for looking into it.

**Comment by acelaya** [comment]
I have found the problem.

As you have noticed, the project is using an abstraction to handle database connections, which allows for multiple databases to be supported.

There's one place in which a query is dinamically built, and most of the code is shared to build a query to count visits for a short URL and a query to select visits for a short URL.

In the shared part there was an `ORDER BY date` block, which makes no sense in the case of the `SELECT COUNT`.

Apparently MySQL just ignored it, but PostgreSQL complains about it.

The solution is as easy as moving that block just for the `SELECT visits` query, and that's it.

I will release the fix as soon as the build passes.

**Comment by acelaya** [comment]
The docker image wit tag `1.16.2` is already built and available.

**Comment by jasoniangreen** [comment]
Thanks a lot!
