### ISSUE TITLE
Remove shlink copyright from error pages

### ISSUE THREAD

**Issue by jasoniangreen** [shlinkio/shlink#379]
One of my colleagues brought up the fact that having the shlink copyright and link on error pages and the root url essentially gives any would be attackers a direct link to the source code which can only aid them in looking for possible vulnerabilities. It's probably us being overly paranoid, given that we aren't selling this as a service, it's just used to send links to clients, but I was wondering what purpose it serves? 

Obviously it gives you some exposure, which I agree you deserve, but I doubt the average person getting an error page is really who you are aiming to have click through to shlink.io. On the other hand, we as CompanyX suddenly have some strange shlink.io link on our error pages?

Anyway, I am curious to know what you think about removing it?

**Comment by acelaya** [comment]
To be honest, it is something I did a long time ago, when shlink was still a half-built idea.

I didn't really do it with any particular purpose, it just has been there forever.

I'm not going to say that I don't care about exposing the project, but this approach does not probably make a lot of sense in a self hosted service.

Regarding the 404 returned when accessing the project root, it is something I have thought about, but haven't found the right "solution" yet.

While this gets fixed, what shlink does support already is configuring a redirect to a custom URL when an incorrect short code is hit. You might use that to redirect to your company home page or some landing page.

**Comment by jasoniangreen** [comment]
Thanks for reminding me about the custom 404 page, I should have noticed that. And yeah, as for recognition I'm happy to help out in any way I can, even if you just want discuss ideas. You've been very helpful and responsive to issues.

**Comment by acelaya** [comment]
Thanks @jasoniangreen 

It is not easy to build a useful product, and having your feedback is very valuable.

**Comment by jasoniangreen** [comment]
Oh @acelaya there is one issue with the NOT_FOUND_REDIRECT_TO option. It only redirects to that if you have some string after a trailing slash on the url. 
So
`http://localhost:8080` will go to the default 404 page
`http://localhost:8080/` will go to the default 404 page
`http://localhost:8080/blah` will go to the page defined in `NOT_FOUND_REDIRECT_TO`

I think all of those should go to `NOT_FOUND_REDIRECT_TO`.

**Comment by acelaya** [comment]
It is not really an issue, but how it has been designed.

Requests to an shlink instance can result into a 404 for two reasons.

* There's no match to any route when performing the request.
* There's a match to the short code URL (/{shortCode}), but provided short code does not match any existing short URL.

Both of them return a status 404, but the templates have a slightly different message.

When the NOT_FOUND_REDIRECT_TO is defined, it is applied only for the second case.

The first case is something which behavior is still to be defined.

**Comment by jasoniangreen** [comment]
Ah ok, thanks.
