### ISSUE TITLE
Allow to edit Long URL in created shortcodes

### ISSUE THREAD

**Issue by 4n70w4** [shlinkio/shlink#388]
Hi! I need to replace the final links for some shortcodes. For example, the site moved to another domain and I need to change domain in the target link, without changing the shortcodes and links.

**Comment by acelaya** [comment]
This capability could be useful. I will probably include it.

**Comment by NA0341** [comment]
This is, indeed, a very useful and needed feature.
It allows to dynamically redirect links so the shortlink will always be up to date (having static links which always point to the correct destination).

Thank you for implementing this.
For me, it's the number 2 after the ability to redirect.

Can someone point me to the documentation for this feature?
