### ISSUE TITLE
Disable updating GeoLite2 database

### ISSUE THREAD

**Issue by 4n70w4** [shlinkio/shlink#389]
Hi! I run dshlink in docker-container at local network without internet-uplink.

`docker-compose up`

```
Creating shlink ... done
Attaching to shlink
shlink    | Creating fresh database if needed...
shlink    | Updating database...
shlink    | Generating proxies...
shlink    | Updating GeoLite2 database...
shlink exited with code 255
```

**Comment by acelaya** [comment]
This is already fixed from shlink side https://github.com/shlinkio/shlink/issues/376, but it still needs to be fixed in the image entry point.

Ii will be included in next version.
