### ISSUE TITLE
not_found_short_url -> redirect_to and 404 Page not found

### ISSUE THREAD

**Issue by 4n70w4** [shlinkio/shlink#391]
Hi! I want to redirect from **/** page to **not_found_short_url -> redirect_to** instead 404 Page not found. The page you requested could not be found.

![image](https://user-images.githubusercontent.com/38257723/55627918-028e7400-57b8-11e9-8487-bb62f7bde9fc.png)

**Comment by acelaya** [comment]
This is a known use case already discussed in the past.

This page is shown when no route is matched, while the config you mention is only used when the "short code" route is matched but provided short code does not exist.

It is already to be decided what should be done with the "/" path.

**Comment by 4n70w4** [comment]
I did not understand, so how to solve the question? Why is issue closed?

I need to redirect to **not_found_short_url -> redirect_to** instead of any 404

**Comment by acelaya** [comment]
Long story short, this is the expected behavior for now. No way to change it via configuration.

**Comment by 4n70w4** [comment]
I as a user expect a completely different behavior.
I as a user need the ability to redirect from `/` url.

I use only API for management.
Web part only for redirects.
