### ISSUE TITLE
User-fiendly formatting for punycode domains and special chars in query

### ISSUE THREAD

**Issue by 4n70w4** [shlinkio/shlink#393]
Hi! Urls like `https://xn--c1aea8akcddj.xn--p1ai/2019/04/5905239098-%D0%BD%D0%BF-%D1%84%D1%86-%D0%BA%D0%BE%D0%BB%D0%B8%D0%B7%D0%B5%D0%B9/`
not userfriend and uninformatively.

This format informative and understandable to users.
`https://госреестр.рф/2019/04/5905239098-нп-фц-колизей/`

**Comment by acelaya** [comment]
Is this a question, or are you trying to report something? I can't really tell.

**Comment by 4n70w4** [comment]
This is problem. Similar links are not readable:
![image](https://user-images.githubusercontent.com/38257723/55858420-5b735900-5b78-11e9-8ed6-f748762f38a0.png)

**Comment by 4n70w4** [comment]
![image](https://user-images.githubusercontent.com/38257723/55858536-9bd2d700-5b78-11e9-9b40-8f9adcc09c35.png)

**Comment by acelaya** [comment]
Oh, I see.

Do you have an example I could use to do some tests?

I need to see if the issue is in the API or the web client.
