### ISSUE TITLE
Bug: All shortcodes - Oops! We encountered a 500 Internal Server Error error.

### ISSUE THREAD

**Issue by 4n70w4** [shlinkio/shlink#396]
I spent 2 hours searching and describing playback.

Steps to reproduce:

1) start new clean instances

2) docker exec -it shlink shlink api-key:generate

3) create shortcode via api: `{"longUrl": "https://google.com/"}` - ok resonse

4) test shortcode - redirect sucessful

5) create shortcode via api: `{"longUrl": "https://google.com/", "customSlug": "/"}` - ok resonse

6) create shortcode via api: `{"longUrl": "https://google.com/", "customSlug": "/"}` - `{"error":"INVALID_SLUG","message":"Provided slug  is already in use. Try with a different one."}`

7) test shortcode from step 3 - redirect sucessful

8) again create shortcode via api: `{"longUrl": "https://google.com/"}`  - `{"error":"UNKNOWN_ERROR","message":"Unexpected error occurred"}`

9) test shortcode from step 3 - `Oops! We encountered a 500 Internal Server Error error.`

```
shlink          | [2019-04-10 08:38:31] Swoole.NOTICE: Swoole is running at 0.0.0.0:8080, in /etc/shlink {"host":"0.0.0.0","port":8080,"cwd":"/etc/shlink"} []
shlink          | [2019-04-10 08:38:31] Swoole.NOTICE: Worker started in /etc/shlink with ID 0 {"cwd":"/etc/shlink","pid":0} []
shlink          | [2019-04-10 08:38:43] Swoole.INFO: 172.25.0.3 - - [10/Apr/2019:08:38:43 +0000] "POST /rest/v1/short-urls HTTP/1.1" 200 193 [] []
shlink          | [2019-04-10 08:38:46] Swoole.INFO: 172.25.0.3 - - [10/Apr/2019:08:38:46 +0000] "POST /rest/v1/short-urls HTTP/1.1" 200 184 [] []
shlink          | [2019-04-10 08:38:53] Swoole.INFO: 172.25.0.3 - - [10/Apr/2019:08:38:53 +0000] "GET /NTQH HTTP/1.1" 302 - [] []
shlink          | [2019-04-10 08:38:58] Swoole.ERROR: 172.25.0.3 - - [10/Apr/2019:08:38:58 +0000] "POST /rest/v1/short-urls HTTP/1.1" 400 96 [] []
shlink          | [2019-04-10 08:39:02] Swoole.INFO: 172.25.0.3 - - [10/Apr/2019:08:39:02 +0000] "GET /NTQH HTTP/1.1" 302 - [] []
shlink          | [2019-04-10 08:39:06] Swoole.ERROR: 172.25.0.3 - - [10/Apr/2019:08:39:06 +0000] "POST /rest/v1/short-urls HTTP/1.1" 500 63 [] []
shlink          | [2019-04-10 08:39:13] Swoole.ERROR: 172.25.0.3 - - [10/Apr/2019:08:39:13 +0000] "GET /NTQH HTTP/1.1" 500 1107 [] []
```

After restart docker containers - redirects work again. But after create new shortcode repeated 8 and next steps.

```
shlink          | [2019-04-10 08:40:10] Swoole.NOTICE: Swoole is running at 0.0.0.0:8080, in /etc/shlink {"host":"0.0.0.0","port":8080,"cwd":"/etc/shlink"} []
shlink          | [2019-04-10 08:40:10] Swoole.NOTICE: Worker started in /etc/shlink with ID 0 {"cwd":"/etc/shlink","pid":0} []
shlink          | [2019-04-10 08:40:17] Swoole.INFO: 172.25.0.3 - - [10/Apr/2019:08:40:17 +0000] "GET /NTQH HTTP/1.1" 302 - [] []
shlink          | [2019-04-10 08:40:22] Swoole.ERROR: 172.25.0.3 - - [10/Apr/2019:08:40:22 +0000] "POST /rest/v1/short-urls HTTP/1.1" 500 63 [] []
shlink          | [2019-04-10 08:40:26] Swoole.ERROR: 172.25.0.3 - - [10/Apr/2019:08:40:26 +0000] "GET /NTQH HTTP/1.1" 500 1107 [] []
```

**Comment by acelaya** [comment]
Haha, that's a nice hack to workaround something which is not supported.

Obviously, that's not supposed to work that way, so I cannot provide a fix.

**Comment by 4n70w4** [comment]
@acelaya You will have to figure it out and fix it. At least you need:
1) understand why the entire system breaks down after adding such a link and fix it
2) add to the validation rules the prohibition of creating links with such customSlug

Any attacker can make your system inoperable by adding a non-valid link.

Why do you disrespect your users?
What is the trend for aggressively closing issues without problem solving?

**Comment by arhimede** [comment]
@4n70w4 
This is an open source project.
 There are no "users" , and you are paying nothing for using this script. 

If you are not happy with it, you are free to use something else OR to fix the problem yourself. 
You can submit a patch at any time.

**Comment by acelaya** [comment]
Thanks @arhimede, I have nothing else to add 🙂
