### ISSUE TITLE
Edit not found page and landing page

### ISSUE THREAD

**Issue by captainAldi** [shlinkio/shlink#397]
is that possible to custom the 404 not found page ?
and the landing page  ? (not the webClient page)

ex: 

i want to redirect 404 not found to another link
and for the landing page (doma.in) is automatically redirect to 404 not found right ? how to change this also to another link ?

or where i can edit the page .html of this ? 

thanks before

**Comment by acelaya** [comment]
It is something I'm planning to add, but it is not possible for the moment.
