### ISSUE TITLE
Add support for other url schemas

### ISSUE THREAD

**Issue by ahmadalli** [shlinkio/shlink#409]
When I try to create a short url for a url with other schemas, (e.g. `ftp://`) I'm getting 500 error and `Zend\Diactoros\Exception\InvalidArgumentException: Unsupported scheme` on log files

**Comment by acelaya** [comment]
I'm afraid that's not possible.

Shlink (as well as any other URL shortener) is based on HTTP redirects, so it cannot handle URIs from other schemas.
