### ISSUE TITLE
Prevent checking of the long url with an app setting or API option

### ISSUE THREAD

**Issue by lenba** [shlinkio/shlink#413]
I have a use case where long urls should not be accessed until the link is clicked by the customer. When shlink checks the long url for validity, the long url resource is accessed and my use case is triggered by shlink check instead of the customer.

Can a global app setting or per url API option added to prevent shlink from checking the long url and directly redirect to it regardless of validity?

**Comment by acelaya** [comment]
Shlink sorts that already.

You probably left the default value during installation. In order to disable URL validations, follow the steps explained here https://github.com/shlinkio/shlink/issues/394#issuecomment-481341874
