### ISSUE TITLE
Base url not redirecting

### ISSUE THREAD

**Issue by lenba** [shlinkio/shlink#414]
I'm trying to redirect base url of the shortener (without shortlink portion) as well as non existent shortlinks to another site/page.

I initially had this in config:
`
         'not_found_short_url' => array(
            'enable_redirection' => false,
        ),
`
Which I later changed to:
` 
       'not_found_short_url' => array(
            'enable_redirection' => true,
            'redirect_to' => 'https://www.google.com',
        ),
`

After deleting data/config/app_config.php, the invalid shortlinks are redirecting, but not the base url. For example sho.rt/Invalid redirects, but sho.rt does not. What setting do I need for this?

**Comment by acelaya** [comment]
Hey @lenba 

I'm afraid redirecting the base domain is still not supported. I'm still deciding what would be the best behavior, but for now, I would recommend handling that from the web server in front of shlink.
