### ISSUE TITLE
Add endpoint to create several short URLs in one API call

### ISSUE THREAD

**Issue by kip-13** [shlinkio/shlink#422]
I know the specifications about RestAPI design, a specific endpoint to create a resource like `rest/v1/short-urls` but could be amazing have another endpoint to create various short urls at a time, maybe `rest/v{x}/short-urls/bulk`, `rest/v{x}/short-urls/batch` or maybe a more elegant way like [this](https://developer.mailchimp.com/documentation/mailchimp/guides/how-to-use-batch-operations/).

**Comment by acelaya** [comment]
Yep. An endpoint to create several short URLs in just one call sounds useful.

I'll add it to the roadmap.

**Comment by acelaya** [comment]
The amount of issues has been growing in the latest months, and I'm closing old issues that didn't bring enough attention.

This feature's benefit is limited compared to the time needed to implement it, so I'm afraid I have to close it.

**Comment by roo-oliv** [comment]
I'd like to contribute to implementing this feature request. We're using shlink in production, the service is great, but it would be really nice to have a batch creation endpoint since we're hammering the service with multiple concurrent requests currently.

**Comment by roo-oliv** [comment]
@acelaya I've implemented a /short-urls/batch endpoint. You can take a look at the changes [here](https://github.com/shlinkio/shlink/compare/develop...roo-oliv:shlink:develop?expand=1), and I can open a pull request if it's acceptable and in line with shlink's standards.

I've written unit tests and performed some local tests, and it works as expected (tested with a batch of 1000 URLs, taking 4s without title resolution and 1m30s with title resolution).
