### ISSUE TITLE
Error creating shortened url for .. subdomains?

### ISSUE THREAD

**Issue by LordMike** [shlinkio/shlink#426]
I've tried creating shortened urls for a rather long link for Onedrive, but it keeps failing for me. I've narrowed it down to this:

* This works: `https://sharepoint.com/`
* This fails: `https://m.sharepoint.com/`

It seems that any subdomain I add, will stop the url shortening from working.

Thanks in advance, nifty little project :)

**Comment by acelaya** [comment]
What's exactly the error you get?

**Comment by LordMike** [comment]
I've had a chance to look at this now. It's really weird. I'm told it's an invalid URL.

![image](https://user-images.githubusercontent.com/1027111/62320609-e28a6b00-b4a0-11e9-95a3-8850c4754d57.png)

It's pretty consistent that "m.google.com" is ok, while "m.sharepoint.com" is not.

**Comment by LordMike** [comment]
Looking at the PHP code, it seems Shlink.io tries to resolve the final destination of the provided URL ?

https://github.com/shlinkio/shlink/blob/20c3bde0368d4f04194c04e15517729e36e4b5d1/module/Core/src/Service/UrlShortener.php#L150-L159

**Comment by acelaya** [comment]
Yes, Shlink verifies the end user will end up in a public URL once a short URL is created, if validation is enabled (which is the default).

I guess the returned error could be improved with more information, not only at API level but also in the web client.

If you want, feel free to contribute :)
