### ISSUE TITLE
Deprecate the preview generation

### ISSUE THREAD

**Issue by acelaya** [shlinkio/shlink#428]
Generating web previews is not a very useful feature, and yet it has a high maintenance cost.

Document the fact that it is deprecated, and mark it as deprecated in code.

To be removed in v2.

**Comment by ypereirareis** [comment]
Hi, thanks for this usefull project !

I want to generate a lot of redirection matching, but the preview feature is performance killer.

Is there a way to disable preview generation before the version 2 release or not at all, maybe already developed in master branch? Do you have a v2 release date ?

Thx again.

**Comment by acelaya** [comment]
Where did you exactly find performance issues?

The preview feature shouldn't affect any other workflow at all. Previews are generates only if you run the command manually (or programmatically), or if someone hits the short URL with the /preview suffix.

If you avoid both of them, you should be ok.
