### ISSUE TITLE
[Feature Request]API keys that can only be used to generate short link but not managing them

### ISSUE THREAD

**Issue by Plausible0Bug** [shlinkio/shlink#473]
We currently work with a workflow model that will need link shortener API key to be exposed on the client side and called via CORS requests, I wonder if it would be possible to make API keys that can only be used to generate short link but not manage them.

If we utilize the jwt claims it would be great:
https://auth0.com/docs/tokens/jwt-claims

**Comment by Plausible0Bug** [comment]
Relate to: https://github.com/shlinkio/shlink/issues/147

**Comment by acelaya** [comment]
Sure!

I closed that issue because I thought it wouldn't be that useful, but I'll reopen it and start with this.

But it will not work with anything related with JWT. Authentication with JWT is deprecated and will be removed in a future major release.

Permissions will be implicit to the API key and you will be able to manage them from the command line only.

**Comment by acelaya** [comment]
Sorry, I thought you referenced #150, so I was talking about that and not #147 😅

**Comment by kappelmann** [comment]
I am facing the same issue - would very much appreciate such a feature.

**Comment by acelaya** [comment]
Blocked until #882 is implemented. This feature will be implemented on top of that.

**Comment by calvinbui** [comment]
@acelaya no plans to add this feature anymore?

**Comment by calvinbui** [comment]
For anything that needs this feature, I've moved to [Polr](https://github.com/cydrobolt/polr) using this [docker image by ajanvier](https://github.com/ajanvier/docker-polr).  The API has the ability to lookup paths if you know the path, but there's no ability to list all links. I just disabled that part of the API by redirecting `^/api/v2/action/lookup(.*)` to `/`.
