### ISSUE TITLE
Add title field for short url entries

### ISSUE THREAD

**Issue by SirFlip** [shlinkio/shlink#478]
I think it would be usefull to have a title field for the short url entries.

For now I use the Tags field. But it's not really the gist of having unique tags for every url ;).

**Comment by acelaya** [comment]
I guess it's something that can be consideres :)

Thanks for the request.

**Comment by acelaya** [comment]
Closing, add o don't see a very big need for this.

**Comment by acelaya** [comment]
Hey @SirFlip, this is finally going to happen. You may want to subscribe to https://github.com/shlinkio/shlink/issues/941

**Comment by SirFlip** [comment]
Thanks for the hint. I somehow missed the closing anyway. ;)
