### ISSUE TITLE
How is this project self-hosted? 

### ISSUE THREAD

**Issue by motionland** [shlinkio/shlink#480]
Hello, 

How is this project self-hosted when the only way to interact with it is via your website: https://app.shlink.io/ ?

Could you explain ?

Thanks

**Comment by poblabs** [comment]
[Install the web client](https://github.com/shlinkio/shlink-web-client)

**Comment by acelaya** [comment]
Exactly.

As @poblabs says, you can also self-host the web client if you want.

I provide an instance under app.shlink.io as a convenience, to simplify starting to work with shlink.
