### ISSUE TITLE
installation  issue 

### ISSUE THREAD

**Issue by drkamine** [shlinkio/shlink#487]
Hello , i try to install it in ubuntu but  i get a lot of issue can any one please send me the step by step installation

**Comment by acelaya** [comment]
You can follow these steps https://shlink.io/documentation/install-dist-file/

**Comment by drkamine** [comment]
I follow the stepby i can't access to my url

**Comment by acelaya** [comment]
Could you provide more information? Are you getting some error? What do the logs say (you can find them in data/log)?

**Comment by drkamine** [comment]
the log fodler is empty . but wheen  i see the apache2 log  i have this  in error.log 

[Mon Sep 16 15:52:38.438963 2019] [php7:warn] [pid 1349] [client 10.188.16.156:1                                                                                                                     823] PHP Warning:  require(vendor/autoload.php): failed to open stream: No such                                                                                                                      file or directory in /var/www/shlink/config/container.php on line 9
[Mon Sep 16 15:52:38.439048 2019] [php7:error] [pid 1349] [client 10.188.16.156:                                                                                                                     1823] PHP Fatal error:  require(): Failed opening required 'vendor/autoload.php'                                                                                                                      (include_path='.:/usr/share/php') in /var/www/shlink/config/container.php on li

**Comment by acelaya** [comment]
Could you share your Apache config?

**Comment by drkamine** [comment]
Hello , here the apache configuration for virtual host 
<VirtualHost *:80>
    ServerName mysite.lan
    DocumentRoot "/var/www/shlink/public"

    <Directory "/var/www/shlink/public">
        Options FollowSymLinks Includes ExecCGI
        AllowOverride all
        Order allow,deny
        Allow from all
    </Directory>
</VirtualHos

**Comment by acelaya** [comment]
Everything looks fine.

The only thing that could happen is that [this](https://github.com/shlinkio/shlink/blob/master/config/container.php#L7) instruction that is run his before requiring the autoloader, is not working add expected for some reason.

Do you have any kind of restriction in place that could be making PHP apps not to be able to change to a dir out of the document root?

**Comment by acelaya** [comment]
I'm thinking on something else. How did you install shlink? What's the zip file you downloaded?

Only dist files include the project dependencies (and the autoloader). Could it be that you downloaded the sources instead? Does the zip file include the word "dist"?

**Comment by acelaya** [comment]
I'm closing this for now. Let me know if there's other way I can help.
