### ISSUE TITLE
Feature Request: Geni.us Like Amazon Affiliate Integration

### ISSUE THREAD

**Issue by tivyhosting** [shlinkio/shlink#493]
https://geni.us has full localized Amazon affiliate integration, meaning any Amazon links you create with geni.us will automatically insert your appropriate affiliate code, and will send anyone who clicks the link to the localized version of Amazon according to their country of origin.

This would be an awesome feature to implement into Shlink!

**Comment by acelaya** [comment]
I've been taking a look at this website, and I'm not completely sure that I'm understanding what they do.

Could you elaborate exactly what would you like shlink to do?

**Comment by acelaya** [comment]
Hey @tivyhosting, could you please elaborate a bit on what do you expect to be implemented?

**Comment by acelaya** [comment]
I'm afraid I have to close this, because I really don't know what's expected.

Feel free to add more comments and information and I will gladly reopen this issue.
