### ISSUE TITLE
How to skip URL validation?

### ISSUE THREAD

**Issue by jonmjoyce** [shlinkio/shlink#495]
#### How Shlink is set-up

* Shlink Version: 1.18.1
* PHP Version: 7.3.8
* How do you serve Shlink: Docker image
* Database engine used: default

#### Summary

I am using shlink to shorten URLs that are behind a firewall, so I'd like to disable URL validation. I saw the instructions in issue #394 but there is no longer a generated_config.php. I modified url-shortener.global.php to set 'validate_url' to false but that did not seem to do anything. Do I need to reload the service somehow? Stopping and starting the container didn't do anything either.

Thanks!

**Comment by acelaya** [comment]
When using the docker image, disabling the URL validation is just a matter of passing the VALIDATE_URLS env bar with value false.

Let me know if that helped.

**Comment by jonmjoyce** [comment]
Thanks, I missed that in the documentation earlier, but it's working now.

**Comment by acelaya** [comment]
Great to hear that :)
