### ISSUE TITLE
Consider to be included in https://github.com/Kickball/awesome-selfhosted/blob/master/README.md?

### ISSUE THREAD

**Issue by Haocen** [shlinkio/shlink#499]
It seemed that catalog is ranked high when searching for "self-hosted".

I don't see a problem with the license of this project at the meantime.

**Comment by acelaya** [comment]
I didn't know about this project, bit it would be a good idea. I'll investigate.

Thanks!

**Comment by acelaya** [comment]
Done! https://github.com/Kickball/awesome-selfhosted/pull/1823

Let's hope it gets merged. Thanks for letting me know about this project :)
