### ISSUE TITLE
Short URL - pass parameters

### ISSUE THREAD

**Issue by ssrini** [shlinkio/shlink#511]
Quick question before setup. If parameters are passed to the short URL will the be appended and sent to the redirected URL?

**Comment by acelaya** [comment]
Hello @ssrini.

No, that's something shlink dies not do right now. Do to know any interesting use case for that?

**Comment by ssrini** [comment]
If the redirection is to an app for eg and the tenant needs to be
determined that would be useful. For eg to redirect to tenant.shlink.io a
potential short url could be go.to/shlink?tenant with the destination
taking care to route to the correct tenant. Multiple shirt urls for each
tenant need not be created then. rebrandly etc support it already.

**Comment by acelaya** [comment]
Yep, I guess it can be useful, and should not be hard to implement. I will plan this to be done :)

Do you know which one of these behaviors is rebrandly following?

* Always forwards query parameters from short URL to redirected one.
* Forwards parameters by default but, can be disabled individually on every short URL.
* Does not forward parameters by default, but can be enabled individually on every short URL.

**Comment by ssrini** [comment]
The parameters are forwarded by default AFAIK.  What would be useful would be to perform some form of parameter substitution if possible.
1.  By default parameters can be forwarded.
2. Additional feature could be some form of parameter substitution like nginx.  For e.g. the redirected URL can refer to these parameters and substitute them in which case it would not be a default forward but substitution.  For e.g lets say the short URL go.to/lnk is configured as forward to https://$t.shlink.io?$u then:
   -  go.to/lnk?t=github&u=acelaya  ==> github.shlink.io?u=acelaya
   -  go.to/lnk?t=github  ==> github.shlink.io
   -  go.to/lnk ==> shlink.io
   -  go.to/lnk?r=reset ==> shlink.io?r=reset

Your call :)

**Comment by acelaya** [comment]
I will probably start with the simplest approach, which is forwarding params, and after that, I will consider improving the feature if it seems useful.

**Comment by ssrini** [comment]
Another very important use of this will be in tracking Google Analytics campaigns etc.  Once a campaign is created the parameters utm_source, utm_medium, utm_campaign and utm_term can all be passed in the redirection so that analytics can be updated.

**Comment by acelaya** [comment]
That's a really good point :)

**Comment by acelaya** [comment]
hey @ssrini 

Yesterday I merged a fix to make query params to be propagated to the URL before redirecting users.

The fix will be part of the upcoming v1.20.1

**Comment by ssrini** [comment]
Thanks.  Will check it out once released

**Comment by acelaya** [comment]
It was released yesterday, so you can already check.
