### ISSUE TITLE
App not recognizing server

### ISSUE THREAD

**Issue by bnornholm** [shlinkio/shlink#564]
#### How Shlink is set-up

* Shlink Version: stable
* PHP Version: 7.3
* How do you serve Shlink: Docker image
* Database engine used: SQLite

#### Summary

After running the image and generating the API key, app.shlink.io won't recognize my server.  After putting the address of the server its running on (like https://127.0.0.1:8080), I am unable to generate a url short name, getting an error of `An error occurred while creating the URL :(`

**Comment by bnornholm** [comment]
After setup the docker container of shlink-web-client and going through the json file setup, the app still won't create a short url.

**Comment by acelaya** [comment]
Could you check the container logs? They should contain some info about what's failing.

**Comment by bnornholm** [comment]
No errors in the logs for both containers.

**Comment by acelaya** [comment]
Is the shlink container at least logging the http requests?

If not, then it looks your browser is not capable of reaching your shlink insurance.

**Comment by acelaya** [comment]
I'm closing this for now due to the lack of activity.

Let me know if there's any other way I can help.
