### ISSUE TITLE
Server config for multi-domain

### ISSUE THREAD

**Issue by mretich** [shlinkio/shlink#569]
* Shlink Version: 1.20.2
* PHP Version: 7.3.11
* How do you serve Shlink: Docker image
* Database engine used: MySQL (5.7.25)

Hello,

I couldn't find any documentation on how to set up a multi-domain config.
Is there a example for this somewhere?

Regards,
Michael Retich

**Comment by acelaya** [comment]
Yep, that's on me.

It was a feature developed more or less in a hurry, and I didn't prepare some proper documentation.

Basically, you make sure requests performed to all domains you want to support, are redirected to your shlink instance.

Then, when creating short URLs, you can provide any of those domains (or none, which will fall back to the default one), and the link will be "attached" to that domain.

**Comment by mretich** [comment]
Thanks, that helped me a lot.
