### ISSUE TITLE
Setting a valid 'validUntil' ISO date string on a request to POST ​/rest​/v1​/short-urls always fails

### ISSUE THREAD

**Issue by Ross65536** [shlinkio/shlink#573]
#### How Shlink is set-up

* Shlink Version: 1.20.2
* PHP Version: 7.2.25
* How do you serve Shlink: Docker image
* Database engine used: SQLite

#### Summary

When making a POST request to `​/rest​/v1​/short-urls` setting a string for example  `"2020-12-12T08:40:04.123Z"` (this is just the string from the docs example + 1 year) as the `validUntil` json field will make the request fail with 400.

#### Current behavior
400 error

#### Expected behavior

200

#### How to reproduce

Make a request with the example string.

**Comment by acelaya** [comment]
The format you need to use is something like this `2019-12-13T00:00:00+01:00`, which is [ISO-8601](https://en.wikipedia.org/wiki/ISO_8601)

**Comment by Sd-OmerFarooq** [comment]
Hi there, I tried postman for checking with 'validUntil'   by using my domain endpoint url...with a valid ISO 8601 format posted this      {
  "longUrl": "https://medium.com/blog/newsletter",
  "tags": [
    "receiver-966580705163\t\t"
  ],
  "meta": {
    "validUntil": "2024-09-03T00:00:00+03:00"
  }
}                                       

.................................... got response as {
    "shortUrl": "https://s/Vuv8K",
    "shortCode": "Vuv8K",
    "longUrl": "https://medium.com/blog/newsletter",
    "dateCreated": "2024-09-02T06:37:53+00:00",
    "tags": [
        "receiver-966123456783"
    ],
    "meta": {
        "validSince": null,
        "validUntil": null,
        "maxVisits": null
    },
    "domain": null,
    "title": "Sign Up for Newsletter - The Medium Newsletter - Medium",
    "crawlable": false,
    "forwardQuery": true,
    "visitsSummary": {
        "total": 0,
        "nonBots": 0,
        "bots": 0
    }
}   ...kindly suggest.. Thank you

**Comment by acelaya** [comment]
Check the right body here https://api-spec.shlink.io/#/Short%20URLs/createShortUrl

**Comment by Sd-OmerFarooq** [comment]
use the structure as suggested but still    

{
  "longUrl": "web.whatsapp.com",
  "tags": [
    "receiver-966580705163\t\t"
  ],
  "meta": {
    "validSince": "2024-09-02T00:00:00+03:00",
    "validUntil": "2024-09-03T00:00:00+03:00",
    "maxVisits": 0,
    "tags": [
    "string"
  ],
  "title": "string",
  "crawlable": true,
  "forwardQuery": true,
  "customSlug": "string",
  "pathPrefix": "string",
  "findIfExists": true,
  "domain": "string",
  "shortCodeLength": 0
}
}  ...still the same issue...persists

**Comment by Sd-OmerFarooq** [comment]
Thanks for your support as need to modify the body by removing "meta"
