### ISSUE TITLE
Url Validation bug

### ISSUE THREAD

**Issue by GammaPi** [shlinkio/shlink#582]
docker exec -it shlink_shlink_1 shlink short-url:generate "https://www.ip138.com"

docker exec -it shlink_shlink_1 shlink short-url:generate "https://www.ip.com:2342"

Both throw **[ERROR] Provided URL https://www.ip.com:2342 is invalid. Try with a different one.** 

Could I turn this validation off? 
In my opinion, shlink can trust the user to check url format. Shlink just need to replace certain characters to prevent XSS.

**Comment by GammaPi** [comment]
#281 related...
I'll temporarily turn validation off from config file~

**Comment by acelaya** [comment]
Yes, URL validation should be disabled by default. It's enabled for historical reasons, but it will change on v2.

Regarding your issue, are those the actual URLs you have tried, or are those examples?

**Comment by GammaPi** [comment]
Both. You may use these urls to debug when url validation is on.

**Comment by acelaya** [comment]
If those are the URLs you have tried, then the error is expected.

If you plan to shorten private URLs that shlink will not be able to reach, then the solution is disabling URL validation, as you already did :)
