### ISSUE TITLE
How to setup shlink for local development

### ISSUE THREAD

**Issue by Ross65536** [shlinkio/shlink#598]
#### How Shlink is set-up

* Shlink Version: 1.20.3
* PHP Version: 7.3.13
* How do you serve Shlink: Self-hosted php development server
* Database engine used: MariaDB (inside docker)

#### Summary

I'm running maria with `docker-compose up shlink_db_maria` using the docker-compose.yml from this repository.
 
I'm trying to run shlink using `php -S 0.0.0.0:8080 -t public public/index.php` but when I open `http://localhost:8080/` I get a 500 (I'm expecting a 404) error with this log:

```
[2019-12-30 15:55:19] Shlink.ERROR - Error occurred while dispatching request:
Doctrine\DBAL\DBALException: The options 'driver' or 'driverClass' are mandatory if no PDO instance is given to DriverManager::getConnection(). in /home/ros/Code/Work/Sources/shlink/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:116
Stack trace:
#0 /home/ros/Code/Work/Sources/shlink/vendor/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(225): Doctrine\DBAL\DBALException::driverRequired()
#1 /home/ros/Code/Work/Sources/shlink/vendor/doctrine/dbal/lib/Doctrine
/DBAL/DriverManager.php(183): Doctrine\DBAL\DriverManager::_checkParams(Array)
.......
```

I also get the same error if I run `php bin/cli db:create -n -q`:

``` 

In ServiceManager.php line 771:
                                                         
  Service with name "Doctrine\ORM\EntityManager" could   
  not be created. Reason: The options 'driver' or 'driv  
  erClass' are mandatory if no PDO instance is given to  
   DriverManager::getConnection().  

In DBALException.php line 116:
                                                         
  The options 'driver' or 'driverClass' are mandatory i  
  f no PDO instance is given to DriverManager::getConne  
  ction().
```

I have this `.env` file:
```
# Application
APP_ENV=development
SECRET_KEY=2f658169-925a-4261-bd76-93df1640584b
SHORTENED_URL_SCHEMA=http
SHORTENED_URL_HOSTNAME=localhost:8080

# Database
DB_USER=root
DB_PASSWORD=root
DB_NAME=shlink
```

and I have also tried to modify the  `config/autoload/entity-manager.local.php.dist` file to:
```php
<?php
return [

    'entity_manager' => [
        'connection' => [
            'driver' => 'pdo_mysql',
            'host' => 'localhost:3308',
            'driverOptions' => [
                PDO::MYSQL_ATTR_INIT_COMMAND => 'SET NAMES utf8',
            ],
        ],
    ],

];
``` 

I'm getting this error no matter what I try, I've also tried to run with the command `docker-compose up shlink_swoole` but I get a `The command "start" does not exist.` error relating to the swoole binary.

**Comment by acelaya** [comment]
Hey @Ross65536.

Sorry for the inconvenience. Improving the docs on how to contribute and work on the project is something planned, but I'm not there yet.

The only thing probably missing in your set-up is copying all the *.dist files from the `config/autoload` folder and removing the `dist` extension.

So, for example, `config/autoload/entity-manager.local.php.dist` would become `config/autoload/entity-manager.local.php`.

Depending on how old is your fork, you might also need to define some env vars, but I recently removed the need to have a `.env` file.

After that, just running `docker-compose up` should get you up and running, and shlink available in `localhost:8000` through nginx+php-fpm or `localhost:8080` through swoole.

**Comment by Ross65536** [comment]
I have done all of these inside the `shlink_swoole` container. 

I have tried what you mentioned but I still get the same error. From what I've debugged the error is that the config is not used by doctrine, which is strange because the config inside the deployment Dockerfile works fine. I have even edited the file `config/autoload/entity-manager.global.php` and tried copying `docker/config/shlink_in_docker.local.php` to `config/autoload` and none of the changes in the config variables are propagated to doctrine.


For now i'm using this workaround to get it to work: `sudo ex -s -c "870i|        \$connection = ['driver' => 'pdo_sqlite','path' => 'data/database.sqlite',];" -c x vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php`

**Comment by acelaya** [comment]
If I had to guess, I would say that, the first time you run the project without the local config files, shlink thought it was running on a production environment.

That makes shlink cache de merged config and ignore any change in any further requests.

Check if you have a file in `data\cache\app_config.php`.

If that's the case, delete it. After that, restart the containers (making sure you have the local config files without the `dist` extension), and everything should work.

**Comment by Ross65536** [comment]
Yep, that was it. It works now.

**Comment by acelaya** [comment]
Cool. I'm happy we solved the issue :)

This is something I definitely want to document, because it's impossible to know otherwise.
