### ISSUE TITLE
Is it possible to re-run the installer and generate a totally new config?

### ISSUE THREAD

**Issue by kuerious** [shlinkio/shlink#601]
#### How Shlink is set-up

* Shlink Version: **1.21.1**
* PHP Version: **7.2**
* How do you serve Shlink: **Self-hosted Apache**
* Database engine used: **MariaDB**

How do you use shlink-web-client: **app.shlink.io**

#### Summary
Is it possible to simply re-run `sudo -u www-data php /var/www/shlink/bin/install` a second time and re-generate the configuration, or do I need to delete the database and start over?

**Comment by acelaya** [comment]
The short answer is yes.

It is perfectly possible to run the command again, and it will overwrite the old generated config with the new information you provide.

However, it will not delete your data (it would be dangerous), which means you need to create a new empty database first and make sure to provide the new name during the new install tool execution.

After that, you can do what you want with the old database, and shlink will work with the new confiruation.

**Comment by kuerious** [comment]
Thanks. That makes sense.
