### ISSUE TITLE
Expanded URL is incorrect

### ISSUE THREAD

**Issue by calvinbui** [shlinkio/shlink#615]
#### How Shlink is set-up

* Shlink Version: docker stable tag, 2.0.1
* PHP Version: docker stable tag, 7.4.1
* How do you serve Shlink: Docker image
* Database engine used: MariaDB Docker image

#### Summary

Shorten a link such as `https://google.com/?abc#123` and it will return `https://google.com/#123` when accessing the short url.

I have found the same with any URL where it's `https://<domain>?<data>#<data>`

#### Current behavior

Drops anything between `?` and `#`

#### Expected behavior

Return the URL as expected without changing the URL

#### How to reproduce

Shorten a link such as `https://google.com/?abc#123` and it will return `https://google.com/#123` when accessing the short url.

Can be checked via 
- cURL
- 302 location in headers

web-client shows correct URL.

**Comment by acelaya** [comment]
Interesting.

I will check what's going on there.

Thanks for reporting.

**Comment by acelaya** [comment]
I have been investigating a bit and found the issue.

It is not related with the fact that the URL has a fragment or not (`#123`), but with the fact that it has a query argument with no value (`?abc`).

Shlink does some internal parsing, which is making query args with no value to be lost.

I can enforce args with no value to have an "empty string" value, but that would result on URLs like this `https://google.com/?abc=#123`, which is also not the one you originally provided.

I need to investigate a bit to see what is the standard approach for this.

**Comment by acelaya** [comment]
I have found the way to keep the query params with no value, however, I have done a few tests and I have realized that, even if the response contains the header `Location: https://google.com/?abc#123`, browsers still redirect you to `https://google.com/?abc=#123`, with the `=` character.

So I'm going to release it that way. Shlink will respect the URL as it was provided, and HTTP clients will act as they want :sweat_smile:

**Comment by calvinbui** [comment]
To be specific, i found this issue when shortening URLs made with privatebin: https://privatebin.net/

e.g. https://privatebin.net/?ddefb39f381ea2d4#3jrdyg59Vh3xiLgHWY7LWXdqWSJmPWcC7KzsgNS7P7YZ

**Comment by acelaya** [comment]
With the fix I have just done, the redirection works fine:

![image](https://user-images.githubusercontent.com/2719332/72216719-57200600-3525-11ea-9f65-1d70d5777909.png)

![image](https://user-images.githubusercontent.com/2719332/72216740-8767a480-3525-11ea-9e2e-8060c7a12a01.png)

**Comment by acelaya** [comment]
@calvinbui I have just released versions 2.0.2 and 1.21.2 whcih include this fix.

Docker images arte building and usually take a while. Give it 1-2 hours.

**Comment by calvinbui** [comment]
working thanks
