### ISSUE TITLE
Need to support await to generate shlink url

### ISSUE THREAD

**Issue by ayeteng** [shlinkio/shlink#622]
It takes about 0.2 second to generate a short url but it take long time to generate about 2000 at a time. I'd like to understand any possible to use python concurrent async/await to Shlink function.

Below is my example code:

```
async def post(self):
    # ADD_SHORT_URL
    shlink = Shlink(url="https://goo.ng/",
                            api_key="f619cf64-0602-fe96-7f67-f624e5409a86"
                        )    
result = await shlink.add_short_url(long_url="https://future.org/8551b450bc0572f619cf698eb903676b5409a862b28c7347f673732fe968360faecff06020f2d9af,
                        tags=[
                            "future"
                        ],
                        valid_since=datetime.datetime(2019, 7, 15),
                        valid_until=datetime.datetime(2100, 7, 15),
                        custom_slug="",
                        max_visits=9999999,
                        find_if_exists=True
                    )       
```

TypeError: object ShortUrl can't be used in 'await' expression

Thank you.

**Comment by ayeteng** [comment]
Sorry, I post to wrong forum. Should be in shlink-py

**Comment by acelaya** [comment]
Nice!

I didn't know there was a python library.

Could you point me out to the repository?

**Comment by ayeteng** [comment]
it's in here.

https://bitbucket.org/davidksouthgate/shlink-py/src/master/

I will try to check them if they could add the async/await function.

Thanks.

**Comment by acelaya** [comment]
Thanks!
