### ISSUE TITLE
Cannot override client-detection.global.php

### ISSUE THREAD

**Issue by MarcHagen** [shlinkio/shlink#624]
#### How Shlink is set-up

* Shlink Version: 2.0.2
* PHP Version: 4.7.2
* How do you serve Shlink: Self-hosted swoole
* Database engine used: MariaDB (x.y.z)

#### Summary
I would like to override the ip_address_resolution because the X-Real-IP is not working correctly for me.

#### Current behavior

```
array (size=1)
  'headers_to_inspect' => 
    array (size=13)
      0 => string 'CF-Connecting-IP' (length=16)
      1 => string 'True-Client-IP' (length=14)
      2 => string 'X-Real-IP' (length=9)
      3 => string 'Forwarded' (length=9)
      4 => string 'X-Forwarded-For' (length=15)
      5 => string 'X-Forwarded' (length=11)
      6 => string 'X-Cluster-Client-Ip' (length=19)
      7 => string 'Client-Ip' (length=9)
      8 => string 'Forwarded' (length=9)
      9 => string 'X-Forwarded-For' (length=15)
      10 => string 'X-Forwarded' (length=11)
      11 => string 'X-Cluster-Client-Ip' (length=19)
      12 => string 'Client-Ip' (length=9)
```

#### Expected behavior

```
array (size=1)
  'headers_to_inspect' => 
    array (size=13)
      0 => string 'Forwarded' (length=9)
      1 => string 'X-Forwarded-For' (length=15)
      2 => string 'X-Forwarded' (length=11)
      3 => string 'X-Cluster-Client-Ip' (length=19)
      4 => string 'Client-Ip' (length=9)
```

#### How to reproduce

1. Add a `client-detection.local.php` with : 
```
<?php
declare(strict_types=1);
return [

    /**
     * If using a second proxy (clien > apache > traefik > container) the X-Real-IP is the IP of the 1ste proxy
     * X-Forwarded-For is then preferred because it contains the client IP: client, proxy1, (proxy2, ...)
     */
    'ip_address_resolution' => [
        'headers_to_inspect' => [
            'Forwarded',
            'X-Forwarded-For',
            'X-Forwarded',
            'X-Cluster-Client-Ip',
            'Client-Ip',
        ],
    ],
];
```
2. Run server

I have added a `var_dump($config['ip_address_resolution']);exit;` at
https://github.com/shlinkio/shlink-common/blob/e6110c87ca098cb7428cdc37e75b90da8ecfbf95/src/Middleware/IpAddressMiddlewareFactory.php#L16-L17

**Comment by MarcHagen** [comment]
Wheeeuww.. 
So this is not a bug, it's a user bug. Turns out for arrays you have to use the `MergeReplaceKey` class. Else it will be flat merged.
So the `client-detection.local.php` should then be:
```
<?php
declare(strict_types=1);
use Laminas\Stdlib\ArrayUtils\MergeReplaceKey;
return [

    /**
     * If using a second proxy (clien > apache > traefik > container) the X-Real-IP is the IP of the 1ste proxy
     * X-Forwarded-For is then preferred because it contains the client IP: client, proxy1, (proxy2, ...)
     */
    'ip_address_resolution' => [
        'headers_to_inspect' => new MergeReplaceKey([
            'Forwarded',
            'X-Forwarded-For',
            'X-Forwarded',
            'X-Cluster-Client-Ip',
            'Client-Ip',
        ]),
    ],
];
```

**Comment by acelaya** [comment]
Nice!

I actually didn't know about this `MergeReplaceKey` class. I've done a lot of weird workarounds in the past in order to bypass situations like this one.

I will also treat this as a bug, since it should be possible to solve it by changing the order so that `x-real-ip` has a lower priority.

**Comment by MarcHagen** [comment]
Ah cool oke, there is also a `MergeRemoveKey` that does exactly as it says.
I got the info from : https://github.com/laminas/laminas-stdlib/blob/2510c44b999e756f7c19463ac5595670fa1533ed/src/ArrayUtils.php#L268

**Comment by acelaya** [comment]
I just pushed the fix for this.

This is how the headers will be inspected after v2.0.3 is released:

```diff
'CF-Connecting-IP',
- 'True-Client-IP',
- 'X-Real-IP',
- 'Forwarded',
'X-Forwarded-For',
'X-Forwarded',
+ 'Forwarded',
+ 'True-Client-IP',
+ 'X-Real-IP',
'X-Cluster-Client-Ip',
'Client-Ip',
```
