### ISSUE TITLE
Not working on Plesk without modifying

### ISSUE THREAD

**Issue by MartinH0** [shlinkio/shlink#638]
#### How Shlink is set-up

* Shlink Version: v2.0.3
* PHP Version: 7.4.2
* How do you serve Shlink: Self-hosted Apache
* Database engine used: MariaDB

#### Summary

Server Error 500.
Because of every file inside `/bin/` starts with (https://github.com/shlinkio/shlink/blob/e18187f04ec5fa99ef13784a98911dde83969f9d/bin/install#L1) `#!/usr/bin/env php`

As on Plesk I can change the PHP version of a subscription with the Plesk Panel, this setup is breaking all functuions of Shlink.

I had manually replace the first Line of all Files in `/bin/` with `#!/opt/plesk/php/7.4/bin/php` to make it work.

#### Current behavior

Not working with the selected PHP version but always with `#!/usr/bin/env php` (which for me does not exist on my server.

#### Expected behavior

Using the selected PHP version for this subscription.
Btw implementing it in a way, all systems and Panels can work with. Actually I dont know how to implement it in a way to be more compatibly and working on everything out of the box, but may you do?

**Comment by acelaya** [comment]
What are you exactly trying to do?

Because this "server error 500" you mention is making me think you are trying to reach files from inside the bin folder through the web, while those are meant to be run from the CLI instead.

**Comment by MartinH0** [comment]
Its just not even working anyhow if I use it like stock provided.
Means its not working on Plesk if you do not modify it how I told.

I ever had to do this with shlink.

**Comment by acelaya** [comment]
Could you provide the steps to reproduce the issue?

What is the operation you are exactly trying to do?

**Comment by MartinH0** [comment]
Sorry just checked again, somehow this have to be related to something else.. cant reproduce it. Sorry.

Also it works now out of stock so this will not be a problem of shlink.
Will close this issue
