### ISSUE TITLE
Once a log file is created from CLI, it's no longer writable from web

### ISSUE THREAD

**Issue by mnewt00** [shlinkio/shlink#648]
#### How Shlink is set-up

* Shlink Version: 2.0.4
* PHP Version: 7.4.2
* How do you serve Shlink: Self-hosted nginx
* Database engine used: MariaDB

#### Summary

When I navigate to an invalid link, I receive a 500 error instead of the 404 error. The QR code also throws back a 500 error.
#### Current behavior

Invalid Link is 500 error
QR Code is 500 error
#### Expected behavior
Invalid link is 404 error and redirects to set page
QR Code should generate and display with 200 success.

#### How to reproduce

1. Install php7.4 with fpm and all extensions
2. Download shlink, extract in /var/www/shlink
3. Run install
4. Configure **nginx**

**Comment by acelaya** [comment]
I'm afraid I'm not being able to reproduce it.

Do you see a shlink error page together with the 500 status?

If that's the case, can you check the logs? (located inside data/log). Maybe we can get more information from them.

**Comment by MartinH0** [comment]
> Invalid link is 404 error and redirects to set page

For me its doing this.
When I call a invalid link like this:
https://l.hotmann.de/invalidLINK

I get redirected to the 404 site (which is set to my Hopepages 404 Error Page)
For me this works perfectly

**Comment by mnewt00** [comment]
If you want to see, [https://sqcraft.xyz/invalidlink](https://sqcraft.xyz/invalidlink)

All that is in the logs is this:
```
Successfully acquired the "db:create" lock.
Shlink.INFO - Expiration defined for "db:create" lock for "90" seconds.
```

Here is nginx logs:
[https://bin.ptdl.co/om696/
](https://bin.ptdl.co/om696/
)
and nginx config:
[http://bin.ptdl.co/d157v](http://bin.ptdl.co/d157v)

Could it be because of CORS?

**Comment by acelaya** [comment]
According to the logs, it looks like shlink does not have permission to write in the data/log directory.

Granting write permissions to this directory will probably solve the issue.

**Comment by mnewt00** [comment]
[https://i.imgur.com/pnv3DJq.png ](https://i.imgur.com/pnv3DJq.png )
is has all permissions, with www-data being the owner

**Comment by acelaya** [comment]
I was about to edit my message, because I realized it's something else, but you were faster.

The problem is probably that today's log file was created from the command line (I would say, during installation), which made that specific file belong to other user, and therefore not being editable by the www-data user.

Change permissions to that specific file (or just deleted so that it gets recreated) and let me know if that helps.

**Comment by mnewt00** [comment]
Thank you! It works. Can successfully get a 404 error.

**Comment by acelaya** [comment]
Awesome!

I will keep this open in order to investigate of a proper solution can be provided, by making sure log files are created with enough permissions.

**Comment by acelaya** [comment]
Hey @mnewt00 

I have just merged a fix that will make sure all users can write in the log files, preventing this error from happening.

It will be available in next hotfix release.
