### ISSUE TITLE
Adding root URL with slug `/` does not work and is not deleteable

### ISSUE THREAD

**Issue by Empty2k12** [shlinkio/shlink#663]
#### Summary

Adding a new short URL with custom slug as `/` works, shlink displays this URL as `domain.tld` in the list. However the root URL does not resolve (https://domain.tld gives the 404 page) and the short URL cannot be deleted with the message: `Something went wrong while deleting the URL :(`

#### How Shlink is set-up

Docker: https://hub.docker.com/layers/shlinkio/shlink/stable/images/sha256-7a50dd4401dd366f9636c3fa146d9de82d3a918fb6d03807fa0a7a445582e8b6?context=explore

#### How to reproduce

On https://app.shlink.io/:

1. Add new short URL with these settings: `Insert the URL to be shortened`: `https://gero.dev` and `Custom Slug`: `/`
2. Navigate to `List short URLs`
3. See new short domain for root domain. Open that, it will 404. Try to delete it, it fails.

**Comment by acelaya** [comment]
That shouldn't really be allowed. I will make sure that gets validated and a meaningful error is returned.

In order to configure a fallback redirect from your base domain, you have to pass the `BASE_URL_REDIRECT_TO` env var to the docker image.

You can find more information here https://github.com/shlinkio/shlink/tree/develop/docker#supported-env-vars

**Comment by Empty2k12** [comment]
I got the `BASE_URL_REDIRECT_TO` to work, thanks! I appreciate your work on the project and that the behavior will be fixed soon.

Maybe it can be allowed that the empty URL I have in my instance can be deleted, but new empty ones can't be created?

**Comment by acelaya** [comment]
Yes, that's the plan. However, you can always manually delete that URL from the database, of you don't want to wait for the next release to be ready.

**Comment by acelaya** [comment]
Hey @Empty2k12 

I'm afraid I cannot make this URL to be deletable. You will have to manually remove it from the database if it bothers you to see it there.

**Comment by Empty2k12** [comment]
@acelaya I appreciate your fix for this! I already deleted the URL so everything is fine. Thanks for your work, the product is excellent!

**Comment by acelaya** [comment]
Thanks for the kind words 🙂

**Comment by n1LWeb** [comment]
This was changed to DEFAULT_BASE_URL_REDIRECT in the meantime. Just für the people landing here from Google.
