### ISSUE TITLE
Error on using validSince and validUntil to create short URL (v2)

### ISSUE THREAD

**Issue by pethersonmoreno** [shlinkio/shlink#664]
**How Shlink is set-up**

- Shlink Version: 2 (docker image [shlinkio/shlink:stable)](https://hub.docker.com/layers/shlinkio/shlink/stable/images/sha256-7a50dd4401dd366f9636c3fa146d9de82d3a918fb6d03807fa0a7a445582e8b6?context=explore)
- PHP Version: all (just using docker image)
- How do you serve Shlink: docker
- Database engine used: mariadb

**Summary**
When you try to create a short URL or edit its metadata and provide any date (validSince and/or validUntil), shlink tries to parse them as chronos objects before calling the input filter.

That makes an exception to be thrown that in turn translates into a 500 status being returned, when a 400 coming from the input filter not being valid, would be expected.

**Current behavior**
Providing valid dates results in 400 error with the following JSON as output:
```json
{
    "invalidElements": [
        "validSince"
    ],
    "title": "Invalid data",
    "type": "INVALID_ARGUMENT",
    "status": 400,
    "detail": "Provided data is not valid"
}
```

**Expected behavior**
Providing valid dates results in 200 status with the short URL created.

#### How to reproduce
To reproduce it run the following command with the service active:

```shell
curl --location --request POST '{shlinkUrl}/rest/v2/short-urls' \
--header 'X-Api-Key: eef31456-7a7b-41f6-834f-351a1293b8b5' \
--header 'Content-Type: application/json' \
--data-raw '{
  "longUrl": "https://www.google.com",
  "tags": [
    "google"
  ],
  "validSince": "2020-02-25",
  "customSlug": "google",
  "maxVisits": 1,
  "findIfExists": true,
  "domain": "testing.com.br"
}'
```

Replacing {shlinkUrl} with the URL of shlink used.

#### Other comments
Maybe it is related to Issue https://github.com/shlinkio/shlink/issues/555, but the problem is happening with valid dates.

**Comment by acelaya** [comment]
Hello @pethersonmoreno.

Try using the `2020-02-25T00:00:00+01:00` format (is the one actually expected by the API).

Replace the `01:00` offset by the one you want to use.

**Comment by acelaya** [comment]
It is documented https://shlink.io/documentation/api-docs/#dates

**Comment by marcel-necker** [comment]
You're right! I overlooked that detail when I spotted ISO-8601. Thanks for clarification!
