### ISSUE TITLE
How to map volume to sqlite file on docker?

### ISSUE THREAD

**Issue by Inrego** [shlinkio/shlink#681]
I'd like to use sqlite, but I want to map the db file path via volumes so I save it outside of the image. But I didn't see any volume mappings for this.

**Comment by Inrego** [comment]
I tried adding this to my docker command: `-v /opt/shlink/data:/etc/shlink/data`
But that just results in the following error:

    The directory "/etc/shlink/config/autoload/../../data/locks" is not writable.

**Comment by acelaya** [comment]
I would encourage you not to use sqlite, but if you want to use it, follow these steps: https://github.com/shlinkio/shlink-docker-image/issues/40#issuecomment-491924262
