### ISSUE TITLE
.htaccess missing in 2.1.0 release zip

### ISSUE THREAD

**Issue by SirFlip** [shlinkio/shlink#697]
#### How Shlink is set-up

* Shlink Version: 2.1.0
* PHP Version: 7.4.4
* How do you serve Shlink: Self-hosted Apache
* Database engine used: MariaDB

#### Summary

the `public/.htaccess` got missing in the release zip

#### Current behavior

Apache gives 404 error for all endpoints except root.

with .htaccess from old versions it works fine.

**Comment by acelaya** [comment]
I think I know the reason. Will get it fixed on a patch release.

Thanks!

**Comment by acelaya** [comment]
@SirFlip I have just released v2.1.1, which brings the htaccess file back.
