### ISSUE TITLE
QR Codes refers to localhost

### ISSUE THREAD

**Issue by reactpro** [shlinkio/shlink#705]
#### How Shlink is set-up

* Shlink Version: 2.1.2
* How do you serve Shlink: Docker image (latest stable)
* Database engine used: MySQL 5.7

#### Summary

Setting custom domain with variable SHORT_DOMAIN_HOST, QR codes refers to 127.0.0.1:8080, is it possible to change host for QR codes?

**Comment by acelaya** [comment]
It should not behave like that, but instead, it should use the value defined in that env var.

I will investigate it.

**Comment by acelaya** [comment]
Ok, I have just checked that the hostname used when generating the URL that is then used inside the QR code, is inferred from the request, which means it will be localhost if you are serving shlink in localhost, even if you set the env var value.

That is a bug. It should respect the domain defined for the short URL or the one in the env var.

I will get it fixed.

**Comment by acelaya** [comment]
Hey @reactpro, I have just released v2.1.3 which fixes this issue.

**Comment by reactpro** [comment]
@acelaya, thank you!
