### ISSUE TITLE
Allow all short URLs to be listed from the CLI by using a flag

### ISSUE THREAD

**Issue by jakkuh** [shlinkio/shlink#707]
#### How Shlink is set-up

* Shlink Version: 2.1.2
* PHP Version: 7.4
* How do you serve Shlink: Self-hosted nginx
* Database engine used: MySQL
#### Summary

Is there a way to get a text-based dump of the links (like you would with `./cli short-url:list`) that isn't paginated? I want to dump them to a text file by piping but with the current setup I'll need to respond "yes" almost 200 times.

Would be cool if there was an `--all` flag for that command or something... let me know!

**Comment by acelaya** [comment]
You can use `yes | shlink short-url:list`.

However, you will still have the questions mixed in between the list, but it's the best I can offer you now.

I will add this `--all` flag so that it's available on future releases.
