### ISSUE TITLE
Short Menu

### ISSUE THREAD

**Issue by MingyJ** [shlinkio/shlink#708]
I'm wondering if you may know the proper config. to setup "Short Menu" - a Mac toolbar app to work with Shlink. Unfortunately, this is a macOS only piece of software, it's pretty awesome though!

https://shortmenu.com/mac/

Any guidance would be appreciated.

**Comment by acelaya** [comment]
Hey @MingyJ 

Actually, I have just finished documenting that about 10 minutes ago :-)

Here you have the instructions: https://shlink.io/documentation/integrations/short-menu-mac/

**Comment by MingyJ** [comment]
Man, thank you :) Much appreciated! Works perfect.

**Comment by oezh** [comment]
The app Short Menu works fine for auto shrink url, but is failing when using custom slug. The error message is: "The format of the server's response is not supported!" Is there something missing in the config to allow custom slug from Short Menu?
