### ISSUE TITLE
Multi-Arch images

### ISSUE THREAD

**Issue by Starbix** [shlinkio/shlink#709]
#### Summary

Currently the docker images are amd64-only.
I've tried building the image on an aarch64 machine and it worked out of the box, although MS SQL probably wouldn't work as [these](https://github.com/shlinkio/shlink/blob/develop/Dockerfile#L27) binaries are amd64.

Having multi-arch images would make running shlink on devices like the Raspberry Pi much easier.

An easy way to build multi-arch images is `docker buildx` like here: https://github.com/Starbix/docker-plex-ldap/blob/master/.github/workflows/build.yml

---

https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/

**Comment by acelaya** [comment]
Hey @Starbix 

This is interesting. I didn't know about this `buildx` experimental feature.

I will investigate further to see if it's possible to support docker images for both architectures.
