### ISSUE TITLE
Make sure entities metadata cache is cleaned when updating Shlink

### ISSUE THREAD

**Issue by MarcHagen** [shlinkio/shlink#712]
#### How Shlink is set-up

* Shlink Version: 2.1.2
* PHP Version: 7.4.4
* How do you serve Shlink: Self-hosted swoole Docker
* Database engine used: MariaDB (10.4)

#### Summary

Running `php bin/cli visit:locate --retry` doesn't give the desired effect.
Updating from 2.0.5 to 2.1.2 gave no issues. And database is like expected.
 
```
create table x.visit_locations
(
    id           bigint unsigned auto_increment primary key,
    country_code varchar(255)         null,
    country_name varchar(255)         null,
    region_name  varchar(255)         null,
    city_name    varchar(255)         null,
    timezone     varchar(255)         null,
    lat          double               not null,
    lon          double               not null,
    is_empty     tinyint(1) default 0 not null
)
collate = utf8_unicode_ci;
```

#### Current behavior

```
/app # php bin/cli visit:locate --retry
[2020-04-05T22:37:19.811662+00:00] [NULL] Shlink.INFO - Successfully acquired the "visit:locate" lock.
[2020-04-05T22:37:19.812096+00:00] [NULL] Shlink.INFO - Expiration defined for "visit:locate" lock for "90" seconds.


 [ERROR] [Semantical Error] line 0, col 121 near 'isEmpty = :isEmpty': Error: Class
         Shlinkio\Shlink\Core\Entity\VisitLocation has no field or association named isEmpty

```

#### Expected behavior

Running retry on database

#### How to reproduce

Updating from 2.0.5 to 2.1.2

**Comment by acelaya** [comment]
That's weird :thinking: 

The only thing that could make that happen is that this command failed https://github.com/shlinkio/shlink/blob/develop/docker/docker-entrypoint.sh#L13

Could you try opening a shell on your container and running that without the -q flag? Then let me know what's the output.

Also, if the command does not fail, you will have to restart the container, otherwise it will continue using an outdated version of the entity proxies.

**Comment by acelaya** [comment]
BTW, I have a question regarding these two points

> * PHP Version: 7.4.4
> * How do you serve Shlink: Self-hosted swoole Docker

Is it "self-hosted swoole" or "docker image"? Because my instructions were for the second, but I have just realized it might not be the case.

Also, if you are using the docker image, how can it be that you are using PHP 7.4.4? Maybe you built your own docker image?

**Comment by MarcHagen** [comment]
Lol i was just typing this ...

It's the a "custom" build swoole docker container to get it working with my docker/hosting setup.
Yes i have build my own docker image / docker-compose.
I have used the latest v2.1.2 at master to build this container. 

```
shlink_1  | 🏗 Creating fresh database if needed...
shlink_1  | [2020-04-06T10:16:01.870501+00:00] [NULL] Shlink.INFO - Successfully acquired the "db:create" lock.
shlink_1  | [2020-04-06T10:16:01.871670+00:00] [NULL] Shlink.INFO - Expiration defined for "db:create" lock for "90" seconds.
shlink_1  |
shlink_1  |  [OK] Database already exists. Run "db:migrate" command to make sure it is up to
shlink_1  |       date.
shlink_1  |
shlink_1  | 🏗 Updating database...
shlink_1  |
shlink_1  |                     ShlinkMigrations
shlink_1  |
shlink_1  |
shlink_1  | No migrations to execute.
shlink_1  | 🏗 Generating proxies...
shlink_1  |
shlink_1  |  Processing entity "Shlinkio\Shlink\Core\Entity\Domain"
shlink_1  |  Processing entity "Shlinkio\Shlink\Core\Entity\ShortUrl"
shlink_1  |  Processing entity "Shlinkio\Shlink\Core\Entity\Tag"
shlink_1  |  Processing entity "Shlinkio\Shlink\Core\Entity\Visit"
shlink_1  |  Processing entity "Shlinkio\Shlink\Core\Entity\VisitLocation"
shlink_1  |  Processing entity "Shlinkio\Shlink\Rest\Entity\ApiKey"
shlink_1  |
shlink_1  |  Proxy classes generated to "/app/data/proxies"
shlink_1  | ✅ Starting swoole...
```

```
php:7.4.4-alpine3.11
APCU_VERSION 5.1.18
APCU_BC_VERSION 1.0.5
INOTIFY_VERSION 2.0.0
SWOOLE_VERSION 4.4.17
REDIS_VERSION 5.2.1
composer:1.9
composer install \ 
    --no-dev \
    --prefer-dist \
    --optimize-autoloader \
    --apcu-autoloader \
    --no-suggest \
    --no-interaction 
```

**Comment by acelaya** [comment]
Ok, then I think it might be related with the fact that you are using APCu.

APCu does not behave as one would expect when using swoole, as every web worker and task worker has it's own non-shared memory, which means that they have separated caches.

Also, considering swoole keeps everything in memory anyway, it does not provide any real performance benefit.

Could you try removing APCu from your image? Also, very important, remove the apcu-autoloader flag from the computer command.

And finally, how do you run the visit:process command inside your container?

**Comment by MarcHagen** [comment]
So i have removed all APCu from the images including the autoloading from composer.

```
# docker-compose exec shlink  sh -c "php bin/cli visit:locate --retry"
[2020-04-06T11:10:36.645249+00:00] [NULL] Shlink.INFO - Successfully acquired the "visit:locate" lock.
[2020-04-06T11:10:36.645662+00:00] [NULL] Shlink.INFO - Expiration defined for "visit:locate" lock for "90" seconds.
Downloading GeoLite2 database...
 30410400/30410400 [============================] 100%


 [ERROR] [Semantical Error] line 0, col 121 near 'isEmpty = :isEmpty': Error: Class
         Shlinkio\Shlink\Core\Entity\VisitLocation has no field or association named isEmpty
```

> And finally, how do you run the visit:locate command inside your container?
i do both from external and internal so:
`docker-compose exec shlink  sh -c "php bin/cli visit:locate --retry"` or
`docker-compose exec shlink sh` > `php bin/cli visit:locate --retry` from the root app dir.

**Comment by acelaya** [comment]
I have to admit I'm a bit lost here, as I'm not being able to reproduce this.

Would you be willing to share your custom Dockerfile with me?

Also, what's the reason not to use the official docker image?

**Comment by MarcHagen** [comment]
To be fair, when you first released the docker image it was not great. 
So i build/created my own build system for the image and updated it. 
It's heavy inspired by [netbox-community/netbox-docker](https://github.com/netbox-community/netbox-docker) project.

But i wanted to change some options within the image like php.ini and shlink_in_docker file
_because how traefik handles requests_ and have a but more control on how the image is presented and what is inside it.
So now i'm running it with docker-compose and a easy upgrade script.
I have uploaded it now to my github: [MarcHagen/shlink-docker-expirimental](https://github.com/MarcHagen/shlink-docker-expirimental)

**Comment by acelaya** [comment]
Ok, thanks for sharing.

I will try to test with your image later today, to see if I can produce it and find out the root cause.

**Comment by MarcHagen** [comment]
To be fair. I used the official shlink image. And it's the same result.
It's erroring on isEmpty.

Setup is same as in my repo, but then with the stable version and my .env file.
And for checking sake here it is:

```
SHORT_DOMAIN_HOST=doma.in
SHORT_DOMAIN_SCHEMA=http
VALIDATE_URLS=true
DB_DRIVER=mysql
DB_NAME=***********
DB_USER=***********
DB_PASSWORD=***********
DB_HOST=***********
INVALID_SHORT_URL_REDIRECT_TO=http://doma.in/404
REGULAR_404_REDIRECT_TO=http://doma.in/404
BASE_URL_REDIRECT_TO=http://doma.in/home
REDIS_SERVERS=tcp://redis:6379
WEB_WORKER_NUM=8
TASK_WORKER_NUM=8
DISABLE_TRACK_PARAM=
```

[logs.log](https://github.com/shlinkio/shlink/files/4438468/logs.log)

**Comment by acelaya** [comment]
Thanks for trying. I was going to ask you, but didn't want to bother you again.

I will investigate further this afternoon, trying to be as closer as possible to your setup.

I'm guessing it might be related with redid. It's the only thing I haven't tried yet.

I will get to the bottom of the problem. Thanks for your patience.

**Comment by MarcHagen** [comment]
Yeah no problem, i love the project it well documented and you put allot of effort in it. 
And i know how annoying it is when users of the product are not cooperating or don't give enough / misleading information. So if you have **any** questions regarding my setup/configs or something else just ask me and i'm happy to help you :)

**Comment by acelaya** [comment]
Thanks for the kind words. It's much appreciated.

Ok, I definitely think redis has to be related with the issue.

I haven't tried yet, but when redis config is provided, Shlink uses it as the cache for the entities metadata, which includes the properties of every entity.

Since the isEmpty property did not exist in VisitLocation in v2.0.5, I think an outdated metadata is cached in redis, and when running a newer Shlink version, it is picking it by mistake.

Can you try running this command inside your container?

`./vendor/bin/doctrine orm:clear-cache:metadata`

It has to be run on the project root dir.

After that, try running the visit:locate command again and let me know if it solves the problem.

**Comment by MarcHagen** [comment]
Ah yes that sounds logical indeed. 
And works for the both images.

**Comment by acelaya** [comment]
I'm glad to hear that. This was a tricky one :sweat_smile: 

I will also add this command to the official docker entry point, and to the installer, for users not using docker.

Thanks a lot for your help :-)
