### ISSUE TITLE
Twitter parsing issue

### ISSUE THREAD

**Issue by damirsel** [shlinkio/shlink#716]
### How Shlink is set-up

* Shlink Version: 1.18.1
* PHP Version: 7.2.4
* How do you serve Shlink: Self-hosted Apache on DigitalOcean VPS
* Database engine used: 5.7.29-0ubuntu0.18.04.1 (Ubuntu)

### Summary

Our issue is with Twitter, whenever we share shortened link on Twitter it just doesn't extract original link and parse og tags and images. At first we thought that it happens bcs TW doesn't follow redirections all the way through, but then we saw some other shortening services are working just fine with Twitter.

Is there something we can set on our Shlink app that can make it produce shortened links compatible with Twitter ?

Thanks.

**Comment by dejanmarkovic** [comment]
Hi friends, 
I am having the same problem too. 

Thanks

**Comment by acelaya** [comment]
It's weird, it shouldn't be the case, as Shlink does not do anything to prevent Twitter from following those redirects (at least intentionally), but I have also noticed some inconsistent behaviors on that regards.

I will investigate.

**Comment by dejanmarkovic** [comment]
@acelaya thank you so much!

Here are the links to a working post (not shlink) and broken post (shlink but rebranded to sws.sh)

working
https://twitter.com/my_test_tweet/status/1246073902884765706/

broken
https://twitter.com/my_test_tweet/status/1246071768537862144/

Thank you so much in advance.
I appreciate your time and efforts!

Dejan

**Comment by acelaya** [comment]
I found out the reason. Twitter does not check the links you paste doing a GET request, but a HEAD request.

Shlink is not prepared to receibe those, which always results either on a 404 or on the client being redirected to any of the default redirects.

So that's why it does not work.

It should be easy to fix, but I need a bit of investigation on how other social networks behave and what's the proper way to handle HEAD requests.

**Comment by acelaya** [comment]
Only thing here @damirsel is that Shlink 1.X is no longer receiving bugfixes, only critical security issues, which means you will have to update to v2.1.3 once published, in order to get the fix for this.

You might start taking a look at this https://github.com/shlinkio/shlink/blob/develop/UPGRADE.md#from-v1x-to-v2x

**Comment by dejanmarkovic** [comment]
@alesub please note that I only have the problem with Twitter posts. Facebook and LinkedIn posts are working properly. 

Thank you very much!

Dejan

**Comment by acelaya** [comment]
Most probably because they do a GET request instead of a HEAD one, which is properly handled by Shlink.

**Comment by acelaya** [comment]
I'm now seeing GET requests coming from Twitter. This is weird. It doesn't seem to have a consistent behavior.

**Comment by dejanmarkovic** [comment]
I am assuming that they have maybe "old implementation" and "new" so sometimes you hit the old server and sometimes new. We had similar issues with some other implementations with other social networks.

Hope this helps. 
Thanks

**Comment by acelaya** [comment]
You might be into something. I'm not sure if it's two APIs, but I have tried in two different ways, using this https://cards-dev.twitter.com/validator, and trying to publish on a regular tweet.

**Comment by acelaya** [comment]
@damirsel @dejanmarkovic looks like I managed to fix it by doing a proper handling of HEAD requests.

I still need to make Shlink "ignore" HEAD requests, in the sense of not track them, but other than that, it seems to work with this change. I will merge it in ~1h

**Comment by acelaya** [comment]
I have just merged the fix. It will be available as part of v2.1.3

**Comment by acelaya** [comment]
@damirsel @dejanmarkovic Shlink v2.1.3 has just been released, including the fix for this issue.

**Comment by damirsel** [comment]
guys thanks a lot for such a fast response!

**Comment by dejanmarkovic** [comment]
Thank you so much @acelaya! 
You rock!
