### ISSUE TITLE
Can't Delete Short URL after Upgrade to 2.1.2

### ISSUE THREAD

**Issue by renaldiAlterra** [shlinkio/shlink#723]
#### How Shlink is set-up

* Shlink Version: 2.1.2
* PHP Version: 7.4.4
* How do you serve Shlink: Self-hosted nginx
* Database engine used: MariaDB (10.2.31)

#### Summary

When finish upgrade i create a short url and it's work, but when i want to delete it's not working

#### Current behavior

when i tried on the cli it show like this

**In AbstractMySQLDriver.php line 49:**
`
An exception occurred while executing 'DELETE FROM short_urls WHERE id ...
SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails`

**In PDOStatement.php line 123:**
`
An exception occurred while executing 'DELETE FROM short_urls WHERE id ...
SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails`

**In PDOStatement.php line 121:**
`
An exception occurred while executing 'DELETE FROM short_urls WHERE id ...
SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails`

when i treid on the webClient it show like this

![image](https://user-images.githubusercontent.com/49466271/78963581-23537d00-7b22-11ea-9e27-2fe89dd1f04b.png)

#### Expected behavior

The short url is deleted

#### How to reproduce

Create new url and try delete it..

Thanks before

**Comment by acelaya** [comment]
It looks like there's some missing `ON DELETE CASCADE` constraint somewhere.

I will investigate.

**Comment by acelaya** [comment]
I have checked, and there's only two foreign keys pointing to the short URL table.

One in the short_urls_in_tags table, and another in the visits table. Both should have ON DELETE CASCADE, and I think the missing one in your case is the second.

Could you verify it, please?

**Comment by renaldiAlterra** [comment]
sorry, how to chek that ? i mean.. how to do that ? 

which path i should check ? or what query i should run ?

**Comment by renaldiAlterra** [comment]
Like this rigth ?

**for visits table**
![image](https://user-images.githubusercontent.com/49466271/79089601-e630fa00-7d70-11ea-8bd1-c13f34950863.png)
**for short_urls table**
![image](https://user-images.githubusercontent.com/49466271/79089754-7b33f300-7d71-11ea-9a77-2720f43236af.png)

**for short_urls_in_tags table**
![image](https://user-images.githubusercontent.com/49466271/79089768-8d159600-7d71-11ea-8ef0-a242db5cb837.png)

well from that, i dont have ON DELETE CASCADE on my short_urls_in_tags table right ?

**Comment by acelaya** [comment]
Yep, that's the missing one apparently.

I have been checking the history, and it looks there's was a bug for some time in which that constraint was not properly created when setting-up the database.

Just run this `ALTER` instruction in your database. It should fix the issue.

```sql
ALTER TABLE short_urls_in_tags DROP CONSTRAINT FK_59775203F1252BC8;

ALTER TABLE short_urls_in_tags ADD CONSTRAINT FOREIGN KEY (short_url_id)
REFERENCES short_urls(id) ON DELETE CASCADE;
```

I have just tested that on a MariaDB database and it worked, but just in case, create a back-up oif your database first.

**Comment by acelaya** [comment]
BTW, the bug also affected the reference against the tags table, so you will probably not be able to delete tags if they are being used in some short_url.

To fix that, use this similar instruction:

```sql
ALTER TABLE short_urls_in_tags DROP CONSTRAINT FK_59775203BAD26311;

ALTER TABLE short_urls_in_tags ADD CONSTRAINT FOREIGN KEY (tag_id)
REFERENCES tags(id) ON DELETE CASCADE;
```

**Comment by renaldiAlterra** [comment]
Thanks, i can delete my short url know..

well just wanted to know, those script missing when upgrading to v2.1.2 right ?
cause i didn't mess with query or code
