### ISSUE TITLE
Wrong IP address logged by swoole when served behind proxy

### ISSUE THREAD

**Issue by acelaya** [shlinkio/shlink#732]
#### How Shlink is set-up

* Shlink Version: All
* PHP Version: All
* How do you serve Shlink: Self-hosted swoole|Docker image
* Database engine used: All

#### Summary

Currently swoole access logger is logging the IP address from the caller, but if this is a proxy, it should be the forwarded one instead.

#### Current behavior

The proxy IP address is logged when serving Shlink with swoole behind a proxy.

#### Expected behavior

The original forwarded IP address is logged instead.

---

https://github.com/mezzio/mezzio-swoole/issues/9

**Comment by Ennazk** [comment]
Your proxy should be forwarding the original IP instead of using its own IP. 

If you are using an NGINX reverse proxy, your location block should have the following:

`proxy_set_header  X-Real-IP $remote_addr;`

It may help to also have the host forwarded. Complete block:

`  location / {
    proxy_set_header  Host $host;
    proxy_set_header  X-Real-IP $remote_addr;
    proxy_set_header  X-Forwarded-Proto https;
    proxy_set_header  X-Forwarded-For $remote_addr;
    proxy_set_header  X-Forwarded-Host $remote_addr;
    proxy_pass        http://wp.calvin.me;
  }`

**Comment by acelaya** [comment]
That is not the problem. Shlink is not honoring that header, that's where the bug is.

I also want to make clear that this does not affect geolocating visitors. That is properly working. It just affects the access logging, so it's actually not a really big deal.

**Comment by neilfrndes** [comment]
Would it be possible to specify a custom log format as mentioned here: https://docs.mezzio.dev/mezzio-swoole/v1/logging/#container-usage ?

It looks like it is possible to set a custom format for logging at docker build time using this [config setting](https://github.com/shlinkio/shlink/blob/704958994db6d0c6f9f7d87ace27f5af65f5a246/docker/config/shlink_in_docker.local.php#L154-L158):
   ```
 'mezzio-swoole' => [
        'swoole-http-server' => [
            'options' => [
                'worker_num' => (int) env('WEB_WORKER_NUM', 16),
                'task_worker_num' => (int) env('TASK_WORKER_NUM', 16),
            ],
        ],
    ],
```

**Comment by acelaya** [comment]
Yep, it would be possible. It's something I have considered several times.

However, it's easy to mess it up, so I haven't done it yet because of that.
