### ISSUE TITLE
Allow third party URLs

### ISSUE THREAD

**Issue by benhartwich** [shlinkio/shlink#734]
Now it is not possible to use for example market:// uris for the google playstore when I would like to link out of an android app. See: https://developer.android.com/distribute/marketing-tools/linking-to-google-play

It would be generally nice if shlink could support / allow other uris than http and https. Now I´m getting an error. Is there a workaround?

**Comment by acelaya** [comment]
This can be done, but there's no workaround at this moment.

**Comment by acelaya** [comment]
Hey @benhartwich. This is now implemented and will be part of v2.3.0

Shlink will allow passing deeplinks and other links with schemas other than http and https as the long URL.

**Comment by acelaya** [comment]
@benhartwich Shlink v2.3.0 has just been released, including this. Let me know if something does not work as expected.

**Comment by benhartwich** [comment]
Thanks a lot, works so far!

**Comment by benhartwich** [comment]
tel: urls don´t work - is there a workaround how I could do it via DB?

**Comment by acelaya** [comment]
Hey @benhartwich

If you found an issue, could you open a new bug report please?

It will all you for more detailed information on your setup. Just saying "don't work" is not very helpful to reproduce the issue 😅
