### ISSUE TITLE
Helm Chart for Shlink

### ISSUE THREAD

**Issue by neilfrndes** [shlinkio/shlink#741]
I created a helm chart to deploy Shlink on Kubernetes:
https://github.com/neilfrndes/shlink-helm-chart

Right now, the chart uses the inbuilt SQLite database which I understand is not persistent. I plan to add MySQL integration in the future.

Can I create a merge request to add this feature to the repository? #668

**Comment by neilfrndes** [comment]
Mariadb is now the default database backend

**Comment by neilfrndes** [comment]
To install the helm chart please use the following command:
helm install shlink <path/to/shlink> --set "ingress.enabled=true" --set "env.SHORT_DOMAIN_HOST=<doma.in>" -n <namespace>

**Comment by neilfrndes** [comment]
I tried setting up Mariadb as the default database backend, however I encounter the following error:

> Creating fresh database if needed...
> In ServiceManager.php line 772:
>                                                                                
>   Service with name "Doctrine\ORM\EntityManager" could not be created. Reason  
>   : The options 'driver' or 'driverClass' are mandatory if no PDO instance is  
>    given to DriverManager::getConnection().                                    
>                                                                                
> In DBALException.php line 116:
>                                                                                
>   The options 'driver' or 'driverClass' are mandatory if no PDO instance is g  
>   iven to DriverManager::getConnection().         

Probably related to this #598

**Comment by acelaya** [comment]
Thanks for the effort @neilfrndes :-)

> Can I create a merge request to add this feature to the repository?

I would prefer to keep it separated, but I can definitely link to your repository from this one.

> I tried setting up Mariadb as the default database backend, however I encounter the following error

I'm not completely sure how helm works. Does it use already published docker images, or is it building the image based on the Dockerfile?

In any case, I don't think this error is related with #598, as the docker image takes care of setting the driver option based on the DB_DRIVER env var.

What are exactly the changes you did to make it use mariadb instead of sqlite? Did you follow this instructions? https://shlink.io/documentation/install-docker-image/#use-an-external-db

**Comment by neilfrndes** [comment]
Sure, I'll not create a merge request.

I'm using the published docker image shlinkio/shlink:2.1.3 for Helm.
The following environment variables have been set in the shlink container:

>           env:
>             - name: SHORT_DOMAIN_HOST
>               value: "dom.ai"
>             - name: SHORT_DOMAIN_SCHEMA
>               value: "http"
>             - name:  DB_DRIVER
>               value: "mariadb"
>             - name:  DB_HOST
>               value: "shlink-mariadb"
>             - name:  DB_USER
>               value: "shlink"
>             - name: DB_PASSWORD
>               valueFrom:
>                 secretKeyRef:
>                   name: shlink-mariadb
>                   key: mariadb-password
>             - name: INVALID_SHORT_URL_REDIRECT_TO
>               value: doma.in
>             - name: BASE_URL_REDIRECT_TO
>               value: doma.in

One thing I must add is that I intentionally removed some of the required environment variables like DB_USER and DB_HOST, I still see the `'driver' or 'driverClass' are mandatory` error.

**Comment by neilfrndes** [comment]
Figured it out, I used `mariadb` instead of `maria` for DB_DRIVER :facepalm: 

Thanks for pointing me in the right direction

**Comment by acelaya** [comment]
Ok, good to know.

I will add a link to your repo from the docs, if you plan to maintain it.

Thanks again!
