### ISSUE TITLE
how to create custom slug

### ISSUE THREAD

**Issue by ron-majumdar** [shlinkio/shlink#778]
I am trying to find the exact API or documentation for the creation of a custom slug for a long url.
- Ron.

**Comment by acelaya** [comment]
If you plan to integrate the API yourself, this would be it https://api-spec.shlink.io/#/Short%20URLs/createShortUrl

The `customSlug` param is not mandatory. If it's not provided, then a short code is generated, and if you provide it, then it will be used by shlink.

However, if you plan to use shlink-web-client, it has a simple form to create short URLs where one of the params is the custom slug.

**Comment by ron-majumdar** [comment]
@acelaya - thanks a ton... this covers 90% of my use cases and I am moving forward with the implementation of shlink for my asset website (under construction):
http://ccode.ibm-asset.com:8888/ccode/

I need to integrate this with several tools, most importantly the Vortex Pattern Generator (VPG) that builds the website. I will reach out to you if I have further questions.

I have yet to Open Source VPG but is on it's way soon.

Thanks again.
- Ron.
