### ISSUE TITLE
Cannot update valid_since and valid_until to null

### ISSUE THREAD

**Issue by vijai1996** [shlinkio/shlink#779]
#### How Shlink is set-up

* Shlink Version: 2.2.1
* PHP Version: 7.4.
* How do you serve Shlink: Self-hosted Apache
* Database engine used: MariaDB

#### Summary

Once a link has been created with valid_since and valid_until dates, and an update request is sent with `null` for the date fields, the dates are not modified.

#### Current behavior

The patch request to null the `valid_since` and `valid_until` is not honored and the dates are the old dates.

#### Expected behavior

The dates should be removed and the columns in the database should be nulled.

#### How to reproduce

1. Create a new short link with valid vaid_since and valid_until dates
2. Update the created link with passing `null` value to valid_since and valid_until dates.

**Comment by acelaya** [comment]
When calling the PATCH request, are you sending the values in camelCase? Because that's how it has to be.

So, validSince and validUntil, instead of valid_since and valid_until.

You can find the docs here https://api-spec.shlink.io/#/Short%20URLs/editShortUrl

**Comment by vijai1996** [comment]
Yes, I'm indeed using the correct request param. Sorry, I referred to the db schema in the OP causing confusion. Below is the postman screenshot. I tried passing empty values too. Same is reproduced on my php based front end.

![image](https://user-images.githubusercontent.com/11158959/83963401-79933100-a8c3-11ea-99bf-a13184c78ae7.png)

**Comment by acelaya** [comment]
Can you try sending the request in JSON? Support for non-JSON requests comes from the early days and I don't even know why I supported that. It will be removed in Shlink v3.0.0

My guess is that it is picking `null` as a string.

**Comment by vijai1996** [comment]
Works in json. Probably the docs should be updated then? That only json requests are supported?

**Comment by acelaya** [comment]
In fact, only `application/json` requests are documented, but I will make it more explicit to avoid future confusions.

Thanks for pointing this out.
