### ISSUE TITLE
APCU still needed with PHP7?

### ISSUE THREAD

**Issue by ToeiRei** [shlinkio/shlink#78]
As of PHP7 I would use the built-in OPcache instead of pulling in another dependency.

**Comment by acelaya** [comment]
The APCu is the user cache, while the OPcache is used to cache compiled files.
You can use the OPcache, of course, but the APCu adapter is still needed to store custom chunks of data.
In Ubuntu-based OS with PHP7 I've installed APCu using the `php-apcu` package name.
