### ISSUE TITLE
Multi-domain not redirecting correctly

### ISSUE THREAD

**Issue by Har-Kuun** [shlinkio/shlink#786]
#### How Shlink is set-up

* Shlink Version: 2.2.1
* PHP Version: 7.4.3
* How do you serve Shlink: Self-hosted Swoole behind Nginx reverse proxy
* Database engine used: MariaDB 10.3.22
* System version: Ubuntu 20.04 LTS 64 bit
* Everything is on HTTP; no HTTPS traffic involved.

#### Summary

Multi-domain not redirecting correctly.  All short URLs created under non-main domain names run into 404.

#### Current behavior

Let say my main domain name is domain.com, and I have domain2.com CNAME-pointed to domain.com.
When I create a link under domain.com, e.g., domain.com/link1, both domain.com/link1 and domain2.com/link1 redirects to the correct long url.  This is expected.
However, when I create a link under domain2.com, e.g., domain2.com/link2, both domain2.com/link2 and domain.com/link2 redirects to 404 not found.  

#### Expected behavior

As described in Current Behavior section, domain2.com/link2 should direct to its correct URL instead of 404 not found.

#### How to reproduce

I used the standard setup procedure documented in the shlink.io website.  Since Swoole runs on 8080, I added nginx reverse proxy to set up port 80 access.  In order to catch all domain names that are pointed to this server, the Nginx conf file for this instance is like this:

```
        server {

                listen 80 default_server;
                listen [::]:80 default_server;
                server_name _;
                root /srv/www/shlink/proxy;
                error_log /var/log/nginx/shlink.error;
                access_log /var/log/nginx/shlink.access;
                location / {
                        proxy_pass http://my_ip_address:8080;
                }
                index index.php index.html index.htm index.nginx-debian.html;

        }
```

Thank you!  Let me know if you need any more details.

**Comment by acelaya** [comment]
I'm not being able to reproduce this. I have several URLs created in multiple domains which are working as expected.

How did you create the URL in domain2? What arguments did you pass? Are you using shlink-web-client?

**Comment by Har-Kuun** [comment]
Thank you for your reply!  I am using shlink-web-client passing only "longUrl" and "domain" arguments; I also tried to pass"customSlug" argument and that didn't work as well.

The log file showing the link creation and link visit are listed below.

```
[2020-06-09T16:41:16.430068+02:00] [24567804-c19f-4320-88b7-0ce8cbe246d9] Access.INFO - 127.0.0.1 - - "OPTIONS /rest/v2/short-urls HTTP/1.0" 204 -
[2020-06-09T16:41:16.680174+02:00] [95970bac-0306-4e79-96de-0b237474501f] Access.INFO - 127.0.0.1 - - "POST /rest/v2/short-urls HTTP/1.0" 200 245
[2020-06-09T16:41:21.757316+02:00] [NULL] Access.ERROR - 127.0.0.1 - - "GET /IvBqE HTTP/1.0" 404 954
```

Thank you!

**Comment by Har-Kuun** [comment]
Well, I kind of find the issue; it seems that I have to pass the "domain" argument in the form of domain2.com:8080, because Swoole listens to 8080 port.  Then, the domain2.com:8080/link2 does successfully redirect to the correct long URL, though domain2.com/link still redirects to 404.

**Comment by Har-Kuun** [comment]
Removing the Nginx reverse proxy and making Swoole listen to 80 finally solved this issue.

**Comment by acelaya** [comment]
Ok, I see what the issue is. I also have my shlink instance behind an nginx acting as a reverse proxy.

You need to make sure nginx forwards the Host header, otherwise shlink will never know from where the request is coming.

```nginx
location /some/path/ {
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_pass http://localhost:8000;
}
```

The fact that it worked before with port 8080 is because you were bypassing the nginx in that case and going directly to Shlink.

You would also need to pass a few other headers, to ensure geolocation works as expected.
