### ISSUE TITLE
install --no-interaction how to submit values ?

### ISSUE THREAD

**Issue by gohlink** [shlinkio/shlink#788]
#### How Shlink is set-up

* Shlink Version: 2.2.1
* PHP Version: 7.4.6

#### Summary

Hello, first of all thanks for your work on this very nice project. I have been using it for a few days and I really enjoy it. 

I am deploying shlink with the dist archive. I am facing a problem with install with --no-interaction. How is it meant to be used ? Should i create a file containing some config (something like generated_config.php) or maybe I need to use it with arguments ?

When i just set ./install -- no-interaction i get the folowing error :
`PHP Fatal error:  Uncaught TypeError: Return value of Shlinkio\Shlink\Installer\Config\Option\Database\DatabaseUserConfigOption::askRequired() must be of the type string, null returned in /opt/shlink/vendor/shlinkio/shlink-installer/src/Util/AskUtilsTrait.php:20
Stack trace:
#0 /opt/shlink/vendor/shlinkio/shlink-installer/src/Config/Option/Database/DatabaseUserConfigOption.php(22): Shlinkio\Shlink\Installer\Config\Option\Database\DatabaseUserConfigOption->askRequired(Object(Symfony\Component\Console\Style\SymfonyStyle), 'username', 'Database userna...')
#1 /opt/shlink/vendor/shlinkio/shlink-installer/src/Config/ConfigGenerator.php(58): Shlinkio\Shlink\Installer\Config\Option\Database\DatabaseUserConfigOption->ask(Object(Symfony\Component\Console\Style\SymfonyStyle), Object(Shlinkio\Shlink\Config\Collection\PathCollection))
#2 /opt/shlink/vendor/shlinkio/shlink-installer/src/Command/InstallCommand.php(77): Shlinkio\Shlink\Installer\Config\ConfigGenerator->generateConfigInteractively(Object(Symfony\Component\Console\Style\Symfon in /opt/shlink/vendor/shlinkio/shlink-installer/src/Util/AskUtilsTrait.php on line 20`

**Comment by acelaya** [comment]
The install tool is meant to be used on an interactive way, so running it with `--no-interaction` is not yet supported.

**Comment by gohlink** [comment]
Allright, thanks for your answer
