### ISSUE TITLE
Enable multi-arch docker image builds somehow

### ISSUE THREAD

**Issue by acelaya** [shlinkio/shlink#791]
A contributor added support to the project to [build multi-arch docker images](https://github.com/shlinkio/shlink/pull/756). However, after the PR was merged, it had to be disabled, as it was slower than the maximum build time allowed by travis.

Look for some way to get it back and take advantage from all the work done by this contributor.

**Comment by MarcHagen** [comment]
You could look into Github Actions ?

Job execution time - Each job in a workflow can run for up to 6 hours of execution time
Workflow run time - Each workflow run is limited to 72 hours

https://docs.github.com/en/actions/getting-started-with-github-actions/about-github-actions

**Comment by acelaya** [comment]
Yes, that's one of the options I want to explore.

**Comment by acelaya** [comment]
This article explains how to enable multi-arch building with github actions https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/
