### ISSUE TITLE
Geolite & API Key

### ISSUE THREAD

**Issue by matbe81** [shlinkio/shlink#800]
#### How Shlink is set-up

* Shlink Version: 2.2.2
* PHP Version: 7.1
* How do you serve Shlink: Self-hosted Apache|Self-hosted nginx|Self-hosted swoole|Docker image
* Database engine used: MySQL|MariaDB|PostgreSQL|MicrosoftSQL|SQLite (x.y.z)

#### Summary

Dear,

1)I can’t get the geolite licence key from maxmind (I don’t receive their supposed emails)
2) When i'll get it, how to setup the api key when the installation is already made on a classic web server?

Thank you!

**Comment by acelaya** [comment]
1) Have you checked your spam folder?

If it's not there, I would recommend checking maxmind's FAQ or directly contact them https://support.maxmind.com/

2) When you say "setup", do you mean what are you supposed to do with the API key, or how to get it. Or both, haha.

BTW, the project requires PHP 7.4, it won't work with v7.1

**Comment by matbe81** [comment]
Dear,

I upgraded my server to 7.4. Working fine.

1) I'll do that.

One additional point: should I setup a cron task to location IP address? Location is unknown in my statistics.

2) I want to know how to instruct my instance of Shlink to use my API key.

**Comment by acelaya** [comment]
Yes, you need to create a cronjob https://shlink.io/documentation/long-running-tasks/

The API key has to be sent to Shlink on every request to rest endpoints, in the X-Api-Key header https://shlink.io/documentation/api-docs/authentication/

**Comment by matbe81** [comment]
Thank yo for the cron job.

I'm speaking about the MaxMind API?

**Comment by matbe81** [comment]
Thank yo for the cron job. But when trying to run manually, I hot this error:

```
[ERROR] Error opening database file (/home2/xxx/config/autoload/../../data/GeoLite2-City.mmdb) . Is this a valid MaxMind DB file?
Should I put a file manually?
```

Regarding the API, I'm speaking about the MaxMind API?

**Comment by acelaya** [comment]
Oh, you meant what to do with GeoLite's license key. Sorry, I didn't get it.

Everything is explained in the docs https://shlink.io/documentation/geolite-license-key/#provide-the-license-key-to-shlink

**Comment by matbe81** [comment]
I read this page.

`In other cases, you will be asked to provide the license key when installing or updating Shlink.`

But should I proceed with full reinstall as I ran the latest version, there is no update available?

**Comment by acelaya** [comment]
How to update is explained here https://shlink.io/documentation/update-your-instance/#updating-a-self-hosted-instance.

**Comment by matbe81** [comment]
Just tries to make an update while importing previous config to avoid having to retype eveyrhing and making potential mistakes, but it didn't ask me for API key:

`[nanobe@risotto xxx]$ bin/update

 Welcome to Shlink!!
 This tool will guide you through the installation process.

 Do you want to import configuration from previous installation? (You will still be asked for any new config option that did not exist in previous shlink versions) (yes/no) [yes]:
 >

 Previous shlink installation path from which to import config:
 > /xxx

 Provided path does not seem to be a valid shlink root path. Do you want to try another path? (yes/no) [yes]:
 >

 Previous shlink installation path from which to import config:
 > /home2/nanobe/xxx

 Custom configuration properly generated!

Updating database... Success!
Generating proxies... Success!
Clearing entities cache... Success!


 [OK] Installation complete!


[nanobe@risotto xxx]$
`

**Comment by acelaya** [comment]
Oh, ok. You meant how to update the GeoLite2 license key, not how to update shlink.

Unfortunately there's no way to update specific configuration options yet (it's something I want to implement), so you will have to edit the generated config file manually.

Inside the project, open the config/params/generated_config.php file, and add this:

```php
return [
  'geolite2' => [
    'license_key' => 'YOUR_LICENSE_KEY'
  ],
];
```

Be very careful not to delete other entries, but instead just add that together with the rest.

I assume by other tickets you opened, that you have basic PHP knowledge as to be able to edit that file without introducing a syntax error, hehe.

**Comment by matbe81** [comment]
Thank you.

No problem for PHP.

Only issue with cron;

I get this email reporting:
`Shlink 2.2.2

Usage:
  command [options] [arguments]

Options:
  -h, --help            Display this help message
  -q, --quiet           Do not output any message
  -V, --version         Display this application version
      --ansi            Force ANSI output
      --no-ansi         Disable ANSI output
  -n, --no-interaction  Do not ask any interactive question
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Available commands:
  help                Displays help for a command
  list                Lists commands
 api-key
  api-key:disable     Disables an API key.
  api-key:generate    Generates a new valid API key.
  api-key:list        Lists all the available API keys.
 db
  db:create           Creates the database needed for shlink to work. It will do nothing if the database already exists
  db:migrate          Runs database migrations, which will ensure the shlink database is up to date.
 short-url
  short-url:delete    Deletes a short URL
  short-url:generate  Generates a short URL for provided long URL and returns it
  short-url:list      List all short URLs
  short-url:parse     Returns the long URL behind a short code
  short-url:visits    Returns the detailed visits information for provided short code
 tag
  tag:create          Creates one or more tags.
  tag:delete          Deletes one or more tags.
  tag:list            Lists existing tags.
  tag:rename          Renames one existing tag.
 visit
  visit:locate        Resolves visits origin locations.
X-Powered-By: PHP/7.4.7
Content-type: text/html; charset=UTF-8
`
Command is:

`php /home2/path/bin/cli visit:locate -q `

I also still get the error of MaxMing DB file.

Any idea?

**Comment by matbe81** [comment]
Strange as the file is correctly located.

![0](https://user-images.githubusercontent.com/8006424/86240177-f81c7f00-bba0-11ea-95ed-4cb3be74779c.png)

**Comment by matbe81** [comment]
Strange as the file is correctly located.

![0](https://user-images.githubusercontent.com/8006424/86240222-11253000-bba1-11ea-81d6-2b2951b6f796.png)

**Comment by acelaya** [comment]
The file error is most probably die to permissions.

Probably the system user used to run shlink does not have permissions to read that, as it was downloaded from the CLI, most probably with another user.

**Comment by matbe81** [comment]
664. Correct?

**Comment by acelaya** [comment]
Yes, exactly.

I will try to make the file be generated with more permissions, although that may not be possible.

For now, make sure both users belong to the same group.

**Comment by matbe81** [comment]
The point is i didnt changed the permission. The file got 664 and doesn't work. ALso, I have only 1 user set on my hosting and always use the same.

**Comment by matbe81** [comment]
Can you please re-open the case as it's not solved.
