### ISSUE TITLE
Manage shortcodes dynamically from PHP

### ISSUE THREAD

**Issue by matbe81** [shlinkio/shlink#801]
Dear,

I went to know how to dynamically create and maintain shortcodes using PHP.
My need is for another web site than the one hosting Shlink
Should I directly connect to the database of should I do curl calls? What format?

Uses cases:
- Check if a shortcode to a specified url with a specified slug already exist and create it if not.
- Get the number of visite of a specified url/slug
- Get the total visit of a speicifed tag

Thank you;

**Comment by acelaya** [comment]
For integrations, the best approach is using the REST API https://api-spec.shlink.io/

Everything you describe can be done using it.

**Comment by matbe81** [comment]
Dear,

I can make get call.. But unable to post.

Here is my code. Any idea?

`function shlink_shorturl_call(){
	
	$data_array=array();
	
	$response = shlink_query(array(
									"type" => "post",
									"command" => "short-urls",
									"argument" => array(
											"longUrl"		=> "<long url here>",
											"customSlug"	=> "<slug here>",
											"tags"			=> array(
																	"<tag here>",
																),
											"findIfExists" 	=> true,
									),
	));
	
	e($response);
	
}


function shlink_query($data_array){
	
	// https://api-spec.shlink.io/#/Short%20URLs/listShortUrls
	
	// $type: get|post
	
	$curl = curl_init();
	$opts = shlink_load_options($data_array);
	
	curl_setopt_array($curl, $opts);
	$response = curl_exec($curl);
	
	e($opts);
	e($response);
	
	curl_close($curl);
	
	return $response;
	
}


function shlink_load_options($data_array){
	
	global $shlink;

	$opts = array(
		CURLOPT_SSL_VERIFYPEER => true,
		CURLOPT_HTTPHEADER     => array(
										"accept: application/json",
										"X-Api-Key: ".$shlink['api-key'],
									   ),
		CURLOPT_URL            => $shlink['api-url'].$data_array["command"].(count($data_array["argument"])>0?"?":"").http_build_query($data_array["argument"]),
		CURLOPT_RETURNTRANSFER => true,
		CURLOPT_TIMEOUT        => 30,
		CURLOPT_CONNECTTIMEOUT => 30
	);
	
	if ($data_array["type"] == "post"){
		$opts = array_merge_recursive($opts,array(
			CURLOPT_HTTPHEADER	=> array(
										"Content-Type: application/json",
										 ),
			CURLOPT_POST        => true,
			CURLOPT_POSTFIELDS  => http_build_query($data_array["argument"]),
							   ));
	}
	
	return $opts;
}`
