### ISSUE TITLE
Duplicate created while using parameter findIfExists = true

### ISSUE THREAD

**Issue by matbe81** [shlinkio/shlink#803]
#### Summary

I execute the same code providing longUrl, tags and findIfExists as true, as documented [here](https://api-spec.shlink.io/#/Short%20URLs/createShortUrl).

#### Current behavior

It create new shortcode undefinitely.

#### Expected behavior

It shoud reject my second request as another shortcode with same url and tags already exists and provide me the latest one.

#### How to reproduce

`Array
(
    [10002] => https://xxx/rest/v2/short-urls
    [64] => 1
    [19913] => 1
    [13] => 30
    [78] => 30
    [10023] => Array
        (
            [0] => accept: application/json
            [1] => X-Api-Key: xxx
            [2] => Content-Type: application/json
            [3] => Content-Length: 169
        )

    [47] => 1
    [10015] => {"longUrl":"https:\/\/xxx\/url\/","tags":["tag1","tag2"],"findIfExists":true}
    [42] => 
    [44] => 
)`

Results:

`Array
(
    [shortCode] => bpMQZ
    [shortUrl] => http://xxx/bpMQZ
    [longUrl] => https://url/
    [dateCreated] => 2020-07-01T08:29:51+02:00
    [visitsCount] => 0
    [tags] => Array
        (
            [0] => tag1
            [1] => tag2
        )

    [meta] => Array
        (
            [validSince] => 
            [validUntil] => 
            [maxVisits] => 
        )

    [domain] => 
    [httpcode] => 200
)`

**Comment by acelaya** [comment]
Are you sure it is creating new short URLs on every request, or is it returning the same one every time.

When you pass findIfExists with value true, what shlink does is returning any existing short URL that matches provided params. If it does not find any, it creates a new one.

**Comment by matbe81** [comment]
Yes, another shortcode is created.

The issue is exactly that it create a new one except returning the already existing one.

**Comment by acelaya** [comment]
Ok, I will try to reproduce it this afternoon.

**Comment by matbe81** [comment]
Thanks. I stay at your disposal to show your my code.

**Comment by acelaya** [comment]
I'm not being able to reproduce this. For me it is working as expected on every try.

Could you provide some test cases reproducing the issue?

The project includes some E2E and unit tests covering this feature that you can use as an example.

* https://github.com/shlinkio/shlink/blob/develop/module/Rest/test-api/Action/CreateShortUrlActionTest.php
* https://github.com/shlinkio/shlink/blob/develop/module/Core/test/Service/UrlShortenerTest.php#L162

**Comment by matbe81** [comment]
Dear Alejandro,

Sorry, but i don’t have the time for that. I’m 100% sure of the problem and have implemented my own script to check if the link exist before creating it again.

Please find my code below:

`function shlink_shorturl_call(){
	$response = shlink_shorturl_create("xxx", "", array("tag1", "tag2"));
	
	e(($response["httpcode"] == 200)?"Success:".$response["shortCode"]:"Failure");
}

function shlink_shorturl_create($longurl, $slug="", $tags=array()){
	
	$option_array = array(			"type" 	 	=> "post",
									"command" 	=> "short-urls",
									"payload" 	=> array(
										 	"customSlug" 	=> $slug,
											"longUrl"		=> $longurl,
											"tags"			=> $tags,
											"findIfExists" 	=> true,
									),
						  );
				
	// Cleaning array
	if (empty($slug)) unset($option_array['payload']["customSlug"]);
	
	$already_exists = shlink_shorturl_exists($option_array);
	
	if ($already_exists) return "already_exists";
		
	$response = shlink_query($option_array);
	
	e($response);
	
	return ($response);
}


function shlink_query($data_array){
	
	// https://api-spec.shlink.io/#/Short%20URLs/listShortUrls

	
	$curl = curl_init();
	$opts = shlink_load_options($data_array);
	
	curl_setopt_array($curl, $opts);
	$response = curl_exec($curl);
	$httpcode = curl_getinfo($curl, CURLINFO_HTTP_CODE);
	e($opts);
	//e($response);
	//e(json_decode($response, true));
	
	curl_close($curl);
	
	return array_merge(json_decode($response, true),array("httpcode" => $httpcode));
	
}


function shlink_load_options($data_array){
	
	global $shlink;

	$data_array["payload"]["domain"] = $shlink["domain"];
	$data_array["payload"]["shortCodeLength"] = $shlink["shortCodeLength"];
	
	//e($data_array);
	
	$opts = array(
		CURLOPT_URL            => $shlink['api-url'].$data_array["command"].($data_array["type"] == "get"?(count($data_array["payload"])>0?"?":"").http_build_query($data_array["payload"]):""),

		CURLOPT_SSL_VERIFYPEER => true,
		CURLOPT_RETURNTRANSFER => true,
		CURLOPT_TIMEOUT        => 30,
		CURLOPT_CONNECTTIMEOUT => 30,
	);
	
	if ($data_array["type"] == "get"){

		$opts = (array)$opts + array(
				CURLOPT_HTTPHEADER     => array(
										"accept: application/json",
										"X-Api-Key: ".$shlink['api-key'],
									   ),
		);
		
	}elseif ($data_array["type"] == "post"){
		$opts = (array)$opts + array(
			CURLOPT_HTTPHEADER     => array(
										"accept: application/json",
										"X-Api-Key: ".$shlink['api-key'],					
										"Content-Type: application/json",
										"Content-Length: ".strlen(json_encode($data_array["payload"])),
										 ),
			CURLOPT_POST        => true,
			CURLOPT_POSTFIELDS  => json_encode($data_array["payload"]),
			CURLOPT_HEADER		   => false,
			CURLOPT_NOBODY 		   => false,
							   );
	}
	
	return $opts;
}

function shlink_shorturl_exists($data_array){
	
	$response = shlink_shorturl_count($data_array);
	return ($response>0?true:false);

}

function shlink_shorturl_count($data_array){

	$response = shlink_query(array(
										"type" => "get",
										"command" => "short-urls",
									    "payload" => array(
											"searchTerm" => $data_array['payload']['longUrl'],
										),
	));
	
	
	//e($response);
	
	return count($response["shortUrls"]["data"]);

}`

**Comment by acelaya** [comment]
Try not sending an empty custom slug.

If you don't want to provide a custom slug, don't send it, or it can have weird side effects.

And I'm closing this issue. In sure you understand I also have other things to do, and can't test everyone else's code.

The feature works, I'm also sure about that, as it's covered my multiple tests.

There can obviously be edge cases while sending inconsistent data, but that's something you need to take care about.
