### ISSUE TITLE
API Key expiration

### ISSUE THREAD

**Issue by loelkes** [shlinkio/shlink#805]
#### How Shlink is set-up

* Shlink Version: 2.2.1
* PHP Version: 7.4.7
* How do you serve Shlink: Self-hosted nginx
* Database engine used: MariaDB

#### Summary
 
* How can I set an expiration date for API Keys?
* Will disabled or expired keys be listed forever or do they vanish after some time?

Is this some undocumented features? Otherwise I could/would open a PR for the website/docs and specify it there.

Related to #72

**Comment by acelaya** [comment]
You are absolutely right, this needs to be documented.

The way you generate an api-key that expires is by providing the expiration date while generating it:

```bash
> shlink api-key:generate -h
Description:
  Generates a new valid API key.

Usage:
  api-key:generate [options]

Options:
  -e, --expirationDate=EXPIRATIONDATE  The date in which the API key should expire. Use any valid PHP format.
  -h, --help                           Display this help message
  -q, --quiet                          Do not output any message
  -V, --version                        Display this application version
      --ansi                           Force ANSI output
      --no-ansi                        Disable ANSI output
  -n, --no-interaction                 Do not ask any interactive question
  -v|vv|vvv, --verbose                 Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug
```

**Comment by acelaya** [comment]
Hey @loelkes, I have just documented the feature https://shlink.io/documentation/api-docs/authentication/#managing-api-keys

Thanks for noticing it.

**Comment by loelkes** [comment]
Thanks. What about expired or deactivated keys, do they stay there forever?

**Comment by acelaya** [comment]
Yes, currently they are not fully deleted.
