### ISSUE TITLE
[Question] preparing for PHP 8

### ISSUE THREAD

**Issue by MartinH0** [shlinkio/shlink#810]
Just wanted to ask if tests are already done with PHP 8 (alpha 1 or 2) and if Shlink will profit from the new PHP 8 JIT functionality?

As [alpha 2](https://www.php.net/archive/2020.php#2020-07-09-1) is already available and alpha 3 will be available from tomorrow maybe this will bring some new possibillities to Shlink. Like just-in-time lookups from IPs or other things.

**Comment by acelaya** [comment]
I'm not yet testing against PHP 8, as many of the third party dependencies are not yet ready and builds fail.

As of JIT, I still have to investigate the implications. No work has been done yet on that regards.

**Comment by acelaya** [comment]
Just noticed you mentioned the use of JIT for IP lookups, but I don't see how would that get any benefit from JIT 🤔

**Comment by acelaya** [comment]
I have just enabled builds on PHP nightly versions, and the first thing that fails is the installation of pdo_sqlsrv extension.

https://travis-ci.org/github/shlinkio/shlink/jobs/711122126

**Comment by acelaya** [comment]
I'm closing this for now, as I understand the question was answered.

Feel free to open new issues if needed 🙂
