### ISSUE TITLE
Feature request: Granular permissions per API key

### ISSUE THREAD

**Issue by ScrumpyJack** [shlinkio/shlink#811]
It would be nice to be able to make API key a resource, and when generating, assign permissions, such as return 200 checks, max visits per link, force expiry, etc.

**Comment by acelaya** [comment]
I'm not sure if I follow.

Do you mean being able to set what resources can be accessed with every API key? Like for example, creating an API key that can be used to list short URLs bit not create new ones.

If that's the case, there's already a feature request pending implementation https://github.com/shlinkio/shlink/issues/150

**Comment by ScrumpyJack** [comment]
I'm sorry, I should have been more specific. I'll close this and open a proper feature request

**Comment by acelaya** [comment]
Don't worry. I just wanted to make sure I was understanding it properly :-)
