### ISSUE TITLE
Custom Analytics/Pixels

### ISSUE THREAD

**Issue by lazmo88** [shlinkio/shlink#814]
First of all, huge thank you for great project! It's very well thought out and feature set is already very extensive. 

One enhancement that could be useful for many marketers would be option to add custom pixels/analytics scripts into the short urls. These pixels would be loaded/visits would be tracked before initiating the redirect function.

There are services such as getpixelme.com that does this, but their product is not as complete as yours.

How this could be implemented? 
In settings you could create pixels, by specifying the platform and entering the pixel ID. Alternatively you could also enter custom script including the whole script tag.

These saved pixels, could then be attached to short links when they are created and loaded up when visitor uses a link.

These pixel powered short links are especially great for social media, as you can share 3rd party content and still track and create custom retargeting audiences.

**Comment by acelaya** [comment]
So let me see if I get it.

The idea is that you define where the short URL has to redirect depending on the social media the user is coming from?

**Comment by lazmo88** [comment]
> So let me see if I get it.
> 
> The idea is that you define where the short URL has to redirect depending on the social media the user is coming from?

Not exactly, having option to add remarketing pixels to redirect pages is purely paid remarketing tool. Let's say I shorten a link to this Github issue and I would share it on Facebook. Now, normally, you can't really do remarketing to these people who clicked your link, unless there was a Facebook Pixel/Google Ads tag on that redirect page 😉 If such feature would exist, people clicking my link from Facebook, would be added to my remarketing list. Great, now I can run targeted ads to these people visiting the link without the need of having control over the final landing page.

This allows you to use any content available in the internet, drive traffic to 3rd parties, while testing and segmenting your audience to different remarketing lists. 

There is one important consideration as privacy laws has been changing rapidly. You should receive consent from the user before running the remarketing pixels. Pretty much standard GDPR style "allow" modal/popup.

**Comment by acelaya** [comment]
Hey.

I'm reviewing older issues and I have realized we left this one here and I forgot about it.

I was reading the comments again and took a second look to this pixelme project, because back in the day I didn't fully understand what was requested here.

I think I understand it now. Let me confirm.

So basically what you want is being able to configure the short links in a way that, instead of directly returning an http redirect (301/302 + Location header), they actually return a "page" where you can configure arbitrary JavaScript to be run, like Google analytics and similars, and only after those have been run, then you redirect the user to the destination.

Am I right?

**Comment by JamiNishelle** [comment]
Hi @acelaya!  I'm interested in implementing this feature. Would a well-designed 
   pull request with tracking pixel support be accepted?

**Comment by acelaya** [comment]
> Hi @acelaya!  I'm interested in implementing this feature. Would a well-designed 
>    pull request with tracking pixel support be accepted?

If by "this feature", you mean what I was trying to confirm in my last comment above, then no, as I consider this out of Shlink's scope.

I think it makes more sense to combine Shlink with other products dedicated to this, instead of trying to bloat Shlink with more features.
