### ISSUE TITLE
SAML Support

### ISSUE THREAD

**Issue by elliot-labs** [shlinkio/shlink#816]
#### Summary

Hi Team,

I would love it if this app had SAML support.
That would allow it to tie into things like AD FS or Azure Active Directory for authentication allowing for identity centralization and use by enterprises/governments.
Heck if it has direct AAD integration, that would be even better.

Thanks!

**Comment by acelaya** [comment]
I'm afraid I have to say no to this.

Those are end user authentication mechanisms, while shlink is an API with no user concept involved.

Usually, in contexts in which you need such kind of authentication, there are middle layers handling it and providing access to APIs for end users.

Trying to handle this inside shlink itself would introduce a lot of complexity for a relative edge case, and as I mentioned, I also don't think the API is the proper place to handle it.
