### ISSUE TITLE
shlink behind a Nginx reverse proxy (as subdomain)

### ISSUE THREAD

**Issue by Shimakuchi** [shlinkio/shlink#825]
#### How Shlink is set-up

* Shlink Version: (DockerHub) shlinkio/shlink:latest
* PHP Version: -
* How do you serve Shlink: Self-hosted as an Docker image within [Unraid](https://unraid.net). Behind a Nginx Proxy
* Database engine used: -

#### Summary

As I described above, I am running shlink (and the web client) an my Unraid server as an Docker Container. I would like to access the shlink service trough a subdomain. I found the following on [GitHub. There are many config files](https://github.com/linuxserver/reverse-proxy-confs) for using apps behind a Nginx reverse proxy. Maybe some do have such a configuration fiel for me?

**Comment by acelaya** [comment]
I'm hosting myself both Shlink and shlink-web-client behind an nginx reverse proxy, so I can probably help sharing my config:

For Shlink I have this:

```nginx
server {
    # ...

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://localhost:1234;
        proxy_read_timeout 90s;
    }
}
```

It's important that you forward both the `Host` and the real visitor's IP as shown there.

The first one will be used if at some point you need to serve multiple domains with the same Shlink instance. Not forwarding the hostname would make Shlink not properly detect what domain is being visited.

The second one is used to geolocate vists. If you don't forward the visitor's IP, Shlink will think all visits come from the same location.

For shlink-web-client I have this one:

```nginx
server {
    # ...

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://localhost:5678;
        proxy_read_timeout 90s;
    }
}
```

It's more or less the same, but in this case most of the headers are not really needed, as the web client is basically a client-side app.

With those configs you can configure every virtual host with whatever domain or subdomain you want. Event multiple domain names for each one should work.

**Comment by acelaya** [comment]
Hey @Shimakuchi, did that help? Is that what you needed?
