### ISSUE TITLE
Swoole error after upgrade to 2.3.0 while using self-hosted Apache setup

### ISSUE THREAD

**Issue by viktorix** [shlinkio/shlink#827]
#### How Shlink is set-up

* Shlink Version: 2.3.0
* PHP Version: 7.4.7
* How do you serve Shlink: Self-hosted Apache
* Database engine used: MySQL

#### Summary

I upgraded Shlink from 2.2.2 to 2.3.0. The same process as before and ran the update command. Everything went smoothly and was successfully updated. But when I try to visit any short URLs I get 500 error and Shlink app won't connect to the API. The CLI version seems to be working. I can create, list URLs, etc.

The error log has the following error:

```
[Thu Aug 20 12:32:04.886974 2020] [fcgid:warn] [pid 30304] [client XXX.XXX.XXX.XXX:15781] mod_fcgid: stderr: PHP Fatal error:  Uncaught Swoole\\Exception: Swoole\\Http\\Server can only be used in CLI mode in /var/www/public/prt.link/public_html/vendor/mezzio/mezzio-swoole/src/HttpServerFactory.php:97
[Thu Aug 20 12:32:04.887038 2020] [fcgid:warn] [pid 30304] [client XXX.XXX.XXX.XXX:15781] mod_fcgid: stderr: Stack trace:
[Thu Aug 20 12:32:04.887047 2020] [fcgid:warn] [pid 30304] [client XXX.XXX.XXX.XXX:15781] mod_fcgid: stderr: #0 /var/www/public/prt.link/public_html/vendor/mezzio/mezzio-swoole/src/HttpServerFactory.php(97): Swoole\\Server->__construct()
[Thu Aug 20 12:32:04.887056 2020] [fcgid:warn] [pid 30304] [client XXX.XXX.XXX.XXX:15781] mod_fcgid: stderr: #1 /var/www/public/prt.link/public_html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(704): Mezzio\\Swoole\\HttpServerFactory->__invoke()
[Thu Aug 20 12:32:04.887065 2020] [fcgid:warn] [pid 30304] [client XXX.XXX.XXX.XXX:15781] mod_fcgid: stderr: #2 /var/www/public/prt.link/public_html/vendor/shlinkio/shlink-event-dispatcher/src/Async/TaskRunnerDelegator.php(16): Laminas\\ServiceManager\\ServiceManager->Laminas\\ServiceManager\\{closure}()
[Thu Aug 20 12:32:04.887074 2020] [fcgid:warn] [pid 30304] [client XXX.XXX.XXX.XXX:15781] mod_fcgid: stderr: #3 /var/www/public/prt.link/public_html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(739): Shlinkio\\Shlink\\EventDispatcher\\Async\\TaskRunnerDelegator->__invoke()
[Thu Aug 20 12:32:04.887083 2020] [fcgid:warn] [pid 30304] [client XXX.XXX.XXX.XXX:15781] mod_fcgid: stderr: #4 /var/www/public/prt.link/public_html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(743): Laminas\\ServiceManager\\ServiceManager->Laminas\\ServiceManager\\{closure}()
[Thu Aug 20 12:32:04.887106 2020] [fcgid:warn] [pid 30304] [client XXX.XXX.XXX.XXX:15781] mod_fcgid: stderr: #5 /var/w in /var/www/public/prt.link/public_html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php on line 772
```

Shlink is self-hosted with Apache, so I'm not sure why there is a Swoole error. Swoole is installed on this server. We initially tried setting it up, but ran into a problem and just went with Apache set up to keep things simple. Tried restarting Apache, didn't help.

Did I miss anything?

Thank you for you help.

**Comment by acelaya** [comment]
Te library I use to run shlink with swoole makes sure to enable it's integration only when the extension is detected.

I never took into consideration the use case in which swoole is installed and enable but you don't want to use it.

As a workaround, I would try disabling swoole extension, while I try to find a way to avoid the integration if you are not running with swoole even if it's installed.

**Comment by acelaya** [comment]
BTW, you will have to clean the config cache after disabling swoole, by deleting the data/cache/app_config.php file (just ignore this comment of the file does not exist).

**Comment by viktorix** [comment]
Thank you. That worked.

**Comment by acelaya** [comment]
Hey @viktorix, I think I have found out why this happened.

I have checked that the library used by shlink to hook-up with swoole makes sure the SAPI is cli and the extension is enabled, in order to enable the integration.

In your case, the extension was there, but the SAPI is not cli when runing it with Apache+mod_fcgid, therefore, it should have never been eneabled.

However, if you run any of shlink's CLI commands first, both conditions match, and the config could get cached including the integration, which makes subsequent web requests through Apache fail.

I'll check what's the best way to address this. Maybe having separeted config cache files for web and CLI executions, or disabling the cache completely for CLI.

**Comment by acelaya** [comment]
I have found a simple way to address this, by making sure the config is always cached on the first web request.

That will prevent the config cache file to be generated on any console command executed before it.

With this change, you should be able to serve shlink with Apache/nginx even if you have swoole installed and enabled.
