### ISSUE TITLE
SSL: wrong version number for https installation

### ISSUE THREAD

**Issue by sluge** [shlinkio/shlink#828]
#### How Shlink is set-up

* SHLINK_VERSION=2.2.2
* SWOOLE_VERSION 4.5.2
* PHP Version: 7.4.9
* How do you serve Shlink: Docker image
* Database engine used: SQLite 

#### Summary
Hello, I just deployed shlink docker container locally by command: 

```
docker run \
    --name my_shlink \
    -p 8080:8080 \
    -e SHORT_DOMAIN_HOST=shlink.mydomain.com \
    -e SHORT_DOMAIN_SCHEMA=https \
    shlinkio/shlink:stable
```
But using curl I got an error:
```
curl -v -H "X-Api-Key: A9cD9003-b7b4-1234-4321-124e8e121e0a"  -d '{"longUrl":"https://example.com"}' -H 'Content-Type: application/json' https://shlink.mydomain.com:8080/rest/v2/short-urls 
*   Trying shlink.mydomain.com...
* TCP_NODELAY set
* Connected to shlink.mydomain.com (shlink.mydomain.com) port 8080 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* error:1408F10B:SSL routines:ssl3_get_record:wrong version number
* Closing connection 0
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number

```
http works Ok. Is any additional setup required to make it work as https?

**Comment by acelaya** [comment]
In afraid that passing SHORT_DOMAIN_SCHEMA=https will not magically make it work with https, you still need to add a proper certificate.

Usually the best idea is to put shlink behind an nginx or similar and configure the HTTPS certificate there.

**Comment by sluge** [comment]
> Usually the best idea is to put shlink behind an nginx or similar and configure the HTTPS certificate there.
Hello @acelaya , Thanks a lot for your support.
Is any way to setup swooli for https usage? I can't find any info about it

**Comment by acelaya** [comment]
Swoole supports SSL out of the box, but you still have to provide the certificate, same as if you use any other means.

Take a look here https://www.swoole.co.uk/docs/modules/swoole-server/configuration, at the options prefixed with ssl_

In any case, I haven't tried those with shlink's docker image. I guess you could mount a volume or something. It should work, technically speaking, but I can't tell for sure.

My recommendation is that you put an nginx in front of shlink, configured as reverse proxy. That's what I do.

I know there are even modified nginx docker images, or other web servers like caddy, that come with the feature to transparently download a "let's encrypt" certificate for you, but I haven't tried those.

**Comment by sluge** [comment]
Hello @acelaya , Thanks a lot for your help. I'll try!
