### ISSUE TITLE
timezone support in shlink

### ISSUE THREAD

**Issue by sluge** [shlinkio/shlink#830]
#### How Shlink is set-up

How Shlink is set-up
SHLINK_VERSION=2.2.2
SWOOLE_VERSION 4.5.2
PHP Version: 7.4.9
How do you serve Shlink: Docker image
Database engine used: SQLite

#### Summary

Hello, I did the following request: 
`curl -v -H "X-Api-Key: API_KEY"  -d '{"longUrl":"http://example.com", "validUntil":"2020-09-04T07:35:00+00:00"}' -H 'Content-Type: application/json'  https://shlink.mydomain.com/rest/v2/short-urls`

The` validUntil` is 5 minutes ahead of my current time, and after 5 minutes I got 
`Oops!
This short URL doesn't seem to be valid.
Make sure you included all the characters, with no extra punctuation.`

But then I specify the timezone in `"validUntil":"2020-09-04T10:48:00+03:00"`, it doesn't work, i.e. after 5 minutes link is still valid. My timezone is '+3'. Should I always use UTC in `validUntil` timezone?

**Comment by acelaya** [comment]
The problem here is that when provided date is parsed and stored in the database, the timezone is lost, as this is not supported.

That makes that, when the link is visited, the date is considered to be in the timezone configured in PHP.ini, which is UTC for the docker image.
