### ISSUE TITLE
Badge for easy demo

### ISSUE THREAD

**Issue by kklin** [shlinkio/shlink#831]
#### Summary

As discussed out of band, it'd be helpful to have a way for users to demo shlink without having to install it locally themselves.

I'm tentatively imagining a GitHub badge that links to a [Blimp](https://kelda.io/blimp) service, which would boot the compose file for shlink. But I haven't gotten to dig into the details of shlink deployment yet.

The status right now is that I'm building a generic version of the Blimp demo badge, and then will look at setting it up for shlink specifically.

**Comment by acelaya** [comment]
Hey @kklin, is there any progress on this?
