### ISSUE TITLE
Instead of using port 8080 in Docker image, use the value of $PORT

### ISSUE THREAD

**Issue by darinpope** [shlinkio/shlink#832]
#### Summary

I've tried using the Docker image on both Heroku and Google Cloud Run. Both of these services expect to be able to inject the listener port into the container via the $PORT environment variable.

Instead of hardcoding the port to 8080, allow for the listener port to use the $PORT environment variable and then fall back to 8080 if there is no $PORT environment variable defined.

#### Supporting docs

- https://help.heroku.com/PPBPA231/how-do-i-use-the-port-environment-variable-in-container-based-apps
- https://cloud.google.com/run/docs/developing#code_requirements

Note:
- You can set a port for GCR, but since GCR's standard behavior is the same as Heroku's (read $PORT), it would be nice to have the $PORT environment variable available.

**Comment by acelaya** [comment]
Sounds good. It shouldn't be super hard to do.

**Comment by acelaya** [comment]
Hey @darinpope, I have just implemented this. Shlink 2.3.0 will support providing the `PORT` env var while running the docker image in order to change the port in which shlink listens.
