### ISSUE TITLE
Slowness when using findIfExists

### ISSUE THREAD

**Issue by lgjluis** [shlinkio/shlink#837]
> English translation by @acelaya 

Good afternoon.

I have performance issues with the "findIfExists=true" parameter. Estimated time can vary between 3 and 18 seconds. Applied command is:

Server: http://{Server IP}/rest/v2/short-urls
ParametERS: {longUrl: "http://www.prueba.com", findIfExists: true}
Database: MySQL.

Is there any configuration I can use to improve loading times?

---

> Original message in Spanish by @lgjluis

Buenas tardes,

Tengo problemas de lentitud con el parámetro "findIfExists=true". El tiempo estimado puede variar entre 3 a 18 segundos. El comando aplicado es:

Servidor: http://{IP Servidor}/rest/v2/short-urls
Parametros: {longUrl: "http://www.prueba.com", findIfExists: true}
Base de datos: MySQL.

Hay alguna configuración que pueda hacer para mejorar el tiempo de respuesta?

Saludos cordiales
Jose

**Comment by acelaya** [comment]
The purpose of this param is to avoid creating "duplicated" short URLs.

It's slower, as it needs to match existing URLs against provided data. However, providing just the longUrl shouldn't have a significant impact.

How many short URLs do you have in total?

What are the times when you do not provide this param?

**Comment by lgjluis** [comment]
How many short URLs do you have in total?

- More than 200 000 urls.

What are the times when you do not provide this param?

- Only when creating from a new url generated by an application.


The query to Mysql is for "Like" or =?. Is there a way to optimize that
query?


Saludos cordiales

José León

**Comment by acelaya** [comment]
> More than 200 000 urls

That's a big number, haha.

The longUrl is matched through strict equality, but it's not as simple as a query (or maybe yes, but I need to investigate a bit to determine the bottleneck).

I'll do some testing and get those numbers improved. Thanks for reporting it.

**Comment by acelaya** [comment]
I have found the root cause for these high times and fixed it. It should take milliseconds now regardless the amount of short URLs.

I just need to add a few more tests and will merge the fix.
