### ISSUE TITLE
Limit access to generate short URL by ip or domain 

### ISSUE THREAD

**Issue by lookingdown** [shlinkio/shlink#859]
* Shlink Version: 2.3.0
* PHP Version: 7.4.11
* How do you serve Shlink: Self-hosted swoole
* Database engine used: MySQL

Is there a built in way to limit access to "Create a short URL" POST/GET and PATCH (edit) by IP address?
like allowed ip addresses (ipaddress1, ipaddress2, ipaddress3) OR by domain.

The short urls are automatically generated in my case on the server for images and items, but are accesible from anywhere.

Thank for an awesome script..

**Comment by acelaya** [comment]
I'm afraid this is something not supported at the moment.

However, there's some work planned on this regards (see https://github.com/shlinkio/shlink/issues/795#issuecomment-695190408), but there are some things to take into consideration.

* First, accessing a short URL is not part of the API itself (only endpoints starting with `/rest` are), so it would be handled differently for POST/PATCH than GET (unless you mean the GET rest endpoint). However, there are already other limits that can be set to URLs (dates, max visits, etc), so it could be handled in a similar way.
* Second, limiting the access to a URL via domain or IP address, is not really reliable, as those values are set by the consumer. Yes, a standard browser will set those values and the user cannot change them, but I can easily create a HTTP client that easily bypasses those rules.
* Third, you could already achieve this by putting an nginx in front of your shlink instance and setting up some rules to ensure your short URLs, which are public by default, can only be visited from certain origins.

Let me know if that's waht you meant.

**Comment by lookingdown** [comment]
Thanks for the reply..
I run shlink on a swoole instance behind nginx so that's not a problem.. Was just curious.. for use in an admin panel that accesses shlink api to generate short urls for lots of items.. 
Works like a charm.. Thanks a lot.. :)
