### ISSUE TITLE
Backup database in Docker container or snapshot the entire Docker image?

### ISSUE THREAD

**Issue by AutomationRed** [shlinkio/shlink#861]
#### How Shlink is set-up

* Shlink Version: 2.3.0
* How do you serve Shlink: Docker image
* Database engine used: the one in the Docker image

#### Summary

First of all thank you for the great work. The software is really great. 

We will soon be using it productively. Now the question for me is how to make sure that if something goes wrong, the already shortened URLs can be imported again. 

Do I have to create an image of the Docker Container each time, or can I back up the database within the Docker Container? Or is this only possible when using an external database? 

These are a few topics that are important for us in the worst case. 

Best Regards
Andreas

**Comment by acelaya** [comment]
Hey!

For production environments I would strongly recommend using an external database, so that the image itself is stateless and you can update at will.

The SQLite one is only there for testing purposes, so that you can easily get shlink up and running.

**Comment by acelaya** [comment]
Oh, and thanks for the kind words 🙂

**Comment by AutomationRed** [comment]
All right, works perfect. Thanks for the fast support.
