### ISSUE TITLE
Support publishing updates in AMQP / RabbitMQ

### ISSUE THREAD

**Issue by mariotacke** [shlinkio/shlink#868]
Similar to: https://github.com/shlinkio/shlink/issues/524 but for RabbitMQ.

In lieu of a dedicated Mercure service in my infrastructure, I'd like to subscribe to changes and publish them to my message broker via an exchange on RabbitMQ. Would you be interested in supporting something like this?

Implementation wise, it could work similarly to the existing Mercure integration. All we'd have to provide is an AMQP connection string and an exchange. When provided, a publisher would connect to the broker and publish the same content it sends to Mercure to that exchange.

I find that Mercure is fairly new tech (I haven't heard about it until I started using shlink!) whereas RabbitMQ/AMQP is a well known enterprise tool.

What do you think?

---

https://github.com/php-amqplib/php-amqplib

**Comment by acelaya** [comment]
The reason to use Mercure was that it works over HTTP, which means you can have web clients subscribing to updates directly on it (shlink-web-client is the main consumer I had in mind).

It is also very easy to configure and very lightweight compared to RabbitMQ.

That said, it's true that RabbitMQ is well known technology, so I could implement an integration too.

**Comment by acelaya** [comment]
This feature is now implemented.

Starting with Shlink 2.10, it will be possible to configure a RabbitMQ server where Shlink will send real-time updates.

**Comment by gpuliyar** [comment]
I used RabbitMQ without SSL and it works beautifully. But with SSL it is not working. Is there a change in configuration to support `AMQPS` or is that feature not supported?
