### ISSUE TITLE
When using a standalone shlink docker container, what is the storage locations for API keys?

### ISSUE THREAD

**Issue by mcx808** [shlinkio/shlink#871]
I want to map them to persistent storage so they are not lost with each redeploy.

I see in portainer a default volume is created for  /etc/shlink/config/params but on my host machine the volume is empty.

**Comment by acelaya** [comment]
I'm afraid there's no way to persist the SQLite database on a volume.

For production, it is strongly recommended that you use an external database https://shlink.io/documentation/install-docker-image/#use-an-external-db

That will solve the problem.
