### ISSUE TITLE
Minimum GRANTs for MYSQL user

### ISSUE THREAD

**Issue by gradano-c4w** [shlinkio/shlink#876]
#### How Shlink is set-up

* Shlink Version: 2.3.0
* PHP Version: that inside docker image shlinkio/shlink:2.3.0
* How do you serve Shlink: docker-image
* Database engine used: MySQL

#### Summary

What are the minimum GRANTs that a mysql user must have in order to work correctly with shlink (including the GRANTs needed only for the creation of the schema)?

**Comment by acelaya** [comment]
It needs ALTER, CREATE, DROP, INDEX, LOCK TABLES, REFERENCES, SELECT, INSERT, DELETE and UPDATE.
