### ISSUE TITLE
Support CJK characters in short links

### ISSUE THREAD

**Issue by adan89lion** [shlinkio/shlink#896]
#### Summary

I've been running a HTTP directory server where some of the folders and files are in Korean / Hanja. I wanted to shorten them since they are quite long and then URL encoded links are very ugly. It would be a nice to support CJK characters.

Additional Info: 
#767 Here, people have been suggesting to support emojis to short links, might be relative.

**Comment by acelaya** [comment]
I guess that, if you request this it's because it throws some kind of error at the moment?

Can you share some combinations for me to test?

**Comment by adan89lion** [comment]
Hi,

Maybe the fault is on my end, I tried again with long links with CJK characters, it worked fine eventually. But short urls still don't support CJK characters.

For example:
https://google.com for https://go.example.com/구글
it shows ``An error occurred while creating the URL :(``

I'll change the title to Support CJK characters in short links to avoid misunderstanding to others.

**Comment by acelaya** [comment]
Yeah, the problem comes when providing a custom slug.

Those are validated against a regular expression which doesn't work with unicode characters.

As you guessed, it's the same as with emojis.

I need to investigate a bit further.

**Comment by acelaya** [comment]
I think I have found out a regexp that works with unicode characters :slightly_smiling_face: 

![image](https://user-images.githubusercontent.com/2719332/100863611-19a5cd80-3495-11eb-92a2-2d876294ce9d.png)

I need to check if it also covers emojis, but at least, this should be fixed with that.
