### ISSUE TITLE
Exclude validUntil from findIfExists

### ISSUE THREAD

**Issue by viniciusb** [shlinkio/shlink#897]
#### Summary

Shlink will always create a new link if we parse validUntil parameter with now() date. Is it possible to exclude validUntil parameter from check, when deciding if it should create a new link or reply with the latest one?

**Comment by acelaya** [comment]
Currently the findIfExists only matches existing URLs if everything you provide has the same vale. Therefore, if you pass a different value for validUntil every time, it won't throw a match.

It could of course exclude it, but that opens the door to many other combinations which could make the feature very hard to maintain.

**Comment by viniciusb** [comment]
Thank you for your quick answer. Can you point the piece of code to make this change at our installation? It's very important for us. Also, can you please send your donation link? I would like to contribute with your excellent work!

**Comment by acelaya** [comment]
I haven't tested it, but I think that, if you drop this `if` statement completely, it should work as you expect.

https://github.com/shlinkio/shlink/blob/develop/module/Core/src/Repository/ShortUrlRepository.php#L221

And as for the donation, I so much appreciate it :-)

You can make a donation here https://slnk.to/donate

**Comment by viniciusb** [comment]
It works. Thank you, will close this.
