### ISSUE TITLE
Add support for additional privacy-preserving features

### ISSUE THREAD

**Issue by Firehed** [shlinkio/shlink#898]
#### Summary

The current configuration options relating to end-user privacy are limited (as far as I can tell) to the following:
- `ANONYMIZE_REMOTE_ADDR`
- `DISABLE_TRACK_PARAM`

As a privacy advocate, I think it would be really beneficial if Shlink could be additionally configured in the following ways:
- Disable all tracking (the same behavior of `DISABLE_TRACK_PARAM` when enabled and the URL has the query param, but without needing to opt-in)
- Disable IP recording (`ANONYMIZE_REMOTE_ADDR` taken a step further; nulling it out entirely)
- Disable geolocation (continue to record IPs, anonymized or not, but do not resolve a corresponding `visit_location`)
- Disable tracking of referrer
- Disable tracking of user agent (a more anonymized UA version might also be welcome, but that sounds like a horrible parsing mess)

I'm personally not comfortable with holding on to even anonymized IP addresses, nor geolocation information, but I don't see any way to prevent these from being recorded unless I use DISABLE_TRACK_PARAM and make sure all links I send out include the relevant query parameter - and that's problematic because it (seems to) removes even basic but completely anonymous visit counting.

It's possible this is simply a documentation issue (I'm primarily using what's listed in the [docker env vars](https://shlink.io/documentation/install-docker-image/)). Assuming that's not the case, I can probably contribute at least some of the necessary changes if they'd be welcomed - though I'll ask that the maintainers specify any naming preferences up front.

Thanks!

**Comment by acelaya** [comment]
This definitely sounds like something nice to have. 

Having this granularity on deciding how much information should be tracked would make shlink useful for more people.

While this gets implemented, you can probably disable any kind of tracking by putting a reverse proxy in front of shlink and removing the sources holding this information, naming `user-agent` and `referer` headers, as well as `REMOTE_ADDR` env

**Comment by Firehed** [comment]
> you can probably disable any kind of tracking by putting a reverse proxy in front of shlink and removing the sources holding this information, naming user-agent and referer headers, as well as REMOTE_ADDR env

That's a great idea - thanks for the suggestion!

**Comment by acelaya** [comment]
This is how the new tracking configuration will look like 🙂 

The docker image will support the same options as env vars.

![image](https://user-images.githubusercontent.com/2719332/118357654-99bf7b80-b57b-11eb-98d5-93e5a4de564b.png)
