### ISSUE TITLE
Associate color to tag internally in Shlink instead of the web client

### ISSUE THREAD

**Issue by noook** [shlinkio/shlink#902]
#### Summary

I'd like to build an App in React Native where I would be able to perform all the REST actions, and something came accross my mind when I noticed that the colors associated to the tags are actually not saved in the database but stored client-side in localstorage.

Would adding a column in the database be doable / wanted ?

**Comment by acelaya** [comment]
Doable, yes. Wanted, I'm not so sure.

The color of the tag is something very tied to how it is displayed on a UI.

Shlink's API should not contain any of that. It should hold only the data model.

The fact that tags are colored in shlink-web-client doesn't mean they should be colored in all the contexts.

For example, bitly also supports tags, and they use always the same color in the UI.

Maybe at some point the design in shlink-web-client also dchandes in a way that those color don't make sense anymore. I don't want the API model to dictate how the UI should be.
