### ISSUE TITLE
Open API spec UI bug for QR code example

### ISSUE THREAD

**Issue by codaamok** [shlinkio/shlink#906]
#### How Shlink is set-up

* Shlink Version: x.y.z
* PHP Version: x.y.z
* How do you serve Shlink: Self-hosted Apache|Self-hosted nginx|Self-hosted swoole|Docker image
* Database engine used: MySQL|MariaDB|PostgreSQL|MicrosoftSQL|SQLite (x.y.z)

n/a

#### Summary

I think the "open API spec UI" is broken when trying out the QR code stuff. If I specify a size, the example `curl` command doesn't show `size` in the URI. I think this screenie demos what I probably fail at explaining:

![image](https://user-images.githubusercontent.com/6683266/99587744-6bece600-29e1-11eb-9be2-c7da3adbf945.png)

#### Current behavior

CURL command and request URL properties do not include `size` when a value is entered in the Size box

#### Expected behavior

CURL command and request URL properties to include `size` when a value is entered in the Size box

**Comment by acelaya** [comment]
You should probably report that to swagger UI project. I don't think there's much that can be done here.
