### ISSUE TITLE
Setting ANONYMIZE_REMOTE_ADDR=true has no effect

### ISSUE THREAD

**Issue by jakubgs** [shlinkio/shlink#916]
#### Setup

* Shlink Version: `2.4.1`
* PHP Version: `7.4.11`
* Self-hosted using Docker image
* Database engine used: PostgreSQL

#### Summary

I have `ANONYMIZE_REMOTE_ADDR=true` set but it has no effect.

#### Current behavior

I have it clearly set in my application container:
```
 > docker exec -it shlink-app sh
/etc/shlink # echo $ANONYMIZE_REMOTE_ADDR
true
```
And yet my database contains IPs of visitors:
```
 % d exec -it shlink-db psql -U shlink shlink -p 5434
psql (13.1)
Type "help" for help.

shlink=# select date,remote_addr from visits limit 4;
        date         | remote_addr  
---------------------+--------------
 2020-11-18 19:04:36 | 1.2.3.4
 2020-11-18 19:04:48 | 2.3.4.5
 2020-11-20 09:57:07 | 3.4.5.6
 2020-11-20 09:57:19 | 4.5.6.7
(4 rows)

shlink=# 
```

#### Expected behavior

It actually anonymizes remote addresses.

**Comment by acelaya** [comment]
Anonymizing the visitors addresses is the default behavior. You just need to pass that env var if you want to set it to false.

That said, anonymizing does not mean turning tracking off, but replacing the last octet from every IP address by a 0, which makes the IP address still geolocatable, but no longer considered personal data.

If you check, you'll notice all the addresses end by 0 when persisted in the database.

There are plans to have more granular control over what information is tracked (see https://github.com/shlinkio/shlink/issues/898), but for now, it is not possible to turn it off completely.
