### ISSUE TITLE
db:migrate failed on postgess from 2.3.0 to 2.4.1/2.4.2

### ISSUE THREAD

**Issue by levdad** [shlinkio/shlink#918]
#### How Shlink is set-up

* Shlink Version :2.3.0
* PHP Version: ---
* How do you serve Docker image
* Database engine used: PostgreSQL

#### Summary

When trying to update / run new container with latest version on existing db the migration fails on timeout.

log from container:

[2020-11-25T09:59:15.145559+00:00] [NULL] Shlink.INFO - Successfully acquired the "db:create" lock.
[2020-11-25T09:59:15.146758+00:00] [NULL] Shlink.INFO - Expiration defined for "db:create" lock for "90" seconds.
Updating database...
[2020-11-25T09:59:16.651031+00:00] [NULL] Shlink.INFO - Successfully acquired the "db:migrate" lock.
[2020-11-25T09:59:16.651497+00:00] [NULL] Shlink.INFO - Expiration defined for "db:migrate" lock for "90" seconds.

In Process.php line 1201:
                                                                               
  The process "'/usr/local/bin/php' 'vendor/doctrine/migrations/bin/doctrine-  
  migrations.php' 'migrations:migrate' '--no-interaction'" exceeded the timeo  
  ut of 60 seconds.                                                            
                                                                               

db:migrate

**Comment by acelaya** [comment]
Hey.

I have just started a new shlink 2.3.0 instance through docker, connected to a postgres DB. I have created a copule of links and tags, and then I have stoped the container, and started a new one with v2.4.1 connecting to the same postgres.

It has properly run the migrations and everything continued working.

Can you try running the command with the env var `SHELL_VERBOSITY=3`? It should in theory be more verbose on the output with that, and print the errors if any.

**Comment by levdad** [comment]
Hey,
thanks for your reply.

this is the result (same as above even with `SHELL_VERBOSITY=3`).

```
Status: Downloaded newer image for shlinkio/shlink:2.4.1
Creating fresh database if needed...
[2020-11-29T06:49:00.088200+00:00] [NULL] Shlink.INFO - Successfully acquired the "db:create" lock.
[2020-11-29T06:49:00.088522+00:00] [NULL] Shlink.INFO - Expiration defined for "db:create" lock for "90" seconds.
Updating database...
[2020-11-29T06:49:01.614024+00:00] [NULL] Shlink.INFO - Successfully acquired the "db:migrate" lock.
[2020-11-29T06:49:01.614472+00:00] [NULL] Shlink.INFO - Expiration defined for "db:migrate" lock for "90" seconds.

In Process.php line 1201:
                                                                               
  The process "'/usr/local/bin/php' 'vendor/doctrine/migrations/bin/doctrine-  
  migrations.php' 'migrations:migrate' '--no-interaction'" exceeded the timeo  
  ut of 60 seconds.                                                            
                                                                               

db:migrate
```

is there any other way to get more info?

**Comment by acelaya** [comment]
> it is a very big database as of know it has "2,792,987" links

Since v2.4.0 short URLs are linked to the API key used to create them.

In order to keep things as consistent as possible, I added a DB migration which tries to find out if there's only one active API key, and if so, links all short URLs to it.

Most probably, this migration is taking more than 60 seconds to run due to the large amount of links, which makes it time out.

One way you can go around this is by creating a second API key first. With this, the migration won't be able to pick just one, and will not try to do the linking.

After that, try running the update script again and it should work. Once finished, you can disable the new API key.

**Comment by acelaya** [comment]
If you can confirm this is the problem, I'll also increase the command's timeout, as 1 minute could be too low.

**Comment by levdad** [comment]
I tried what you suggested, the first time it didn't work but it did the second time.
Thanks a lot!
