### ISSUE TITLE
Access denied when migrating from 2.3.0 to 2.4.2

### ISSUE THREAD

**Issue by codaamok** [shlinkio/shlink#920]
#### How Shlink is set-up

* Shlink Version: 2.3.0 -> 2.4.2
* PHP Version: 7.4
* How do you serve Shlink: Self-hosted nginx
* Database engine used: mariadb

#### Summary

When issuing `update` and pointing it to the old directory for migrating config over from old > new, I get the below. The `shlink` user does exist in the database. I'm not 100% sure how I give the update utility a password for the `shlink` db user?

```
root@CODAAMOKSAZ01:/var/www/shlink# bin/update -vvv

 Welcome to Shlink!!
 This tool will guide you through the installation process.

 Do you want to import configuration from previous installation? (You will still be asked for any new config option that did not exist in previous shlink versions) (yes/no) [yes]:
 >

 Previous shlink installation path from which to import config:
 > /var/www/shlink.old/

 Custom configuration properly generated!

Updating database... [Running "/usr/bin/php7.4 bin/cli db:migrate"]   RUN  '/usr/bin/php7.4' 'bin/cli' 'db:migrate'
  OUT  Migrating database...
  OUT
  ERR
  ERR  In ProcessHelper.php line 110:
  ERR
  ERR    The command "'/usr/bin/php7.4' 'vendor/doctrine/migrations/bin/doctrine-mig
  ERR    rations.php' 'migrations:migrate' '--no-interaction'" failed.
  ERR
  ERR    Exit Code: 1(General error)
  ERR
  ERR    Working directory: /var/www/shlink
  ERR
  ERR    Output:
  ERR    ================
  ERR
  ERR
  ERR    Error Output:
  ERR    ================
  ERR
  ERR    In AbstractMySQLDriver.php line 112:
  ERR
  ERR
  ERR      An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for
  ERR     u
  ERR      ser 'shlink'@'localhost' (using password: YES)
  ERR
  ERR
  ERR
  ERR
  ERR    In Exception.php line 18:
  ERR
  ERR
  ERR      SQLSTATE[HY000] [1045] Access denied for user 'shlink'@'localhost' (using
  ERR     p
  ERR      assword: YES)
  ERR
  ERR
  ERR
  ERR
  ERR    In PDOConnection.php line 38:
  ERR
  ERR
  ERR      SQLSTATE[HY000] [1045] Access denied for user 'shlink'@'localhost' (using
  ERR     p
  ERR      assword: YES)
  ERR
  ERR
  ERR
  ERR
  ERR    migrations:migrate [--write-sql [WRITE-SQL]] [--dry-run] [--query-time] [--
  ERR    allow-no-migration] [--all-or-nothing [ALL-OR-NOTHING]] [--configuration CO
  ERR    NFIGURATION] [--db-configuration DB-CONFIGURATION] [--] [<version>]
  ERR
  ERR
  ERR  db:migrate
  ERR
  ERR
  RES  1 Command did not run successfully
```

**Comment by codaamok** [comment]
Same is true if I try 2.4.0

**Comment by acelaya** [comment]
What do you mean when you say you are not sure how to give the password? Has the password changed in any way? Because if you are migrating from previous version, it will just pick the same config you had before.

Does it also throw an error if you still try to run v2.3, or that one still works?

**Comment by codaamok** [comment]
> What do you mean when you say you are not sure how to give the password? Has the password changed in any way? Because if you are migrating from previous version, it will just pick the same config you had before.

I know the documentation doesn't suggest I need to pass any kind of password, but I was just thinking aloud. I was trying to rationalise why it was throwing access denied error. 

> Does it also throw an error if you still try to run v2.3, or that one still works?

2.3.0 starts fine, no issues. Can create, view, update and delete short codes fine so db access must be fine.

**Comment by acelaya** [comment]
Ok, I'll see if I can reproduce it.

What's the exact Mariadb version you use?

**Comment by codaamok** [comment]
10.1.47-MariaDB-0ubuntu0.18.04.1

**Comment by codaamok** [comment]
Please do not waste any more time on this. I literally rebooted and it is now fine.

I remembered that before updating Shlink, I issued apt update/upgrade - I didn't see a restart file in /var so I didn't reboot. However after rebooting on a whim to see if it improved things, it did.

I hope you didn't waste too much time.
