### ISSUE TITLE
Unclear/Undocumented state of php configuration files

### ISSUE THREAD

**Issue by loelkes** [shlinkio/shlink#929]
* Shlink Version: 2.4.2
* PHP Version: 7.4.13
* How do you serve Shlink: Self-hosted nginx
* Database engine used: MySQL

I wanted to change my GeoIP2 key. So first I changed it in `shlink/config/params/generated_config.php`. This did not change anything, so I looked further and changed it in `shlink/config/autoload/geolite2.global.php` without success. Then I found out that `shlink/data/cache/app_config.php` overwrites all previous files. Changing it in the last file fixed it.

**Question:** I see multiple types of configuration files, none of them explained in the docs. Where and how should modifications be made? 

I would also like to configure `not_found_redirects` and it did most likely not work because of this issue. This issue might be related to #800 as the suggestion to change it in `generated_config.php` does not work.

**Comment by acelaya** [comment]
The configuration works this way.

* Everything inside `config/autoload` is the general project config. It's spread in several files to improve maintainability, and it gets merged at runtime.
  Usually, you shouldn't need to edit those files.
* Then, during installation, the `config/params/generated_config.php` file gets generated dynamically, with the information you provided.
  This file is also merged with the rest, overwriting options coming from the autoload folder.
  Usually it's enough to edit this file when you need to change some config.
* All the files above, once merged, are cached in the `data/cache/app_config.php`, to avoid loading several files on every request.
  This is what usually makes things more counterintuitive when you try to change some config option.

So, with that in mind, there are things you can do.

* Edit the `generated_config.php` file (the only one that should be edited manually, if any), completely dropping the options you want to overwrite. The run the `bin/update` script. It will take care of asking those questions only, and clearing the config cache.
* Edit the `generated_config.php` file, replacing the keys you want to change. Then delete the `data/cache/app_config.php` file.
* Running the `bin/install` script, which will ask for all the options again.

Ideally, shlink should include a CLI command to update config options, but I have spent my time in other improvements and features, so it's still to be done (see https://github.com/shlinkio/shlink-installer/issues/51).

Better documenting these things is also something that needs to be improved. I have a list of tickets tagged with "troubleshooting" with things that I want to better explain in some kind of FAQs or similar (see https://github.com/shlinkio/shlink/issues?q=label%3Atroubleshooting+is%3Aclosed)

**Comment by acelaya** [comment]
Next shlink version (2.5) will include a `bin/set-option` script to set individual configuration options after shlink is already installed.

It will take care of clearing config cache and setting the option appropriately.

See https://github.com/shlinkio/shlink/pull/931 and https://github.com/shlinkio/shlink-installer/pull/97
