### ISSUE TITLE
Running the install script doesn't show any options

### ISSUE THREAD

**Issue by balakumarshanmugam** [shlinkio/shlink#939]
#### How Shlink is set-up

Shlink Version: 3.0
PHP Version: 7.4
How do you serve Shlink: Self-hosted Apache
Database engine used: MySQL

#### Summary

I have set up LAMP stack and uploaded the shlink files to the server. When I try to configure the DB parameters by running ./install in the bin directory, it doesn't show me any options. It simply returns to the command line as if nothing happened. Is there any other way I can configure the params? Or ifs there any way I can get the install script working? Thanks for your help.

**Comment by acelaya** [comment]
> Shlink Version: 3.0

There's no such version. Can you try running `bin/cli -V` from the project's root to get the actual version?

> When I try to configure the DB parameters by running ./install in the bin directory, it doesn't show me any options

Can you share the output you get when running this command?

Also, can you try running it with higher verbosity by providing `-vvv`?

**Comment by balakumarshanmugam** [comment]
> > Shlink Version: 3.0
> 
> There's no such version. Can you try running `bin/cli -V` from the project's root to get the actual version?
> 
> > When I try to configure the DB parameters by running ./install in the bin directory, it doesn't show me any options
> 
> Can you share the output you get when running this command?
> 
> Also, can you try running it with higher verbosity by providing `-vvv`?

Thanks for your quick response. I tried all commands. Everything comes back with no display. Please see screenshot below.
![image](https://user-images.githubusercontent.com/25269667/103165387-645a0180-4817-11eb-8b60-6d6834eeae0f.png)

Ubuntu 20.04 is the OS. Would it make any difference if I tried it in 18.04? Thanks for your help.

Regards,
Bala

**Comment by acelaya** [comment]
That's pretty weird 🤔

How did you download shlink?

Can you try running `ls -l` inside that folder and share the result?

What does the `php -v` command print?

Have you tried running other PHP scripts? Do they work?

Can you try running some of the shlink scripts prefixed with `php`? For example `php bin/install`

**Comment by balakumarshanmugam** [comment]
> How did you download shlink?

My bad. I first downloaded shlink-develop.zip. Maybe that's why it didn't work. Now I downloaded shlink_2.4.2_dist and trying. I'll let you know how it goes. Thanks for looking into this :)

**Comment by acelaya** [comment]
> I downloaded the latest copy from GIT yesterday

Ok, I just noticed this. If you just git-cloned the project, it won't work.

Your PHP config is probably set to hide all errors, and that's why it doesn't show anything.

The proper approach is to download a dist file, which comes pre-bundled with all the dependencies and ready to use.

This is the dist file from latest stable version (v2.4.2) https://github.com/shlinkio/shlink/releases/download/v2.4.2/shlink_2.4.2_dist.zip

**Comment by balakumarshanmugam** [comment]
> This is the dist file from latest stable version (v2.4.2) https://github.com/shlinkio/shlink/releases/download/v2.4.2/shlink_2.4.2_dist.zip

Thanks. I downloaded this and ftping this to the server. I'll let you know if this works.

**Comment by balakumarshanmugam** [comment]
@acelaya Thank you so much for your help. I have set shlink up and it's working great. I had few problems setting up multiple domains. But I saw in other github tickets that I have to create cname records on the extra domains to make them point to the domain where shlink server is running. That seems to be working. Thanks a lot for this awesome product. I'm going to use it for all my website.

However one question: I don't have any login id, pwd in the client. So how do I get back to my server some other day. Do I have to add the server again? I tried that in incognito mode, and it says something went wrong. Could you guide please?

**Comment by acelaya** [comment]
I'm glad it's working now 🙂

If it's ok, let's close this issue, and you can open a new one with the new question, just in case someone else wonders the same in the future.

**Comment by balakumarshanmugam** [comment]
> If it's ok, let's close this issue, and you can open a new one with the new question, just in case someone else wonders the same in the future.

Ok, sure. Will do :)
