### ISSUE TITLE
Ability to customize QR Codes look and feel

### ISSUE THREAD

**Issue by ajtatum** [shlinkio/shlink#944]
Sorry for the feature requests, just kind of adding things that I've used from other URL Shortening Services.

Anyway, it would be nice if from the UI side (ie: https://app.shlink.io), I could generate a QR Code for a Short URL. I know that there are plenty of ways that I could take a URL and then generate a QR Code elsewhere, but it'd be nice if it were in the same app. To be more specific about this feature, I really like what Rebrandly does:

- Customize the color of the QR Code so it's not your standard black & white (this is at the short domain level)
- Add a logo to the QR Code (this is also at the short domain level)

Here's an example from Rebrandly:
![rabrandly_qr_code](https://user-images.githubusercontent.com/318022/103330409-6ac2c600-4a2f-11eb-9c8a-cbe945c643bd.png)

**Comment by acelaya** [comment]
That looks cool 🙂 

The thing is that Shlink already supports generating QR codes. Here you can find the docs https://api-spec.shlink.io/?version=v2.4.2#/URL%20Shortener/shortUrlQrCode

It's basically just spending `/qr-code` to any existing short URL, and you can customize sizes and such on the fly.

Having further customization is not yet supported, but it looks like something nice to have. I'll try to get it done.

**Comment by berts** [comment]
Hi, I was going to send a message proposing this very thing, it would be a nice addition to this useful tool.
Off topic
I didn't know, until I entered github, that the developer was from Zaragoza. Hello fellow citizen ;)
Great work.

**Comment by acelaya** [comment]
Closing this to narrow down the amount of features due to limited amount of time.
