### ISSUE TITLE
Is it possible to pass parameters to the shortened link?

### ISSUE THREAD

**Issue by garethjax** [shlinkio/shlink#951]
#### Summary

This feature is something that works for rebrand.ly: if you append a string to a short url, the string is appended to the final expanded url.

Example:

- long url : https://www.widget.com
- short url : https://short.url/1
- customized url:https://short.url/1&utm_source=soup
- final url: https://www.widget.com&utm_source=soup

I'm sorry if it's a feature already in pipeline, but i don't know how to search for it! 

Thanks in advance

**Comment by acelaya** [comment]
Hey @garethjax 

Shlink already behaves like this. Any query params sent to the short URL are automatically forwarded to the long URL.

**Comment by garethjax** [comment]
@acelaya my bad! I added "&id=something" at the end of the url and it caused an error. Using "?id=something" works perfectly

**Comment by acelaya** [comment]
No problem :)

I have published today some docs explaining this, as it was one of a few smaller undocumented features, but not anymore https://shlink.io/documentation/some-features/#query-params-forwarding
