### ISSUE TITLE
Robots.txt and Server Question

### ISSUE THREAD

**Issue by qualifysolutions** [shlinkio/shlink#956]
I have yet to install shlink as I am debating what architecture to use to do so. One concern is that I want to allow all shortlinks to be crawled by search engines but blocked by many other bots.  I assume there is no problem making that change in the robots.txt file.  In the past I have done it via robots.txt and htaccess for the added protection of some redundancy.

Considering that would you recommend I use docker or my own apache server instance?

A separate question - does shlink allow for 1 shortlink to have multiple destination urls.  Several other tools allow that and they are configured either by time, device or just split evenly.  I just use them split evenly most often.

I will be supporting the project as a small thank you for this great tool.

**Comment by acelaya** [comment]
> Considering that would you recommend I use docker or my own apache server instance?

Any of the options should be ok. If you do a classic hosting, you can edit the robots.txt file included in the dist file. If you decide to use the docker image, you can overwrite the robots.txt file via a docker volume:

    docker run [...] -v ${PWD}/robots.txt:/etc/shlink/public/robots.txt shlinkio/shlink

> does shlink allow for 1 shortlink to have multiple destination urls

This has been discussed in the past, but it is not yet supported. See https://github.com/shlinkio/shlink/issues/366

**Comment by acelaya** [comment]
I guess the question can be considered answered.

Feel free to place new comments or open new issues if there's anything else you need to clarify.
