### ISSUE TITLE
Concerting safety and abuse

### ISSUE THREAD

**Issue by garethjax** [shlinkio/shlink#961]
This is not really a technical issue, but it's more about safety.

Let me be clear, that shlink is **amazing** and the web app is cool! 

But my hosting provider (Opalstack, the successor of Webfaction) told me that i should be responsible for the use and **abuse** of my url shortening app, which is pretty correct in my opinion. 

I don't plan to open the shortening service to more than one person (my business partner) but the doubt remains, and i think i've followed the installation guidelines as much as i could : could the service be abused without me knowing it ? 

Thanks for any insight.

**Comment by acelaya** [comment]
What do you mean by "abused"? Do you mean if someone could access your data?

Why did your hosting provider bring this up? Could you give me a bit more context?

**Comment by garethjax** [comment]
Yes, imagine if somebody creates a lot of shortened urls and use them for spamming or phishing.

This is the url of the conversation: https://community.opalstack.com/d/426-url-shortening-supported-by-opalstack

**Comment by acelaya** [comment]
Ok, got it.

Shlink's API requires an API key to be able to create short URLs, so as long as you keep it safe and always serve shlink through HTTPS, you should be ok.

There's no way someone creates short URLs under your Shlink instance if they don't have a valid API key.

**Comment by acelaya** [comment]
Also, if for any reason an API key gets accidentally leaked, you can revoke it and create a new one.

**Comment by garethjax** [comment]
thanks for the clarification!

**Comment by acelaya** [comment]
Welcome 🙂

**Comment by acelaya** [comment]
Welcome 🙂
