### ISSUE TITLE
Add support for real-time update when a short link is created or reused

### ISSUE THREAD

**Issue by ajtatum** [shlinkio/shlink#962]
One integration that I enjoyed with Bitly was the ability to receive a notification whenever a new short link was created. This gave me some sense how popular content was without having to worry about trying to figure out share counts, etc. I think it would be a nice feature to have in Shlink so that if a new short link was created OR reused, a POST request was made to a webhook URL. I could then build some notification mechanism on my end, log it, or do whatever I want with it.

If you need more details, please let me know!

Thanks for your dedication,
AJ

**Comment by acelaya** [comment]
Things like this will start to make more and more sense after this 🙂  https://github.com/shlinkio/shlink/issues/795
