### ISSUE TITLE
optional URI suffix prepend to short URL

### ISSUE THREAD

**Issue by sgohl** [shlinkio/shlink#989]
Instead of like https://doma.in/4UcxL , is it possible to prepend a fixed (in terms of always) suffix to the generated short URL, like:

https://doma.in/s/4UcxL

**Comment by acelaya** [comment]
You can serve shlink in a subpath. That's already supported.

The installer probably asked you about it.

If you are using the docker image, then you want to use the `BASE_PATH` env var.

**Comment by sgohl** [comment]
damn, sure, thanks a lot ^^

**Comment by sgohl** [comment]
Unfortunately, this does not work with multiple domains. Domain value will not accept a sub-path
